#+TITLE: MA1: God of Small Things Close Reading Paragraph

* text
  #+begin_quote
  She didn't even trust the twins. She deemed them Capable of Anything. Anything at all. /They might even steal their present back/ she thought, and realized with a pang how quickly she had reverted to thinking of them as though they were a single unit once again. After all those years. Determined not to let the past creep up on her, she altered her thought at once. /She. She might steal her present back./
#+end_quote

* brainstorm

** the past lingers, yet baby kochamma is running from the past

*** redundant "reverted...once again" stresses the past, as if she is trying to keep it in the past

*** "how quickly" it's much easier to go back

*** "after all those years" as opposed to "these" years. disassociating the years where they were away from self. also guilty.. why?

*** "not to let the past creep up on her" the way rahel/estha do. rahel/estha represent the past

*** pang = guilty?

*** no hesitation in correction, has been doing this for a while.

*** lack of "even" in corrected thought?

** scared of silence
