#+TITLE: PS#11
#+AUTHOR: Dylan Wallace

* 1.
Done on Friday

* 2.
\begin{equation}
\int_{-\infty}^{0} xe^{-x} \,dx = 0 - (-\infty) = \infty
\end{equation}

We know that the limit of $xe^{-x}$ as x goes to negative infinity is zero because as x decreases past zero $e^{-x}$ approaches infinity.

* 3.
We know that $\int_{1}^{\infty} e^{-x} \,dx$ is finite because $e^{-x}$ converges to 0.
If we write $e^{-x}$ as a function $f$, then the gaussian curve ($e^{-x^2}$) can be written as $\frac{1}{f(x)^2}$, or $f(x)^{-2}$.
With reverse chain rule we can easily integrate this: $\int_{1}^{\infty} f(x)^{-2} \,dx = F(1)^{-1} - F(\infty)^{-1}$
We know that $F(\infty)^{-1}$ is finite because $F(\infty)$ is finite because the integral of $e^{-x}$ earlier is finite. Of course, $F(1)^{-1}$ is also finite. Therefore, the entire integral is finite.

* 4.
The orthogonal direction is the cross product:
\begin{aligned}
\vec{r} \times \vec{s} &= (\vec{r}_y\vec{s}_z - vec{r}_z\vec{s}_y)\hat{i} + (\vec{r}_z\vec{s}_x - \vec{r}_x\vec{s}_z)\hat{j} + (\vec{r}_x\vec{s}_y - \vec{r}_y\vec{s}_x)\hat{k} \\
&= ((-2)(-3) - (6)(1))\hat{i} + ((6)(-5) - (10)(-3))\hat{j} + ((10)(1) - (-5)(-2))\hat{k} \\
&= 0\hat{i} + 0\hat{j} + 0\hat{k} \\
\end{aligned}

This makes sense because $\vec{r}$ and $\vec{s}$ are colinear.
