#+TITLE: PS#21
#+AUTHOR: Dylan Wallace

* Salt Flats
** 1)
N/A
** 2&3)
\begin{aligned}
\vec{v}(t) &= \frac{d}{d t}\vec{f}(t) &= \begin{bmatrix}2t \\ 12\cos{(t)} + 1\end{bmatrix} \\
\vec{a}(t) &= \frac{d^2 t}{d t^2}\vec{f}(t) &= \begin{bmatrix}2 \\ -12\sin{(t)}\end{bmatrix}\\
\end{aligned}
** 4)
\begin{aligned}
v(t) &= ||\vec{v}(t)|| \\
v(\pi) &= ||\vec{v}(\pi)|| \\
&= ||\begin{bmatrix}2\pi \\ 12\cos{(\pi)} + 1\end{bmatrix}|| \\
&= ||\begin{bmatrix}{2\pi \\ -11 \end{bmatrix}|| \\
&= \sqrt{(2\pi)^2 + (-11)^2} \\
&= \sqrt{4\pi^2 + 121} \\
\\
a(t) &= ||\vec{a}(t)|| \\
a(\pi) &= ||\vec{v}(\pi)|| \\
&= ||\begin{bmatrix}2 \\ -12 \sin{(\pi)} \end{bmatrix}|| \\
&= ||\begin{bmatrix}2 \\ 0\end{bmatrix}|| \\
&= \sqrt{(2)^2 + (0)^2} \\
&= \sqrt{4} \\
&= 2 \\
\end{aligned}

** 5)
\begin{aligned}
v(t) &= ||\vec{v}(t)|| \\
&= \sqrt{\vec{v}_x(t)^2 + \vec{v}_y(t)^2} \\
&= \sqrt{4t^2 + 144\cos^2{(t)} + 24\cos{(t)} + 1} \\
\end{aligned}

We know that both $\cos^2{(t)}$ and $\cos{(t)}$ have a maximum value of $1$, and they are maximized at $t \in \{x : \frac{x}{2\pi} \in \mathbb{Z}\}$.
However, $4t^2$ is quadratic, and it does not have a maximum value, as it diverges as $t$ increases or decreases towards infinity.
We do know, however, that the function is bounded between $-2\pi$ and $3\pi$. The value(s) that fits this is $-2\pi$ (and $2\pi$):

\begin{aligned}
max(v(t)) &= \sqrt{4(2\pi)^2 + 144\cos^2{(2\pi)} + 24\cos{(2\pi)} + 1} \\
&= \sqrt{16\pi^2 + 144 + 24 + 1} \\
&= \sqrt{16\pi^2 + 169} \\
\end{aligned}

** 6)
\begin{aligned}
a(t) &= ||\vec{a}(t)|| \\
&= \sqrt{\vec{a}_x(t)^2 + \vec{a}_y(t)^2} \\
&= \sqrt{4 + 144\sin^2{(t)}} \\
\end{aligned}


We know that the maximum value of  $\sin^2{(t)}$ is 1, so the above becomes

\begin{aligned}
max(a) &= \sqrt{4 + 144} \\
&= \sqrt{148} \\
&= 2\sqrt{37} \\
\end{aligned}

We have no units so I can't tell if I can survive this or not.

** 7)
To get the distance travelled, we need to get the length of the parametric function. We'll try to adapt arc length for parametric equations.
We know that the distance between two really close points can be modeled as:

\begin{aligned}
|P_{i-1}P_i| &= \sqrt{\Delta x^2 + \Delta y^2} \\
\end{aligned}

Of course, both $x$ and $y$ are functions of $t$.
Using the MVT, we can condense this down to 

\begin{aligned}
|P_{i-1}P_i| &= \sqrt{f_x'(t_i^{*})^2\Delta t^2 + f_y'(t_i^{*})^2\Delta t^2} \\
&= \sqrt{f_x'(t_i^{*})^2 + f_y'(t_i^{*})^2}\Delta t \\
\end{aligned}

Then, the length of the curve is

\begin{aligned}
L &= \sum_{i=0}^n |P_{i - 1}P_i| \\
&= \sum_{i=0}^n \sqrt{f_x'(t_i^{*})^2 + f_y'(t_i^{*})^2}\Delta t \\
&= \int_a^b \sqrt{f_x'(t)^2 + f_y'(t)^2} \,dt \\
\end{aligned}

But wait... This is just integrating $v(t)$ from $a$ to $b$! We know what $v(t)$ is, so we can easily do that:

\begin{aligned}
L &= \int_{-2\pi}^{3\pi} \sqrt{v_x(t)^2 + v_y(t)^2} \,dt \\
&= \int_{-2\pi}^{3\pi} \sqrt{4t^2 + 144\cos{(t)}^2 + 24\cos{(t)} + 1} \,dt\\
&= 189.669
\end{aligned}

It wasn't so easy after all. I had to use wolfram. But I think this is the answer.
