#+TITLE: PS#23
#+AUTHOR: Dylan Wallace

* Rotation
Ask me for a picture of the whiteboard or something

* Temperature
The gradient of the function $T$ is as follows:

\begin{aligned}
\nabla T(x, y, z) &= \begin{bmatrix}\frac{\partial f}{\partial x} \\ \frac{\partial f}{\partial y} \\ \frac{\partial f}{\partial z}\end{bmatrix} \\
&= \begin{bmatrix}12yz \\ 12xz \\ 12xy\end{bmatrix} \\
\nabla T(1, 1, 1) &= \begin{bmatrix}12 \\ 12 \\ 12\end{bmatrix} \\
\end{aligned}

We know that the direction of steepest slope is in the direction of the gradient, or in the direction of $12\hat{i} + 12\hat{j} + 12\hat{k}$ in our case.

To get the rate of change in a particular direction, we first can take the dot product of the gradient and the position vector. Doing this, we get $12\cdot1 + 12\cdot 1 + 12\cdot 1 = 36$. Then, because we know that the vector $\hat{i} + \hat{j} + \hat{k}$ has a magnitude of $\sqrt{3}$, we can divide our value by that value to get $\frac{36}{\sqrt{3}} = 12\sqrt{3}$.

IDK how to explain this next part, just follow along

\begin{aligned}
0 &= 12a + 12b + 12c \\
1 &= \sqrt{a^2 + b^2 + c^2} \\
\end{aligned}

We can conceptualize this as the intersection between a sphere and a plane. This, of course, is a circle. We now do algebra:

\begin{aligned}
0 &= a + b + c \\
a &= -b - c \\
1 &= \sqrt{(-b-c)^2 + b^2 + c^2} \\
&= \sqrt{(b + c)^2 + b^2 + c^2} \\
&= \sqrt{b^2 + 2bc + c^2 + b^2 + c^2} \\
&= \sqrt{2b^2 + 2bc + 2c^2} \\
&= \sqrt{2} \cdot \sqrt{b^2 + bc + c^2} \\
\sqrt{b^2 + bc + c^2} &= \cos{\frac{\pi}{2}} \\
\end{aligned}

All values of $b, c$ are on this equation of an ellipse. In fact, all values of $a, b$ and $a, c$ will also satisfy this equation because of the property of the plane. Cool stuff.







