#+TITLE: PS#20
#+AUTHOR: Dylan Wallace

$h:\mathbb{R}^2\rightarrow\mathbb{R}^1$

$h(x,y)=x^2+y^2+2x - 6y+5$

The point $(-1, +3, h(-1,+3))$ (work out what the $z$-coordinate at $x=-1,y=+3$ is) is a minimum of this function! I guarantee it! Prove this, in two ways:
\begin{itemize} \item Using the gross ugly don't-memorize-it multivariable second derivative test. (Feel free to look it up; do summarize/explain in your solution how to use it.) \item Without using calculus {\em at all}! (Let alone multivariable calculus!) (I have a hint for you if you need it.) \end{itemize}


* Calculus
We know that the gradient of $h(x, y)$ is

\begin{aligned}
\nabla h(x, y) &= \begin{bmatrix}2x + 2 \\ 2y - 6\end{bmatrix} \\
\end{aligned}
Given this, we know that
\begin{aligned}
\nabla h(-1, 3) &= \begin{bmatrix}0 \\ 0\end{bmatrix}
\end{aligned}
We know that $(-1, 3)$ is a root of the function.
We can also take the second partial derivative:
\begin{aligned}
h_{xx}(x, y) = 2 \\
h_{xy}(x, y) = 0 \\
h_{yy}(x, y) = 2 \\
\end{aligned}
Because we know that there is no acceleration in the x or y component with respect to their counterparts, and because we know that $h_{xx}$ and $h_{yy}$ are positive, we know that the function is a minimum at $(-1, 3)$.

* Non-calculus
We know that $\nabla h(-1, 3) = 0$.
We also know that $h(-1, 3) = -5$. 
Given this, we can solve for $h(x, y)$ and prove that the function cannot be less than $-5$:
\begin{aligned}
h(x, y) &= x^2 + y^2 + 2x - 6y + 5 \\
&= (x)(x + 2) + (y)(y - 6) + 5
\end{aligned}
