#+TITLE: PS#20
#+AUTHOR: Dylan Wallace


* Calculus
We know that the gradient of $h(x, y)$ is

\begin{aligned}
\nabla h(x, y) &= \begin{bmatrix}2x + 2 \\ 2y - 6\end{bmatrix} \\
\end{aligned}

Given this, we know that

\begin{aligned}
\nabla h(-1, 3) &= \begin{bmatrix}0 \\ 0\end{bmatrix}
\end{aligned}

We know that $(-1, 3)$ is a root of the function.
We can also take the second partial derivative:

\begin{aligned}
h_{xx}(x, y) = 2 \\
h_{xy}(x, y) = 0 \\
h_{yy}(x, y) = 2 \\
\end{aligned}

Because we know that there is no acceleration in the x or y component with respect to their counterparts, and because we know that $h_{xx}$ and $h_{yy}$ are positive, we know that the function is a minimum at $(-1, 3)$.

* Non-calculus
We know that $\nabla h(-1, 3) = 0$.
Given this, we can factor $h(x, y)$ and prove that the function's absolute minimum is at $(-1, 3)$:

\begin{aligned}
h(x, y) &= x^2 + y^2 + 2x - 6y + 5 \\
&= (x)(x + 2) + (y)(y - 6) + 5
\end{aligned}

After we factor $h(x, y)$, we learn that the function is in reality a sum of two "parabolic" functions with different variables. We can separate $h(x, y)$ into an $x$ component, $(x)(x + 2)$, a $y$ component, $(y)(y - 6)$, and a constant, $5$.
We know that the minimum of the $x$ component is at the vertex of the parabola given by the expression, or at $x=-1$.
We also know that the minimum of the $y$ component is at the vertex of the parabola given by the expression, or at $y=3$.
Now that we know the x value that minimizes the $x$ component and the y value that minimizes the $y$ component, we know that $(-1, 3)$ must be the minimum of $h(x, y)$.

* Fur Trading
We will model the price of fox pelts as $p_f$ and the price of seal pelts as $p_s$. We will also model the quantity of fox pelts sold as $q_f$ and the quantity of seal pelts as $q_s$.
The quantity of fox pelts sold and seal pelts sold can be modeled by the equations

\begin{aligned}
q_f &= 200 - p_s - 3p_f \\
q_s &= 150 - 2p_s - p_f \\
\end{aligned}

respectively.
The total revenue can be modeled by the equation

\begin{aligned}
r(p_f, p_s) &= p_f \cdot q_f + p_s \cdot q_s \\
&= p_f(200 - p_s - 3p_f) + p_s(150 - 2p_s - p_f) \\
&= 200p_f + 150p_s - 2p_fp_s - 3p_f^2 - 2p_s^2 \\
\end{aligned}

We can take the gradient of $r$ to find extremas:

\begin{aligned}
\nabla r(p_f, p_s) &= \begin{bmatrix}200 - 6p_f - 2p_s \\ 150 - 4p_s - 2p_f\end{bmatrix}
\end{aligned}

We can set both the $p_f$ and $p_s$ component of the vector to zero to get a system of equations and find the extrema:

\begin{aligned}
200 - 6p_f - 2p_s = 0 \\
150 - 4p_s - 2p_f = 0 \\
\\
2p_s &= 200 - 6p_f \\
150 - 2(200 - 6p_f) - 2p_f &= 0 \\
150 - 400 + 10p_f &= 0 \\
10p_f &= 250 \\
p_f &= 25 \\
p_s &= 150 - 3p_f \\
&= 100 - 3(25) \\
&= 25
\end{aligned}

We have a value for $(p_f, p_s)$ at which the gradient is zero: $(25, 25)$.
We only have one extrema, so given the context of the problem, we can assume that it is a maxima. But, because I think Andrew will get mad at me if I don't, I will give a brief explanation as to why this is the minima:
If we take the second order partial derviative of $r$, we get the following:

\begin{aligned}
r_{p_{f}p_{f}}(p_f, p_s) &= -6 \\
r_{p_{f}p_{s}}(p_f, p_s) &= -2 \\
r_{p_{s}p_{s}}(p_f, p_s) &= -4 \\
\end{aligned}

Even though when taking the $xy$ second degree partial we get a value, this doesn't really matter because the product of the $xx$ and $yy$ partials are greater than the square of the $xy$ partial, so it is a maximum or minimum.
We know that it is a maximum because both $xx$ and $yy$ partials are negative.
Therefore, we know that the optimal price for fox and seal pelts are $25$ and $25$, respectively.


