#+TITLE: salt flats and sand dunes
* salt flats
** chart the adventure
   Our adventure is of the form $f(t) = \begin{bmatrix}t^2-9 \\ 12 \sin  t - t\end{bmatrix}$.
   Here's a graph, to scale: [[https://www.desmos.com/calculator/qchdfts4in]].
** velocity as a function of time
   
   \[\begin{aligned}
   \frac{d}{dt} f(t) = \begin{bmatrix}2t \\ 12 \cos  t - 1\end{bmatrix}
   \end{aligned}\]
** acceleration as a function of time
   
   \[\begin{aligned}
   \frac{d^2}{dt^2} f(t) = \begin{bmatrix}2 \\ -12 \sin  t\end{bmatrix}
   \end{aligned}\]
** the moment $t = \pi$
   
   \[\begin{aligned}
   \left| \frac{d}{dt} f(t) \Bigr|_\pi \right| &= \sqrt{4\pi ^2 + 144 \cos ^2 \pi + 1 - 24 \cos  t}= \sqrt{4\pi ^2 + 144 + 1 + 24} \approx 208\\
   \left| \frac{d^2}{dt^2} f(t) \Bigr|_\pi \right| &= \sqrt{4 + 12^2 \sin ^2 t} = \sqrt{4 + 144} \approx  12
   \end{aligned}\]
** maximum speed
   The acceleration is zero at the maximum speed (but also at the minimum speed). 
   
   \[\begin{aligned}
   \sqrt{4 + 12^2 \sin ^2 t} &= 0\\
   12 ^2 \sin  ^2 t &= -4\\
   \sin  ^2 t &= -\frac{4}{12^2}\\
   \sin  t &= -\frac{1}{6}
   \end{aligned}\]

   It's hard to find exactly which value of $t$ both lies in the bounds and corresponds to the maximal speed, though.
** maximum acceleration
   
   \[\begin{aligned}
   \left| \frac{d^3}{dt^3} f(t) \right| = -12 \cos  t = 0\\
   \end{aligned}\]

   The maximum acceleration occurs when $t = (2n+1) \pi  + \frac{\pi}{2}, n \in \mathbb Z$.

   The acceleration at these maxima is 12 miles / hour squared, which is 0.0001 gs. This may not be the most joyous joyride. 
** distance traveled by odometer
   
   \[\begin{aligned}
    \int_{-2\pi}^{3\pi} \sqrt{4t^2 + 12^2 \cos ^2 t - 24 \cos  t + 1} dt \approx  189.5 \text{mi}
   \end{aligned}\]
* sandy times
** [[https://sagecell.sagemath.org/?z=eJyr0FGoVLBVKEss0lCvALLVNXm5CoACBfmZeSUaGkbGWgWZ-sY6CsbmmkAZECzIyS8xTtEozszTqNDUUdAA6iqINojVq0hJLEkEMnRN0QS0TUHKKqGilejKKhHKNBW0FQr04BZUpdqaGOgoVNmC7IK6RFMTANJYMYQ=&lang=sage&interacts=eJyLjgUAARUAuQ==][a chart]]
** elevation
   
   \[\begin{aligned}
   \sin  \frac{23 \pi }{3} = \sin  \frac{5\pi}{3} = -\frac{\sqrt{3}}{2}
   \end{aligned}\]
** hike as a path

   \[\begin{aligned}
   f(t) = \left\langle \frac{23\pi}{3} + t \cos  \frac{3\pi}{8}, 37 + t \sin  \frac{3\pi}{8}, \sin \left( \frac{23\pi}{3} + t \cos  \frac{3\pi}{8} \right)  \right\rangle
   \end{aligned}\]

 [[https://sagecell.sagemath.org/?z=eJx9UN0KgjAUvhd6h3PXZkunC4zAJ4mQpUIjdcNWuJ6-M5OkH7o7-_7OtzMwcJDDTfZkOeC8pIvAIGC06iwhqQiNigUDkVFkFsFJneuivPa32otkL9va9qosTKOtqMi-ke2xkmB3kAoIwSiIQcAKLD5KfSFj3pYymIUim_iL6n7xHv4bRg8MCGeQcN9xauJdA-YQ_JXZ80M0VNJKHNYJ_0BWaEShm2D3JXRvQm1kqazLeZRRLGOi18Z7nW_Qc8-flcfTUa-Zr_YAXIVndA==&lang=sage&interacts=eJyLjgUAARUAuQ==][a chart!]]
** slope along the path
   
   \[\begin{aligned}
   \frac{d}{dt} f_z(t) &= \frac{d}{dt}  \sin \left( \frac{23\pi}{3} + t \cos  \frac{3\pi}{8} \right)\\
   &= \cos  \left( \frac{23\pi}{3} + t \cos  \frac{3\pi}{8} \right) \cos  \frac{3\pi}{8}
   \end{aligned}\]
** slope when you start
   
   \[\begin{aligned}
   \frac{d}{dt} f_z(t) \Bigr|_0 = \cos \frac{23\pi }{3} \cos \frac{3\pi}{8}
   \end{aligned}\]

   But you want an angle, so we have to take the arctan.
   \[\begin{aligned}
   \tan^- \left(  \cos \frac{23\pi }{3} \cos \frac{3\pi}{8} \right) \approx  0.189 \text{ rad}
   \end{aligned}\]


