#+TITLE: Assignment 9: Vectors Part 2
* boatman problem

  Target displacement: $\langle 3 \text{km}, 2 \text{km} \rangle$

  We are working with the velocities of the boat and the river. The velocity of the river is defined as $r = \langle 0, -3.5 \rangle$. We want to find vector $v = \langle v_x, v_y \rangle$ s.t.
  
  \[\begin{aligned}
  \lvert v \rvert = 13 \text{ km/h}\\
  \lambda (v + r) = \langle 3, 2 \rangle
  \end{aligned}\]

  Where the trip will take $\lambda$ hours

  \[\begin{aligned}
  v_x ^2 + v_y ^2 = 13^2\\
  \lambda ( v_x + 0 ) = 3\\
  \lambda ( v_y + -3.5 ) = 2\\\\
  v_x &= \frac{3}{\lambda}\\
  v_y &= \frac{2}{\lambda } + 3.5\\
  \frac{3^2}{\lambda^2} + \left(\frac{2}{\lambda } + 3.5\right)^2 &= 13^2\\
  \frac{3^2}{\lambda^2} + \frac{2^2}{\lambda^2} + 3.5^2 + \frac{4(3.5)}{\lambda} &= 13^2\\
  \frac{3^2 + 2^2}{\lambda^2} + \frac{4(3.5)}{\lambda} &= 13^2 - 3.5^2\\
  3^2+2^2 + 4(3.5)\lambda  &= \lambda^2 \left(13^2 - 3.5^2\right)\\
  13 + 4(3.5)\lambda  &= \lambda^2 \left(156.75\right)\\
  -156.75 \lambda ^2 + 14^2 + 13 &= 0\\
  \lambda &= \frac{-14 \pm \sqrt{14^2 + 4(13)156.75}}{-2(156.75)}\\
  \lambda &= \frac{-14 + \sqrt{14^2 + 4(13)156.75}}{-2(156.75)}=-0.24676847741\\
  \lambda &= \frac{-14 - \sqrt{14^2 + 4(13)156.75}}{-2(156.75)}=0.336082671987\\
  \end{aligned}\]

  
\[\begin{aligned}
\boxed{ \lambda \approx 0.33608 = 20 \min }
\end{aligned}\]


  Maybe it's time to do it geometrically
  
\begin{tikzpicture}
\draw[black, thick, ->] (0, 0) -- (3, 2);
\draw[black, thick, ->] (0, 0) -- (0, -3.5)    node[above right] {m/s}
\end{tikzpicture}

Let $\theta$ be the angle difference that you paddle at, and $\phi$ be the angle that you are aiming for.


\[\begin{aligned}
 3.5^2\lambda^2 &= 13 + 13\lambda - 2(13)13\lambda \cos \theta \\
 \tan \phi    &= \frac{3}{2}\\
 \sin (\theta + \phi)  &= \frac{3.5 \lambda + 2}{13 \lambda}\\
\end{aligned}\]


attempt 3: after getting help from leonard

\[\begin{aligned}
\beta &= \alpha + \frac{\pi}{2} = \tan ^- \frac{2}{3} = 2.158\\
\frac{\sin \beta}{|v|} &= \frac{\sin  \gamma}{3.5}\\
\frac{\sin \left( 2.158 \right)}{13} &= \frac{\sin  \gamma}{3.5}\\
3.5\frac{\sin \left( 2.158 \right)}{13} &= \sin  \gamma\\
\gamma &= 3.5\frac{\sin \left( 2.158 \right)}{13} = 0.2241\\
\alpha  + \gamma &= 0.588 + 0.2241 = \boxed{0.8121 \text{ radians}}
\end{aligned}\]

The speed

\[\begin{aligned}
\frac{3}{13 \cos 0.812} = 0.3353 \text{ hours}
\end{aligned}\]

dang it i was actually right the first time. apparently math isn't a democracy.
* circular motion 
  
  \[\begin{aligned}
  \theta'(t) &= \omega_0\\
  \theta (t) &=  \int \omega _0 dt &= \omega _0 t + \theta _0
  \end{aligned}\]

** position
   
   \[\begin{aligned}
   \vec{r}(t) &= ( R \cos  \theta (t), R \sin \theta (t))\\
   &= \left( R \cos \left(\omega_0t + \theta _0 \right), R \sin \left( \omega_0t + \theta _0 \right) \right)\\
   \end{aligned}\]

   
** velocity
   
   \[\begin{aligned}
   \vec{v}'(t) &= \left( -\omega _0 R \sin \left(  \omega_0 t + \theta _0 \right) ,   \omega _0 R \cos  \left( \omega _0 t + \theta _0 \right)  \right)
   \end{aligned}\]
   
** acceleration
   
   \[\begin{aligned}
   \vec{a}(t) &= \vec{v}'(t)\\
   &= \frac{d}{dt}\left( -\omega _0 R \sin \left(  \omega_0 t + \theta _0 \right) ,   \omega _0 R \cos  \left( \omega _0 t + \theta _0 \right)  \right)\\
   &= \left( -\omega _0^2 R \cos \left(  \omega_0 t + \theta _0 \right) ,  -\omega _0^2 R \sin  \left( \omega _0 t + \theta _0 \right)  \right)\\
   \end{aligned}\]
   
** perpendicular
   
   \[\begin{aligned}
   \text{pos: }&\frac{\cancel{R}\sin (\omega _0t + \theta _0)}{\cancel{R} \cos  \left( \omega _0 t + \theta _0 \right)  }\\
   \text{vel: }&\frac{\cancel{\omega _0 R }\cos ( \omega _0 t + \theta _0 )}{-\cancel{\omega _0 R }\sin  (\omega _0 t + \theta _0)}
   \end{aligned}\]
   See? They are negative reciprocals of eachother.
   
   \[\begin{aligned}
   \left| \vec{v} \right| &= \sqrt{\omega _0^2 R^2 \sin ^2(\omega _0 t + \theta _0) + \omega_0 ^2 R^2 \cos  ^2 ( \omega _0 t + \theta 0 )}\\
   &= \omega _0 R \sqrt{\sin ^2(\omega _0 t + \theta _0) + \cos  ^2 ( \omega _0 t + \theta 0 )}\\
   &= \omega _0 R \sqrt{1}\\
   &= \omega _0 R\\
   \end{aligned}\]
   
** acceleration

   
   \[\begin{aligned}
   \text{accl }&= -\omega _0 ^2 R \left( \cos  (\omega _0 t + \theta _0), \sin  (\omega _0 t + \theta _0) \right)  \\
    \text{pos  }&= R \left( \cos  ( \omega _0 t + \theta _0) + \sin  (\omega _0 t + \theta _0 ) \right)  
   \end{aligned}\]

   The acceleration is a negative scalar multiple of the position, and thus points towards the center.

   
   \[\begin{aligned}
   \left| \vec{a} \right| = -w_0^2 R \sqrt{1} = \frac{w_0^2R^2}{R} = \frac{ \left| \vec{v} \right|^2 }{R}
   \end{aligned}\]

** non uniform motion
   
   \[\begin{aligned}
   \theta ''(t) = a_0\\
   \theta ' (0) = 0\\
   \theta (0) = 0
   \end{aligned}\]
   
   \[\begin{aligned}
   \theta '(t) = a_0 t + C_0 = a_0 t
   \end{aligned}\]
   
** angular position
   
   \[\begin{aligned}
   \theta (t) = \frac{1}{2} a_0 t^2 + C_1 = \frac{1}{2} a_0 t^2
   \end{aligned}\]

   
** position
   
   \[\begin{aligned}
   \vec{r}(t) &= (R \cos  \theta (t), R \sin  \theta (t))\\
   &= \left(  R \cos \left( \frac{1}{2} a_0 t^2 \right)  , R \sin  \left( \frac{1}{2} a_0 t^2 \right)  \right)  
   \end{aligned}\]
   

** velocity

   
   \[\begin{aligned}
   \vec{v}(t) &= R \left(-\sin  \left( \frac{1}{2} a_0 t^2 \right) a_0 t, \cos  \left( \frac{1}{2} a_0 t^2 \right)  a_0 t \right)\\
   &=  R a_0 t \left(-\sin  \left( \frac{1}{2} a_0 t^2 \right), \cos  \left( \frac{1}{2} a_0 t^2 \right) \right)\\
   \end{aligned}\]
   
   
** acceleration

   
   \[\begin{aligned}
   \vec{a}(t) = a_0 R \left( - \cos  \left(  \frac{1}{2} a_0 t^2 \right) a_0 t^2 - \sin  \left( \frac{1}{2} a_0 t^2 \right)  ,\\-\sin  \left( \frac{1}{2} a_0 t^2 \right)  a_0 t  ^2 + \cos  \left( \frac{1}{2} a_0 t^2 \right)  \right)  
   \end{aligned}\]

   
** velocity vector
   
   Both magnitudes are non-zero, so we can use the dot product to show that the position and velocity are perpendicular. 
   \[\begin{aligned}
   \vec{r}(t) \cdot \vec{v}(t) &= R \left( - \cos \left( \frac{1}{2} a_0 t^2 \right)  \sin \left( \frac{1}{2} a_0 t^2 \right)  a_0 t + \sin  \left( \frac{1}{2} a_0 t^2 \right)  \cos  \left( \frac{1}{2} a_0 t^2 \right)  a_0 t\right)  \\
   &= R 0 = 0
   \end{aligned}\]

   Thus, the velocity is tangent to the circle.

   Magnitude:
   
   \[\begin{aligned}
   \vec{v}(t) = R a_0 t \sqrt{\sin ^2 \left( \frac{1}{2} a_0 t^2 \right)  + \cos  ^2  \left( \frac{1}{2} a_0 t ^2 \right)  }\\
   = R a_0 t \sqrt{1} = R a_0 t = R \theta ' (t)
   \end{aligned}\]
   

** acceleration
   We can split it up because we know the $\left| \vec{v} \right|^2$ term is the one with $a_0^2t^2$
   
   \[\begin{aligned}
   \vec{a}(t) &= R \left( -a_0^2 t^2 \left( \cos  \left(\frac{1}{2} a_0 t^2 \right), \sin  \left( \frac{1}{2} a_0 t^2 \right)  \right) + a_0 \left(- \sin  \left( \frac{1}{2} a_0 t^2 \right),  \cos  \left( \frac{1}{2} a_0 t ^2 \right)   \right)  \right)  \\
   &= R \left( - \frac{\left| \vec{v} \right| ^2}{R^{\cancel{2}}} \frac{\vec{r}}{R} \right) + R a_0 \frac{\vec{v}}{| \vec{v} |}\\
   &= \left( - \frac{\left| \vec{v} \right| }{R} \frac{\vec{r}}{R} \right) + R a_0 \frac{\vec{v}}{| \vec{v} |}\\
   \end{aligned}\]

   
* derivative distribution
  
  \[\begin{aligned}
  \frac{d \vec{A}}{dt} &= \lim_{h \to  0} \frac{\vec{A}(t + h) - \vec{A}(t)}{h}\\
  &= \lim_{h \to 0} \frac{ \left( A_x (t+h), A_y (t+h), A_z (t+h) \right)  - \left( A_x(t), A_y(t), A_z(t) \right)  }{h}\\
  &= \lim_{h \to 0} \frac{ \left( A_x (t+h) - A_x(t), A_y (t+h) - A_y(t), A_z (t+h) - A_z(t) \right)  }{h}\\
  &= \lim_{h \to 0} \left( \frac{ A_x (t+h) - A_x(t)}{h}, \frac{ A_y (t+h) - A_y(t)}{h}, \frac{ A_z (t+h) - A_z(t) }{h} \right) \\
  &= \left( \lim_{h \to 0} \frac{ A_x (t+h) - A_x(t)}{h}, \lim_{h \to 0} \frac{ A_y (t+h) - A_y(t)}{h}, \lim_{h \to 0} \frac{ A_z (t+h) - A_z(t) }{h} \right) \\
  &= \left( \frac{d A_x(t)}{dt}, \frac{d A_y(t)}{dt}, \frac{d A_z(t)}{dt} \right) \\
  \end{aligned}\]

  
* derivative linearity
  
  \[\begin{aligned}
  \frac{d}{dt}  \left(  \alpha \vec{A} (t) + \beta \vec{B} (t) \right)   &= \frac{d}{dt}  \left(\alpha A_x(t), \alpha  A_y(t) \right) + \left(\beta  B_x(t),\beta  B_y(t) \right)  \right)  \\
  &= \frac{d}{dt}  \left(\alpha A_x(t) + \beta B_x(t), \alpha  A_y(t) + \beta B_y(t) \right)\\
  &= \left(\frac{d}{dt}  \left(   \alpha A_x(t) + \beta B_x(t) \right), \frac{d}{dt} \left( \alpha  A_y(t) + \beta B_y(t) \right) \right)\\
  &= \left(\left(   \alpha \frac{d}{dt} A_x(t) + \beta \frac{d}{dt} B_x(t) \right), \left( \alpha \frac{d}{dt} A_y(t) + \beta \frac{d}{dt} B_y(t) \right) \right)\\
  &= \left(\left(   \alpha \frac{d}{dt} A_x(t),  \alpha \frac{d}{dt} A_y(t) \right)+\left(\beta \frac{d}{dt} B_x(t), \beta \frac{d}{dt} B_y(t) \right) \right)\\
  &= \alpha \frac{d}{dt}\left(A_x(t),  A_y(t) \right)+ \beta \frac{d}{dt} \left(B_x(t), B_y(t) \right)\\
  &= \alpha \frac{d \vec{A}(t)}{dt} + \beta \frac{d \vec{B}(t)}{dt}\\
  \end{aligned}\]

  
* chain rule for derivatives
  
  \[\begin{aligned}
  \frac{d}{dt} \vec{A}(u(t)) &= \left( \frac{d}{dt} A_x(u(t)), \frac{d}{dt} A_y(u(t)) \right)  \\
  &= \left( \frac{dA_x(u)}{du} \frac{du}{dt}, \frac{dA_y(u)}{du}\frac{du}{dt} \right)  \\
  &= \left( \frac{dA_x(u)}{du}, \frac{dA_y(u)}{du}\right)  \frac{du}{dt} \\
  &= \frac{d \vec{A}(u)}{du}\frac{du}{dt} \\
  \end{aligned}\]

