#+TITLE: Problem Set 3: some derivatives and a parameterization
* find the third order partials of $f(x, y) = 4x^2y^5 + 3x^3y^2$

  \[\begin{aligned}
  \frac{\partial}{\partial x} &= 8x y^5 + 9 x^2 y^2\\
  \frac{\partial}{\partial y} &= 20x^2 y^4 + 6 x^3 y\\
  \frac{\partial^2}{\partial x^2 } &= 8 y^5 + 18 x y^2\\
  \frac{\partial^2}{\partial x \partial y} &= 40x y^4 + 18 x^2 y\\
  \frac{\partial^2}{\partial y^2 } &= 80x^2 y^3 + 6 x^3\\
  \frac{\partial^3}{\partial x^3 } &= 18 y^2\\
  \frac{\partial^3}{\partial^2 x \partial y} &= 40 y^4 + 36 x y\\
  \frac{\partial^3}{\partial x \partial^2 y} &= 160x y^3 + 18 x^2\\
  \frac{\partial^3}{\partial y^3 } &= 240x^2 y^2\\
  \end{aligned}\]
* for some function of $\mathbb R ^n \to  \mathbb R ^m$, the $k$-th order partial 
  can have up to $\frac{{kn \choose k}}{k!}$ possible partials???? I was going to tackle this but I realized that I have significant amounts of one-night homework. Will return.

  Well, for $n = 2$, there can be up to $k+1$ $k$-th order partials.
* the parameterization $x(t) = 3t + 4, y(t) = 5t-7, - \infty < t < \infty$
** equation of the line

I feel like there must be a better way of doing this. However, I shall have to find the slope and y-intercept manually.

y-intercept:
\[\begin{aligned}
x(t) &= 3t + 4 = 0\\
3t &= -4\\
t &= -\frac{4}{3}\\
y \left( -\frac{4}{3} \right)  &= - \frac{20}{3} - 7 = -\frac{41}{3}
\end{aligned}\]

Slope:

\[\begin{aligned}
\frac{d}{dt} y(t) &= 5\\
\frac{d}{dt} x(t) &= 3
\frac{\frac{dy}{dt}}{\frac{dx}{dt}} &= \frac{dy}{dx} = \frac{5}{3}
\end{aligned}\]

Thus, the equation for the line is

\[\begin{aligned}
\boxed{ y = \frac{5}{3}x - \frac{41}{3} }
\end{aligned}\]
** parameterization start

\[\begin{aligned}
 \left( x(0), y(0) \right)  = ( 4, -7 )
\end{aligned}\]
** speed in $x$ direction

\[\begin{aligned}
\frac{d}{dt} x(t) = \boxed{3}
\end{aligned}\]
** speed in $y$ direction


\[\begin{aligned}
\frac{d}{dt} y(t) = \boxed{5}
\end{aligned}\]
** actual speed

Lets find the velocity vector first
\[\begin{aligned}
\vec{v} = \frac{d}{dt} ( x(t), y(t) ) = (3, 5)
\end{aligned}\]

The magnitude of that velocity vector is 

\[\begin{aligned}
\lvert \vec{v} \rvert  = \sqrt{3^2 + 5^2} = \boxed{5.83}
\end{aligned}\]



