#+TITLE: Assignment 12: cross product
* cross product is distributive across addition
   
  #+BEGIN_QUOTE
  Show that
   \[\begin{aligned}
   \vec{A} \times \left( \vec{B} + \vec{C} \right)  &= \vec{A} \times \vec{B} + \vec{A} \times \vec{C}
   \end{aligned}\]
   #+END_QUOTE

    First, notice that each term in the previous equation is perpendicular to $\vec A$. Thus, we can consider compress this 3d problem into two dimensions. Let $\vec A$ point out of the page. Then, to show that the direction of $\text{proj}_{\vec A} \vec{B} + \vec{C}$ is the same as $\text{proj}_{\vec A} \vec B + \text{proj}_{\vec A} \vec C$.

    They are the same because rotation is linear, ie. if $R_{90}$ is the rotation matrix (the result of $\vec A$ when looking at projections onto the plane), then 
    \[\begin{aligned}
    R_{90} \left( \vec{A} + \vec{B} \right)  = R_{90} \left( \vec{A} \right)  + R_{90} \left( \vec{B} \right)  
    \end{aligned}\]

*** proof that rotation is additive
    
    Deconstruct the input vector into its components. You can rotate the coordinate system and notice that the sum of the rotated components is still the same as the rotated sum. 

    
*** magnitude of cross product distributivity
    
    For the magnitude
    \[\begin{aligned}
    \lvert \vec{A} \rvert  \lvert \vec{B} + \vec{C} \rvert \sin  \theta &= \lvert \vec{A} \rvert \left( \vec{B} + \vec{C} \right)_{\perp A}\\
    &= |\vec{A}| \vec{B}_{\perp \vec{A}} + |\vec{A}| \vec{C}_{\perp \vec{A}}\\
    &= |\vec{A}| |\vec{B}| \sin  \theta  + |\vec{A}| |\vec{C}| \sin  \theta 
    \end{aligned}\]


    
* use distributivity to derive the algebraic form
  
  \[\begin{aligned}
  \vec{A} \times \vec{B} &=  \left( \vec{A}_x \hat{i} + \vec{A}_y \hat{j} + \vec{A}_z \hat{k} \right)  \times \left( \vec{B}_x \hat{i} + \vec{B}_y \hat{j} + \vec{B}_z \hat{k} \right)\\
  \end{aligned}\]
  
  \[\begin{aligned}
 &= \vec{A}_x \hat{i} \times \vec{B}_x \hat{i} &&+ \vec{A}_x \hat{i} \times \vec{B}_y \hat{j} &&+ \vec{A}_x \hat{i} \times \vec{B}_z \hat{k}\\
 &+ \vec{A}_y \hat{j} \times \vec{B}_x \hat{i} &&+ \vec{A}_y \hat{j} \times \vec{B}_y \hat{j} &&+ \vec{A}_y \hat{j} \times \vec{B}_z \hat{k}\\
 &+ \vec{A}_z \hat{k} \times \vec{B}_x \hat{i} &&+ \vec{A}_z \hat{k} \times \vec{B}_y \hat{j} &&+ \vec{A}_z \hat{k} \times \vec{B}_z \hat{k}\\
 &= 0 &&+ \vec{A}_x \vec{B}_y \hat{k} &&- \vec{A}_x \vec{B}_z \hat{j}\\
 &- \vec{A}_y \vec{B}_x \hat{k} &&+ 0 &&+ \vec{A}_y \vec{B}_z \hat{i}\\
 &+ \vec{A}_z \vec{B}_x \hat{j} &&- \vec{A}_z \vec{B}_y \hat{i} &&+ 0\\
  \end{aligned}\]

  
  \[\begin{aligned}
 &= \left( \vec{A}_y \vec{B}_z - \vec{A}_z \vec{B}_y \right)  \hat{i} &+ \left( \vec{A}_x \vec{B}_z - \vec{A}_y \vec{B}_x \right)  \hat{j} &+ \left( \vec{A}_x \vec{B}_y - \vec{A}_z \vec{B}_y \right)  \hat{k}
  \end{aligned}\]

  Leonard's amazing mnemonic: ijkijkijk
  
* plane equation
  Plan: Perpendicular to the cross product of the differences.

   The points being $\vec{P_1}, \vec{P_2}, \vec{P_3}$

   Perpendicular to the perpendicular 
   \[\begin{aligned}
   \vec{n} =  \left( \vec{P_1} - \vec{P_2} \right)  \times \left( \vec{P_1} - \vec{P_3} \right)  
   \end{aligned}\]

   We know the plane is perpendicular to that normal $\vec n$, and offset by one of the $P_i$
   
   \[\begin{aligned}
   \vec{r} = \vec{r} : \left(\vec{r}-\vec{P_1} \right) \cdot \vec{n} = 0
   \end{aligned}\]

   Plugging in our definition of $\vec n$,
   
   \[\begin{aligned}
   \vec{r} &= \vec{r}: \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \left( \vec{P_1} - \vec{P_2} \right)  \times \left( \vec{P_1} - \vec{P_3} \right) \right)  = 0\\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_1} \times \vec{P_1} + \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( 0 + \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} \right)  + \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \vec{P_1} \times \vec{P_2} \right)     + \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} \right)  + \vec{r} \cdot \left(  \vec{P_1} \times \vec{P_2} \right)  + \vec{r} \cdot \left( \vec{P_1} \times \vec{P_3} \right)   = 0
   \end{aligned}\]
   
* trying it with a set of numbers
  
  \[\begin{aligned}
  \vec{P} &= ( 2, 0, -1 )\\
  \vec{Q} &= ( 0, 1, 3 ) \\
  \vec{R} &= ( 0, -2, 4)\\
  \vec{Q} - \vec{R} &= ( 0, 3, -1 )\\
  \vec{P} - \vec{R} &= ( 2, 2, -5 )
  \end{aligned}\]
  
  Cross product time
  \[\begin{aligned}
  n &= \left| \begin{matrix}\hat{i}  & \hat{j}  & \hat{k}  \\ 0 & 3 & -1 \\ 2 & 2 & -5\end{matrix} \right|\\
  &= (-15 + 2) \hat{i} + (-2) \hat{j} + (-6) \hat{k} \\ 
  &=\left( -13, -2, -6 \right)\\
  \end{aligned}\]


  
  \[\begin{aligned}
  \vec{r} \cdot \vec{n} &= \vec{P} \cdot \vec{n}\\
  -13x - 2y - 6z &= -26 + 6 &= -20\\
  13x + 2 + 6 &= 20
  \end{aligned}\]


