:PROPERTIES:
:ID:       19B0494D-B7E6-448D-ABA8-41A977195BB8
:END:
#+title: Gyroscoop
#+author: Houjun Liu

* Precessional Velocity
Taking the setup, we can figure the sum of the angular momentums and leverage it to figure the spin angular momentum.

Let's first define a system: $\hat{i}$ is "right" on the figure, $\hat{j}$ "in" the page, $\hat{k}$ "up" the figure.

We note that the normal spin of the flywheel gives us:

\begin{equation}
   \vec{L}_s = I\vec{\omega}_s \hat{i}
\end{equation}

As the flywheel is rotating at a constant speed, we have actually no torque that this contributes to the net system --- that is $\frac{d\vec{L}_s}{dt} = 0$. 

Furthermore, we can figure torque---and subsequent angular momentum contribution---of gravity as follows:

\begin{equation}
    \vec{\tau}_g = lmg \hat{j}
\end{equation}

The total net torque on the system, then:

\begin{align}
   \vec{\tau}_{net} &= \vec{\tau}_g + 0 \\
&= \vec{\tau}_g
\end{align}

We also have that:

\begin{equation}
   \vec{\tau}_{net} = \frac{\vec{L}_{net}}{dt} = \Delta \vec{L}_s = lmg
\end{equation}

We see that, because of small-angle approximation, $\Delta \vec{L}_s = L_s \Omega$

Therefore, we can replace the values determined above and solve for $\Omega$:

\begin{align}
    &\Delta \vec{L}_s = L_s \Omega\\
\Rightarrow\ & lmg = I\vec{\omega}_s \Omega\\
\Rightarrow\ & \Omega = \frac{lmg}{I\vec{\omega}_s}\ \blacksquare
\end{align}

* Discussion Questions

** Gyro in the Opposite Direction
If $\omega_s$ was in the opposite direction, $\vec{L}_s = -\vec{L}_s_{old}$ --- by the right hand rule, it would be in the other direction.

The direction of procession would be in the same direction, "into" the page, by the $\hat{j}$ direction.

Therefore, the direction of $\vec{L}_s$ would be inching up and to the right---resulting in procession in the opposite ("clockwise") direction.

** Tilted Gyro
In our expressions above, the thing that will change is the fact that the value of $r\times F$ for $\vec{\tau}_g$ would change to account for the angle $\phi$: $\vec{\tau}_g = l\sin\tau mg$.

Therefore, the final expression $\Omega$ becomes:

\begin{equation}
   \Omega = \frac{lmg\sin \tau}{I \vec{\omega}_s} 
\end{equation}

** Biker
If a bicyclist leans towards the right, they are adding a small "forward" change to the angular momentum originally pointing strictly towards the left. This would orient the axis of rotation a little bit more towards the forward direction from being completely towards the left, which points the axis a little more towards the front.

The bike then responds to this axis change by turning to an angle orthogonal (per the right hand rule) to the location a little "more forward", which is a little "more right."

** Forces on the COM

*** Normal Force and Torque
When the gyro is precessing, it performs uniform circular motion by a radius $l$. We see that, as determined above, it is precessing at a constant speed of $\frac{lmg}{I\vec{\omega}_s}$.

Therefore:

\begin{equation}
   \frac{v^2}{R} = a = \frac{lm^2g^2}{I^2{\vec{\omega}_s}^2}
\end{equation}

The net horizontal force on the object can be modeled by:

\begin{equation}
   \vec{F}_{net} = -T
\end{equation}

Therefore:

\begin{align}
   &ma = -T \\
\Rightarrow\ & T = -\frac{lm^3g^2}{I^2{\vec{\omega}_s}^2}
\end{align}

Given, though tension, the gyro is exerting this amount of force upon the stand, the stand's normal force in the opposite direction (i.e. horizontal, in the "negative" direction) would be: $\frac{lm^3g^2}{I^2{\vec{\omega}_s}^2}$.

When the gyroscope is simply limp, it would hang with a weight of $mg$. Calculations with tension work in a similar manner, resulting in the fact that the normal force would be $mg$.

The gyroscope can't just fall, under this circumstance, when spinning as, per what we deduced above, there is a /large/ tension which is applied to the flywheel due to its rotation.

Per the torque (prime frame) theorem, we can define an origin at the "horizontal" center of mass position of the flywheel. The CoM begins with of course no sag---rending $r$ vector being zero--but should the flywheel deviate from its original horizontal position, $r\times T$ would result in a torque component /out of the page/, which counters the torque provided by gravity /into the page./

*** "Push" force and "Pull" force
Acceleration due to gravity is the force by which the center of mass is "pushed" into a precessional acceleration. However, the tension from the pole "pulls" the object from simply rotating and falling over and instead providing centripetal acceleration.

*** Net Direction of Force by Stand
The stand would be providing for a force towards the "left" ($-\hat{i}$) oriented horizontally, in the same direction as the tension.

*** Impulse
This is a very quick application question of the same principle. 

The direction of presession, as we have established before, is consistent with the direction of the angular momentum change resulting from the added torque. By the right hand rule, we can figure that the direction of procession should be towards the "right" of the figure, along $+y$.

We first setup the problem by defining, presumably, $\tau = Fl$. 

We again find that:

\begin{equation}
   \frac{d\vec{L}}{dt}  = \tau_{net} = Fl = \vec{L}\Delta \phi
\end{equation}

where, $\Delta \phi$ is the angular velocity by which $\vec{L}$ rotates.

Therefore:

\begin{equation}
 \Delta \phi = \frac{Fl}{\vec{L}} = \frac{\tau}{L} = \Omega\ \blacksquare
\end{equation}

* Some Dynamics
