:PROPERTIES:
:ID:       C2B581FF-9F7D-4328-AA8E-33148264B060
:END:
#+title: MVC 2 PS#27
#+author: Houjun Liu

* Electric Change
We are finally taking a surface integral! This is essentially multiplying the surface area of the shape of the function to the value of the function itself.

Firstly, taking the area $dA$ by $dV$:

\begin{align}
   dA &= \sqrt{1+\left(\frac{\partial z}{\partial x}\right)^2+\left(\frac{\partial z}{\partial y}\right)^2} \\
&= \sqrt{1+\left(3\right)^2+\left(2\right)^2} \\
&= \sqrt{14} 
\end{align}

Supplying the value into the function:

\begin{align}
   &\int_0^7 \int_0^{11} (3x+2y+7)\sqrt{14}\ dy\ dx\\
\Rightarrow &\sqrt{14}\int_0^7 \int_0^{11} (3x+2y+7)\ dy\ dx\\
\Rightarrow &\sqrt{14}\int_0^7 \left (3xy+y^2+7y)\right|_0^{11} \ dy\ dx\\
\Rightarrow &\sqrt{14} \left\left(\frac{33x^2}{2}+198x\right)\right|_0^7\\
\Rightarrow & \frac{4389\sqrt{14}}{2}
\end{align}

The charge, therefore, is proportional to $\frac{4389\sqrt{14}}{2}\rho$.

* Infinite wire
Recall first that a semicircle with radius 7 can be defined as:

\begin{align}
   y &= \sqrt{7^2 - x^2} \\
&= \sqrt{49 - x^2}
\end{align}

Let's first figure the value of this function $dA$:

\begin{align}
   dA &= \sqrt{1+\left(\frac{d}{dx}\sqrt{49-x^2}\right)^2} \\
&= \sqrt{1+\left(\frac{d}{dx}\sqrt{49-x^2}\right)^2}\\
&= \sqrt{1-\frac{x^2}{x^2-49}}
\end{align}

We will take the line integral of this function, and proceed to multiply by the value of $xy$ at that point.

\begin{equation}
   \int_0^7 \int_0^7\ xy\ \sqrt{1-\frac{x^2}{x^2-49}}\ dx\ dy
\end{equation}

#+begin_src sage
f(x,y) = x*y*sqrt(1-x^2/(x^2-49))
f.integrate(x, 0,7).integrate(y,0,7)
#+end_src

#+RESULTS:
: 2401/2

Looks like the solution for the wire's weight is about $\frac{2401}{2}$ grams.

