:PROPERTIES:
:ID:       E6E7D8CC-AAD2-4C16-A851-C6FC4A6DB128
:END:
#+title: MVC 2 PS#30
#+author: Houjun Liu

* Jacobian Determinant for Polar
We are to determine (pun not intended) the polar correction factor for a double integral, $dA= r\ dr\ d\theta$.

To do this, we will have to first figure the change of bases expressions such that we can take:

\begin{equation}
   f(x,y) = g(r, \theta) 
\end{equation}

Fortunately, this is already derived to use from before.

\begin{equation}
   \begin{cases}
   x = r\cos\theta \\
   y = r\sin\theta \\
\end{cases}
\end{equation}

Therefore, we have that:

\begin{equation}
   f(x,y) = f(r\cos\theta, r\sin\theta) 
\end{equation}

And therefore, we can figure $J_{r,\theta}$:

\begin{equation}
   J = \begin{bmatrix} 
cos\theta & -r\sin\theta \\
sin\theta & r\cos\theta \\
\end{bmatrix} 
\end{equation}

Taking its determinant, then:

\begin{equation}
   det(J) = r\cos^2\theta +r\sin^2\theta = r
\end{equation}

And therefore, the change-of-basis result would be:

\begin{equation}
   dx\ dy = r\ dr\ d\theta 
\end{equation}

* Jacobian Determinant for Spherical
We again need to figure a correction factor for $dx\ dy\ dz = \rho^2\ \sin\phi\ d\rho\ d\theta\ d\phi$.

We therefore have to figure a change of bases for the expression:

\begin{equation}
   f(x,y,z) = g(\rho, \theta, \phi) 
\end{equation}

We can leverage the shape of the object to determine the parameterization:

\begin{equation}
   \begin{cases}
   x = \rho\sin\phi\cos\theta \\
   y = \rho\sin\phi\sin\theta \\
   z = \rho\cos\phi \\
\end{cases}
\end{equation}

We will now figure the matrix for $J_{\rho, \theta, \phi}$:

\begin{equation}
   J = \begin{bmatrix} 
sin\phi\cos\theta & -\rho\ sin\phi\sin\theta & \rho\ cos\phi\cos\theta \\
sin\phi\sin\theta & \rho\ sin\phi\cos\theta & \rho\ cos\phi\sin\theta \\
cos\phi & 0 & -\rho \sin \phi\\
\end{bmatrix} 
\end{equation}

 #+begin_src sage
var("rho phi theta")
M = matrix([[sin(phi)*cos(theta), -rho*sin(phi)*sin(theta), rho*cos(phi)*cos(theta)], [sin(phi)*sin(theta), rho*sin(phi)*cos(theta), rho*cos(phi)*sin(theta)], [cos(phi), 0, -rho*sin(phi)]])
M
M.det().full_simplify()
 #+end_src

 #+RESULTS:
 : (rho, phi, theta)
 : [     cos(theta)*sin(phi) -rho*sin(phi)*sin(theta)  rho*cos(phi)*cos(theta)]
 : [     sin(phi)*sin(theta)  rho*cos(theta)*sin(phi)  rho*cos(phi)*sin(theta)]
 : [                cos(phi)                        0            -rho*sin(phi)]
 : -rho^2*sin(phi)

Not quite sure why Sage didn't simply $(-\rho)^2$ into $\rho^2$, but, we can see that:

\begin{equation}
   dx\ dy\ dz = \rho^2\sin\phi\ d\rho\ d \theta\ d\phi 
\end{equation}

* Surface area in polar
Given the fact that:

\begin{equation}
  dA = \sqrt{1 + \left(\frac{\partial f}{\partial x}\right)^2 + \left(\frac{\partial f}{\partial y}\right)^2}\ dx\ dy
\end{equation}

We are to figure the corresponding for a function in polar.

I suppose we can work this out as if we are doing traditional u-substitution: that is, we are to find a function that corrects for the correction factor as well as the $dx$ and $dy$ components.

Recall again, that:

\begin{equation}
   \begin{cases}
   x = r\cos\theta \\
   y = r\sin\theta \\
\end{cases}
\end{equation}

Furthermore: per the chain and total derivative rule, we have that:

\begin{equation}
   \frac{\partial f}{\partial x} = \frac{\partial f}{\partial \theta}\cdot \frac{\partial \theta}{\partial x} + \frac{\partial f}{\partial r}\cdot \frac{\partial r}{\partial x}
\end{equation}

and,

\begin{equation}
   \frac{\partial f}{\partial y} = \frac{\partial f}{\partial \theta}\cdot \frac{\partial \theta}{\partial y} + \frac{\partial f}{\partial r}\cdot \frac{\partial r}{\partial y}
\end{equation}

To actually figure this, then, we have to find expressions for each of the rightward partials.

Take, first, $\frac{\partial \theta}{\partial x}$; we have:

\begin{align}
   &x = r\ cos\theta \\
\Rightarrow &\frac{\partial}{\partial x} x = \frac{\partial}{\partial x}r\ cos\theta \\
\Rightarrow &1 = -r\ sin\theta \frac{\partial \theta}{\partial x}\\
\Rightarrow &\frac{\partial \theta}{\partial x} = \frac{-1}{r\ sin\theta} 
\end{align}

Furthermore, for $\frac{\partial r}{\partial x}$

We have, trivially:

\begin{equation}
\frac{\partial r}{\partial x} = \frac{1}{cos\theta}
\end{equation}

Therefore:

\begin{equation}
   \frac{\partial f}{\partial x} = -\frac{\partial f}{\partial \theta}\cdot \frac{1}{r\sin\theta} + \frac{\partial f}{\partial r}\cdot \frac{1}{\cos\theta}
\end{equation}

We can repeat this for $y$:

For $\frac{\partial \theta}{\partial y}$; we have:

\begin{align}
   &y = r\ sin\theta \\
\Rightarrow &\frac{\partial}{\partial x} x = \frac{\partial}{\partial x}r\ cos\theta \\
\Rightarrow &1 = r\ cos\theta \frac{\partial \theta}{\partial x}\\
\Rightarrow &\frac{\partial \theta}{\partial x} = \frac{1}{r\ cos\theta} 
\end{align}

Furthermore, for $\frac{\partial r}{\partial y}$

We have, trivially:

\begin{equation}
\frac{\partial r}{\partial x} = \frac{1}{sin\theta}
\end{equation}

Therefore:

\begin{equation}
   \frac{\partial f}{\partial y} = \frac{\partial f}{\partial \theta}\cdot \frac{1}{r\cos\theta} + \frac{\partial f}{\partial r}\cdot \frac{1}{\sin\theta}
\end{equation}

Lastly, we recall that $dx\ dy = r\ dr\ d\theta$

Finally, putting it all together:

\begin{align}
  dA &= \sqrt{1 + \left(\frac{\partial f}{\partial x}\right)^2 + \left(\frac{\partial f}{\partial y}\right)^2}\ dx\ dy\\
&= \sqrt{1 + \left(\frac{\partial f}{\partial r}\cdot \frac{1}{\cos\theta}-\frac{\partial f}{\partial \theta}\right)^2 + \left(\frac{\partial f}{\partial \theta}\cdot \frac{1}{r\cos\theta} + \frac{\partial f}{\partial r}\cdot \frac{1}{\sin\theta}\right)^2}\ dx\ dy\\
\end{align}
