:PROPERTIES:
:ID:       B4B3E271-626F-43A0-AE2C-5570D88376F9
:END:
#+title: MVC PS#17
#+author: Houjun Liu

\begin{enumerate}
\item Make a picture/graph of this situation, using your favorite technological 3D visualizer.
\item What's your elevation?
\item From your perspective, what does your hike look like? Meaning: your hike is some sort of one-dimensional path---what's the equation for it, and what does it look like (i.e., draw/make a picture)?
\item What's the function for the slope along your hike? (Draw a picture, too.)
\item How steep is the sand dune at the point you're standing (in the direction you're hiking)? Give the answer both in slope units, and as an angle up from the horizontal.
\end{enumerate}

* Taylor Series in $e^x$
#+begin_quote
Calculate, from the big scary formula, the Taylor series for $e^x$, centered around $x=2$. 
#+end_quote

\begin{equation}
   f(x) = e^x = e^2 + e^2(x-2) + \frac{e^2(x-2)^2}{2} + \frac{e^2(x-2)^3}{3} \cdots + \frac{e^2(x-2)^n}{n} 
\end{equation}

* Diff. in Higher Dimensions

** Derivative Matrix 14
#+begin_quote
Find the derivative matrix of 

\begin{equation}
f:\mathbb{R}^4 \to \mathbb{R}^5; f(x_1,x_2,x_3,x_4) = \begin{bmatrix}
x_1 x_3 \\
\tan(x_4) \\
-\ln(x_2) \\
(3x_1-2)^4 \\
1729
\end{bmatrix}
\end{equation}
#+end_quote

