:PROPERTIES:
:ID:       733B42A4-486E-4F66-A4BC-14527BB2DDA6
:END:
#+title: MVC 2 PS#28
#+author: Houjun Liu

* Evaluating a Cylindrical Integral 
#+begin_quote
Considering the function: 

\begin{equation}
   f(x,y,z) = \sqrt{x^2+y^2} 
\end{equation}
#+end_quote

To evaluate the integral, we will convert it to cylindrical coordinates. We note first that the integral is to be evaluated inside the cylinder of $x^2+y^2 = 16$, which means that we wish to evaluate it in a circle with center at the origin with radius $4$.

Furthermore, we understand that the bounds of the function are to be evaluated between $[-5, -4]$.

If we set up the integral, we will get:

\begin{equation}
   \int_{-5}^{-4} \int_C\ \sqrt{x^2+y^2}\ dx\ dy\ dz 
\end{equation}

This is convenient. We can evaluate the inner integral first like in $\mathbb{R}^2\to\mathbb{R}^1$, then simply evaluate the other integral after.

Let's do so.

Note that the inner integral is a normal cylindrical coordinate setup. Therefore, we can take the following substitution:

\begin{equation}
   \sqrt{x^2+y^2} = r 
\end{equation}

Furthermore, that:

\begin{equation}
   dx\ dy = dr\ d\theta 
\end{equation}

With the appropriate bounds, then:

\begin{align}
   &\int_0^{2\pi} \int_0^4 r\ dr\ d\theta\\
\Rightarrow &\int_0^{2\pi} \left \frac{r^2}{2}\right|_0^4 d\theta\\
\Rightarrow &\int_0^{2\pi} 8\ d\theta\\
\Rightarrow &16\pi
\end{align}

Finally, we will take the integral of this value $dz$:

\begin{equation}
   \int_{-5}^{-4} 16\pi\ dz  = 16\pi
\end{equation}

Therefore, the value of the integral is $16\pi$.

* Uselessly Spherical Integral
We first recall that the differential volume can be written as:

\begin{equation}
   dV = \rho^2 \sin \phi\ d\rho\ d\phi\ d\theta
\end{equation}

To take this integral, then, we have to figure the distance $\rho$ to a rectangle for every point $(\phi, \theta)$.

We will take this integral w.r.t. one quadrant of the four parts of the rectangle, then we will scale it up by $4$. Each of the quadrants are divided into again two equally-sized pieces: one sweeping from the baseline until halfway up, the other sweeping halfway up until the center line. These are the areas where either the adjacent side is consistently $\frac{b}{2}$ or the opposite side is consistently $\frac{a}{2}$.

The switch happens exactly at the triangle where the bottom side has length $\frac{b}{2}$ and the right side has length $\frac{a}{2}$. This triangle, per the definition of arctan, has an angle of:

\begin{equation}
   \theta = \tan^{-1}\left(\frac{a}{b}\right) 
\end{equation}

Therefore, from $\theta = [0, \tan^{-1}\left(\frac{a}{b}\right)]$, we have sidelength $\frac{b}{2\cos\theta}$. From $\theta = [\tan^{-1}\left(\frac{a}{b}\right), \frac{\pi}{2}]$, we have sidelength $\frac{a}{2\sin\theta}$.

By the same token, for the vertical declination, from $\theta = [0, \tan^{-1}\left(\frac{a}{b}\right)]$, $\phi = [0,\tan^{-1}\left(\frac{c}{b}\cos\theta\right)]$, we have $\rho=\frac{b}{2\cos\theta\cos\phi}$. From $\theta = [\tan^{-1}\left(\frac{a}{b}\right), \frac{\pi}{2}]$, $\phi = [0,\tan^{-1}\left(\frac{c}{a}\sin\theta\right)]$, we have $\rho=\frac{a}{2\sin\theta\cos\phi}$. For all other $\phi$, $\phi = [\tan^{-1}\left(\frac{c}{b}\cos\theta\right), \frac{\pi}{2}]$, we have the $\frac{c}{2}$ term taking precedence and hence $\rho = \frac{c}{2\sin\phi}$. 

Therefore, we will have to take the quarter-integral in three parts:

\begin{align}
&\int_0^{\tan^{-1}\left(\frac{a}{b}\right)} \int_0^{\tan^{-1}\left(\frac{c}{b}\cos\theta\right)} \frac{b}{2\cos\theta\cos\phi}\ d\phi\ d\theta\\
&\int_0^{\tan^{-1}\left(\frac{a}{b}\right)}\frac{b}{\cos\theta} \int_0^{\tan^{-1}\left(\frac{c}{b}\cos\theta\right)} \frac{2}{2\cos\phi}\ d\phi\ d\theta\\
\end{align}

