:PROPERTIES:
:ID:       7936CF0C-9DF1-44C7-840E-F79A497A376C
:END:
#+title: MVC 2 PS#31
#+author: Houjun Liu

* Correction factor in Cylindrical
For this question, we are actually essentially just doing the Jacobian determinant form for /cylindrical/ coordinates.

Turns out, this is actually just saying the same expression for polar, but doing it with an additional, trivial $z=z$ component.

\begin{equation}
   f(x,y,z) = g(r, \theta,z) 
\end{equation}

Fortunately, this is already derived to use from before.

\begin{equation}
   \begin{cases}
   x = r\cos\theta \\
   y = r\sin\theta \\
   z = z
\end{cases}
\end{equation}

We can then figure out, then the Jacobian determinant. Since the last parameter is $z=z$, we have:

And therefore, we can figure $J_{r,\theta,z}$:

\begin{equation}
   J = \begin{bmatrix} 
cos\theta & -r\sin\theta & 0\\
sin\theta & r\cos\theta & 0\\
0 & 0 & 1
\end{bmatrix} 
\end{equation}

The determinant would still, unsurprisingly, be $r$: you can see this by the fact that each of the "valued" column is multiplied by $1$, and the last column's determinant is just canceled by $0$.

Taking its determinant, then:

\begin{equation}
   det(J) = r\cos^2\theta +r\sin^2\theta = r
\end{equation}

And therefore, the change-of-basis result would be:

\begin{equation}
   dx\ dy\ dz = r\ dr\ d\theta\ dz
\end{equation}

* Frankenstein coordinates
It seems like Frankenstein coordinates are .
