:PROPERTIES:
:ID:       7EA64C6E-FEA3-45DB-A291-C904DC7C4A79
:END:
#+title: Self Evals: PHYS360 Sem. 1
#+author: Houjun Liu

Describe an important or interesting learning experience that you had in Advanced Mechanics.  What message can you take away from that experience, being a life-long learner. Or write about anything else you'd prefer to write about related to your growth as a learner or about this class.

What was most fruitful for me in advanced mechanics was the marble bead launcher experiment. It highlighted for me the need of cross-disciplinary exploration even when exploring a specific field like physics. My relative lack of mechanics construction skills forced me to spend longer testing out ideas that others may have been able to execute in a very short period of time. For instance, the construction of the marble launcher had been missexecuted a few times before we were able to actualize the numerical construction. Through this experience, I learned to be more conscientious of the other sides of engineering which may, after a chance interaction, become important aspects of my work like fabrication did for mechanics today.
