#+TITLE: Cross Product
* the cross product
** geometric definition of magnitude
   
   \[\begin{aligned}
   \left| \vec{A} \times \vec{B} \right| = \left|\vec{A}_{\perp \vec{B}} \right| |B| = |\vec{A}| |\vec{B}| \sin  \theta 
   \end{aligned}\]
** geometric definition of the direction
   If you rotate the first vector towards the second, and use the right hand rule, then your thumb will point in the direction of the cross product. (Fingers curve in the direction of the first vector rotating towards the second).
* properties
** anticommutative
   
   \[\begin{aligned}
   \vec{A} \times \vec{B} = -\vec{B} \times \vec{A}
   \end{aligned}\]
** not associative 
   
   \[\begin{aligned}
    \left( \vec{A} \times \vec{B} \right) \times \vec{C} \neq  \vec{A} \times \left( \vec{B} \times \vec{C} \right)  
   \end{aligned}\]

   i.e.
   
   \[\begin{aligned}
    \left( \hat{i} \times \hat{i} \right)  \times \hat{j} = 0 \neq  \hat{i} \times \left(  \hat{i} \times \hat{j} \right)  = \hat{i} \times \hat{k} = - \hat{j}
   \end{aligned}\]

   How to remember cross products of i, j, k? If it's in consecutive alphabetical order, then the result is positive. Else, it's negative.
** associative with scalar multiplication
   
   \[\begin{aligned}
   \lambda  \left( \vec{A} \times \vec{B} \right)  = \left( \lambda \vec{A} \right)  \times \vec{B}
   \end{aligned}\]
** the product is a vector 
   \[\begin{aligned}
   \vec{A} \times \vec{B} = \vec{C}
   \end{aligned}\]
** R.H. rule defines the direction
   Point fingers in direction of first vector, curl towards direction of the second. thumb is the direction.
** measures of orthogonality / perpendicularity
   Maximum value for two vectors of same magnitudes is when the two vectors are orthogonal.
** cross product is perpendicular to both operands
** distributes over addition
   
   \[\begin{aligned}
   \vec{A} \times \left( \vec{B} + \vec{C} \right)  &= \vec{A} \times \vec{B} + \vec{A} \times \vec{C}
   \end{aligned}\]
*** proof
    First, notice that each term in the previous equation is perpendicular to $\vec A$. Thus, we can consider compress this 3d problem into two dimensions. Let $\vec A$ point out of the page. Then, to show that the direction of $\text{proj}_{\vec A} \vec{B} + \vec{C}$ is the same as $\text{proj}_{\vec A} \vec B + \text{proj}_{\vec A} \vec C$. They are the same because rotation is linear.

    
    For the magnitude
    \[\begin{aligned}
    \lvert \vec{A} \rvert  \lvert \vec{B} + \vec{C} \rvert \sin  \theta &= \lvert \vec{A} \rvert \left( \vec{B} + \vec{C} \right)_{\perp A}\\
    &= |\vec{A}| \vec{B}_{\perp \vec{A}} + |\vec{A}| \vec{C}_{\perp \vec{A}}\\
    &= |\vec{A}| |\vec{B}| \sin  \theta  + |\vec{A}| |\vec{C}| \sin  \theta 
    \end{aligned}\]

* uses
** finding a plane containing points
   
   The points being $\vec{P_1}, \vec{P_2}, \vec{P_3}$

   Perpendicular to the perpendicular 
   \[\begin{aligned}
   \vec{n} =  \left( \vec{P_1} - \vec{P_2} \right)  \times \left( \vec{P_1} - \vec{P_3} \right)  
   \end{aligned}\]

   We know the plane is perpendicular to that normal $\vec n$, and offset by one of the $P_i$
   
   \[\begin{aligned}
   \vec{r} = \vec{r} : \left(\vec{r}-\vec{P_1} \right) \cdot \vec{n} = 0
   \end{aligned}\]

   Plugging in our definition of $\vec n$,
   
   \[\begin{aligned}
   \vec{r} &= \vec{r}: \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \left( \vec{P_1} - \vec{P_2} \right)  \times \left( \vec{P_1} - \vec{P_3} \right) \right)  = 0\\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_1} \times \vec{P_1} + \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( 0 + \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} - \vec{P_1} \times \vec{P_2} - \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} \right)  + \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \vec{P_1} \times \vec{P_2} \right)     + \left( \vec{r} - \vec{P_1} \right)  \cdot  \left( \vec{P_1} \times \vec{P_3} \right)  \\
   &= \left( \vec{r} - \vec{P_1} \right)  \cdot \left( \vec{P_2} \times \vec{P_3} \right)  + \vec{r} \cdot \left(  \vec{P_1} \times \vec{P_2} \right)  + \vec{r} \cdot \left( \vec{P_1} \times \vec{P_3} \right)  
   \end{aligned}\]



