#+AUTHOR: Exr0n
#+TITLE: Module 2 Group Test Prelim

* Openstax Calc vol 1 chap 2.4 ex 134
  $$g(t) = \frac{1}{t}+1$$ which is basically $\frac{1}{x}$ shied up by one, so there is an $\boxed{\text{infinite discontinuity at} x=0}$
* 136
  There is a jump discontinuity at $x=2$, because normally $y=\frac{x}{x}$ simplifies to $y=1$, but the sign flips at $x=2$.
* 142
  $$f(y) = \frac{\sin(\pi y)}{\tan(\pi y)} = \frac{\cancel{\sin(\pi y)} \cos(\pi y)}{\cancel{\sin(\pi y)}}$$
  So there is a removable discontinuity at $y=1$, because there is a discontinuity but it can be removed with algebra.
* 148
  $$\begin{aligned}e^{4k} = 4+3\\e^{4k}=7\\4k=\ln(7)\\k=\frac{\ln(7)}{4}\end{aligned}$$
* TODO 174
  Prove $f(x)$ is continues everywhere, meaning show that $\forall c\in \mathbb{R}$
  $$\lim_{x\to c} f(x) = f(c)$$
  Because we can always evaluate $f(x)$, the limit always exists.
* Paul's online math notes Section 2-9: 23
  The IVT states that when a function is continuous over a closed interval $[a, b]$, then for all $\min\{f(a), f(b)\} \le y \le \max\{f(a), f(b)\}$ there exists some $a \le c \le b$ s.t. $f(c) = y$.
  In this case, we have $f(4) = 193$ and $f(8) = -511$. $f(x)$ is a polynomial, so it is continuous over the range. Because our values stradle zero, there must be some value $4 \le c \le 8$ s.t. $f(c) = 0$.
* Boundedness theorem
  Given a function $f(x)$ that is continuous on a closed interval $[a, b]$, there exists some $M \in \mathbb R$ s.t. $f(c) \le M$ for all $a \le c \le b$ aka $M$ is an upper bound on $f(x)$ over the interval $[a, b]$. There's also one that's less than all $c$. Doesn't work for open intervals.
** $(0, 1]$: not continuous, not a closed interval
** $[0, 1)$: not a closed interval
** $(0, 1]$: not a closed interval
** $(0, 1]$: not continuous, not a closed interval
** $f(x) = \frac{1}{x}$: not continuous
* Epilouge
  Other than Problem 5, this took roughly 40 minutes. I still don't know how to do problem 5..
