#+TITLE: N.R. Hanson

*Bold for comments*, plain for description of N.R. Hanson's arguments

* 1A
Raises the topic of how we compare novel phenomena to existing phenomena. When viewing a cell, is the dark splotch of matter an organ or a clot? Is an amoeba fit for comparison with an animal or a cell. Two people observe different things, yet their subject is the same.

An explanation: they make the same observation yet intepret what they see differently. Then how do theories mould data?

Describes seeing as an 'experience' as retinal reactions are chemical states. Cameras and eye-balls are blind as they merely react to photons, it is our brain that inteprets them.

* 1B
One could represent what they see by drawing a representation of a cube on paper. When observing such a figure, one could construe it as many different things: a cube viewed from below or above, just a number of crisscrossed lines, or the frame for a kite.

The solution of intepretation can be used to explain this: while retinal reactions are the same, it is our /interpretation/ that varies. This raises the idea that one does two things when they partake in seeing.

*These ideas continue to be repeated once more with another example but mentions the following:*
#+BEGIN_QUOTE
this difference is due neither to differing visual pictures, nor to any 'interpretation' superimposed on the sensation.
#+END_QUOTE

Context controls the experience of seeing, where depending on a choice of frame, antelopes can be made to look like seagulls. Context is part of the illustration and is part of the intepretation process.
#+BEGIN_QUOTE
Seeing is not only the having of a visual experience; it is also the way in which the visual experience is had.
#+END_QUOTE

Seeing also depends on the observer: both the layman and the physicist/artist/surgeon can see, but each see things differently.

* 1C
Observation of something is defined by prior knowledge of it.

*Of particular interest is the following quote:*
#+BEGIN_QUOTE
Another influence on observations rests in the language or notation used to express what we know, and without which there would be little we could recognize as knowledge.
#+END_QUOTE

Seeing is knowledge, as it is to understand and intepret objects. (*Note that this is in contradiction to [[id:556b40ed-43b4-46ae-83ec-1ee942a46743][Theaetetus]]*)
