#+TITLE: Gradients
#+SETUPFILE: ~/Dropbox/setupfile.org
#+filetags: fledgling

A gradient is a vector of all of the [[file:partial-derivatives.org][partial derivatives]] of a multivariable function usually denoted by the symbol $\nabla$. For a function $f$, $\nabla f$ points in the direction of the greatest increase in the function - as the gradient itself is a vector, and in order to see how your unit vector (a single "step") away from your initial point affects the function one would compute the dot product of the gradient and the unit vector. To maximize the positive change one would want to maximize the dot product, and a vector pointing in the same direction as the gradient would maximize the change. 

As $\nabla f$ is a vector-valued function, it can be easily represented by a [[./20200831153854-vector_field.org][vector field]]. Another representation of gradients is that of the contour map, and when superimposed upon the vector field the vectors in a gradient's field are always perpendicular to the contour line (the shortest path between two parallel or close to parallel lines is going to be the line perpendicular to them).

A gradient can be thought of as a differential operator like $\frac{d}{dx}$ or $\frac{\partial}{\partial x}$ that takes a function and returns it's own function that points in the direction of the greatest increase.

*EXAMPLE*
$f(x,y) = e^{2y}\sin{x}$
To find the gradient, one takes the partial derivative w/ respect to x, then w/ respect to y, and places them within a vector.
$\nabla f(x,y) = \big(\frac{\partial f}{\partial x} f(x,y), \frac{\partial f}{\partial y} f(x,y)\big) = (e^{2y}\cos{x}, 2e^{2y}\sin{x})$


* Sources
See [[https://www.khanacademy.org/math/multivariable-calculus/multivariable-derivatives/gradient-and-directional-derivatives/v/why-the-gradient-is-the-direction-of-steepest-ascent][this]] for more on subject.
