:PROPERTIES:
:ID:       5C925C70-28DE-4D7B-854C-0522F458729D
:END:

#+TITLE: Eurocentrism

Other large powers like the Ottoman Empire, the Ming dynasty, and more make it clearer that Europe was not "destined to rise" from the start. It was not clear by the times of the 1500s that Europe would succeed. 

One of the factors responsible for this was overextension of empires.

* The European Miracle
How did Europe go from a fragmented collective of states to a global hegemony?

** Growth through Exploitation
Marx claims that this relied on the advancement of science as well as increase of wealth/capital through the means of imperialism, slavery, and slave trade. Growth of Europe was on the backs of the weak and this was primarily _class struggle_.

** Protestant Work Ethic
Max Weber (see [[id:2F9754BC-EF10-435C-80EE-F007EA432B31][States]]) claims that it is because of sociological reasons and that Calvinism (branch of Protestantism) encouraged Europeans to be concerned with material gain and had "proto-capitalist ideals". This (according to Weber) was not the case in other states.

** Geology and Geography
Ken Pomeranz claims that Europe's divergence began in the 1900s with its access to coal and ability to trade with the New World. These two factors allowed Europe to grow and have an excess of labor.

** Environmental Determinism
Jared Diamond claims that this is because Europe had domesticable plants and animals, and its population had more resistance to disease. These two factors allowed more productivity and higher population density, leading to cities, institutions, and more.

** Separate but Whole
Based off of Kennedy's views, one could surmise that he believed it was because of the the geography in Europe that imposed a sectioning off into individual independent states that took place in frequent trade and commmunication of ideas. Another key point is that the independence prevented any large scale governmental mistakes, meaning that Europe was unable to figuratively shoot itself in the foot.

** Fewer Disadvantages
Another interpretation of Kennedy's views is the idea that Europe had less disadvantages than the competition.

