#+TITLE: Voltage
#+filetags: unresearched

PhET simulation from [[file:phys-fields-exp.org][Exploration of Fields/Voltage]] shows contour lines for the field's equipotential. A couple interesting things can be noted by utilizing one of the sensors: first that the direction of the sensor's force is always perpendicular to the contour line (for the exact same reason as [[file:20200830000157-gradients.org][gradients]] are), and second that the magnitude of the force is proportional to the density of the potential lines.

* Gravitational Potential
Gravitational potential energy is not present in a sole mass, but only exists/changes when the configurations of 2+ masses change. $PE_g$ is expressed in terms of differences as well (a rock lying on the ground has a $PE_g$ of "0", which is in fact relative to an arbitary point like a table or the ground).

To distinguish the $PE_g$ of a 1kg object at three different points on a mountainscape, one could refer to them by their relative height or $gh$. Units of $gh$ are m^2/s^2, a.k.a. J/kg. $gh$ is the _gravitational potential_ (note: *not* $PE_g$) of different heights relative to the ground.

* Electrical Potential
The equivalent of the gravitational potential (or $gh$) for the electrical force is electrical potential, the unit of which is called the Volt (which is equal to 1 J/C). For two points at 0V and 1V respectively, moving a charge of 1 C from 0V to 1V would increase its $PE_v$ by 1J (hence V = J/C). This means $\Delta PE_v = \Delta V Q$).

*EXAMPLE:* Moving a charge of 1C from the bottom to the top of a 1V battery would increase its electrical potential energy by 1.5J.

* Video Mini-Review
See [[https://iad.cdn.nv.instructuremedia.com/originals/o-adA9qAwy85sjgp4UbaH2sTRimQrcFVx/transcodings/t-aTb6kwimWTmWB3wCBMtxScpfPxqRas9.mp4?&Expires=1599349193&Signature=SQ6LR2EkhmXjz07ri-R0KUmvFpwjT3LtLWP59oUyrcov7Kz-FI6aFr8n-ljRljZVcB2KPnbK73IKUeIevgEnAzE8Y1f2ySjl2bBzguQAVMWdUxz0TXyCmxj8FvNH1WXDyYhm~lcy8XM6YhOrTnVcvXc2uEhD2w5imLCr2xw~95djFuQk5awotnBt6bajCNXYxKZ1PQUFdL3rz3fZq9i6yqvCWsW32-3AoIsudODhOkV7yCBTLZCdVCIiI5rkK3sVcQJxKXgyCokVBoPWcCbETkfkwrAcC8Pfw0OO97vNzpr-4zsmrvBY5Y176I8-zQb5feLcvrex8S4ZNeL0Sx6I9Q__&Key-Pair-Id=APKAJLP4NHW7VFATZNDQ][here]] at 24:00.
1) 4.5 J
2) 4.8 * 10^19 protons. 
