#+title: Exposure Control

* Exposure - Shutter Speed
Longer exposure lets more light hit the sensor. Higher exposure can capture more movement and vice versa. You can usually handhold 1/focal length and still get a sharp picture. Anything longer needs to be secured on a tripod.

* Exposure - Aperture
Aperture is the size of the iris opening. Larger apertures let in more light.

The actual setting on the camera is the /f-stop/ which is actually the _inverse_ of the aperture. Usual progression is 1.8, 2, 2.8, 4, 5,.6, 8, 11, 16, 22, 32. We can actually determine the size the opening by dividing $f$ by the f-stop. At a f-stop of 2, we can find the diameter of the iris opening via $\frac{50\text{mm}}{2} = 25\text{mm}$. Each f-stop in the progression lets in twice as much light as the previous f-stop.

* Exposure - [[file:20210921130010-iso.org][ISO]]
Range is usually from 100-25600. Increased sensitivity brings more noise because overall signal is lower so noise is higher relative to signal (also electrical noise because not all sensors are same). 

* Sensor Size
Larger sensor size means better image as more light can be captured properly and there's less noise. Larger sensors are quite expensive.

Old cameras had very large sensors. Part of the benefit of large sensors is that there's no need to enlarge the photo.

* Histogram
Bins that represent how much of the image is how bright (rightmost is maxed out, leftmost is no light). If there's a spike on the left that means that a lot of the image is dark, and vice versa. 

* Exposure Modes
| Mode | Shutter controlled by... | Aperture controlled by... |
| M    | Photographer             | Photographer              |
| Av   | Camera                   | Photographer              |
| Tv   | Photographer             | Camera                    |
| P    | Camera                   | Camera                    |
