#+title: Declaration of Independence


* What is the tone of this text? Which words lead you to that conclusion?
- Objective tone in the text, almost like this is a general fact/principle. Religious tone also adds to this. Words like "Nature's God" and "when in the course" presents it as a fact.
* What has “become necessary” ? What does this phrase imply about the actions taken by colonists prior to the declaration?
- To declare the reasons for their separation
  - Implies that it has already become necessary to separate
* How are American colonists described in this section? What implications does it have?
- Described as "one people"
  - United
* What does Jefferson mean by “Laws of Nature” and of “Nature’s God”? What does this reveal about his belief in human nature and government?
- Government tied to God
- Underscores idea of factuality and inevitability
* What “entitled” Americans to claim this separation? How does this justification affect their case for independence?
- the separate but equal stations to which God entitled them
  - Idea of freedom as human right
* What’s the key point in this portion of the text?
- They need to declare points of contention
* What questions does this text prompt?
- What reasons for separation?
* What are some ideas about government that are implied in the text?
- Government is a "power of the earth"
