#+title: Edmund Randolph

1. Do you favor greater power to the states or the national government? Why?
I strongly favor power to the federal government and wish for states to be held accountable to federal law. 
2. Should the new government be more concerned with protecting property rights or giving absolute democracy? Why?
No info available, although it seems as if he is most interested in allowing absolute democracy: he opposed a one-person executive branch because he thought it’d lead to monarchy, and he focused on his pitch for a bicameral legislative branch representing the people for the Convention.
3. What form would you like to see the legislative branch have? Why?
It should be a bicameral system where one chamber is determined by the population (for 3-year terms) and the other by state (with 7-year terms), satisfying both sides of the controversy. Both would have seats divided by population. 
4. How should representation in the legislature be determined? Why?
See above.
5. Shall Congress have the power to regulate and tax foreign trade? Why or why not?
No info available.
6. Which other delegates share your views?
- Worked with James Madison to make Virginia Plan. 
- Elbridge Gerry is also pro federal government and strong accountability for states. Governeur Morris also is pro federal government. 
- Technically agreed with Dickinson on Connecticut Compromise about two chambers. 
7. Which delegates would oppose you & why?
- John Dickinson is against central government, not pro-force against dissenters. William Patterson and Gunning Bedford Jr. were also anti-federalist. 
8. What questions, surprises, or contradictions did you discover researching your delegate?
My delegate was very in favor of a three-person executive branch (believed a one man executive branch was the “fetus of monarchy”), which is bizarre to think about from a modern perspective. He also thought that the federal government should have the right to use force to convince states to comply with federal laws, but was pressured out of including it in the Virginia Plan.
9. Cite your sources!
https://www.ushistory.org/germantown/people/randolph.htm
https://www.archives.gov/exhibits/treasures_of_congress/Images/page_1/8a.html

