#+TITLE:Mirror Exam Prep
#+COURSE: PHYS220
#+LATEX_HEADER: \usepackage[total={6in, 10in}, right=2in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \thispagestyle{empty}
#+LATEX_HEADER: \let\tempone\itemize
#+LATEX_HEADER: \let\temptwo\enditemize
#+LATEX_HEADER: \renewenvironment{itemize}{\tempone\addtolength{\itemsep}{-0.5\baselineskip}}{\temptwo}

*  Pinhole Cameras
You can create an image through allowing light to travel through small hole: light ray from bottom of object will graze the top of the hole, and vice versa. As a result, image is flipped upside down. Increasing the size of the hole increases the the brightness of the image but makes it blurrier. Increasing focal distance (in the case of the pinhole camera this is distance between hole and photosensitive material).

* Mirrors
#+begin_aside Aside: Specular vs. Diffuse Reflections
- /Specular/ reflections obey the Law of Reflection and are flat while /diffuse/ reflections happen on materials that are bumpy and scatter light.
#+end_aside

#+begin_defn Law of Reflection
- The Law of Reflection is that the angle of incidence is angle of reflection.
#+end_defn

** Plane and Right Angle Mirrors
- Plane mirrors intuitively follow the Law of Reflection and project a virtual image behind the mirror.
- Similarly, just following the Law of Reflection works fine for mirrors at right angles.

** Spherical & Parabolic Mirrors
- Parallel rays reflect through the focus
- Rays through the focus reflect parallel
- Rays through the center (of the _sphere_) reflect back through the center.
- Rays that reflect off the center of the _surface_ reflect according to the Law of Reflection

  
- Mirror equation is $\frac{1}{f} = \frac{1}{d_o} + \frac{1}{d_i}$ (derive via similar triangles)

- $\frac{d_i}{d_o} = \frac{h_i}{h_o}$ (NOTE: remember to only keep magnitude of $h_i$!)

- Center of sphere is twice as far as focal length? 

* Refraction
- Waves change direction when they encounter a medium that changes their speed.
- $n_1\sin\theta_1 = n_2\sin\theta_2$
- $n=\frac{c}{v}$ where v is speed of light in medium (and c = 299792458 m/s)
- Critical angle is the angle of total internal reflection: aka when refraction angle is $90^\circ$
- Remember that angles are relative to the /normals/!

* Rainbows

- Mediums can be /dispersive/, meaning that the velocity of light traveling through the medium varies with wavelength.
- Shorter wavelengths like violet have higher indices of refraction in a medium whilst longer wavelengths like red have smaller indices of refraction.
- This means that in a rainbow, colors like red will be at the top and blue at the bottom.


