:PROPERTIES:
:ID:       AF982AF7-0BEF-4CB6-B161-ECCB4FD3808C
:END:

#+TITLE: Proteins
#+STARTUP: indent showstars
#+filetags: :triage:

Proteins are the building blocks of much of our body. They are composed of some of the 21 different amino acids. Amino acids have multiple components attached to a carbon atom: a carboxyl group, amino group, and side chain. The side chain is what varies and differentiates the behavior of amino acids. These building blocks can be hydrophilic, hydrophobic, and charged.

* Structure/Folding

Proteins have primary structure (the combination of amino acids linked by peptide bonds that it is made of). A protein backbone is formed with the inclusion of the peptide bonds and is composed of a chain of carbons and nitrogens in the pattern N-C-C (with the central carbon having the side chain). These backbones determine secondary structure, of which there are two kinds: alpha helices and beta sheets. These are formed when hydrogen bonds form between specific parts of the amino acids within the protein. The properties of the R groups within protein's amino acids (charge, hydrophobic/philic) dictate its tertiary structure. Quaternary structure is when these forces act across proteins to form a multi-protein complex.

The process in which the structure of a protein is formed is called "protein folding". This process seeks to minimize entropy in a way akin to [[id:38DBBD6F-5BB0-4A8D-9995-C24A60FFE980][Gradient Descent]] and this is how folding takes place in a short time span (this is spontaneous because the surrounding water molecules gain entropy due to more possible configurations).

Proteins, similarly to [[id:C09869A6-EB7D-4543-A42B-BF14BE12B4C9][polymers]], are formed via combining amino acids via dehydration reactions.

Folding is the protein attempting to reach the lowest-energy state with the competing properties of its amino acids. [[id:92A321E4-2B43-4684-86B6-FB2670159549][The electrical force]] plays a part in the form of the charged amino acids, and these forces influence the folding process. pH can affect these charged amino acids, and by extension protein folding, via allowing some of the atoms within the amino acids to gain/lose electrons and lose their charges.

Proteins can be shifted by adding energy and disrupting its low-energy structure.

Note that this delicate balance of structure that takes in each amino acid's properties can also be influenced by outside molecules that are also hydrophobic/philic and charged.

* Simulation
The important role of protein folding in biology has caused it to become a topic of interest among other subjects as well. Protein folding is a algorithmically hard problem (NP-Hard, NP-Complete) and complex simulations attempting to efficiently solve this problem are used in the field.

More recently, fields like machine learning have made inroads in this problem with DeepMind's [[id:B53CD1E6-1CB9-4D7A-AA55-084A533BB3A8][AlphaFold]] algorithm utilizing gradient descent for the accurate prediction of protein folding.

See Ramachandran Plot for prediction of secondary structure.

* Roles
One of the roles of proteins within the body is allowing transport throughout cell membranes (as their [[id:A9B5E329-1FD1-4245-A5CB-FECB4AD714D3][lipid]] bilayers seek to keep everything out).
