:PROPERTIES:
:ID:       A9B5E329-1FD1-4245-A5CB-FECB4AD714D3
:END:
#+filetags: :fledgling:

#+TITLE: Phospholipids

A lipid is generally a hydrophobic and nonpolar structure made up of hydrocarbon chains. Phospholipids are a specialized variant of a lipid with a hydrophilic phosphate head and two fatty acid tails. These phospholipids form a bilayer: a structure where hydrophobic tails face the inside and hydrophilic heads face the outside. Phospholipids can also combine to form other stable arrangements such as micelles or liposomes (single layer and bilayer spheres respectively). 

Phospholipids form cell membranes (via bilayers), their stable arrangment protecting the cell and regulating entry to it.

Fat molecules are essentially polymers of lipids (fatty acids and glycerols). All hydrodphobic that exclude water.

Hydrophobic tails of micelles repel each other and spontaneously form the structure.
More carboxyl groups form larger aggregates as pH goes up and the large curvature and hydrogen bonds allow stable forming of liposomes.
