
#+TITLE: LinApprox + Differentials Quiz
#+SUBTITLE: Let's do this.
#+STARTUP: indent showstars

* Implicit Differentiation
The usual process:
1. Differentiate everything with respect to x
2. Apply the chain rule to functions left in the mix: since $(f(g(x)))' = g'(x) f'(g(x))$, $\frac{d}{dx}y^2 =  \frac{dy}{dx}y^2$.
3. Apply algebra to get $\frac{dy}{dx}$ on one side.
4. OPTIONAL(?): Convert back to explicit form by plugging in value of $y$.

** Common Problems and their Respective Approaches
*** Find the equation of the tangent/normal at (A,B)    
Remember that $L(a) = f(a) + f'(a)(x-a)$, and that'll give you tangent.
Normal line is just perpendicular of tangent, so $\frac{-1}{L(a)}$.
*** Find location of curve where tangent is /vertical/
Simply find what values of x and y make the tangent go to infinity.
System of equations with the derivative and the original implicit equation itself. You can make this faster with fractions by only using denom/numerator.
*** Find location of curve where tangent is /horizontal/
Same as above but solve for what makes tangent go to zero.
** Misc Tips
*** Pay attention to the original equations!
They're very useful in algebra!

* Derivatives of Inverse Functions
Formula for this is $(f^{-1}(x))' = \frac{1}{f'(f^{-1}(x))}$. 
  
* Derivatives of Inv. Trig Functions
Remember the derivs

** TODO Explicitly deriving

* Linear Approximations
$L(a) = f(a) + f'(a)(x-a)$
Plug in for appropriate a, and manually check for over/underestimation if problem asks.

** TODO Algebraically getting set accuracy bounds

* Differentials
$dy = f'(x)dx$

$-dx < dy < dx$
