#+TITLE: MIT SVC Exam Review (Unit 1)
#+STARTUP: indent showstars latexpreview
#+filetags: reviewpublish:

* Exam Review :unit1:

** Exponents (Continued)

$\lim\limits_{k\rightarrow\infty} a_k = (1+\frac{1}{k})^k$ as definition of $e$.

_Why?_
/PREVIOUSLY/ We found that $\lim\limits_{k\rightarrow\infty} \ln{a_k} = 1$.

As a result the limit of $e^{\ln{a_k}}$ will be $e^$.
$e^{\ln{a_k}} = a_k$ by properties of logs/exponents so $a_k = e$.

$e$ is approximated with this expression (by plugging in large values of $k$).

** Derivative of The Powers

Validate that the Power Rule is true for all real numbers.

_Method 1_

- $x^2 = (e^{\ln{x}})^r = e^{r\ln{x}}$
-$\frac{d}{dx} x^r = (e^{r\ln{x}})' = e^{r\ln{x}} (r \ln{x})'$ by chain rule.
$= x^r * \frac{r}{x}$ by both exponent rules and the fact that $r$ is a constant and the derivative of the log is $\frac{1}{x}$
$= rx^{r-1}$ and so Power Rule is correct.

_Method 2_

Logarithmic diffrentiation!

- -$u = x^r$ and take log: $\ln{u} = r \ln{x}$.
- $\frac{u'}{u} = (\ln{u})' = \frac{r}{x}$
- $u' = u * \frac{r}{x} = x^r * \frac{r}{x} = rx^{r-1}$

*NOTE:* The notation here is incredibly confusing! Note that the $\frac{y'}{y}$ is really implicit diffrentiation in disguise! Logarithmic differentiation diffrentiates the equation with respect to $x$ and so the same chain rule trickery applies. It is in fact $\frac{u}{dy}\frac{dy}{dx}$ where $u = \ln{y}$ but because the derivative of log is $\frac{1}{x}$ and we're using prime notation it looks like $\frac{y'}{y}$. but with Read up more thourough overview of the steps [[id:c44b175b-9593-4cab-995a-b4efcb5c744d][here]].

** The Natural Log

The natural log is natural.
Example: economics is a field where only ratios matter ("my stock went up by a dollar" depends on context). If FTSE went down by 27.9 today we'd only care about $\frac{\Delta p}{p} = \frac{27.9}{6432} = .43%$. However infinitesmal changes matter in this context as well as small timeframes can be important and so $\frac{p'}{p} = (\ln{p})'$ is used to model prices! Natural log is natural.

** Unit 1 Formula Review

*/// !! FILL ME IN !! ///*

*** General Formulas
- $(u+v)'$ = $u' + v'$
- $(cu)'$ = $cu'$
- $(uv)'$ = $u'v + v'u$
- $(u/v)'$ = $\frac{u'v - uv'}{v^2}$
- $(u(v(x))'$ = $v'(x) u'(v(x))$ (more generally $\frac{dx}{du}\frac{du}{dy} = \frac{dx}{dy}$)
- Implicit differentiation
  
  Implicit differentiation is a method of computing derivatives implicitly. Implicit equations are where the equation is not explicitly in the form y = ... but in a different form like $y^2 + x^2 = 1$. One can usually express the equation in an explicit form to avoid implicit differentiation but this process can be significantly simpler sometimes.

  First, one attempts to differentiate the entire equation with respect to x: $\frac{d}{dx} y^2 + 2x = 0$. This is all well and good but how is the derivative of the y term determined? A clever application of the chain rule: $\frac{du}{dy}\frac{dy}{dx} = \frac{du}{dx}$ and by declaring $u = y^2$ we get $2y\frac{dy}{dx} = \frac{du}{dx}$. Finally, solve for $\frac{dy}{dx}$ algebraically in the larger formula to get $\frac{-2x}{2y}$ or $\frac{-x}{y}$ and as $y = \sqrt{1-x}$ our final answer is $\frac{-1}{\sqrt{1-x}}$.

  - Inverses

    Simply structure the inverse as a implicit function.

    Example: $y = \sin^{-1}{x}$ is equivalent to $\sin{y} = x$.
    $\frac{d}{dx} \sin{y} = 1 \rightarrow \cos{y}\frac{dy}{dx} = 1 \rightarrow \frac{dy}{dx} = \frac{1}{\cos{y}} \rightarrow \frac{dy}{dx} = \frac{1}{\cos{(\sin^{-1}{x})}}$
    Finally, through trig identities, it can be reduced to $\frac{1}{\sqrt{1-x^2}}$

  - Logarithmic diffrentiation

    Another, albeit more confusing, application of implicit differentiation is logarithmic differentiation.

    Example: $y = x^x$ can be rephrased as $\ln{y} = x \ln{x}$ (Note that properties of logs help here)
    $\frac{d}{dx}\ln{y} = \ln{x} + 1$ (product rule), so $\frac{d}{dx}\ln{y} = \ln{x}$. $\frac{1}{y}\frac{dy}{dx} = \ln{x} \rightarrow \frac{dy}{dx} = y \ln{x}$ so $x^x (\ln{x} + 1)$
    
*** Specific Formulas
- $(x^r)'$ = $rx^{r-1}$
- $(\sin{x})'$ = $\cos{x}$
- $(\cos{x})'$ = $-\sin{x}$
- $(\tan{x})'$ = $\sec^2{x}$
- $(\sec{x})'$ = $\sec{x}\tan{x}$
  NOTE: See lecture for sec formula.
- $(e^x)'$ = $e^x$
- $(\ln{x})'$ = $\frac{1}{x}$
- $(\sin^{-1}{x})'$ = $\frac{1}{\sqrt{1-x^2}}$
- $(\tan^{-1}{x})'$ = $\frac{1}{x^2+1}$
- *REMEMBER*: You can easily derive many of these trig formulas through either implicit differentiation or the quotient rule.

** Chain Rule Tangent

Intuitive demo:
$y = 10x + b$, $y' = 10$ with respect to x.
$x = 5t + a$, $x' = 5$ with respect to t.
$y = 10(5t + a)+b = 50t + 10a + b$, $y' = 50$ with respect to t.

Also note that the quotient rule can be avoided with chain rule and product rule.

** Unit 1 Misc. Concept Review

 - Defined derivative as $f'(x) = \lim\limits_{\Delta x\rightarrow0} \frac{f(x+\Delta x) - f(x)}{\Delta x}$
   - Reviewed lots of functions like $\frac{1}{x}$, $x^n$, $\sin{x}$, $\cos{x}$, $a^x$. Note that the arguments for trig functions were done with case $x=0$.
 - Read Formula Backwards

   $\lim_{x\rightarrow0} \frac{f(x_0+\Delta x) - f(x_0)}{x-x_0} = f'(x)$

   See lecture for more details, essentially how the x=0 case works.

 - [X] You should be able to derive formulas for $(\sin^{-1}{x})'$ and $(\ln{x})'$ by implicit differentiation (as $y=\sin^{-1}{x}$ is the same as $\sin{y} = x$).
 - You will be expected to compute tangent lines as well as graph derivatives.
 - You will be expected to recognize differentiable functions by check if left/right tangents are equal.
