#+TITLE: Calculating Derivatives
#+STARTUP: indent showstars latexpreview

* Calculating Derivatives :unit1::derivatives:
** Types of Formulas
Two kinds of formulas, specific (for specific functions) and general. Both are needed to solve polynomials.
** Derivative of sin(x)
  This only works with radians!
Loose summary of derivation:
- $\lim_{x\rightarrow0} \frac{sin(x+\Delta x) - f(x)}{\Delta x}$
- Use trigonometric identities to expand the $sin(x+\Delta x)$ term.
  $sin(a+b) = sin(a)cos(b) + cos(a)+sin(b)$.
- Group the terms by plugging in the derivative at $x=0$ such that the resulting quotients end up cancelling.
$sin(x)\bigg(\frac{cos(\Delta x)-1}{\Delta x}\bigg) + cos(x)\bigg(\frac{sin(\Delta x)}{\Delta x}\bigg)$
Right side's quotient goes to $1$, left side goes to $0$, so the entire equation goes to $cos(x)$
  The derivatives of sin and cosine at $x=0$ give all values of the derivative of sine and cosine.
** Derivative of cos(x)
Similar derivation to above which yields $-sin(x)$.
** Some General Rules
- Product rule: $(uv)' = u'v + uv'$
- Quotient rule: $(\frac{u}{v})' = \frac{u'v - uv'}{v^2}$

* Links

 [[id:5ae60f81-8f87-44be-a5ad-e5770254168e][Differentiation Rules]] builds upon this.
