#+TITLE: Calculus Syllabus/Expectations

* Homework/Assessments
- Expect 30 min of homework per class
- All assessments are take-home
- List how much time each assignment takes you

* Syllabus
1. Limits
2. Continuity
3. Derivatives
4. Applications of Derivatives
5. Fall Culmination Project
6. Fundamental Theorem of Calculus
7. Integration
8. Applications of Integration
9. Differential Equations
10. Sequences
11. Series Convergence/Divergence
12. Taylor Series
13. Spring Culmination Project
* Expecations
/(verbatim from Canvas page)/

- All students will maintain a notebook where they will take notes on key concepts and some solved example problems.
- Students have HW assigned each time they meet that they will turn in online on Canvas. We will review HW assignments in class when students share their solutions with peers.
- The students will share their solutions and look for alternate approaches. The problem sets are meant for students to practice their mathematical reasoning and solidify content knowledge. 
- All students are expected to be collegial and create a safe space for all to learn/share their ideas.
- HW is graded for Habits of Mind attributes like Academic Habits and Community (sharing their solutions and classroom participation) as well as Skills and Practices attributes like Clarity and Articulation, Estimation, Precision and Accuracy.
- There will be one graded assessment every two to three weeks that will be turned in on paper so to provide timely feedback and assess understanding of content as well as skills and practices.
- These assessments, (written or oral), will be cumulative and build on prior knowledge. Students will be required to justify their work completely with proper mathematical vocabulary and logic.
- To demonstrate understanding of content and to show improvement, 
  - Correct the original assessment and show evidence of work to improve your understanding, such as revising/redoing previous assignments and coming in for help. 
  - Reassess up to two times beyond the original assessment.
