:PROPERTIES:
:ID:       E6A24F5F-78E0-4D74-97C6-4A92142A5F06
:END:

#+TITLE: Circuits

* Flow
While flow of charge within the wire is from positive to negative along with the E field, note that eleectrons are negatively charged and therefore go the opposite way (neg to pos).
* Convention
- Small side of battery symbol is negative.
- Line is wire
- Current is measured in amperes (1 C/s)
* Misconceptions
Electrons do not in fact move at the speed of light but it is because the electrons are present throughout the wire that a light appears to activate instantaneously (as the electrons next to it activate it). 
More current is more electrons moving in parallel.
* AC/DC
Alternating current has varying levels of power, so we use RMS to get one number.
* Kirchoff's Laws
1. Sum of all voltage changes in a closed loop in a circuit must be zero.
Think of a rollercoaster - changes in speed because of a decline must be regained as you climb back up the peak of the rollercoaster. The loop's net change is 0.
2. Sum of all currents entering a point in the circuit must be equal to the sum of all currents leaving the point.
* Arranging Circuits
** Series
The current goes into the first part of the circuit and then back out, into the next and out, and so forth. Sequentially. Each component therefore has the same current, although voltage can differ based on resistance.

** Parallel
Battery generates current which gets split into separate branches and each branch passes through a component simultaneously. Each component has same voltage across it, although current can differ based on resistance.
* DC Circuits
* Associated
  - [[id:3E0DE19B-4CC8-4620-BBFA-3C0699C8548C][Current]]
  - [[id:A22EC0AE-0F15-481E-B5ED-71F17D74088D][Capacitance]]
  - [[id:C99316E0-8DB0-4639-8093-50580E41E0FD][Semiconductors]]
  - [[id:EAE717D1-85F7-441B-A611-71E26F377752][Transistors]]
