#+TITLE: ENG201 Syllabus

* Content Focus
- Expanding skills + knowledge from ninth grade.
- Focusing more on the classics of the rest of the world (as opposed to the West).

* Guiding Questions
- How have the processes, effects, and tools of colonialism changed across time and place? What does colonialism mean in the 19th century, 20th century, and today? What does colonialism mean in different parts of the world? 
- How do different cultures understand the relationship between the individual and the collective or community? In what ways are the individual and the collective in conflict with each other? In what ways do the individual and the collective support or complement each other? 
- How does colonialism shift notions of race, equity, socio-economic status, natural resources, religion for the colonizer, colonized, and the reader? 
- How do literature, language, and storytelling both perpetuate and dismantle the tools of the colonizer?

* Main Texts
- /Heart of Darkness/ by Joseph Conrad
- /A Small Place/ by Jamaica Kincaid
- /The God of Small Things/ by Arundhati Roy

* Assessments
- Expect 40 min of homework per class
- Expect rubrics + strict grading
  - Note: communicate with teacher
  - This may be a repeat of Sam. *Be prepared!*
- Essays + creative assignments
  - Pastiche is going to happen
  - Presentations + visual assignments
  - Only 50% essays
- Examples will be provided for each major assignments

* Expectations
- Arrive on time. *Teacher really cares about this!*
- Begin with video on.
- Create a general google doc for in-class assignments.
- 
