:PROPERTIES:
:ID:       C906819F-DECF-4FB9-99BD-32A9026A350C
:END:
#+TITLE: The Bird-Dreaming Baobab

* Initial Thoughts
- Couto uses third person to distance the reader from the main character just as the main character is distanced from society (or at least the society's white population). Throughout the story the protagonist is only referred by generic and distancing terms like 'that man', 'the birdman', 'that black', etc...
- The choice to have much of the story be told through the eyes of the adults in the white populace further emphasizes the notion of ostracization - not even the story is accepting the main character.
- Much of the initial dialogue being in the form of whispers, rumors, and thoughts highlights the muted (amorphous? indistinct? not explicit) nature of racist views within communities (before it builds up to an uproar).
- This story seems to take place within the history of the Portuguese colonization of Mozambique (around 1560?) and the general theme of the Portuguese mistreatment of other races engages with the movement against Portuguese control in the author's lifetime.
- Now that I've heard other people's ideas concerning /The I is Never Alone/ it's possible birds work as a symbol of the colonized - potentially more explicitly in this story with the idea of a specific "foreign-ness" to the birds.
- The birds reflect the culture of the native population in the settlers’ eyes and are part of an uneasy standoff between the settlers and a foreign culture in a land they are largely unfamiliar with (as indicated by their confusion over the source of the birds). 
- It is when these birds mysteriously make their way to what the settlers find important (also potentially the technologies/things that settlers think differentiate themselves from the the natives like bureaucracy and firearms) that their uproar begins. Maybe because culture they believe lesser than them is interacting with what they believe differentiate them from others?
