:PROPERTIES:
:ID:       E2A91423-343F-46A8-92AD-5B08CF83ECF2
:END:
#+TITLE: Gaussian Random Field

* Random Fields
A random field is a stochastic process within Euclidean space and with dimensionality > 1.
What's a stochastic process? Note that $T$ is a traditional Euclidean space like a cube.
/DEFINITION/ A stochastic process $f$ over $T$ is a collection of random variables $\{f(t) : t \in T\}$.
/DEFINITION/ If $T$ is a set of dimension $N$, and the random variables $f(t)$ are all vector
valued of dimension $d$, then we call the vector valued random field $f$ a $(N, d)$
random field. 

An intuitive example of a random field is the ocean surface.

* Gaussian Random Fields
** Gaussian Variables
A random variable is Gaussian if its density distribution is a Normal distribution. Let's leave it at that. [Note to future self: Math is hard!]
** Gaussian Fields

* Generation
Combination of last two sources may enable some amount of info to go off of.

* Useful Sources
- http://pages.stat.wisc.edu/~mchung/teaching/stat992/ima01.pdf 
Describes basic definitions.
- https://www.astro.rug.nl/~weygaert/tim1publication/lss2007/computerIII.pdf
Mentions Fourier space generation
- https://www.astro.rug.nl/~weygaert/tim1publication/lss2016/lss2016.gaussian_fields.handout2.pdf
Cosmology-focused source + goes into some detail on power spectra and fourier space.
