#+TITLE: States

* Max Weber on the State
A state is an entity with the sole right to commit violence or allow its use within a territory.

* Formation 
** Social Contract Theory
States arise from a population's cooperation as it becomes larger and requires more resources to be managed properly. As a result the state is a place where members of a community express their opinions and arrive at a collective decision with the rest of the community. An 'ideal' theory of states in a more philosophical manner.
** Bellicist
A state is a mechanism for defending territories from threats and exist primarily for fighting wars. Development is related to wider conflict and competition among states. War defines all aspects of states from governmental structures to administrative ability. A theory based off of historical evidence.

* Bellicist Theory
** Four Functions
1. War Making: Defeating external rivals.
2. State making: Defeating internal threats (i.e. insurgents).
3. Protection: Mitigating threats to your population - primary metric of legitimacy of a state.
4. Extraction: The act of executing upon the previous three goals. Administrative tasks like funding and management.

/SIDENOTE: Without legitimacy there is no reason for the state./

** Connections
- Protecting from external threats requires a military, which can also protect against internal threats like insurgents.
- Militaries need funding, and therefore beauracratic systems are needed to be run *better* than your competitors.
- Populations must be wealthy enough to be taxed (or more internal threats), and therefore resources and capital are required.
  - Protect the wealthiest citizens who could make their own systems of protections and stop paying taxes.
    - Courts of law and policing can protect the wealthy and ensure continual taxation.
