:PROPERTIES:
:ID:       31026AE9-B75E-4FBD-94A8-148DD2073D35
:END:
#+TITLE: Classifying Systems

Terms like '[[id:2F9754BC-EF10-435C-80EE-F007EA432B31][state]]' or 'empire' can be too general.

* Independence
States in independent systems are free to make domestic decisions as well as "external" decisions (i.e. foreign affairs), although the latter decisions are limited to their reliance/involvement in the system and need to manage relations. When such states interact they realize it is more difficult to forgo external help and eventually a network of alliances and agreements is established. These alliances influence the decisions of each state and order is then promoted by the idea that all seek to gain mutual benefits by holding up the system. This belief that working to uphold the system will be beneficial to all parties is described by the term /raison de système/.

This notion of freedom is limited by the amount of reliance on outside parties as well as the possibility of hegemony arising.

* Hegemony
States in a hegemonic system continue to have the ability to make domestic and foreign decisions, but a single or few powerful states has authority over the agreements and alliances between other nations. In other words: a powerful state supervises and controls the independent system. 

Some say that hegemony refers to a single power: in reality, there are many examples of dual-hegemony or a number of controlling states so generalizing the definition is useful.

Hegemony is not dicatorship: there is conversation/debate between the authority and the other states.

* Suzerainty

Suzerainty is when a state exercises political control over another, much like hegemony. Suzerainty is where hegemonial power is considered legitimate power (as opposed to the "soft power" nature of a hegemonial system). A good example might be the relationship between the Roman Empire and its outer colonies like Spain. This along with other historical examples has it amount to "having control over" or "owning" a state but leaving it alone. 

It can be argued that this and hegemony are equivalent as tacit acceptance of power is still acceptance.

* Dominion

Dominion is where an authority controls the domestic decisions of a state, but the state remains its own discrete entity and a level of control over domestic affairs.

* Empire

Direct governance from a political authority, essentially no freedom.
