:PROPERTIES:
:ID:       3B06B8AF-6D0F-4202-9B20-1F832E9A60ED
:END:
#+TITLE: Theaetetus
#+STARTUP: showstars indent

* 144e
Socrates and Theaetetus discuss Theodorus' claim that they look alike. Socrates raises the point that if Theodorus were to claim that two lyres are similarly tuned they would look into his musical qualifications - were he experienced with drawing they would believe him, otherwise they would not.

Essentially: ignore the statements/arguments of those inexperienced with the subject.

* ~150?
Socrates and Theaetetus discuss what knowledge is. Theaetetus states that one's knowledge is based off of their present perception of something, and therefore knowledge is merely perception. 

* 152
Socrates raises the example of a breeze, and how one may feel could and the other not and asks whether the wind itself is cold or not cold. Is it cold for the one who feels cold, and for the other, not cold? 

* ~156
Socrates also describes how misperception confuses this definition of knowledge - not all that appears to a man really exists. How is the idea that perception is knowledge and all that is visible to an individual is what it appears to them as still valid?

* 160c
Socrates moves towards a potential resolution of this conundrum by arguing that his perception is true to himself and he alone of judge of whethere things that exist are indeed things that exist for him, and things that don't exist are indeed things that don't exist for him. 

* 164b/c
Socrates and Theaetetus agree that equating perception and knowledge leads to impossibilities and therefore are separate.

* 186a/b
They discuss how perception is rooted in observation and comparison.

* 186d
If perception fails of finding the truth of something and is the root of knowledge, can that truth ever be known? It seems not, and therefore knowledge is not to be found in perception and experiences but in the process of reasoning about them it is possible to attain knowledge.

* 187b
Knowledge shall not be looked for in perception but in the actions of the soul left to its own devices. Knowledge is correct judgement.

* ~200
Correct judgement in it of itself is not knowledge, as forming decisions via hearsay would still potentially result in correct judgement. They must be separate. Theaetetus remembers that it was once told to him that only true judgement with an argument/statement - and things without arguments are unknowable.

* 210
It is the addition of the argument that allows the person to /know/ the difference, rather than simply judge it. This definition centering around knowledge of differences may be recursive - and therefore problematic.

