#+TITLE: Limits and Continuity Practice
#+STARTUP: indent showstars latexpreview
#+filetags: reviewpublish:

* Practice Problems
The relevant questions can be found [[https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/1.-differentiation/part-a-definition-and-basic-rules/session-5-discontinuity/MIT18_01SCF10_ex05prb.pdf][here]].
1. One should use a one-sided limit, more specifically a right-hand limit because $sqrt(x)$ is only defined for $x \geq 0$. 
   
   $\lim_{x \rightarrow 0^+} \sqrt{x} = 0$
2. One should use a one-sided limit because $\frac{1}{x+1}$ has an infinite discontinuity with asymptotes at $x = -1$. Either side will work. 
   $\lim_{x \rightarrow 0^+} \frac{1}{x+1} = \infty$
   $\lim_{x \rightarrow 0^-} \frac{1}{x+1} = - \infty$
3. One should use a two-sided limit because $\frac{1}{(x-1)^4}$ goes to infinity as $x$ tends toward one from either side due to its even asymptote. 
   
   $\lim_{x \rightarrow 1} \frac{1}{(x-1)^4} = \infty$
4. One should use a two-sided limit because $|sin(x)|$ is continuous. 
   $\lim_{x \rightarrow 1} |sin(x)| = 0$
5. One should use a one-sided limit as the function $\frac{|x|}{x}$ has a jump discontinuity at $x=0$ and the left and right hand limits are not equal. Either side will work. 
   $\lim_{x \rightarrow 0^+} \frac{|x|}{x} = 1$
   $\lim_{x \rightarrow 0^-} \frac{|x|}{x} = -1$
