:PROPERTIES:
:ID:       F474E2F3-1471-4A5C-8A02-B22C22A1F8CB
:END:
#+TITLE: Magnetism
#+STARTUP: showstars indent

* Intro Magnetism

There is no such thing as a monopole, as splitting up a magnet into two pieces just gives you two smaller magnets.

** Fields
Magnetic field lines point to the direction of magnetic north at each point.

Magnetic fields are created by moving charges (like a current in a wire), and in the case of a straight current-carrying wire the magnetic field is a series of circles with increasing radius wrapping around it (encircling it). Because of this, magnetic fields are inherently
three-dimensional in their representation.

The convention for depicting three-dimensional fields is as follows:
- $\bigodot$ for arrows going out of the page (tip of the arrow facing you)
- $\bigotimes$ for arrows going into the page (tail of the arrow facing you)

A current-carrying loop of wire produces the same series of circles for each point (imagine twisting the straight wire), all of which have the largest radius as the approach the center of the loop and the field line becomes nearly straight.


Charge moving through a magnetic field feels a force that is the cross product of its velocity and the field lines (perpendicular to both forming a right angle): its direction can be decided by Right Hand Rule 2.

** Cross Product Notes
 - Right hand rule 2 only for positive charges
 - Perpendicular force causes circular motion
   - In a field pointed into the page and a particle travelling right, there is a force exerted downward. As the particle moves because of its velocity, the force's direction and magnitude change to continue to be perpendicular to it. A consistent perpendicular force inwards is circular motion (as we know from PHYS101)
 - When direction of velocity equals direction of magnetic field there's no force (intuitive reason: there's no way to do that with the right hand rule)
 - Cross product is used to calculate force
 - $F = q\mathbf{V} \times \mathbf{B}$
   - This means direction is determined through right hand rule
   - Magnitude is just $F = qVB\sin{\theta}$
 - Earth has a magnetic field
   - Charged particles enter earths field and make circles around field lines (as lines converge the spiral becomes tighter).

 Electron is travelling at 2km/s to the right in a 50µT field which is directed upwards. Magnitude of the force = $-1.602 * 10^{-19} * 2000 * 50 * 10^{-6} * \sin{90\degrees}$


 - For a wire we need to consider the amount of the wire inside the field to get force (we need length $L$).
   - A wire is just a tube of electrons so $F=Q_{\text{total}} B V$. $Q_{\text{total}}=nALq$
   - this cancels to $Q_{\text{total}}=ILB$ since multiplying density of charge times area times the velocity yields current (since current is a measure of how much charge is flowing past a certain point per second).


* Right Hand Rules

** Right Hand Rule 1
 Hold your right hand out in a thumbs up motion, where the thumb points in the direction of current. Your curled up fingers follow the direction of the magnetic field encircling the wire.

** Right Hand Rule 1.5

Thumbs up motion, where the curled up fingers follow the direction of the wire's current. Your thumb points in the direction of the magnetic field lines going outwards (do not that there are loops of field lines that close up farther from the center too).

** Right Hand Rule 2

Thumb is current, fingers are a magnetic field and the palm is the force experienced. AKA cross product.
Coil:
* Field Equations
Note that $\mu_0 = 4\pi * 10^7$. N refers to number of loops throughout.

- Straight portion of wire: $B = \frac{\mu_0 I}{2\pi r} N$ where r is dist from wire
- Loops: $B = \frac{\mu_0 I R^2}{2(d^2 + R^2)^{3/2}}N$ where R is radius of loop and d is dist from loop center
- Long solenoid approximation (idealized, only use when length is much more than loop radus): $B\approx \mu_0 \frac{N}{L} I$ where L is length of solenoid.

* Motors

* Circular Motion

* Induction

It's all just RHR 2: do consider that mechanical movement is movement of charge and therefore acts as current.

Ex 1: current flowing through a loop induces movement by RHR 2 because

* Flux and EMF
Flux through a surface is $BA$, aka field times area. If there are loops, multiply this by $N$. If the surface is tilted relative to the field lines the equation $BA\cos{\theta}$ applies.

EMF is given by rate of change in flux ($-\frac{d\Phi}{dt}$), aka Flux per second. Since Flux is in units of Volt-seconds this means that EMF is just Volts.

#   | EXAMPLE | Take a conducting loop laying horizontally with an increasing magnetic field pointing up through it.


1. As flux is $BA$, flux increases.
2. The corresponding EMF is in the opposite direction ($-\frac{d\Phi}{dt}$)
3. EMF is electromotive force, so true to its name it creates current in the opposite direction
4. This current induces a downward pointing field opposing the flux change
