#+TITLE: Universe Initial Conditions
#+STARTUP: indent showstars latexpreview

See [[id:ab943f6d-11d3-4b89-a86a-6ce07898e9d9][Millennium Simulation]].
* Initial Notes
** Linear Theory Power Spectrum
"Matter power spectrum" seems to be the fourier transform of the matter corellation function which describes the distrbution of galaxies within the universe (the probability of finding two galaxies that far apart)

What does a fourier transform mean in this context???

** Nyquist frequency mode sampling 
First off, does this imply a nested fourier transform? 
Idea of mode sampling within a sphere 

** Yet another fourier transform
Complex-to-real implies everything leading up to this involved complex numbers? How does that make sense?

* Meeting Notes
- Nyquist frequency half the sampling rate.
  - Construct model with frequencies up until nyquist limit.

- Units found in graphs in paper are dimensionless equivalent of matter power spectrum
- There are linear and nonlinear power spectra
- $q$ represents a vector position?
- Langrangian coordinates are a function that represents the position of particle $n$ at time $t$

* The Conclusion
A good way to get around the confusing and dense description of displacement field generation would be to generate a [[id:a4a36501-0fea-4a0b-ad27-3859ae46b589][Gaussian random field]].
