#+TITLE: Nuclear Screencast 2
#+STARTUP: indent showstars

Nuclear decay releases thermal energy, so a generator seeks to use that energy to boil water and the resulting steam spins a turbine which spins magnets around a coil of wire, inducing a current and generating electricity.

Two main types: pressurized water reactors and boiling water reactors.

* Reactors
** Pressurized Water Reactors
High pressure water (that isn't allowed to boil due to pressure) flows over decaying material and then heats up nearby normal water which generates steam (which spins turbine...). A source of cool water cools down the steam back into water and the cycle is started anew.
** Boiling Water Reactors
Water flows right into the reactor vessel instead (rest of the process is the same).

Potential downsides:
# Check back on this
- Different phase states are in the same loop.
- Less safe due to radioactive water not being isolated.

Boiling Water Reactors (henceforth BWRs) can be identified by the steam dryer (eliminate liquid water droplets in air to prevent damage) and steam nozzles. Control rods are down below in a BWR.
** Parts of a Reactor
- Fuel rods are tubes containing uranium dioxide pellets. Only ~3% of a pellet is 'fissionable' uranium (or uranium-235), the rest is uranium-238. The tubes themselves are made of a zirconium alloy which absorbs less neutrons than steel. Many rods group up into a grid pattern to make up /fuel assemblies/.
- The control rod is responsible for absorbing neutrons and halting fission
** Risks
1. The isotope that things fission into with roughly half the original mass is usually quite radioactive, and this makes spent fuel dangerously radioactive. It needs to sit in a pool of water until the daughter products are done decaying (to the point where its safe).
2. The ‎^{238}U in the fuel pellets can absorb a neutron to become ‎^{239}U which can undergo beta decay twice to become leftover ‎^{239‎}Pu, which can be made into a nuclear weapon. It's also a source of alpha rays. Toxic too.
3. The daughter products produce a large amount of heat even when oxygen is shut off - meaning that fires become a very large problem. Lots of cooling water is required to counteract this.
** Cherenkov Radiation
Spent fuel tanks glow blue because of /Cherenkov Radiation/, where the fission products move faster than the speed of light within water, releasing radiation in the process.
** Reprocessing
Reprocessing can allow radiotoxicity of spent fuel to drop far faster (without any reprocessing it takes ~20000 years to get to 10x natural levels).
** Quantifying Radiation
Radiation is ionizing (knocking electrons off of atoms), and also can cause nuclei to fragment in extreme situations. It can weaken materials, or cause somatic and genetic damage to life.

- You can measure it in strength of source, where 1 Becquerel (Bq) is 1 disintegration per second (a Curie, or Ci, is 3.7 * 10^10 Bq).
- You can measure it in absorbed dose: 1 rad is the amount of radiation that deposits 0.01 J per kg of absorbing material.

However, the effect on biological material depends on a "quality factor". A rem is rads*QF, although the Sievert (Sv) is used most often and is equal to 100 rems. Most radiation has a QF of ~1, slow and fast neutrons can have from 3 to 10 respectively (you'd have to be near fission to get this), and alpha particles have a QF of up to 20 (although they are easily stopped).s
