:PROPERTIES:
:ID:       10686D2E-FBFC-4823-966D-85F82142A607
:END:

#+TITLE: Origin Narratives of the United States Essay
#+SUBTITLE: HIST301
#+AUTHOR: David Freifeld
#+OPTIONS: \n:t 
#+EXCLUDE_TAGS: noexport

* Prompt :noexport:
The telling of American history has become one of the focal points of conflicts over our national culture, particularly the relationship between ideas of American exceptionalism and stories of race and conquest in US history. What is the value of a shared national narrative and what dangers does crafting such a narrative present? Why does the telling of US history generate such controversy?

In a 2-3 page, double spaced essay, evaluate how the authors we’ve read so far approach the telling of American history and _make an argument for what you see as the key considerations in constructing a narrative of early American history_. Historical narratives, by their nature, are created through choices of what to include and what not, what to emphasize and what to relegate to the margins. In making your argument, include an explicit engagement with the sources we’ve worked with so far. You might, for example, engage with the controversy over the 1619 project, with Dunbar-Ortiz’s criticism of multiculturalism or with Richter’s geographical positioning of history. You are free to use any of the readings from class which include:

- 1491 - Charles Mann
- An Indigenous People’s History - Roxanne Dunbar-Ortiz
- Facing East from Indian Country - Daniel K. Richter
- Pilgrims & Puritans and the Myth of the Promised Land - Paul Heike
- 1619 - Nikole Hannah-Jones
- Slavery & Freedom: The American Paradox - Edmund Morgan
 
* Thesis :noexport:
Critically examining the origins and legitimacy of American exceptionalism through emphasis on the epidemiological situation of Native Americans, the "Promised Land" mindset of the Puritans, and the 1619 project's role in the American Revolution is central to constructing a historical narrative of early America.

* Outline :noexport: 
** Introduction
*** Thesis
+Puritan ideals have persisted in American culture in the form of American exceptionalism yet are incompatible with the historical realities of Native American deaths to European plagues and the role of slavery in America's founding.+



The experiences of marginalized communities like Native Americans and African Americans demonstrate the disconnect between the values of American exceptionalism and the physical reality of early America, and as a result are central to understanding early American history.

to an understanding of early American history due to how they demonstrate how the values of American exceptionalism were not present in the country's beginnings.



** Paragraph 1
*** Topic Sentence
Puritan values alongside their view of America as a utopic "Promised Land" provided the basis for American exceptionalism and have endured in American media.
*** Evidence 1
"we shall be as a city upon a hill. The eyes of all people are upon us, so that if we shall deal falsely with our God in this work we have undertaken, and so cause Him to withdraw His present help from us, we shall be made a story and by-word throughout the world" (Puritans 152)

**** Loose Analysis:
The Puritan fixation on establishing that they are to become the moral example for the rest of the world highlights their belief in their own moral superiority. Additionally, the emphasis on how God is the one aiding them in their mission demonstrates the ideal that they believe that their success was "destined to be" / granted by God.

*** Evidence 2
Multiple novels authored as recent as the 20th century by immigrants continue to reinforce and identify with Puritan values: few examples out of many include the aptly titled /The Promised Land/ (1912) by Mary Antin which "refers to the Pilgrim Fathers as 'our forefathers'" and Anzia Yezierska's short story "America and I" in which the author declares that "America started with a band of Courageous Pilgrims...[that] had left their native country as I had left mine."

Pilgrims / Puritans 173 and 174
**** Loose Analysis:
Imagery of "Promised Land" shows that despite usage of the term Pilgrim, the works are referencing Puritan ideals. 20th century authors continuing to identify with the Puritans and their ideals highlight how their values have continued to persist within American soci(ety for centuries.

** Paragraph 2
*** Topic Sentence
The mass death within Native American societies caused by the diseases brought over from the New World contradicts the narrative of the Puritans - and by extent, Americans as a whole - as well as their perceived moral superiority.

*** Evidence 1
# Pilgrims - problematic 

"The newcomers - hungry, cold, sick - dug up graves and ransacked houses, looking for underground stashes of corn"

"All through the coastal forest the Indians had "died on heapes as they lay in their houses"..."And the bones and skulls upon the severall places of their habitations made such a spectacle" that the woods seemed to be a "new found Golgotha".  

**** Loose Analysis:
Unethical behavior of the Pilgrim settlers in relation in the form of thievery undercuts the notion of moral superiority propagated by the Puritans. Mass death of Native Americans caused by earlier Europeans bringing plague and direct comparison to Golgotha itself (from a devout Christian no less) draws the morality of American origins into question.

*** Evidence 2

"The good hand of God favored our beginnings...[by] sweeping away great multitudes of the natives ... that he might make room for us." 

**** Loose Analysis:
Deaths of Native Americans exposes a contradiction in the form of the traditional Puritan narrative that their success in America was destined and granted by God.

** Paragraph 3
*** Topic Sentence
The partial role of a desire to protect the economic benefits of slavery in the motivations for the Revolutionary War  and the exclusion of slaves from rights endowed by the Declaration of Independence undermines the moral argument of American exceptionalism.

*** Evidence 1
"The wealth and prominence that allowed Jefferson...and the other founding fathers to...break off from one of the mightiest empires in the world came from the dizzying profits generated by chattel slavery" (1619 pg 4)

"[slaves] grew and picked the cotton that at the height of slavery was the nation’s most
valuable commodity, accounting for half of all American exports and 66 percent of the world’s
supply." (1619 pg 2)

**** Loose Analysis:
The economic motivations of the Revolutionary War further contradict American exceptionalist ideals of moral superiority.

*** Evidence 2
"“all men are created equal” and “endowed by their Creator with certain unalienable rights.”...did not apply to fully one-fifth of the country." (1619 pg 3)

**** Loose Analysis:
The failure to apply the ideals of the Declaration of Independence to slaves (comprising 1/5 of the country) weakens the exceptionalist view of American history.

** Conclusion
Tie back to how exceptionalism influences modern day politics (1619 controversy?)

* Draft 
The experiences of Native Americans demonstrate the disconnect between the values of American exceptionalism and the physical reality of early America, and as a result are central to understanding early American history.

The American exceptionalist narrative has endured throughout history and assertsnn that early American history is characterized by early Americans prospering in an empty New World due to their courage and exemplary moral values. This narrative is originally reinforced by the early Americans themselves, with John Winthrop declaring that "we must consider that we shall be as a city upon a hill..." and describing "His present help" and William Bradford describing America as "a wild and savage view" (Puritans 11,17). The imagery of the 'city on a hill' demonstrates how the Puritans thought they were to be morally superior to the rest of the world and therefore supported the narrative that early American societies succeeded because of their values. Bradford's description of America similarly props up this narrative by establishing America as an empty, untamed wilderness and that the settlers succeeded due to their own merits. The American exceptionalist narrative has continued to be reinforced within America in the centuries after. The Wilderness Act of 1964 reinforces Bradford's notion of America as a wild and untamed land by describing it as "untrammeled by man" before the arrival of the settlers (1491 4). Popular culture in the form of short stories like Anzia Yezierska's 1923 piece "America and I" reinforce the notion of the settlers being defined through their morality, proclaiming that "America started with a band of Courageous Pilgrims". As a result of this narrative's root in the settler's description of themselves and its continual reinforcement over time, much of early American history is framed through an idealized lens.

Focusing on the mass death within Native American societies resulting from European diseases highlights contradictions in the narrative of American exceptionalism and allows for a more accurate understanding of how early American societies prospered. In /1491/, Charles C. Mann relays how members of the Pilgrims like Thomas Morton noted that Native Americans had "died on heapes, as they lay in their houses...[Massachusetts seemed] a new found Golgotha". The extensive removal of the Native American population contradicts the notion that the early settlers arrived at a near empty America and succeeded on their own rather than through epidemiological means. William Bradford himself even goes as far as to acknowledge that God "favored our beginnings...[by] sweeping away great multitudes of natives...[so that] he might make room for us." Furthermore, Daniel K. Richter outlines in /Facing East from Indian Country/ how the smallpox had drastic effects for the surviving Native Americans as well, stating "with...the able-bodied adults more incapacitated than the rest, the everyday work of raising crops, gathering...fetching water...hunting...[and] harvesting fish virtually ceased." The catastrophic societal damage incurred by the various plagues afflicting Native Americans meant that Puritans and Pilgrims experienced little to no resistance in their efforts to establish their own society and provide the foundations for America. <conclusion needed>

Viewing history from the lens of Native American interactions with the settlers further reveals inconsistencies in the American exceptionalist narrative by highlighting the moral shortcomings of early Americans. Mann describes how the Pilgrims survived their initial winter without food or shelter, stating that "[t]he newcomers - hungry, cold, sick - dug up [Native] graves and ransacked houses, looking for underground stashes of corn". The Pilgrims' desecration of Native graves emphasizes a disconnect between their alleged moral superiority and their actions as well as provides a more accurate understanding of how the Pilgrims initially survived their first months. Additionally, In /The Myths That Made America/, Heike Paul explains how Pilgrims "are extremely condescending towards the Natives" and draws attention to a letter written by a Pilgrim that declares "it hath pleased God so to possess the Indians with a fear of us, and love unto us...[such that they] have either made suit unto us or been glad of any occasion to make peace". The Pilgrims' general condescension towards Native Americans and view of them as inferior undercuts the traditional exceptionalist narrative of early Americans being characterized by their admirable values. Moreover, the Natives' fear of the Pilgrims and attempts to pursue good standing after the decimation of their people provides additional insight into a more accurate understanding of how Pilgrims prospered. <conclusion needed>








# The partial role of the desire to protect the economic benefits of slavery in the motivations for the Revolutionary War and the exclusion of slaves from rights endowed by the Declaration of Independence undermines the moral argument of American exceptionalism.



