#+TITLE: Conductors/Insulators

* The Atom
Electrons are around the nucleus in a sort of probability cloud, and it is only electrons that are mobile in the atom. The mass of the atom rests in the nucleons.

* Conductors/Insulators
We can separate materials into two categories: Conductors and Insulators. Electrons move freely in the conductors - where they to be pushed, they would move. The opposite is true for insulators.

Conductors tend to be metals, insulators tend to be plastics or glass or wood etc... Why this is the case is the subject of Solid State Physics. 
/Sidenote: Solid State Physics is usually a senior class at Nueva./  

As noticed in class, different materials take on different net charges when rubbed (some gain electrons and become positive and vice versa). Most common plastics tend to become negative, and things like fur/cotton/wool tend to become positive.

Two like charges repel and opposites attract (remember the experiments in class with the pen and fabric). If a positively charged metal object is touched to a neutral conductor, electrons can jump across and cause the positive rod to become less positive and the neutral rod to become slightly more positive. 

In fact, even if the neutral and positive rods don't touch, electrons will migrate throughout the conductor and each end will become charged. The neutral rod would return to normal if the charged rod was removed, as opposed to the original example where the neutral rod lost electrons. One thing to observe is that the electrons in the conductor are closer to the positive end than the protons (as the protons were repelled) and therefore experience more force. As a result of this there is a net force in the direction of the charged rod. 

Similar effects happen with an insulating rod (or a piece of paper) but to a much lesser degree as the electrons are unable to flow throughout the material. This is consistent with the paper being attracted to the rod in the class experiment. But why does it fall back down? Once it gets close enough small amounts of electron transfer between the materials takes place and it is suddenly repelled.

* Electroscope
An electroscope has a conductor at the top and two gold leaves at the bottom. Once a charged object is introduced, the metal polarizes and protons (or electrons, depending on the charge) flow back down to the gold leaves and cause them to repel.

* Links
  These are examples of [[id:3df9876e-c186-45f6-8897-4b6a593d9fc5][The Electrical Force]].

