#+TITLE: Exploration of Fields/Voltage
#+filetags: review

* Topics Covered
[[id:3df9876e-c186-45f6-8897-4b6a593d9fc5][Electrical Force]], [[id:55b5f3cd-6022-46f7-8439-8e02adf478b9][Fields]]
* 1. Place a single charge in the working area. Using the E-field sensor (with "values" selected), and the measuring tape, confirm that the E-field calculated by the PhET simulation agrees with the equation we have used in class. (Note, the units for E-field that we learned in class were N/C. The PhET simulation may express the units differently. But the numerical values should be the same.)

Take a charge of one nC 1.1 meters away from the field.
$E = k\frac{q_1q_2}{r^2}$
$k = 8.99 \cdot 10^9$
$E = 8.99 \cdot 10^9\big(\frac{10^-9}{1.1^2}\big)$
$E = 7.42975$

* 2. Place two positive charges in the working area. Where do you expect the E field to be zero? Does the simulation confirm that?

We expect the E-field to be zero at a point halfway between the two charges, and the simulation confirms this. The E-field is zero at that point because the test charge experiences two forces of equal magnitude but of opposite direction, leading to a net force of zero.

* 3. Same as above, but use one positive and one negative charge.

We do not expect the E field to be zero at any point and the simulation confirms this. Unlike the first one there is no such cancellation at the center because the forces experienced by the test charge are not in opposite directions but the same direction.

* 4. The E field at a given point can be thought of as the force that a +1 C charge would feel if it were placed there. What does "electric potential" or "voltage" appear to represent? The units mentioned in #1 may be of interest as you consider this question.

The electric potential is the work the electric field has to do to push 1 C of charge to a reference point like infinity.

* 5. Does electric potential appear to be a scalar or a vector?

The electric potential is a scalar. As electric potential is work the field has to do to push a unit of charge and work itself is a scalar, it stands to reason that electric potential is as well.

* 6. What or where is the zero-point for electric potential?

The zero-point for electric potential is infinitely far from the origin of the E-field.

* 7. What is the relationship between the local E-field vector and a line of constant electric potential? (You can explore this first by moving the voltage sensor [drag the little box, not the crosshairs] and observing the voltage values, then by plotting lines of constant potential).

The local E-field vector is perpendicular to the line of constant electric potential. 
We calculate electric potential with the equation $V = \int E \cdot dr$. Because of the dot product, any movement perpendicular to the E-field does not change the potential. So, the points with the same electric potential all form a line perpendicular to the E-field.
The electric potential of the E-field is equal at every point on a sphere around a point charge with the charge at the center of the sphere.

* Questions
How does all of this work in the context of [[id:900ae259-1fff-4112-a9da-98e8549caee9][Conductors/Insulators]]?
