#+TITLE: Electrical Force
#+STARTUP: showstars latexpreview

* Modelling the Electrical Force
The electrical force can be quantified (as seen in class experiments).

Begin by imagining two separate points with charges $q_1$ and $q_2$ respectively, separated by a distance $r$.
/Sidenote: $Q$ is the variable for charge./

The expression for the magnitude of these two forces is given by $F = k\frac{q_1q_2}{r^2}$. The units of charge is the Coulomb, which represents the charge for many protons/neutrons (one electron has $\approx -1.602 * 10^{-19}$ Coulombs). The constant $k$ has a value of $\approx 8.99 * 10^9$ N m^2 / Coulomb^2 (this is just the dimensional analysis required to get Newtons on the left side of thr equationx). Alternatively, $k$ can be representated as $\frac{1}{4\pi\epsilon_0}$.

By plugging into the equation, one can notice that a force > 0 is a repulsion, and force < 0 is attraction.

Note that acceleration from these forces is *not* constant. Kinematic equations will not be useful in problems concerning electrical forces (i.e. determining where the charged points will be in the future is less simple)

* Applications: DNA Replication

Knowing partial charges (shared electrons spend more time at one end vs other) of individual atoms within molecules can let us calculate electrical forces between entire molecules to understand if they will attract. Using computer simulations can reveal that the attraction between cytosine and guanine (or adenine and thymine) is due to Coulomb's Law.

* Links
Electrical forces can be described with [[file:phys250-fields.org][Fields]].
