:PROPERTIES:
:ID:       D3BAA8CE-20BE-4AA8-B3E3-804B47E0FCED
:END:
#+TITLE: The Quantum World
#+STARTUP: indent showstars
* Chapter One

In quantum physics, distinguishing laws from particles is challenging (unlike Newtonian mechanics where the same rules generally apply to everything).

There are a lot of particles, but most are composite. The Standard Model is comprised of 24 'fundamental' (non-composite) particles.

There is variety in the types of particles: /leptons/, /quarks/, /force carriers/, and more.

* Chapter 2

** Units
 - The /femtometer/ ($10^{-15} \text{ m}$), or for short just 'fm', is used often as a measure of length.
 - The speed of light is frequently used for expressing speed.
 - The /electron volt/ or eV is used for expressing energy. It's also used for measuring mass since it is equivalent to energy (but in that case its KeV, MeV, or GeV). It's the acquired by an electron when it is being accelerated through an electric potential of 1 volt.

** Length
Picture an atom as a 3km airport. Inside it is a 30cm basketball, and that's a 'large' nucleus like uranium. A golf ball would be equivalent to the hydrogen nucleus. Inside that golf ball are immeasurably small quarks. Finally, the single electron (also immeasureably small) fills up the entire airport. Why? It's a wave.

The diameter of a proton is one femtometer. Distances this small are measured via scattering electrons through a wall of particles to be measured and then determining distances via the resulting scatter patterns. Diffraction of energetic particles can allow for measuring small things as well (think how waves can inform you about a ship's length).

There is also an even smaller length known as the /Planck length/ ($10^{-35} \text{ m}$) which is used in theoretical physics (one example being string theory).

** Speed
d/t and modern clocks are good enough that this isn't as much a problem.

** Time
An apt unit is the time it takes a particle moving close to speed of light to cross a proton ($~10^{-23} \text{ s}$). Gluons only exist this long.

** Mass
A measure of inertia (how hard to to get/stop something moving). As mentioned in [[Units]], this is usually measured in terms of energy because $E=mc^2$.

** Energy
Just like how Cost = Amount * Price, Energy = Mass * Constant-of-Proportionality (aka $c^2$). This also means that mass is very energy-packed. The coloumb is also a relevant unit.

** Spin
Everything rotates, and this is measured through /angular momentum/. Bohr suggested that $\hbar = \frac{h}{2\pi}$ is the unit of spin and that particles can only spin in constant multiples of $\hbar$. It was later found out that particles can also have half-spin. Spin is fundamental to a particle (so much that changing a spin of a particle makes it another particle).

$\hbar = 1.05 \times 10^{-34} \times \text{m} \times \text {m/s}$

Spin has orientation (up or down).

** Natural Constants
h and c are both 'natural' constants specifically tied to the rules of quantum physics and relativity respectively.

* Chapter III
** Leptons
Leptons come in three flavors: electrons, muons, and taus. Each has a corresponding neutrino.
*** Electrons
*** Muons
$\mu \rightarrow e + \gamma$
*** Taus

* Chapter 0b100
** Quarks
Quite amount is mysterious about quarks - they're fundamental but we have never witnessed them on their own. Their masses are only vaguely known, and there's no good reason for why the heaviest one is 10000x as heavy as the lightest.

Quarks are somewhat like leptons in some ways: half-spin, exist at a point. Other ways, not as much: strong interactions and link up to form particles like pions, protons, and neutrons.

Measuring the mass of a quark is nontrivial - since the mass of the quarks themselves is only a minor portion of the proton's mass: much of it is just its energy.

Six quarks: up, down, strange, charm, top, bottom.

Quarks have fractional charge ($\pm1/3$, $\pm2/3) but always combine to form integer charges. They also have fractional baryon numbers.

** Composite Particles

There are hundreds, and these are usually what we see in labs. Two types: baryons and mesons.

*** Baryons
Protons and neutrons are the lightest and are made of up and down quarks.
There is a wide variety of greek letter particles like lambda and sigma that contain strange quarks. Even heavier baryons have charm and bottom quarks. No baryons have been discovered to contain top quarks.

Every baryon but the proton is unstable and decays into something.

*** Mesons
Pion is one of the lightest, and was once thought to be the force carrier of the strong force.

All mesons have baryon number 0. They can also decay into leptons, while baryons can't (must conserve baryon number).

** Force Carriers
Leptons, baryons, and mesons are /what is/, and force carriers determine /what happens/.

*** Gravitational Interaction
Gravity is the weakest interaction, and since billions of gravitons are involved in each interaction, we can only detect the presence of many and are eluded in detecting the graviton itself.

We only notice gravity since we're *massive*, made up of an unthinkable number of particles. It plays essentially no role in subatomic dynamics.We don't notice things like the electromagnetic force due to large scale cancellation of forces.

*** Weak Interaction
This is responsible for emmission of beta rays in radioactivity and for some other transformations involving neutrinos. It's much stronger than gravity, but still weak.

It is "mediated" by W and Z particles, which are quite large (80x proton size). W and Z are not composite, but fundamental.

*** Electromagnetic Interaction
Photons are the force carrier.

"Range" or strength of a force is proportional to the mass of its force carriers. It was later proposed that the weak and electromagnetic force are actually one and the same, with the weak force just being a "shorter range" version of it. It's not very straightforward however, as the weak force is universal and not just for charged particles.

*** Strong Interaction

Gluons come in eight forms: each with their own mix of "color charge" - the strong force is represented with either red green or blue colors.

Gluons keep the quarks inside protons, and the strong force /increases/ with distance.

** Feynman Diagrams

Feynman diagrams are mini spacetime diagrams. One notable difference from a traditional spacetime diagram is that particles can move backwards in time.

Simple example is electron scatter: both move up, one emits photon and changes path, the other takes in photon and changes direction.

Places where particle lines meet are /vertices/, usually three-pronged and only involving two fermions and a boson. Every interaction is ultimately the emission/absorption of bosons by leptons and quarks.

These interaction events are catastrophic in nature: when an electron gains a photon it is not modified but destroyed and replaced with an entirely new (yet identical) electron.

Antiparticles move opposite in time to a particle.

* Chapter ⠟
* Chapter 𝍷𝍶
