
#+TITLE: Relativity Notes
#+SUBTITLE: Nonstop Pain
#+STARTUP: showstars indent

Notes for [[id:b01c0c9f-72d5-4f6d-aec2-0a5226c2340f][Relativity Quiz]].

* [#B] Space-Time diagrams 
** Representing basic events
** Representing a frame at a velocity
   
* [#C] Einstein Readings
** Reference Frames
A coordinate system is comprised of position and time.

An inertial reference frame is a reference frame in which the law of inertia holds true: things at motion do not suddenly stop, and things at motion do not suddenly start. This is most relevant for frames that are rotating (e.g. Earth rotates and therefore it looks as if stars do) or accelerating. The basic laws of Newtonian mechanics only hold true for inertial frames.

** Principle of Relativity

All reference frames that are uniform translations of an inertial reference frame $K$ are inertial reference frames (as they're just constant motion and a shift). Even more generally so, all frames that are uniform translations of $K$ are describable with the exact same general laws as $K$. This is the /principle of relativity/.
e it's moving, the galaxy, the local cluster, etc... essentially the idea of a 'true frame' is problematic.

** Relativity of Velocity

If someone is walking with a velocity $w$ within a train with velocity $v$, what's their velocity to an observer at rest outside the train? $v+w$? This would be problematic because if the train were traveling at the speed of light this would mean that the total velocity the observer sees is greater than the speed of light.

** Speed of Light issues

If a train at 0.5c is passing by a photon it'll see it as being 0.5c instead of c - velocity of light is no longer a constant and POR is violated.

** Time and Physics
How do we tell if two things are simultaneous? Say two thunderbolts are striking spots A and B at the same time - we could test this by setting up two mirrors such that the light emitted from bothe events travels in the same manner and is reflected towards your eye in the same manner. If you see both at the same time, it was simultaneous.

This does, however, rely on the assumption travels between both paths at the same time, which would require a way to measure time in the first place - except no, this is a valid stipulation to arrive at a definition. Using this we can define time: say we have 3 identical clocks placed at points A, B, and C such that the positions of the hands are simultaneously the same (verified in the same way as above). Through this, we can associate a time value with any event.

** Relativity of Simultaneity

Are two events that are simultaneous in one frame simultaneous in the other? No.
Every reference frame has it's own corresponding time and position axes, so simultaneity will not hold true across them.


* [#B] Time dilation
See [[id:aa1910f5-a780-43d6-8d09-42329b03737e][Derivation of Dilation]].
** General Equation
$\Delta T = \frac{\Delta T'}{\sqrt{1-\frac{v^2}{c^2}}}$

$\Delta T = \gamma \Delta T'$ where $\gamma = \frac{1}{\sqrt{1-\frac{v^2}{c^2}}$

This means when v is small, gamma is ~1 and no real dilation.
When v is large gamma is >1 and $\Delta T$ is larger

** [#B] Space Dilation
Also a factor of gamma. It's $\frac{x}{\gamma}$.

Unprimed frame sees primed frame as shortened, but primed frame sees unprimed as shortened? Why? Just like a person on a train seeing landscape go by at -v when the landscape sees it going by at v.

** Nested reference frames
See above.


* [#B] Minkowski Diagrams
** [#C] Lorentz transforms

General Lorentz transformations are:
- $x' = \frac{x-vt}{\sqrt{1-\frac{v^2}{c^2}}}$
- $t' = \frac{t-\frac{vx}{c^2}}{\sqrt{1-\frac{v^2}{c^2}}}$
- $x = \frac{x'+vt'}{\sqrt{1-\frac{v^2}{c^2}}}$
- $t = \frac{t'+\frac{vx'}{c^2}}{\sqrt{1-\frac{v^2}{c^2}}}$

Simplified Lorentz transformations for c=1 are:
- $x' = \frac{x-vt}{\sqrt{1-v^2}}$
- $t' = \frac{t-vx}{\sqrt{1-v^2}}$
- $x = \frac{x'+vt'}{\sqrt{1-v^2}}$
- $t = \frac{t'+vx'}{\sqrt{1-v^2}}$

 
** Simple problems (orig. Minkowski)

The line representing the x' axis should have the slope of the velocity of the frame. 0.5c -> line w/ slope 0.5. The ct' axis should have the inverse (0.5c -> line w/ slope 2).

The numbering of the primed axes should be spaced out relative to $\gamma$. 

To graphically find the x' coordinate of a point, draw a line parallel to the c' axis and see where it intersects the x' axis. Vice versa for ct'. (This is just like how normal graphs work).

Comparing to the [[Lorentz transforms]] is usually a good idea since there's a decent amount of error in drawings.

The order of events can flip across frames.


** [#A] More complex problems (other ppl + bridge)


Drawing trajectories is useful for understanding when objects enter/exit things in primed/unprimed frames.


* [#A] Relativistic Physics
** Spacetime interval
Just as how distance is $(\Delta d)^2 = (\Delta x)^2 + (\Delta y)^2 + (\Delta z)^2$, spacetime interval is $(\Delta s)^2 = (\Delta ct)^2 - (\Delta x)^2 - (\Delta y)^2 - (\Delta z)^2$.
It's invariant under the Lorentz transform.

If interval^2 > 0:
If interval^2 = 0:
If interval^2 < 0: Problematic

** Velocity

See the twin-paradox-energy-momentum slides.

** Paradoxes

Other effects will make up for forces which cease to exist across a different frame of reference.

** Momentum



** Energy
