#+TITLE: Relativity Quiz
#+AUTHOR: David Freifeld
#+DATE: March 11, 2021
#+STARTUP: showstars indent
#+OPTIONS: \n:t toc:nil indent:nil
#+LATEX_HEADER: \usepackage[a4]{geometry}

* Problem 1
a) Rearrange existing relationships in terms of $v$:
\begin{align*}
\Delta T = \gamma \Delta T' =  \frac{\Delta T'}{\sqrt{1-\frac{v^2}{c^2}}} \\
\Delta T \sqrt{1-\frac{v^2}{c^2}} = \Delta T' \\
\sqrt{1-\frac{v^2}{c^2}} = \frac{\Delta T'}{\Delta T} \\
1 - \frac{v^2}{c^2} = \frac{\Delta T'}{\Delta T}^2 \\
1 - \frac{\Delta T'}{\Delta T}^2 = \frac{v^2}{c^2}\\
\sqrt{\left(1 - \frac{\Delta T'}{\Delta T}^2\right)c^2} = v\\
\end{align*}

Plug in $\Delta T = 10$, $\Delta T' = 7$: $\sqrt{\left(1 - \frac{7}{10}^2\right)c^2} = 2.1424 \cdot 10^{8}$.
\indent Divide by $c$ to get in terms of speed of light: $(2.1424\cdot 10^8) / c = \boxed{0.7141c}$.

b) See above problem: $\boxed{v = 2.1424 \cdot 10^{8} \text{ m/s}}$.

c) In Max's reference frame I am going $-v$ or $-0.7141c$.
\indent As a result, he sees my clock as $\frac{\Delta T'}{\gamma}$ (where $\Delta T'$ is the time passed in _his_ frame).
\indent $\gamma = \frac{1}{\sqrt{1-\frac{v^2}{c^2}}} =  \frac{1}{\sqrt{1-\frac{(-0.7141)^2c^2}{c^2}}} = 1.428$
\indent $\Delta T' = 7$, and $7/1.428 = \boxed{4.9 \text{ minutes}}$.

* TODO Problem 2
Energy for photons, particles without rest mass, is given by $E=\frac{h}{\lambda}$.
Substitute $\lambda=510 \text{ nm}=510\cdot 10^{-9} \text{ m}$ and $h=6.63*10^{-34} \text{ J s}$: $E = \frac{6.63 \cdot 10^{-34}}{510 \cdot 10^{-9}}$.
$E = \frac{6.63 \cdot 10^{-34}}{510 \cdot 10^{-9}}=\boxed{1.3\cdot 10^{-27} \text{ J}}$

\noindent Relativistic momentum is given by $p = \gamma m_0 v$, and since $\gamma = \frac{1}{\sqrt{1-\frac{v^2}{c^2}}}$ and $v=c$, $\gamma$ is $\boxed{\text{undefined}}$ as the denominator is zero. If one were to use the traditional momentum formula $p = mv$, the photon's rest mass of 0 would mean that it's momentum is $\boxed{\text{zero}}$, which is more reasonable.

* Problem 3

a) Conventionally, $\text{KE } = \frac{1}{2}mv^2$, so it would seem to have $\frac{1}{2}\cdot 35 \cdot (6 \cdot 10^{6})^2 = \boxed{6.3 \cdot 10^{14}\text{ J}}}$ of energy.

\noindent b) At high speeds, $\text{KE } = m_0 c^2 (\gamma - 1)$, so it would actually have
$35 \cdot (3 \cdot 10^8) \cdot \left(\frac{1}{\sqrt{1-\frac{6 \cdot 10^6}{3 \cdot 10^8}}} -1\right) = 35 \cdot (3 \cdot 10^8) \cdot 0.01015$ or $\boxed{106575000 \text { J} \approx 1.07 \cdot 10^8 \text { J}}$ of energy.

* Problem 4
a) $\boxed{\text{Less than}}$, because the atom must be at a lower energy state than the sum of its individual parts in order to be stable. This is further supported by how atoms have a binding energy and need energy to be split into their constituent parts. If the atom has less energy, it must have less mass, since $E=mc^2$.

\noindent b) The binding energy of an atom is the amount of energy needed to split it apart, and therefore is the difference between the energy of the atom and the total energy of its individual nucleons. With Einstein's mass-energy equivalence this can be used to find the difference between the sum of the individual masses of its nucleons and the mass of the atom.

$E=mc^2$, so $\frac{E}{c^2} = m$, and therefore $\frac{\Delta E}{c^2} = \Delta m$.
In this case, $\Delta E = \text{BE}_\text{He} \cdot n_\text{He}$, (where $n = \text{\# of nucleons}$) so $\frac{\text{BE}_\text{He} \cdot n_\text{He}}{c^2} = \Delta m_\text{He}$.
Plug in to get $\Delta m_\text{He} = \frac{4\cdot 1.14425\cdot 10^{-12}}{c^2} = 5.08556 \cdot 10^{-29}$
$\Delta m_\text{He}$ only represents the difference between the total mass of helium's individual parts and the mass of a helium atom, so solve for helium mass and plug in.

$\Delta m_\text{He} = (2\cdot m_p + 2\cdot m_n) - m_\text{He}$
$m_\text{He} = (2\cdot m_p + 2\cdot m_n) - \Delta m_\text{He}$
$m_\text{He} = (2\cdot (1.67262 \cdot 10^{-27}) + 2\cdot (1.67493 \cdot 10^{-27})) - (5.08556 \cdot 10^{-29}) = \boxed{6.44244 \cdot 10^{-27} \text{ kg}}$.

* Problem 5
1) Lorentz-adjusted velocity is given by $\frac{v+u'}{1+(vu' / c^2)}$. Here, $v = 0.5c$ and $u' = 0.6c$, so velocity of passenger relative to myself is $\frac{0.5c + 0.6c}{1+((0.5c\cdot0.6c)/c^2)}=\frac{1.1c}{1.3}=\boxed{0.846c}$.

2) For the graphical parts of the problem, refer to the figure at the end of the last page.
   a) See figure.
   b) See figure.
   c) See figure.
   d) First, let's establish the coordinates of the passenger at Event B in their own reference frame. Their x coordinate will be 0 as they don't see themselves as moving (it's /their/ reference frame, after all). Since at Event B, $ct' = 5$, we can use the handy formula $\Delta T = \gamma \Delta T'$ from the train's reference frame to get the time at the passenger's frame.

   $\Delta T = \gamma \Delta T'$ so $\frac{\Delta T}{\gamma} = \Delta T'$ where $\gamma = \frac{1}{\sqrt{1-\frac{v^2}{c^2}}}$.

   Plug in 0.6c for gamma (since that's the velocity of the passenger relative to the train) to get $\gamma = 1.25$. Plug that into the first equation to get $\Delta T' = \frac{5}{1.25} = 4$. We now know that the coordinates of the passenger relative to their own frame are (0,4).

   From here, we can apply the x Lorentz transformation from the train's frame to get the coordinates of the passenger relative to the /train's/ frame\textemdash we already know it's ct value is 5 from the question itself.


   $x = \frac{x'+vt'}{\sqrt{1-v^2}} = \frac{0+0.6\cdot 4}{\sqrt{1-0.6^2}} = 3$

   Now we know that the passenger is at (3,5) in the train's reference frame. Let's now use another two Lorentz transformations on those coordinates from my frame to get the passenger's coordinates. Since it's from /my/ frame, v is now 0.5c (the velocity of the train relative to me), and we'll be applying the x and t Lorentz transforms (as the train's coordinates are primed in comparison to my frame).

   $x = \frac{x'+vt'}{\sqrt{1-v^2}} = \frac{3+0.5\cdot 5}{\sqrt{1-0.5^2}} = 6.35$
   $t = \frac{t'+vx'}{\sqrt{1-v^2}} = \frac{5+0.5\cdot 3}{\sqrt{1-0.5^2}} = 7.5$

   Finally, we come to the conclusion that the passenger is at \boxed{(6.35, 7.5)} in my frame.

   Sanity check: $\Delta T$, or just $ct$ at Event B, is the lowest at the passenger's frame and is larger in the train's frame and even larger in my frame. This makes sense - the passenger is moving the fastest and should have time moving the slowest, while I am not moving and should have time moving the fastest.

   e) Since all frames started at the same origin (0,0)\footnote{At least, I am assuming this is the case, as the problem would be unsolvable otherwise (and all prior logic would be invalidated, too).}, $v = \frac{\Delta x}{\Delta t} = \frac{6.35-0}{7.5-0} = 0.8467$. Since the axis is ct, not t, multiply by c to get $0.8467c$.

   $\boxed{\text{This is almost exactly in agreement with the prediction from subproblem 1.}}$

   f) See figure.
   g) Use the t' Lorentz transform (also see figure for graphical representation) $t' = \frac{t-vx}{\sqrt{1-v^2}}$.
   Plug in for C: $t' = \frac{4-0.5\cdot 0}{\sqrt{1-0.5^2}} = \boxed{4.62}$
   Plug in for C: $t' = \frac{4-0.5\cdot 6}{\sqrt{1-0.5^2}} = \boxed{1.15}$
   h) $ct = \gamma ct' = \frac{1}{\sqrt{1-\frac{v^2}{c^2}}} ct'$. Plug in to get $ct = 3.464$. At $ct=3.464$, I am located at $x=0$ in my own frame of reference.

   Earlier, in sub-subproblem D, it was established that the passenger's velocity in my frame was 0.846c. In the passenger's frame, it is not them who is moving, but me in the opposite direction\textemdash traveling at $-0.846c$.

   \hfill
   Apply the x and t Lorentz transforms from the passenger's frame (where my coordinates are x' and t'):
   $x = \frac{x'+vt'}{\sqrt{1-v^2}} = \frac{0-0.846\cdot 3.464}{\sqrt{1-(-0.846)^2}} = -5.496$
   $t = \frac{t'+vx'}{\sqrt{1-v^2}} = \frac{3.464+0.846\cdot 0}{\sqrt{1-(-0.846)^2}} = 6.497$

   In the reference frame of the passenger, I am at \boxed{(-5.496, 6.497)} at $ct'=3$.

   \begin{figure}[h]
   \includegraphics[width=16cm]{minkowski.jpg}
   \caption{Minkowski diagram for problem 5.}
   \end{figure}
