:PROPERTIES:
:ID:       3A60323C-4A6A-48D5-8DD8-1038D086E4CD
:END:

#+TITLE: There There Example Essay
#+SUBTITLE: A prelude for what's to come.

* Thesis 
Not directly laid out - sort of like "Orange uses Thomas Frank's connection with music to emphasize the impact of Native American history on present day Native American identity as well as the power/comfort of vocalizing generational grief". 

* Compelling Close Reading
- Interpreting the second person in Thomas' narrative as indicating his connection to the past was unique and compelling.
- "kept as close as skin" as evidence for how tied Thomas is to the struggles of his ancestry is also a good find and general analysis of quote is good
- Strong evidence for how Thomas symbolizes "generational grief" in general

* Structure
Focus on establishing Thomas' connection to his ancestry -> focus on establishing how music is outlet for it

* Areas for Growth
I feel like I was waiting for a third paragraph of sorts that continued the progression - perhaps some more focus on music itself or how it symbolizes the burden it places upon modern-day Native Americans. The conclusion gets into some of this, but I think it could've used some more content. Music link feels almost weaker since 3/4 or even more of the essay doesn't directly address music.

* Rubric
- Writing Mechanics | Exemplary
- Writers Voice | Exemplary
- Structure | Proficient
- Close Reading and Argumentation | Proficient? Maybe barely exemplary?
- Understanding Literature | Exemplary? 
