:PROPERTIES:
:ID:       608315BC-A8EC-42DD-BCA7-F73CC4414B3C
:END:

#+TITLE: There There Essay
#+SUBTITLE: ENG301
#+AUTHOR: David Freifeld
#+TEACHER: Allen Frost
#+EXCLUDE_TAGS: noexport

* Evidence Bank :noexport:
- "We come from towns on the sides of highways in northern Nevada with names like Winnemucca. Some of us come all the way out from Oklahoma, South Dakota Arizona New Mexico, Montan, Minnesota; we come from Pheonix, Albeuquerque, Los Angeles, New York City, Pine Ridge, Fort Apache, Gila River, Pit River, the Osage Reservation, Rosebud, Flathead, Red Lake, San Carlos, Turtle Mountain, the Navajo Reservation."
- "We are Indians and Native Americans, American Indians, and Native American Indians, North American Indians, Natives, NDNs and Ind'ins, Status Indians, and Non-Status Indians..."
- "We are full-blood, half-breed, quadroon, eighths, sixteenths, thirty-seconds."

- "We've been coming from miles. And we've been coming for years, generations, lifetimes, latered in prayer and handwoven regalia, beaded and sewn together, feathered, braided, blessed and cursed."
- "To get to powwows we drive alone and in pairs on road trips; we caravan as families, piled in station wagons, vans, and in the back of Ford Broncos. Some of us smoke two packs a day if we're driving, or drink beer continually to keep ourselves occupied. Some of us, who gave up that ried life, on that long red road of sobriety..."

- "That's how we are Blacks and Browns, Greens, Whites, and Oranges. We are Smiths, Lees, Scotts, MacArthurs, Shermans, Johnsons. Our names are poem, descriptions of animals, imags that make perfect sense and no sense at all. We are Little Cloud, Littleman, Loneman, Bull Coming, Madbull, Bad Heart Bull..."
- "Our bumpers and rear windows are covered with Indian stickers like /We're Still Here/ and /My Other Vehicle Is a War Pony/ and /Sure You Can Trust the Government, Just Ask an Indian!/..."

** Questionable 
- "It'll be that prey silence of hiding, the silence of trying to disappear, to not be out there, we'll close our eyes and go deep inside, hope that it's a dream or a nightmare, hope that in closing our eyes we might wake up to that other life, back on the other side of the screen, ..."
  - More like a runon? Goes on for a while.

* Outline :noexport:
** Introduction
*** Thesis
Orange uses lists in the interlude of /There There/ to emphasize the frayed nature of Native American identity and assert that despite their disparate backgrounds, Native Americans are united through their shared struggles and continued participation in their cultural traditions.
** Paragraph 1
*** Topic Sentence
Orange's focus on the wide variety of cultural and geographic background of Native Americans emphasizes how Native American identity is messy and mirrors the wide variety of backgrounds the characters in the novel have.
*** Evidence
"We come from towns on the sides of highways in northern Nevada with names like Winnemucca. Some of us come all the way out from Oklahoma, South Dakota Arizona New Mexico, Montan, Minnesota; we come from Pheonix, Albeuquerque, Los Angeles, New York City, Pine Ridge, Fort Apache, Gila River, Pit River, the Osage Reservation, Rosebud, Flathead, Red Lake, San Carlos, Turtle Mountain, the Navajo Reservation."
**** Analysis
By stressing the wide variety of locations Native Americans come from in the form of a long-winded list, Orange establishes that Native American identity is incohesive and comprised of scattered experiences. 
*** Evidence 2
"We are Indians and Native Americans, American Indians, and Native American Indians, North American Indians, Natives, NDNs and Ind'ins, Status Indians, and Non-Status Indians..."
**** Analysis
Orange focuses on how Native American identity is in actuality a large collection of labels and identities from sometimes entirely unrelated backgrounds in order to further highlight how Native American identity is ill-defined.

** Paragraph 2
*** Topic Sentence
Lists in the interlude of /There There/ underscore how shared struggles with American settlers is an element universal to modern Native American identity. 
*** Evidence 1
"That's how we are Blacks and Browns, Greens, Whites, and Oranges. We are Smiths, Lees, Scotts, MacArthurs, Shermans, Johnsons. Our names are poem, descriptions of animals, imags that make perfect sense and no sense at all. We are Little Cloud, Littleman, Loneman, Bull Coming, Madbull, Bad Heart Bull..."
**** Analysis
By listing the Americanized names of Native Americans, Orange emphasizes the shared impact the settlers have had on Native Americans and how their interactions with Western culture unite them.
*** Evidence 2
"Our bumpers and rear windows are covered with Indian stickers like /We're Still Here/ and /My Other Vehicle Is a War Pony/ and /Sure You Can Trust the Government, Just Ask an Indian!/... [or] /Fighting Terrorism since 1492/"
**** Analysis
The list of bumper stickers criticizing America's founding is used to symbolize the pervasive impact of the America's past upon Native Americans and how despite how scattered and different they may be, they are united through their historical hardship.
** Paragraph 3
*** Topic Sentence
Orange uses lists in the interlude to emphasize how Native Americans are connected through their participation in cultural traditions such as the powwow despite their different backgrounds.
*** Evidence 1
"To get to powwows we drive alone and in pairs on road trips; we caravan as families, piled in station wagons, vans, and in the back of Ford Broncos. Some of us smoke two packs a day if we're driving, or drink beer continually to keep ourselves occupied. Some of us, who gave up that ried life, on that long red road of sobriety..."
**** Analysis
The focus on all the different methods of transportation the attendees of the powwow take to get there highlights how they're united in their honoring of their cultural traditions and brought together by the powwow itself.
*** Evidence 2
"We've been coming from miles. And we've been coming for years, generations, lifetimes, layered in prayer and handwoven regalia, beaded and sewn together, feathered, braided, blessed and cursed."
**** Analysis
When describing their journey to the powwow Orange places emphasis on the connectedness, using language like /feathered/, /sewn/, and /braided/ to highlight how Native Americans are connected through their practicing of tradition in spite of their varied backgrounds.
** Conclusion

* Draft

Tommy Orange uses lists in the interlude of /There There/ to emphasize how Native American identity is incohesive and claim that Native Americans are united through their shared struggles and continued participation in their cultural traditions.


Orange uses lists to focus on the wide cultural and geographic background of Native Americans emphasizes how Native American identity is contradictory and mirrors the wide variety of backgrounds the characters in the novel have. When discussing powwows he writes that they "come from Pheonix, Albeuquerque, Los Angeles, New York City, Pine Ridge, Fort Apache, Gila River, Pit River, the Osage Reservation, Rosebud, Flathead, Red Lake, San Carlos, Turtle Mountain, the Navajo Reservation..." By stressing the wide variety of locations Native Americans come from through a long-winded list, Orange emphasizes the extent to which Native American identity is incohesive and comprised of scattered experiences. Orange continues this theme of scale by later stating "we are Indians and Native Americans...North American Indians, NDNs and Ind'ins, Status Indians and Non-Status Indians...Indians from Mexico...Alaskan Native Indians, Native Hawaiians and European expatriate Indians..." Orange uses a list to establish that Native American identity is a large collection of labels and identities from sometimes entirely unrelated backgrounds: contrast between terms in the list like "Indians from Mexico" and "Native Hawaiians"  highlight how Native American identity is ill-defined. This theme of conflicting backgrounds in the interlude connects to the rest of the novel by mirroring how the characters are all Native Americans despite their vast differences in lived experiences from Octavio the drug dealer to Olivia from Alcatraz. 

Lists in the interlude of /There There/ underscore how shared struggles with American settlers is an element universal to modern Native American identity. Orange describes how "when they decided they needed to keep track of us, last names were given to us...That's how we are Blacks and Browns, Greens, Whites, and Oranges. We are Smiths, Lees, Scotts, MacArthurs, Shermans, Johnsons...Little Cloud, Littleman, Loneman..." By listing the Americanized names of Native Americans, Orange emphasizes the ubiquitous impact the settlers have had on Native Americans and demonstrates how their interactions with Western culture unite them.

Orange describes powwows where "bumpers and rear windows are covered with Indian stickers like /We're Still Here/ and /My Other Vehicle Is a War Pony/ and /Sure You Can Trust the Government, Just Ask an Indian!/... [or] /Fighting Terrorism since 1492/" The list of bumper stickers criticizing America's founding is used to symbolize the pervasive impact of the America's past upon Native Americans and how despite how scattered and different they may be, they are united through their historical hardship.

This assertion that Native Americans are united by their struggle mirrors how as a result of the legacy of Native American history, each character in the novel experiences hardship through their socioeconomic status, struggles to identify with their past, or continued oppression.


Orange uses lists in the interlude to emphasize how Native Americans are connected through their participation in cultural traditions such as the powwow despite their different backgrounds.

"To get to powwows we drive alone and in pairs on road trips; we caravan as families, piled in station wagons, vans, and in the back of Ford Broncos...we stop at motels and hotels; we sleep in our cars on the side of the road..., truck stops, in Walmart parking lots." The focus on all the different methods of transportation the attendees of the powwow take to get there highlights how they're united in their honoring of their cultural traditions and brought together by the powwow itself.

"We've been coming from miles. And we've been coming for years, generations, lifetimes, layered in prayer and handwoven regalia, beaded and sewn together, feathered, braided, blessed and cursed." Each word in the list describing their journey to the powwow places emphasis on their connectedness, using language like /feathered/, /sewn/, and /braided/ to highlight how Native Americans are united through their practicing of tradition in spite of their varied backgrounds.

The novel's characters mirror this idea in how their stories are all connected through their presence at the same powwow: they are united through their practice of their traditions despite their incongruous backgrounds.
