:PROPERTIES:
:ID:       208A3232-ADBD-412B-B204-CE3CC6687211
:END:
#+TITLE: Water
#+STARTUP: hideblocks

* Main Properties
Water has four main properties:
- It is cohesive and adhesive, and has high surface tension and intermolecular forces
Water has strong polar bonds within it and forms hydrogen bonds with other molecules. Hydrogen bonds are especially useful because they break and form depending on temperature.

- It expands when frozen
Water forms an equally spaced crystal lattice when it freezes to ice, as opposed to its free floating dense liquid.

- It has high heat capacity
Water has high specific heat capacity and is therefore resistant to temperature changes.

- It is a strong solvent
The polarity of water lets it dissolve other polar substances.

* Entropy
Once the process of [[id:AF982AF7-0BEF-4CB6-B161-ECCB4FD3808C][protein folding]] begins the amount of translational configurations for the surrounding water molecules increases significantly, and therefore the entropy increases as well. This high-entropy water is a driving force behind parts of the protein folding process.

See [[https://drive.google.com/file/d/1fHZLX6I3hEsrG2kvduSHg04pYl4X6DAm/view?pli=1][here]] for more detail.
