#+AUTHOR: Exr0n
#+TITLE: Special Relativity Problem: Linear Escape

To test his prized cows' intelligence, Farmer John has trapped Bessie and Elsie in an escape room!

The escape room is a long tunnel in which the cows are traveling--Bessie at -0.4c and Elsie at 0.6c. At the start of the puzzle, both cows are at position zero in the tunnel where Farmer John is observing. To escape, Bessie has to turn on a light so Elsie sees it exactly six seconds after the challenge begins. Then, Farmer John will be satisfied that his cows are properly educated.

1. Bessie has a terrible sense of time and can only measure how far she has gone by regular 1-lightsecond markings on the tunnel wall. How far from the start should Bessie be when she turns on the light?

2. Farmer John realizes that the previous rendition of the escape room was too mentally taxing on Bessie. That afternoon, he repeats the test but provides Bessie with a long measuring stick to take with her. As measured by the stick, how far from the start should Bessie be when she turns on the light?

3. If you have too much time on your hands: Bessie successfully completes the challenge and returns to the barn for for the evening. Elsie sleeps peacefully on the on the bunk below her, but Bessie realizes that Farmer John has let her off easy. Taking light travel time into account, where along the measuring stick should the start have been when Bessie turned on the light?
