:PROPERTIES:
:ID:       B7C0625B-655D-4DD7-9000-46629FBFD695
:END:
#+TITLE: Thanksgiving Axler Bonanza
#+AUTHOR: Houjun Liu

Hello, fellow person that comes across this. I have had one brief exposure with Linear Algebra following MATH 21-1 at UCSC. However, Axler is just so cool, so I am trying to learn a bit of linalg on the side to supplement my much more traditional linalg experience at the UC.

A few things of note. This whole thing is very "partial": in the sense that its contents contain many a parts of things omitted which I feel like I have a good grasp on from 21-1 such that I don't need to be reminded again; I only include things that maybe useful to me later either b/c I don't know it or I want to be reminded of it. As such, I don't think this will be helpful for most people.

* 1.A

** Things of Note
- $\lambda \in \mathbb{F}$ is called a "scalar". I mean duh but still.

*** Defining a list
A list of length $n$ is a collection of $n$ elements (any mathematical object?) separated by commas.

"Identical" lists are established when lists have:

- the same length
- same elements
- in the same order.

Its also called a $n$-tuple.

$n$ must be a finite non-negative value. Therefore, an "infinitely long list" is not a list.

*** Sets vs Lists
Lists have order and repetition. In sets, order and repetitions don't matter.

*** $\mathbb{F}$ 
- A set
- Containing 2 elements $0$, $1$
- Operators of "addition" and "multiplication" that satisfy the following properties

**** Properties of $\mathbb{F}$
That, with $\alpha, \beta, \lambda \in \mathbb{F}$:

- **Commutativity** $\alpha + \beta = \beta + \alpha$ and $\alpha \beta = \beta \alpha$
- **Associativity** $(\alpha + \beta) + \lambda = \alpha + (\beta + \lambda)$ and $(\alpha\beta)\lambda = \alpha(\beta\lambda)$
- **Existence of Identities** $\lambda + 0 = \lambda$ and $\lambda 1 = \lambda$
- **Additive Inverse** for every $\alpha$, $\exists \beta$ s.t. $\alpha + \beta = 0$
- **Multiplicative Inverse** for every $\alpha \neq 0$, $\exists \beta$ s.t. $\alpha \beta = 1$
- **Distribution** $\lambda(\alpha + \beta) = \lambda \alpha + \lambda \beta$

*** $\mathbb{F}^n$
\begin{equation}
  \mathbb{F}^n = \{(x_1, \ldots, x_n) : x_j \in \mathbb{F}\ for\ j=1,\ldots,n\}  
\end{equation}

We say $x_j$ is the $j^{th}$ coordinate of $(x_1, \dots,x_n)$.

In $\mathbb{F}^n$...

**** Addition
\begin{equation}
   (x_1,\dots,x_n) + (y_1,\ldots,y_n) = (x_1+y_1,\ldots,x_n+y_n) 
\end{equation}

**** Scalar Multiplication
\begin{equation}
    \lambda(x_1,\ldots,x_n) = (\lambda x_1, \ldots, \lambda x_n)
\end{equation}

**** Zero
\begin{equation}
   0=(0,\ldots,0)
\end{equation}

**** Additive Inverse
...of $x \in \mathbb{F}^n$:

\begin{equation}
   x+(-x) = 0
\end{equation}

That:

\begin{equation}
   x=(x_1, \ldots,x_n), -x=(-x_1,\ldots,-x_n) 
\end{equation}

** In-Text Exercises

*** Verify that $i^2 = -1$
$(0+1i)(0+1i) = (0 + 0 + 0 + i i) = -1$

*** Defining subtraction and division
$\alpha, \beta \in \mathbb{C}$

Subtraction could be defined in that:

- Let $-\alpha$ be defined as the additive inverse of $\alpha$
- Subtraction, therefore, is defined $\beta - \alpha = \beta + (-\alpha)$

Division could be defined in that:

- Let $1/\alpha$ be defined as the multiplicative inverse of $\alpha$
- Subtraction, therefore, is defined $\beta/\alpha = \beta(1/\alpha)$

** Actual Exercises

#+begin_quote
1: Suppose $a, b \in \mathbb{R}$, $a,b \neq 0$, find $c,d \in \mathbb{R}$ s.t. $\frac{1}{(a+bi)} = c+di$
#+end_quote

\begin{align}
    \frac{1}{(a+bi)} &= \frac{(a-bi)}{(a+bi)(a-bi)} =  \\
\Rightarrow & \frac{a-bi}{a^2-(bi)^2} = c+di \\
\Rightarrow & \frac{a-bi}{a^2+b^2} = c+di \\
\Rightarrow & \frac{a}{a^2+b^2}-\frac{bi}{a^2+b^2} = c+di 
\end{align}


Therefore:

\begin{equation}
    c = \frac{a}{a^2+b^2}
\end{equation}

\begin{equation}
    d = \frac{-b}{a^2+b^2}
\end{equation}

#+begin_quote
2: Show that $\frac{-1+\sqrt{3}i}{2}$ is the cube root of 1.
#+end_quote

\begin{align}
    &(\frac{-1+\sqrt{3}i}{2})^3 \\
\Rightarrow &(\frac{-1+\sqrt{3}i}{2})(\frac{-1+\sqrt{3}i}{2})(\frac{-1+\sqrt{3}i}{2})  \\
\Rightarrow &\frac{(-1+\sqrt{3}i)(-1+\sqrt{3}i)(-1+\sqrt{3}i)}{8}  \\
\Rightarrow &\frac{(1-2\sqrt{3}i-3)(-1+\sqrt{3}i)}{8} \\
\Rightarrow &\frac{(1-2\sqrt{3}i-3)(-1+\sqrt{3}i)}{8} \\
\Rightarrow &\frac{8}{8} = 1
\end{align}

#+begin_quote
3: Find two distinct square roots of $i$
#+end_quote

?

#+begin_quote
4: Show that $\alpha + \beta = \beta + \alpha, \forall \alpha,\beta \in \mathBB{C}$  
#+end_quote

Let:

$\forall a,b,c,d \in \mathbb{R}$

- $\alpha = (a+bi)$
- $\beta = (c+di)$

\begin{align}
   \alpha + \beta &= (a+bi) + (c+di) \\
&=(a+c) + (b+d)i \\
&=(c+a) + (d+b)i \\
&=(c+di) + (a+bi) \\
&=\beta + \alpha\ \blacksquare 
\end{align}

#+begin_quote
5: Show that $(\alpha + \beta) + \lambda = \alpha + (\beta+\lambda), \forall \alpha,\beta,\lambda \in \mathbb{C}$
#+end_quote

Let:

$\forall a,b,c,d,e,f \in \mathbb{R}$

- $\alpha = (a+bi)$
- $\beta = (c+di)$
- $\lambda = (e+fi)$

\begin{align}
   (\alpha + \beta)+\lambda &= ((a+bi) + (c+di))+(e+fi) \\
&=((a+c)+(b+d)i)+(e+fi) \\
&=(a+c+e)+(b+d+f)i \\
&=(a+(c+e))+(b+(d+f))i \\
&=(a+bi)+(c+e)+(d+f)i \\
&=(a+bi)+((c+di)+(e+fi)) \\
&=\alpha+(\beta+\lambda)\ \blacksquare 
\end{align}

* 1.B

** Things of Note

*** Vector Spaces $V$

A "vector"/"point" is a member of a vector space. The exact nature of scalar multiplication depends on which $\mathbb{F}$ we are working it; hence, when being precise, we say that $V$ is a vector space "over $\mathbb{F}$".

**** Motivation
- Addition is commutative, associative, and has identity
- Every element has additive inverse
- Scalar multiplication is associative
- Addition and scalar multiplication is connected by distribution

**** Basic Operators
- **Addition** on set $V$ is a function that assigns $u+v \in V$ to each pair $u,v \in V$
- **Scalar Multiplication** on set V is a function that assigns $\lambda v \in V$ to each $\lambda \in \mathbb{F}$ and $v \in V$. Note that this is different than a field, because if you can't multiply two different things in and out of the field and expect it to remain. But you could multiply an element in field $\mathbb{F}$ and a vector in vector space $V$ and expect it to stay in $V$.

Note also "Multiplication" is not defined as 1) there are two and 2) they behave very differently.

**** Properties
For $u,v,w \in V$ and $a,b \in \mathbb{F}$.

- **Commutativity** $u+v = v+u$
- **Associativity** $(u+v)+w = u+(v+w)$ and $(ab)v=a(bv)$. 
- **Additive Identity** $\exists 0\in V\ s.t.\ v+0 = v, \forall v\in V$
- **Additive Inverse** $\forall v \in V, \exists w\in V\ s.t.\ v+w=0$
- **Multiplicative Identity** $1v=v$ 
- **Distribution** $a(u+v) = au+av$ and $(a+b)v = av+bv$

**** Unique Additive Identity
The additive identity ("zero") in a vector space must be unique. (i.e. there cannot be two distinct zeros $0$ and $0'$ which both are $\in V$). This is because:

\begin{equation}
    0 = 0 + 0' = 0'+0 = 0'
\end{equation}

That --- if both $0$ and $0'$ are additive identities, $0=0'$.

**** Unique Additive Inverse
Every element in a vector space has an unique additive inverse (i.e. there cannot be two distinct additive inverses of $v \in V$ $w$ and $w'$ which both are $\in V$). 

Suppose $w$ and $w'$ are both additive inverses of $v$, then it holds that:

\begin{equation}
w = w+0 = w+(v+w') = (w+v)+w' = 0+w' = w'
\end{equation}

That --- if both $w$ and $w'$ exists in $V$, $w = w'$.

**** Zero and Vectors
$0v = 0$ for $v \in V$. $a\vec{0}=\vec{0}$ for $a \in \mathbb{F}$.

*** $\mathbb{F}^{\infty}$
Wait but aren't $\mathbb{F}^n$ supposed to be made of lists, which has finite length?

I guess its just sequences of all of everything in $F$.

\begin{equation}
   \mathbb{F}^{\infty} = \{(x_1, x_2,\ldots):x_j\in \mathbb{F}\ for\ j=1,2,\ldots \} 
\end{equation}

*** $\mathbb{F}^S$
$\mathbb{F}^S$ is defined as the set of functions that maps elements in set $S$ to $\mathbb{F}$. It is a vector space.

**** Addition
Addition between $f,g \in \mathbb{F}^S$ is defined by:

\begin{equation}
   (f+g)(x) = f(x)+g(x),\ \forall x \in S
\end{equation}

**** Scalar Multiplication
Multiplication between $\lambda \in \mathbb{F}$ and $f \in \mathbb{F}^s$, $\lambda f \in \mathbb{F}^s$ is defined as:

\begin{equation}
    (\lambda f)(x) = \lambda f(x),\ \forall x \in S
\end{equation}

**** $\mathbb{F}^n$ and $\mathbb{F}^\infty$ are special cases of $\mathbb{F}^s$
...this is because a list $\{x_1, x_2, x_3, \ldots, x_n\}$ is actually a bijective mapping between $\{1,2,3,\ldots,n\}$ (the indexes) and the values of the list, which are all $\in \mathbb{F}$. so :tada:!

** In-Text Exercises

*** Verify that $\mathbb{F}^n$ is a vector space over $\mathbb{F}$
Not going to write this one out, but:

- Commutativity: via rules addition, commutation (in $\mathbb{F}$), then undoing addition
- Associativity: addition, communication, then undoing addition
- Additive Identity: addition + definition of "zero" in $\mathbb{F}^n$
- Additive Inverse: addition + additive inverse (in $\mathbb{F}$)
- Multiplicative Identity: scalar multiplication (by 1) and then identity (in $\mathbb{F}$)
- Distribution: definition of addition in $\mathbb{F}^n$, scalar multiplication, undoing definition of addition again

** Actual Exercises

#+begin_quote
1: Proof that $-(-v) = v,\ \forall v \in V$
#+end_quote

| Step                 | Explanation          |
|----------------------+----------------------|
| $v = v+0$            | Additive identity    |
| $v = v+(-v+-(-v))$   | Additive inverse     |
| $v = (v+-v) + -(-v)$ | Associative property |
| $v = 0 + -(-v)$      | Additive inverse     |
| $v = -(-v)\ \blacksquare$        | Additive Identity    |

#+begin_quote
2: Suppose $a \in \mathbb{F}, v\in V$, and $av=0$. Proof $a=0$ or $v=0$.
#+end_quote

Let $a \neq 0$. We define the multiplicative inverse of $a$ as $a^{-1}$.

| Step                 | Explanation             |
|----------------------+-------------------------|
| $v = 1v$             | Multiplicative identity |
| $v = a a^{-1} v$     | Multiplicative inverse  |
| $v = av a^{-1}$      | Commutativity           |
| $v = 0 a^{-1}$       | Given                   |
| $v = 0\ \blacksquare$ | Number times 0          |

If $a=0$, $\blacksquare$.

#+begin_quote
3: Suppose $v,w \in V$, explain why $\exists$ unique $x\in V$ s.t. $v+3x = w$ 
#+end_quote

Let $x = \frac{1}{3}(w-v)$; by addition and scalar multiplication, $\exists x \in V$.

| Step                          | Explanation                    |
| $v + 3x = w$                  | Given                          |
| $v + 3(\frac{1}{3}(w-v)) = w$ | Defined                        |
| $v + (w - v) = w$             | Multiplication in $\mathbb{F}$ |
| $v - v + w = w$               | Commutativity                  |
| $w = w\ \blacksquare$       | Additive Inverse               |

Therefore, $\exists x \in V$ that satisfies the needed property.

Suppose there exists more than 1 $x$ which satisfies this property. We call them $x$ and $x'$. This would tell us the following equalities:

$v + 3x = w$, $v+3x' = w$.

It follows from the equalities that:

$3x = w-v$, $3x' = w-v$

Then, it follows that

$3x = 3x'$

Therefore:

\begin{equation}
x = x'
\end{equation}

Hence, if given that there exists $v + 3x = w$, $v+3x' = w$, $x=x'$. Hence, there is only one unique $x$ such that $v+3x = w$.

* 1.C
Axler, in his infinite wisdom, has crammed everything that's interesting to note in Chapter 1.c.

** Things of Note

*** Subspaces
(Woo hoo!)

A subset $U \subset V$ is called a "subspace of $V$" if $U$ is also a vector space using the same addition and scalar multiplication operators.

**** Checking for Subspaces
Check for three conditions:

For $U \subset V$

- **Additive Identity** $0 \in U$. (also could be defined as "set is nonempty", b/c if nonempty, and its closed under scalar multiplication, multiplying any element by $0$ will do the trick. But often showing $0$ is in it is actually simpler.)
- **Closed Under Addition** $u,w \in U$ implies $u+w \in U$
- **Closed Under Scalar Multiplication** $a \in \mathbb{F}$ and $u \in U$ implies $au \in U$

*** Summing Subsets
Suppose $U_1,\ldots,U_m$ are subsets of $V$. The "sum" of the subsets ($U_1 + \cdots + U_m$) is the set of all possible sums of elements in $U_1, \lodts, U_m$. That is:

\begin{equation}
   U_1 + \cdots + U_m = \{u_1 + \cdots + u_m : u_1 \in U_1, \ldots, u_m \in U_m \} 
\end{equation}

**** Properties of the Sums of Subspaces
Suppose $U_1, \ldots, U_m$ are subspaces of $V$. $U_1 + \cdots + U_m$ is the smallest subspace of $V$ containing all of $U_1,\ldots,U_m$.

*** Direct Sum

Suppose $U_1, \ldots, U_m$ are subspaces of $V$

- Sum $U_1 + \cdots + U_m$ is a direct sum if $U_1 + \cdots + U_m$ can be only written only one way as a sum $u_1 + \cdots + u_m$
- Direct sum is noted as $U_1 \oplus \cdots \oplus U_m$ 

"Sums is the union, direct sums is the disjoint union".

**** Checking for Direct Sums
Suppose $U_1, \ldots, U_m$ are subspaces of $V$. $U_1 + \cdots + U_m$ is a direct sum iff the only way to write $0$ as a sum $u_1 + \cdots + u_m$ is by taking each $u_j$ equaling to 0. This could be implied from the definition of a direct sum: that there is only one way to write a $0$ as $u_1 + \cdots + u_m$, and being closed scalar multiplication means that you could multiply $0$ to each subspace individually and they still have to add up to $0$. 

**** Direct Sum of Two Subspaces
Suppose $U,W$ are subspaces of $V$.

$U+W$ is a direct sum iff $U \cap W = \{0\}$. 

** In-Text Excercises

*** Summing Subspaces, an Example
Suppose $U = \{(x,x,y,y) \in \mathbb{F}^4: x,y \in \mathbb{F}\}$ and $W= \{(x,x,x,y) \in \mathbb{F}^4 : x,y \in \mathbb{F}\}$. Then:

\begin{equation}
    U+W = \{(x,x,y,z) \in \mathbb{F}^4 : x,y,z \in \mathbb{F}\}
\end{equation}

We verify this by writing out the sum.

\begin{align}
    U + W &= \{(x_u,x_u,y_u,y_u) + (x_w,x_w,x_w,y_w) : x_u, y_u \in U, x_w, y_w \in W\} \\
&= \{(x_u+x_w,x_u+x_w,y_u+x_w,y_u+y_w) : x_u, y_u \in U, x_w, y_w \in W\} \\
&= \{\left(\underbrace{x}_{x_u+x_w},x,\underbrace{y}_{y_u+x_w},\underbrace{z}_{y_u+y_w}\right) : x,y,z \in \mathbb{F}\}
\end{align}

*** Verify sums equal to spaces
Suppose $U,W$ are subspaces of $\mathbb{F}^3$.

\begin{align}
    U =&\,\{(x,y,0) \in \mathbb{F}^3:x,y \in \mathbb{F}\} \\
    W =&\,\{(0,0,z) \in \mathbb{F}^3: z \in \mathbb{F}\}
\end{align}

Verify $\mathbb{F}^3 = U \oplus W$

\begin{equation}
  U + W = \{(x,y,z) \in \mathb{F}^3 : x,y,z \in \mathhb{F}\} = \mathbb{F}^3
\end{equation}

:tada:?

** Actual Excercises

#+begin_quote
1: For each of the following subsets of $\mathbb{F}^3$, determine if it is a subspace of $\mathbb{F}^3$.
#+end_quote

\begin{equation}
  U = \{(x_1, x_2, x_3) \in \mathbb{F}^3:x_1+2x_2+3x_3 = 0\}  
\end{equation}

We could see that $(0,0,0) \in U$.

Let $u_1 = (x_1, x_2, \frac{-x_1 - 2x_2}{3}}), u_2 = (x_3, x_4, \frac{-x_3 - 2x_4}{3}}). u_1, u_2 \in U$.

$u_1 + u_2 = (x_1+x_3,x_2+x_4,\frac{-(x_1+x_3)-2(x_2+x_4)}{3})$. Define $x_1 + x_3 = x$, $x_2+x_4 = y$. Therefore: $u_1 + u_2 = (x,y,\frac{-x-2y}{3})$.

$x+2y-x-2y = 0$.

Therefore, $U$ is closed under addition.

Let $u_1 = (x_1, x_2, \frac{-x_1 - 2x_2}{3}})$. We scale each element by scalar factor $\lambda$.

$\lambda u_1 = (\lambda x_1, \lambda x_2, \lambda \frac{-x_1 - 2x_2}{3}})$.

$\lambda x_1 + 2\lambda x_2 - \lambda x_1 -2 \lambda x_2 = 0$. Therefore, $U$ is closed under scalar multiplication.

Therefore, it is a subspace of $\mathbb{F}^3$.

#+begin_quote
10: Suppose that $U_1$ and $U_2$ are subspaces of $V$. Prove that the intersection $U_1 \cap U_2$ is a subspace of $V$. 
#+end_quote

Given $U_1$ and $U_2$ are both subspaces, $0$ must be in both subsets hence it must be in their intersection.

Let $u_1 = (x_1,y_1,z_1)$. Let $u_2 = (x_2,y_2,z_2)$. Finally, let $u_1,u_2 \in U_1 \cap U_2$. By this last fact, we could derive the fact that $u1,u2 \in U_1, U_2$.

As $U_1$ is a subspace, $U_1$ closed under addition. Since $u_1,u_2 \in U_1$, $u_1 + u_2 \in U_1$. As $U_2$ is a subspace, $U_2$ closed under addition. Since $u_1,u_2 \in U_2$, $u_1 + u_2 \in U_2$.

As $u_1 + u_2 \in U_1,U_2$, it is additionally $u_1 + u_2 \in U_1 \cap U_2$. $U_1 \cap U_2$ is therefore closed under addition.

By the same token....

As $U_1$ is a subspace, $U_1$ is closed under scalar multiplication. Since $u_1 \in U_1$, $\lambda u_1 \in U_1$. As $U_2$ is a subspace, $U_2$ is closed under scalar multiplication. Since $u_1 \in U_2$, $\lambda u_1 \in U_2$.

Therefore, as $\lambda u_1 \in U_1, U_2$, it is additionally true that $\lamba u_1 \in U_1 \cap U_2$, it is therefore closed under multiplication.
