#+TITLE: Normal Operators
* Axler7.18 normal                                                      :def:
  Not to be confused with [[file:KBrefNormal.org][normal vectors]], which have [[file:KBrefNorm.org][norm]] 1.
  #+begin_quote
  - An operator on an inner product space is called /normal/ if it commutes with its adjoint.
  - aka: $T \in  \mathcal{L}(V)$ is /normal/ if
  \[\begin{aligned}
  TT^* = T^*T
  \end{aligned}\]
  #+end_quote
  Every [[file:KBrefSelfAdjointOperators.org][self adjoint]] operator is normal, because $TT = TT$
* results
** Axler7.20 $T$ is normal iff $\lVert Tv \rVert = \lVert T^* v \rVert$ for all $v$
   This implies that $\onull T = \onull T^*$ for all normal operators $T$..
** Axler7.21 For $T$ normal, $T$ and $T^*$ have the same eigenvectors
   #+begin_quote
   And the corresponding eigenvalues are conjugates of one another.
   #+end_quote
** Axler7.22 Normal operators have orthogonal eigenvectors
   #+begin_quote
   Suppose $T \in  \mathcal{L}(V)$ is normal. Then eigenvectors of $T$ corresponding to disticnct eigenvalues are orthogonal.
   #+end_quote
