:PROPERTIES:
:ID:       8DB29978-821E-497A-BC07-69151C14AB42
:END:
#+TITLE: Normal Operators
* Axler7.18 normal                                                      :def:
  Not to be confused with [[id:0A7A03F7-22CA-459B-9E2B-850141F2FD28][normal vectors]], which have [[id:6D427595-AFFC-41AD-9486-DC0A67E73082][norm]] 1.
  #+begin_quote
  - An operator on an inner product space is called /normal/ if it commutes with its adjoint.
  - aka: $T \in  \mathcal{L}(V)$ is /normal/ if
  \[\begin{aligned}
  TT^* = T^*T
  \end{aligned}\]
  #+end_quote
  Every [[id:24100495-22CB-4857-919B-A415C5F09601][self adjoint]] operator is normal, because $TT = TT$
* results
** Axler7.20 $T$ is normal iff $\lVert Tv \rVert = \lVert T^* v \rVert$ for all $v$
   This implies that $\onull T = \onull T^*$ for all normal operators $T$..
** Axler7.21 For $T$ normal, $T$ and $T^*$ have the same eigenvectors
   #+begin_quote
   And the corresponding eigenvalues are conjugates of one another.
   #+end_quote
** Axler7.22 Normal operators have orthogonal eigenvectors
   #+begin_quote
   Suppose $T \in  \mathcal{L}(V)$ is normal. Then eigenvectors of $T$ corresponding to disticnct eigenvalues are orthogonal.
   #+end_quote
