#+TITLE: Assay Controls
#+AUTHOR: Peter Choi
#+DATE: 12/8/2021

1) What does your assay test for? What is the measurment (variable) and what is the measurement by proxy?

   My group has two assays:

   a) one assay tests for whether the DH5$\alpha$ gain resistance to ampicillin. The measurement by proxy is the number of bacteria colonies.

   b) the other assay tests for whether the DH5$\alpha$ starts to produce the GFP. The measurement by proxy is whether or not the bacteria will glow under the UV light.
3) What is your positive control? What is your thought behind it?

   a) The poitive control for the first assay is the number of bacteria colonies for the plates with just the LB. The thought here is that if the bacteria gain resistance to ampicillin, then we should see about the same amount of bacteria colonies in the plates with LB and ampicillin as we do in just LB.

   b) The positive control for the second assay is the amount of glow that jellyfish cells, with GFP, would glow. Because we do not have access to this we would likely use pictures from the internet. We chose cells instead of the actual jellyfish because that would be closer to our procedure's conditions. The choice of this as a control was because we think that this would give us the best sense of what a plate of glowing bacteria cell would look like.
4) What is your negative control? What is your thought behind it?

   a) The negative control for the first assay is number of bacteria colonies in the plate with the non-transformed DH5$\alpha$ (which I think will be close to 0). This is because if the bacteria do not gain resistance to ampicillin (amp), then the amp will kill them, and thus lower the amount of seen colonies.

   b) The negative control for the second assay is the amount of glow that the plates, with LB and transformed DH5$\alpha$ or the plates with LB + amp and transformed DH5$\alpha$, produce. This is because with out the arabinose the plates should not glow, similar to how the plates should not glow without the expression of GFP. 
