#+TITLE: Examining your Biases
#+AUTHOR: Peter C.
#+DATE: 12/14/2021

* Is it towards design or is it towards action?

I am more biased towards design. I wanted to have everything planned out before we started, even if it took us more time. That being said, if we were on a shorter timeline, then we would have had to be more action biased. 

* What kind of partners (design or action) do you think you work best with?

I think that I work best with partners that are action biased. This way, they can push the group to actually get things done, while I can hold them back and make sure that we have a plan before we go and do something.

* What is your strength in group work?

Following directions. I like the feeling of being helpful, so if I am given a task then for the most part I can get it done.

I also do not like the feeling of wasting time, so getting the group on track and making sure that we are always doing something productive-ish.

* What is your weakness in group work?

Communication. I have plenty of ideas, but for the most part I do not say them because I lack the confidence, I don't think they will be helpful, I am scared of getting shot down (fear of failure), or I think about how other people think about me too much (self conscious). This is something that I am working with in all facets in life, whether that be DATAS, or even socializing. The problem is, I know the problem, but don't have a solution in mind yet. 

* Where is your bias?

Looking at my answers to the questions above: I think that my lack of communication skills pushes me to be more design focused as well as pushes me to be a direction follower instead of a direction giver.
