#+TITLE: First lab meeting and protocol aquisition readings notes
#+AUTHOR: Peter Choi
#+DATE: 12/2/2021

* Prep for first lab meeting:
Link: https://docs.google.com/document/d/1Ig07u3_womf5xr-lkCM3up9aM9NKSAIKRNgZWnARaMI/edit

- be comfortable admitting mistakes to De and Paul
- De and Paul do not care that you make mistakes, they care that you learn from your mistakes
- What a lab meeting should have:
  1) "the conversation"
  2) documentation of your process
  3) data presentation
- for now we just need:
  1) clear goals and deliverables on asana
  2) visual protocol/protocol aquisition stuff

* XRT L1 protocol aquisition: ExDe Bible
Link: https://docs.google.com/document/d/1n_tRw0m1lnigpB5yBji58lQQhU6VgIKb7sXDryQkuoY/edit

** The goal of protocol aquisition:
- to learn how to deo a new protocol in the most effective and efficient way
- finding all of the things you need to do a protocol
- finding all of the things that the protocol itself does not describe

** The steps to learning a protocol:
1) Do it with someone who has done the protocol before.
   - as they do it, write down a basic protocol, and then watch them again, predicting what they are going to do at ecah step
   - then try the protocol yourself, make sure to note the materials you use
   - See one, do one, teach one
2) What it & tech support
   - can use JOVE (the youtbe of protocols) inorder to get you "see one"
3) Work off of mulitple protocols
   - this will let you know what steps need to be done the same way every time and what steps you can fudge a little.
   - gives you fuller understanding of the protocol

** Visual protocols:
- Why: makes you think about what you are going to need to do and going to need for the protocol before you try to do it yourself. It also serves as visual landmarks for when you are actually doing the protocol.
- What: you draw out the steps of your protocol

** Starts and stops:
- After you draw, identify where you can take a break throughout your protocol
- knowing when you can rest (stops) is important because then you know when you can take a break and do more of the protocol on another day
- sometimes before you start you have to turn things on so they warm up in time

** Timers and watches:
- put a timer on all of the things you need to time so that you remember
- write the times of the start and stop instead of the run time so that you can reference later (ex: 17:00-19:00, is better than 2 hours)

** Prep for the dry run and the dry run:
- Look through your protocol and sort things into:
  1) Consumables
  2) Equipment
  3) Need to premake
  4) stops
  5) Day 0 prep
- Stand in the place that you are going to do your protocol and do a dry run where, you make sure that you have all of the materials and machines that you need to do, you have enough space, and try to minimize the amout of steps you need to take
- notify de or paul and your L3 mentor when you are doing your dry run
- then reserve the needed machines (stick note)

** Recording your data and using your protocol:
- when using your protocol take notes of the places you messed up or the places that you fudged a little so that you can collect data for better understanding

* Lab meeting prompt:
Link: https://docs.google.com/document/d/15UBTrF7qsT8H8CG41oziknZWhsuJRoimHV0Dg98UDTQ/edit

Questions to consider (copied from the doc):
  
Check-in questions: To be asked by Oversight at the beginning of the meeting.
1.  Was everyone here this week?
2.  Is your lab space clean?
3.  Is there any new business that we need to put on the agenda?


Big Picture
1.  Pull up a slide show
1. Schedule the next lab meeting
2. What is your overarching question?
3.  What is the current question?
4.  What method of quantification are you headed towards.

Big Questions
1.  What was done.  Present data.
2.  What do you want to do?
3.  What future problems do you think you are going to need help with.

Leadership/Oversight (To be answered by oversight)
1.  What problems are you trying to figure out how to navigate?
2.  What has been a personal difficulty?
3.  What is the current feeling of the group?


Check-in every day with the rest of your team:
1.  Do you have a current task?  Does everyone know what it is?  Does your task have a deadline?
2.  Do you have at least one to-do per person in Asana.

* Lab Meeting Notebook Guidelines: ExDe Bible
Link: https://docs.google.com/document/d/1kXrR6r9tIkao_delhirxaH1ugUTIWkd0sPFMEWfgKjc/edit#heading=h.ek02jxnh9scd

- Every week you should write an answer to each on of the prompts in your lab notebook
  1) Guiding question
  2) response to feedback
  3) Acomplished this week
  4) What I am having trouble with
  5) Meeting notes:
  6) Goals and deliverables
