#+TITLE: Protocol Acquisition
#+AUTHOR: Peter Choi
#+DATE: 10/29/2021

* What is the difference between an assay and a protocol?
- A protocol is a set of directions. like this one: https://www.neb.com/protocols/2012/05/21/transformation-protocol
- An assay is the transformation from a word to a number

* Protocol Acquisition:
- Goal: Create a distributable set of instructions
- Questions to consider:
  1) Do I understand it?
     - take a series of instructions and ask if you know how to understand it
     - know why you are doing what you are doing
     - can I sketch what is happending in each step?
  2) What are the specifics?
     - Is it safe for me? for others?
     - Are there any stops?
       - how far can you go into the experiment before taking a break
       - the focus of this is time: either find time to do the protocol or split the protocol into shorter time chunks
     - What part of this protocol do I need to be exact with and what part can I fudge?
       - to do this you can look at different protocols that achieve the same thing and see what is constant between all of the protocols. 
  3) How do I interact with it?
     - how am I going to record what I need to record and be able to reference the document when I need to reference it. 

* Project managment:
- when you are in a group:
  1) assign a coordinator
  2) define a deliverable
- once you have a deliverable defined:
  1) write out all the tasks you need to get to the final deliverable (flow chart)
  2) divide tasks into parallel tasks and serial tasks
  3) find how many units you have (the number of people in a group - 1)

* Teacher notes: https://docs.google.com/document/d/1n_tRw0m1lnigpB5yBji58lQQhU6VgIKb7sXDryQkuoY/edit

* Try it yourself:
- Using this protocol: https://www.neb.com/protocols/2012/05/21/transformation-protocol
6) Add 950 µl of room temperature media* to the tube.
   - use a micro pipet to pipet 950 µl of media
   - media: 
7) Place tube at 37°C for 60 minutes. Shake vigorously (250 rpm) or rotate.
8) Warm selection plates to 37°C.
9) Spread 50–100 µl of the cells and ligation mixture onto the plates.
10) Incubate overnight at 37°C.
*Please note: For the duration and temperature of the heat shock step as well as for the media to be used during the recovery period, please follow the recommendations provided by the competent cells’ manufacturer.
