
* animal ethics

** what is the ethical issue?

*** should other species be tested on / sacrificed on possibly dangerous products

*** fundamentally, are animal lives worth less than human lives

** perspectives

*** animal testing is often unethical: animals are not treated right and often die during failed attempts

*** however, to push science forward, some ammount of testing is needed. Testing on humans seems worse than testing on animals.

** stakes

*** larger corporations who are trying to get products out to market have the resources, scale, and incentive to use animal testing

*** biodiversity is being harmed when some species are specifically targeted for testing

*** animal testing allows new drugs / procedures to be tested before accidentally hurting humans in clinical trials

**** can see long term / life-long efffects because animal lives are shorter

**** however, 90% of trials that pass animal stages fail on humans, so does it really even work

*** consumer activism can disincentivise corporations from using non-essential animal testing (eg. cosmetic)


* animal ethics

** what is the ethical issue?

*** should other species be tested on / sacrificed on possibly dangerous products

*** fundamentally, are animal lives worth less than human lives

** perspectives

*** animal testing is often unethical: animals are not treated right and often die during failed attempts

*** however, to push science forward, some ammount of testing is needed. Testing on humans seems worse than testing on animals.

** stakes

*** larger corporations who are trying to get products out to market have the resources, scale, and incentive to use animal testing

*** biodiversity is being harmed when some species are specifically targeted for testing

*** animal testing allows new drugs / procedures to be tested before accidentally hurting humans in clinical trials

**** can see long term / life-long efffects because animal lives are shorter

**** however, 90% of trials that pass animal stages fail on humans, so does it really even work

*** consumer activism can disincentivise corporations from using non-essential animal testing (eg. cosmetic)

* isos scategories

** round one

***

*** pluto

*** picosecond

*** planets

***

*** planet earth

*** pangea

***

***

***

*** pliers

***

***

*** pteradactyl

***

***

***

*** paradigms


** W

*** water recycling, wasm

*** watt

*** watts

*** wetlands, water

***

***

*** weight

***

***

***

*** walls, water

*** watch

***

***

***

*** mrs. who

*** weighing

*** watershed ecology, weak force study


** L

*** Lithography

*** lumen

*** lumens

*** laser

***

*** layfette?

*** language

***

*** leonardo davinci

***

*** laboratory lighter

*** lentivirus

*** laser leveling
