:PROPERTIES:
:ID:       E5613568-716F-40B1-9352-564FCFD26A93
:END:
#+TITLE: Money and Economics
#+AUTHOR: Houjun Liu

* So, what's money?
- Abstract representation of value, and a proxy for value
- Medium for exchange
- Universally accepted
- No other function
- An abstract class for "good"
- Medium of exchange: facilitates trade

* Abstract Money
**Abstract Money**: substitute for /trust/ in trade. 

**Symbolic Fiat Money**: money is worthless paper and hence the value of the money does not come from the thing itself. "Fiat": made up.

Money is worthless. The worth of money is drawn simply from you trusting others will trust it, and others trusting that you will trust it, etc.

"Money is the foundation of society and hence it is the government's power over society."

** Fundamental Believes
1. Beliefs in each agent in the acceptability of money to the other agents
2. Beliefs of the individual agents about the trustworthiness of the bank which controls the money supply
3. Beliefs in the government will /not/ run the printing presses: it's cheaper and easier to trust government

Authorities projects stability. You knew who they were, you knew their name, and you know where they lived. That's more stable and nice compared to some guy you see once.

** Scholarly Definitions of Money
- "Money is what money does"
- "Money is an institutionalized symbol of trust"
- "Money is a *strategic decoupling device*" --- it allows us to create more strategies for bartering. Each leg of bartering between two objects could be async; supply and demand is separated
- "Money is a criterion for distinguishing players" --- the printing of the money distinguishes those who print the money from everyone else
- "Money is a means of generalized *side payments*" --- money allows the dealings and splittings of goods and people ("I will pay you for half a cow.")
  
* Representing Market Structures
"Currencies" are nodes in a market that connect to more than one node. Because then it could be exchanged with each other. 

* How is Money Created
How do we make Fiat money? In the "Money Market", someone has control of the printing process, and someone has to put it into circulation.

To represent this, we usually use a graph:

- the good being created: independent variable $M$
- the price that the goods will cost: dependent variable $i$

This is a very special good; its price is the interest rate. There is some value $M_s$ which is the ceiling of the money.

** What's the Demand for Money?
Its cheap and easy to trust the government, as a part of a government bond. The central bank sets an interest rate, and then figures how much money to print.

** Operations of a central bank

| Assets           | Liabilities                                         |
|------------------+-----------------------------------------------------|
| Government Bonds | Currency in circulation (lender of the last resort) |

Note! They don't generate value. Their literal purpose is to convert Trust (government bonds) to Money, and visa versa.

The value of the US government exclusively comes from its ability to tax people.

