#+TITLE: Victory for Democracy Essay
* meeting Arta 28 April 2021
** domestic politics, some on russia and some on germany
** russia kind of thought all the other countries were the same so it didn't matter who won
** imperialism, thus not democratic
*** british/french werent more democratic than tsars or germany or ottoman empire
*** imperialism is the highest stage of capitalism and thus not marxist
** imperialism vs democracy
*** gelvin: russia publicized the mandates, see gelvin
*** woodrow wilson also thought that imperialism was antidemocratic
*** believed that people should have equal say
*** didnt join league of nations bc senate didnt want to, but wilson may have wanted to
*** syria wanted to be an american mandate (in a comitte in 1919)
** body paragraphs
*** democracy won but not that democratic
*** mandates and middle east
**** turkey/germany became "democracies"
*** east asia: japan takes german colonies
** sentence structures
*** developing your own voice: recognize what you like in other people's writing
**** see their topic sentences and transitions
* marxism leninism
** +We are in favor of a democratic republic as the best form of state for the proletariat under capitalism. But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.+
** democracy won but not that democratic
*** 'quoted the words of Lincoln: “When the white man governs himself, that is self-government; but when he governs himself and also governs others, it is no longer self-government; it is despotism.”' (Imperialism, the highest stage of capitalism, IX)
*** 'But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.' (Lenin, state and revolution)
*** tragedy of the majority vs tragedy of the minority
** mandates and the middle east
*** list the countries
**** Syria
	 wanted united states or britain as mandate power, but were given to france
**** Lebanon
***** created by the french 'just enough territyory to make it economically viable and strategically useful, but not enough to threaten Christian dominence' Gelvin 191
**** Jordan
***** originally called "Trans-Jordan" or literally "across the jordan [river]"
***** solved a political problem but created an economic nightmare
***** external help provided 45% of government
**** Palenstine
***** got split in half and the east side was given to Abdallah as Jordan
***** the rest was "ruled like a crown colony [by the British] until they withdrew in 1948"
**** Iraq
***** also created to solve a political problem
***** joined ottoman provices of basra, baghdad, and mosul
***** given to Faysal, whose descendants ruled until 1958
***** looked like a good idea on paper (oil state), but 'system conspired against it's full political and economic development'
***** many (6?) ethnic groups
*** quotes
**** "however, Britain and France accepted the mandates so that they could retain control over those areas in which they felt they had vital interests" (gelvin 192)
**** 'the accumulation of vast agricultural estates by the new rural gentry, as well as the transformation of once independent pasturalists and farmers into tenant labor' (gelvin 194)
**** lenin
***** 'And so in capitalist society we have a democracy that is curtailed, wretched, false, a democracy only for the rich, for the minority. The dictatorship of the proletariat, the period of transition to communism, will for the first time create democracy for the people, for the majority, along with the necessary suppression of the exploiters, of the minority. Communism alone is capable of providing really complete democracy, and the more complete it is, the sooner it will become unnecessary and wither away of its own accord. ' (Lenin, /State and Revolution/, 1917)
***** "[The state is] a special machine for the suppression of one class by another, and, what is more, of the majority by the minority. ... The systematic suppression of the exploited majority by the exploiting minority calls for the utmost ferocity and savagery ... slavery, serfdom and wage labor' (Lenin, /State and Revolution/, 1917)
**** aristotle
***** 'So it is clear that a polis is of best size when it has a population large enough for a self-sufficient lifestyle but one that can be seen at a glance.' (From Dillon, Mathew, Lynda Garland. 2010. /Ancient Greece. Social and Historical Documents from Archaic Times to the Death of Alexander the Great./ New York: Routledge. Aristotle, /Politics/ 1326b11)
***** "aristocracy, either because the rulers are the best men, or because they promote the best interests of the state and citizens; when the many administer the state for the common interest, the government is called a constitutional government" "deviations from these are as follows: from kingship, tyranny (interests of the ruler); from aristocracy, oligarchy (interests of the wealthy); from constitutional government; democracy (interests of the poor)" Aristotle /Politics/ 1279a32, 1279b4
* outline
As American historian Robert Roswell Palmer concludes in his chapter on the first world war, "the war was indeed a victory for democracy" (Palmer 696). However, as Aristotle defines in /Politics/, the democracy is a deviation from a more pure form of government---the constitutional government or polity---in which the many rule in the interests of the poor. Although modern western writers treat democracies as the gold-standard of government, the interests of the poor can be and are manipulated in the aftermath of the first world war. Additionally, Engels and Lenin argue that imperialism is the height of capitalism and that the state is a machine for oppression of one class by another, in democratic republics no less than in monarchies. Although the first world war was "indeed a victory for democracy," neither the victors nor the aftermath promoted widespread liberty.
The victors of the first world war were tyrannies, not polities, and they did not promote widespread liberty.
Although originally induced by the security dilemma, Europe's rapid military expansion was often exaggerated by political and egotistical motivations: the British government's naval ambitions were not strictly defensive. The English public had been historically isolationist and did not want to join the war. However, the British government saw Kaiser's Kruger Telegram of 1896 and Germany's naval expansion as politically insulting. As tensions increased and militaries were expanded, public sentiment shifted to be more nationalist (Huang, The Inevitable Shift). This engineered public sentiment was quickly reversed when the bloody trench stalemate became apparent, but the war torn countries felt they needed to outlast the enemy as a point of pride. The wage slavery and proletariat oppression of Marx, Engels, and Lenin came in the form of state propaganda posters imploring women to work in factories and conserve bread (Khakpour, WWI Aftermath, 5). English war poet Charles Sorley writes of the "millions of the mouthless dead," exposing the loss of life on the battlefield. The English masses had not been thrust into the war for the common good or the liberty of the citizens---Britain entered the war because it's leadership had been insulted by German industrialization. In the process, the Entente powers amassed massive debts to the United States which their citizens would have to suffer in the coming years. The Entente war effort led to democratic victories, but did not promote the liberty of their citizens.
In addition, the new post-war European entities was not conducive to liberty. The new and democratic German republic, who professed their own ideals, did not feel responsible or attached to the previous regime (Palmer 688). However, the treaty makers in Paris working in early 1919 under public pressure and "still in the heat of the war" dealt harshly to Germany---so much so that no German was willing to sign the Treaty of Versailles (Palmer 692-3). Although the German Empire was toppled and replaced with a more democratic government, the harsh treaty opened the way for Adolf Hitler's authoritarian regime. Hitler's election was indeed democratic, but his regime stripped liberty from vast populations. Aristotle writes that democracies are the "rule of the poor", and Hitler leveraged the hunger and anger of the poor masses to amass power (Aristotle, /Politics/). Once in control, he quickly converted the state to a centralized tyranny focused on his own political viewpoints---or, as Lenin would remark, a machine to for one group to oppress another. As Aristotle predicted, neither democratic nor tyrannical policy was beneficial to the citizen body as a whole. This surface-level "victory" for democracy did not lead to widespread liberty. An additional central goal of the Paris settlement was to allow national self-determination in Europe. The peacemakers attempted to create a sovereign nation for each people in eastern Europe through the League of Nations. However, the intermixing of nationalities, lack of population exchange, and independence declarations of various states complicated the process. As a result, each new state found alien minorities within its borders and next of kin under foreign rule (Palmer 692). The newly-formed buffer states, including Lithuania, Latvia, Poland, and Czechoslovakia, were generally parliamentary democracies (Palmer 692, Latvian Institute). However, they were created to serve the purpose of buffering Bolshevik communism from spreading to western Europe and were thus hastily drawn, culturally torn, and politically weak. The first Latvian president went as far as to demilitarize the country, which was presently trampled in the second world war (Latvian Institute). These cultural divides, which were suspiciously reminiscent of the Slavic misrepresentations in the pre-war Austrian Empire, led to numerous fractured states with disgruntled populations---a number of ostensible democracies that failed to rule in the interest of their citizens.
Furthermore, the League of Nations and colonial aftermath of the first world war were neither democratic nor liberating for the citizens of the world. Starting in 1915 when the entente powers realized the war would not be quick, Britain and France made heavy use of post-war land promises to attract nations to their side of the battle; such secret treaties included the Constantinople Agreement, the Treaty of London; the Sykes-Picot Agreement, and the Treaty of Saint Jean de Maurienne (Gelvin 186-7). When the war was over, one central purpose of the League of Nations was to fairly and humanitarian divide the Ottoman empire and German colonies; however, when congress refused to join the League, the allocation of land and colonies under a "mandate" system was directed by France and Britain (Palmer 690, Gelvin 189). In particular, the western coast of the Arabian peninsula (the Levant) and the fertile center of world trade (Mesopotamia) were to be divided into fledgling states and brought into world of western politics (Gelvin 184). As the major victorious powers in the League, Britain and France were able to create, destroy, and manipulate states under the mandate system at will. Britain took advantage of this opportunity to solve political problems it had created in secret agreements during the war and to maintain control over vital regions (Gelvin 191-2). As a result, middle-eastern peoples enjoyed minimal national self-determination and the mandate system promoted neither democracy nor liberty. Jordan, Syria, and Iraq were among the hastily and selfishly created nations. The British arbitrarily split Palestine at the Jordan River and granted the eastern portion to 'Abdallah, who the British had colluded with to cause the Great Arab Revolt and who was threatening to declare war on France (Gelvin 187, 192). This plot of land, which became known as Jordan, turned out to severely lack natural resources and has depended on foreign aid ever since---a dependency which has limited the autonomy and thus liberty of the government and its citizens. Syria, which declared independence from the Ottoman Empire towards the end of the war, sent a diplomatic committee to Paris in 1819 to request that the Syria be allowed an independent government, or at least be given to the anti-colonial United States. The democratically elected Syrian parliament declared France an unacceptable mandatory power (Gelvin 191). However, the League of Nations truncated Syria and gave it to France as a mandate anyway, directly contradicting the League's purported goal national self-determination and trampling the ambitions and liberty of the fledgling democracy. Most embarrassingly, although Iraq was created as a dependency-theory-style producer state for the British government, the economic focus led to the grouping of numerous ethnic groups and thus extreme political instability. Although most of the inhabitants were Shi'i Arabs, the oil-rich northern territory of Mosul was inhabited by Sunni Kurds and the entire country was ruled by Sunni Arab (Gelvin 193). These economic aims exemplify Lenin's theory that "imperialism is the height of capitalism," and the insuring religious turmoil shows that unchecked capitalist ideals fail to support universal liberty. Although national self-determination dictated that peoples should be grouped into countries by culture, the economically-optimized Iraq became a hostile and violent land of oppressed and misrepresented citizens. Additionally, each of these cases show how governance, both international through the League of Nations and national through each mandate state, is used as a machine for oppression. In each of these cases and many more, the British and French mandate decisions refused democratic demands from the citizens and sacrificed the liberty of the people for political or economic gains.
Although the first world war toppled long-standing monarchies and saw the victory of democratic western powers, the mandate system trampled fledgling democratic ambitions and the victors did not promote widespread liberty. Indeed, the "democratic" victors of WWI held colonies with no voice in the democracy, and the decisions made by mandate-holding powers were not favorable for their dependent states. By Aristotle's classification, this "rule by the rich for the rich" is an international oligarchy that strips the liberty of the colonized for capitalistic gain. Thus, the aftermath of the first world war suggests that capitalism reinforces colonialism and that colonial powers cannot be polities.
** sources
Aristotle. /Politics/.
Huang, Albert. "The Inevitable Shift: How International Incentives Cause Individual Radicals", April 2021.
Khakpour, Arta. "WW1 aftermath - Google Slides".
Lenin, 1917. /State and Revolution/.
Gelvin, James L. 2011. /The modern Middle East: a history/, New York: Oxford University Press.
Palmer et al. /A History of the Modern World/, 9th Edition.
Latvian Institute, 28 Feb. 2017. History of Latvia 1918-1940. www.latvia.eu/history-latvia-1918-1940.

** bloopers
   The heavily nationalist French and English public sentiment at the beginning of the war was fueled by a politically motivated arms race (Huang, The Inevitable Shift). Although originally induced by the security dilemma, the rapid military expansion was often exaggerated by political and egotistical motivations: the British government's naval ambitions were not strictly defensive. This engineered public sentiment was quickly reversed when the bloody trench stalemate became apparent, but the war torn countries felt they needed to outlast the enemy as a point of pride.

   If there was one thing Lenin and Woodrow Wilson could agree on, it was that the secret and unprincipled international politics of the past had led the world into anarchy (Palmer 687-9). In January of 1918, as U-boat attacks were more effectively countered and the tide seemed to be turning toward an allied victory, Wilson unveiled his fourteen points which outlined a more righteous framework for international politics (Palmer 677, 688). At the 1819 Paris peace confrence, Wilson negotiated heavily for one point in particular---the creation of a League of Nations whose purpoted purpose was to subvert the international anarchy and settle future conflicts. As a result, numerous comprimises were made on the fourteen points. <>
