#+Title: 20hist201 ret Unit 1 Essay Draft
#+AUTHOR: Exr0n

* Export

See [[https://docs.google.com/document/d/1Yhd8y7zE_mCdagcaUk8-sFHHh6P7te6zYMmJKJDIKkE/edit][the doc]]

* Introduction
  In the 16th century, two great empires of the world began to falter in the face of the Europeans: the Ottoman empire's military weakenend and the Ming lacked a reliable currency.
  The Ottoman military was comprised of two "branches": a group of traditional Turkish cavalrymen who lived on land grants worth fixed amounts of tax money, and Christians turned Janissaries who were an elite force flexible <TODO: WC revolutionary? forward adapting?> in their technology and salary. As European silver inflated the economy, the fixed wages of the cavalry could no longer support them and they joined a growing mob of fixed wage marauders.
  In the east, the Ming empire featured a large economy built on widly volitile currencies: each Emperor tried in vain to fight inflation by banning the previously inflated coins and issuing new currency at inflationary rates. Merchants grew exasparated at the situation, fighting against foregin trade policies and completing transactions using ingots and shards of silver. 
  It was the economic weak points of fixed wages and inflammable currency that led to the downfall of the great empires, but the similarities don't run as deep as Kennedy suggests. Although the economies of both the Ottoman and Ming empires suffered spiraling inflation and civil unrest, the Ottomans' overstretched military was undermined by Europeans trading silver while the Mings' internal inflationary spiral forced trade with and ultimately destruction by Europeans.

* Body 1: counterargument
  Both the Ottoman and Ming empires suffered from similar viscious cycles of economic weakness and civil unrest.
  In the Ottoman empire, the traditional Turkish cavalrymen were slowly losing power. They disdained firearms and were thus becoming irrelevant on the battlefield. To compensate, the government wanted increased the number and therefore cost of the modernizing Janassary corps--it would have to regain control of the land and taxes held by the defunkt cavalry (Bulliet 491).
  The central government needed an excuse to diminish the cavalrymen, and as European silver inflated the Ottoman economy the cavalrymen were finding it increasingly difficult to live off their fixed taxes. The central government siezed the opportunity and reclaimed land from absent cavalrymen, creating an influx of ex-soldiers who were armed and unhappy (Bulliet 491). The revolts that followed required force to quell, and the government had a progressively harder time paying its expensive Janassary corps. Civil unrest worsened with the economic situation, and the Ottoman empire corroded from the inside.
  In the Ming empire, a mix of turbulent currency and trade bans created expensive civil unrest. When private foreign trade was halted, bands of smugglers--collectively known as the /wokou/--cropped up in the province of Fujian. As Mann put it, "if business is outlawed, only outlaws will do business", and these outlaws were a violent group: after years of government raids, the wokou struck back, "overwhelming all resistance", abducting over a thousand people and burning over a thousand homes (Mann 128, 133).
  It didn't help that the empire had sporadically functioning currency--it was difficult to carry out imperial edicts when the prefered money "flipped arbitrarily from one Song empire to another," (Mann 138). The currency was so ineffective that merchants started carrying out transactions with chunks of silver, which could only be sourced by illegal trade with foreigners. Soon the status quo was a cycle of business people paying taxes with smuggled silver that was used to crack down on the violent smugglers and reduce the supply of illegal silver.
  Both the Ottoman and Ming empires suffered decline rooted in cyclic and crippling economic troubles. Kennedy writes that these downfalls were "strikingly similar" due to shared defects in "centralization" and "attitude toward commerce" (Kennedy 11). Although Kennedy attempts to neatly wrap up the downfalls of these great empires as a product of their structural "deficits", Europe significant and contradictory roles in the economic struggles of each empire; this calls for a reevaluation of possible oversimplifications in Kennedy's argument.

* Body 2: Ottomans
  Europeans used soft power to mislead the Ottoman empire into trading agreements that caused cripling inflation and corruption, a corrosive trend that lead ultamately to the Ottoman empire's downfall.
  The Capitulations of the mid sixteenth century were a series of trade agreements between the militarily dominant Ottoman empire and the various states of Europe designed to facilitate trade (Cleveland 50). Because the European nations were weaker than the Ottomans at the time, the Ottoman empire felt safe and philantrophic in the negotiation of the treaties.
  Not only did the Capitulations promise truce at war and zero additional import and export taxes, they also served as a sign of political trust. Even in early drafts of the treaties, the Ottomans grant the French consul juristiction over it's nationals on empire soil. One draft from 1535 states that a French consul is to be maintained in the "proper authority" to "determine all causes, suits, an differences, both civil and criminal, which might arise between merchants and other subjects of the King" (Hurewitz 3). Although this is an early draft of the treaty, the loophole spawn of the Ottoman downfall is already apparent--the French see it as "proper" that they should have juristiction in another country.
  Why did the Ottomans give the French so much power? The drafting of this Capitulation came before the wave of Spanish silver, which was only discovered a decade later in 1545. Although the Ottomans could have extracted more benefits from the weaker French, they instead ratified this treaty to encourage the weaker state to trade--a strategic move to control international commerce. The treaty seemed safe: the foreign bailiffs wouldn't dare abuse the treaty... not in the face of the mighty Ottoman empire. 
  The strong military of the Ottoman empire continued to campaigned against various states of Europe, securing another Capitulation with each victory. Europe's internal international policy of Raison d'etat created a culture of backstabing--a system of balance that discouraged long periods of alturistic trade (Kissinger 69). This conflict in Europe and easy trade with the Ottomans facilitated a boom in international commerce: the citizens of the empire had tariff-less access to manufactured products from all accross Europe. The Ottoman machine ran smoothly, until a sudden influx of European silver turned the system on its head and set the vicious cycle of inflation, weakening, and revolt in motion as seen previously.
  
  +In the late sixteenth century, European who were suddenly bloated with silver started trading at outbidding the Ottomans for their raw materials (Bulliet 494). As Ottoman raw materials were inceasingly traded for European manufactured goods, the Ottoman military found it increasingly difficult to arm themselves and fight effectively (Bulliet 491). Furthermore, the tightknit trade relation between the Ottomans and Europe created a wave of inflation as Ottoman exporters got their hands on the influx of silver.+
  +Coincidentally, the fixed salary land holding cavalrymen were becoming increasingly irrelevant in modern warfare and the government was looking for a way to regain control of it's territory. When the wave of inflation prevented the cavalrymen from reporting to service, the government siezed their land and used the taxes to pay the ever increasing well trained and highly effective Janassaries (Bulliet 491). As the economy inflated, the livelihoods of state employees, students, and professors living on fixed salaries became impossible to maintain, these citizens formed "bands of marauders" who staged revolts that required ever expensive military action to quell (Bulliet 491).+
  +To accelerate the corrosion, the Janassaries took advantage of the confusion to make their position hereditary and abolish the selective recruitment process. Although this saved money on paper, the "increase in total number of Janassaries and their steady deterioration as a military force more than offset these savings," (BUlliet 491). Through this chain of events, European trade induced inflation fed a cycle of revolt and military deficiency, allowing more revolt and further increasing the need for military expenditure.+
  +To cap it all off, as the military prowess of the Ottoman empire dipped into a steady decline, the powers granted to the consuls by the originally advantageous Capitulations were abused with "increasing frequency," (Cleveland 50).+
  This is how Europe bested the Ottomans: a set of exploitable treaties signed under differing circumstances and an influx of inflation targeting an indexterous wage system stiffled down a branch of military with outdated techniques and allowed civil unrest to weaken the empire internally.
  
* Body 3: Ming
  Unlinke the Ottomans, the Ming empire was having money troubles before European merchants showed up. 
  China opened up to European trade to reverse it's existing deflationary spiral, creating a European dependence on Chinese trade that ultamately incentivised it's destruction.
  Since the twelvth century, Chinese currency had been highly volatile. As each ruler realized the "virtues of an active printing press", inflation exploded until the next emperor banned use of the previous currency and issued his own (Mann 136).
  Eventually, merchants grew tired of unreliable government currency, and started paying their dues with ingots and shards of silver. To evaluate the [silvers] purity, they used [silvermasters], who charged a fee for the evaluation and routinely cheated all parties" (Mann 138).
  However, silver was a scarce commodity. Wang Xijue, a Ming dynasty court official, wrote in 1593 that grain prices dropped despite poor harvests due to the deflation of silver. "As the price of grain falls, tillers of the soil recieve lower returns on their labors, and thus less land is put into cultivation," (DBQ Doc 3). That the emperor is recieving and tolorating reports of the issues with silver currency show how helpless the situation is--the Ming empire already relied on silver, yet the veins of it's economy were starved of blood.
  It was only until the Portuguese appeared that the Ming economy could assimilate the silver it needed to function. Three decades into the critical silver deficit, a report from Ming dynasty court official He Qiao Yuan suggests a route to salvation. He writes "Chinese silk yarn worth 100 bars of silver can be sold in the Philippines at a price of 200 to 300 bars," and suggests the possibility of repealing international trade bans to accumulate silver (DBQ Doc 7). Although not explicitly stated, trade in the Philipinnes would revitalize the Ming economy--the effective amount of silver could double per transaction.
  As Mann puts it, "the unexpected discovery of silver-bearing foreigners in the Philippines was [...] a godsend," (Mann 139). Unlike the Ottomans, who had an effective system of government and trade before the European flood of silver, the Ming economy struggled to find enough silver to function. The European influx of silver actually boosted the Ming economy, whose hunger for silver created an inseperable trade relation with Europe.
  As English scholar Charels D'Avenant wrote "But since Europe has tasted of [Chinese] luxury, it can never be advisable for England to quit this trade, and leave it to any other nation," (DBQ Doc 8). When Ming China saved its economy by trading with the Europeans, it created a European dependency that would lead to an addiction. Eventually, Europe would try to control that addiction, an attempt that would manifest itself as the Opium wars. Although European silver saved the Ming government, European trade would kill China two centuries later. 

* Conclusion
  In the sixteenth century, both the Ottoman and Ming empires struggled economically--the first sign of weakening and a shift in the world power dynamic. +Although both empires had strong central governments and systematic flaws, their economic downfalls with relation to Europe were antithetical: the Ottoman empire was internally corroded by outdated treaties and European trade induced inflation while the Ming rulers created economic instability that was solved aliveated by European trade.+
  Although the economic downfalls of the Ming and Ottoman empires appear similar on the surface, a closer look at those arguments (such as Kennedy's) may be called for: Europe caused the downfalls of both empires, but the Ottomans fell to internal deterioration while the Chinese would survive until the Opium wars. European silver killed the Ottoman empire and penultamately saved but set up the destruction of the Ming.
