:PROPERTIES:
:ID:       1359C126-7000-4307-9AB0-8DD5E4FED5F7
:END:
#+title: The 1920s
#+author: Houjun Liu

* Context
- Push-back on conservative
- Jazz
- Massive consumerism; the average American has debt 2.5 their net worth
- Ford cars
- Massive immigration restrictions: pitched to favour northern European immigrants
- Babe Ruth: baseball and celebrity culture takes off
- KKK and white supremacy: most confederate monuments were built around this time

* Reading
- [[id:8A6E6D3D-516C-43B1-8A36-608A2DB7449A][Locke and and DuBois]] 

* Harlem Context
- Jazz: new, edgy art form
- Blues: prohibitively new culture

- "Variety and diversity of Black life."

Common Themes: slavery + freedom, marginalization, folk traditions, black identity; performing arts and culture being sponsored by white audiences, self-determination, and religion

* Jazz
Jazz moved north by Southern migrants. Not Embraced by the black elite + becoming generically "American" genre.

Allowed the first racial mingling.

* So why did the Harlem Renaissance end?
The Great Depression: began to have a greater impact on the black population. 50% of Harlem unemployed, continuous flow of refugees from South needing public assistance, with little to no funding for arts.

- Prohibits ends, white patrons no longer sought illegal clubs.
- Harlem Riot of 1935: arrest of shoplifter, 3 dead.
- Identity Lit => Proletariat Lit: that Black intellectualism focuses from uplifting African Americans to uplifting poor

* Station Gallery
1. What is the most striking, what stands out?
2. Can you identify any poignant imagery? metaphore? symbolism?
3. What is the mood? what is the message?
4. Themes and connections?
5. What can we learn about the Harlem Renissance from this piece?

** Within Our Gates
1. What struck out was the strong element of race which prevailed through the film: that the tension caused by race is made a central element of the actual film.
2. Side note: the association between manhood and women hood is blurred
3. There was great contention throughout the film, but the contention seems to be much more unspoken

** Idyll of the Deep South
1. The most striking point of the figure is of course the faintness of the siloettes which hides a sign of identity and individualism in favor of a specific 
2. One particularly important aspects that I noticed was the overall facing which an individual had---that characters are focused against the "flow" of the crowd, showing a sense of individualism, but generally one moved towards one direction

