:PROPERTIES:
:ID:       5F874584-07A9-4646-9AD0-0C7736308440
:END:
#+title: WWI Notes
#+author: Houjun Liu

- Imperialism
- Nationalism
- Alliances

* Reading Notes
- [[id:8A6E6D3D-516C-43B1-8A36-608A2DB7449A][Locke and and DuBois]] 

* The US

** Staying Out of the War
The United States wanted to keep people out of the war. Europe had been the economic super power at the time, so wanted to stay majority mutual.

- Secretary of State William Jennings Bryan
- Business leader Henry Ford
- Socialist Eugene Debs
- Activist Jane Addams

# Woodrow Wilson is the first Southern Democrat to be elected president. Wilson won on an anti-war platform, and won basically only because Teddy Roosevelt split the vote.

German shot the Lucitania, a commercial ship. Germany attempted Zimmerman telegram: sent telegram to Mexico.

** Starting the War
British enacted a blocade of trade, and Americans followed the blocade. They were funding the British military war effort, and getting an economic boom for it.

Draft was put into place as soon as the war was declared, but named "Selective Service."  Outlawed substitution but created draft boards that were local. Wilson, as a progressive, had to ideologically justify all wars---he used "preserving democracy" as an excuse.

Leveraged movie starts and celebrity culture: Chaplin and Ruth promote bond drives.

People began ostracizing Germans.

** Production
First mechanized war: used industry towards this. No rationing, but "Meatless Mondays" etc. 22% from taxes, 20% creating new money, 58% from bonds. Because all of these production, the US becomes a global predator of production.

** Racial Tensions
Increased racial tensions lead to increased tensions in cities. By 1917, we see the first E. St. Louis Race riot with hundreds of African Americans riot. Young African American solders riot: why fight for democracy when democracy is restricted at home.

** Sedition acts
Uttering "seditious" ideas not allowed. Constitution Upheld

** Propaganda
George Creel ran Committee on Public Information. "The Greatest Experiment in Mass Advertisement."

- Pamphlets
- Newspaper releases
- Magazine advertisements
- Films "The Beast of Berlin"
- 4-minute men speeches - best 4 minute speech between files
- School campaigns
