#+TITLE: Neural-Biology of Emotion
#+AUTHOR: Houjun Liu

* Questions to Respond
- What are emotions? Where do they come from?
- How does lived experience, culture, biology impact our experiences of emotion?
- What contradictory or controversial perspectives or understandings were shared in this resource?

* The Neural Biology of Emotion
:PROPERTIES:
:NOTER_DOCUMENT: Nerobiology_of_Emotion.pdf
:END:

** Depression as a Form of Intense Sadness
:PROPERTIES:
:NOTER_PAGE: (1 . 0.2537313432835821)
:END:

What's critical is that the sadness comes from within one.

** isnatoheusntaoehu
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6490066225165563)
:END:
asonetuhsaoenu
** some note!
:PROPERTIES:
:NOTER_PAGE: (3 . 0.704635761589404)
:END:
notes


Also, the passage seems to take a more balanced perspective with respect to treating emotions. It leverages the idea of both historical and social priming but also accepts the existence of genetic dispositions. Instead of taking a more controversial stance such as the total existence of in-bult emotions or the total rejection thereof, the passage’s focus and acceptance of emotions as a combination of the two — along with specific parts of the brain towards which it points responding to emotions — makes it a more believable candidate than our previous two readings/watchings. 
