#+TITLE: Personal Transformation
#+AUTHOR: Houjun Liu

* Personal Transformation Notes
:PROPERTIES:
:NOTER_DOCUMENT: Personal And Systemic Transformation.pdf
:END:

** Changing individual attitudes is actually the easiest part of social change
:PROPERTIES:
:NOTER_PAGE: (3 . 0.25165562913907286)
:END:
Social change is not just a change of many individual attitudes. In some ways, that may be the easiest part of social change. Many people’s attitudes about racism or climate change have shifted, even in the last decade, but the systems driving white supremacy and climate destruction have not.

** Social justice pitched as an important part of change
:PROPERTIES:
:NOTER_PAGE: (8 . 0.22119205298013245)
:END:
Join organizations and alliances that are focused on equity, changing the economy, and environmental justice.

** We could change our surroundings for positive change
:PROPERTIES:
:NOTER_PAGE: (9 . 0.5358090185676392)
:END:
The great news is that we can also shape and affect these Sites toward what’s more life-affirming, toward change.

