#+TITLE: Rotational Inertia and Kinematics
#+AUTHOR: Houjun Liu
#+INDEX: PHYS360!Derivations!Rotational Inertia and Kinematics

* Deriving Rotational KE and Inertia
Given $m_i$, mass, $\vec{r_i}'$, location of the center of mass, $l_i$, $\omega$, the angular velocity, figure a $KE_{tot,rot}$. 

Because of the fact that the value $\omega$ is in units $\frac{d\theta}{dt}$, the rate of radians change, and we know of a radius of the spin $l_i$, we could figure the velocity at which it is moving by simply scaling the change in radians up to a circle of radius $l_i$, that is:

\begin{equation}
    V_i' = l_i \omega 
\end{equation}

(note that, to understand this, radians $\frac{arc length}{radius}$)

And so, substituting into the statement of $\sum^N_{i=1} \frac{1}{2}m_i\vec{v_i}'^2$

\begin{align}
    KE_{rot} =& \sum^N_{i=1} \frac{1}{2}m_i\vec{v_i}'^2 \\
    =& \sum^N_{i=1} \frac{1}{2}m_i(l_i \omega)^2 \\
    =& \sum^N_{i=1} \frac{1}{2}m_i l_i^2 \omega^2 \\
    =& \frac{1}{2}\omega^2 \sum^N_{i=1} (m_i l_i^2)
\end{align}

** Rotational Inertia
The right sum --- the mass times the distance away from maxis of rotation ($\sum^N_{i=1} (m_i l_i^2)$) --- is defined as the rotational (moment) of inertia (spinny mass). That is,

\begin{equation}
    I = \sum^N_{i=1} (m_i l_i^2)
\end{equation}

Replacing that value in the prior statement, the statement of $KE_{rot}$ is defined as:

\begin{equation}
    KE_{rot} = \frac{1}{2}\omega^2I
\end{equation}


** Rotational Inertia for a Ring
For a ring (that's perfectly circular) rotating on an axis perpendicular to the plane of the ring, the $l_i$ --- distance from axis of rotation --- is the same value: namely, the radius $R$ as the radius of a circle is the same for all positions. Meaning,

\begin{equation}
    l_i = R
\end{equation}

regardless of which value $i$.

Hence, the value of $KE_{rot}$ would be evaluated as...

\begin{align}
    KE_{rot} =& \sum^N_{i=1}(m_il^2_i) \\
    =& \sum^N_{i=1}(m_iR^2) \\
    =& R^2 \sum^N_{i=1}m_i \\
\end{align}

Substituting $M$ as the sum of all masses in the ring ($M=\sum^N_{i=1}m_i$), the statement is therefore:

\begin{equation}
    KE_{rot} = MR^2
\end{equation}

** Rotational Inertia of a Solid Sphere
I believe that the rotational inertia of $I_{sphere}$ to be less than $I_{disk}$. This is because, as the dimension of the object increases, it would be easier to change its velocity (a disk is easier to spin than a ring, etc.). Hence, my intuition states that $I_{sphere}$ would be lower than $I_{disk}$.

Mathematically, as $M$ is staying at the same value, in the disk case has more mass closer to the axis of rotation --- meaning that the $m_iR^2$ term would be smaller in more of the point masses than that of an object at a lower dimension. Hence, the sphere would have more points with lower $m_iR^2$ terms than that of disk; hence, $I_{sphere}$ would be less than $I_{disk}$.

* Kinematics Equations 
Given $a=a_0$, initial velocity $v_0$, and position $y_0$, we derive the kinematics equations.

\begin{align}
    a(t) =& a_0 \\
    \int a(t) dt =& \int a_0 dt \\
    v(t) =& a_0x + v_0 \\
\end{align}


