#+TITLE: Rotational Kinetic Energy
#+AUTHOR: Houjun Liu
#+COURSE: PHYS360
#+SOURCE: KBPHYS360MasterIndex

* A review of what happened before

\begin{align}
PE &= mg \Delta h \\
KE &= \frac{1}{2} mv^2
\end{align}

* Rotational Kinetic Energy
But, really, the definition of kinetic energy is a bit of a lie. Because really, its actually the following thing:

\begin{equation}
KE_{total} = KE_{translational} + KE_{rotational}
\end{equation}

Where, $KE_{rotational} = \frac{1}{2}MV^2$ we already know. That's the movement of CM. But, there is another energy if the object spins:

\begin{equation}
KE_{rotational} = \frac{1}{2}I\omega^2
\end{equation}

Where, $I$ is the moment of inertia ("spinny mass") around the axis of rotation, and $\omega$ the angular velocity ("spinny velocity").

You could see, the same equation just happens twice, but the variables are different for the rotational case.


** Axis of Rotation
A line through the center of mass such that the rest of the mass of the object are going in circular motion around that axis. Yes, if the object is tubing, it will just rapidly change.

** Angular Velocity
Its the speed at which its rotating. So:

\begin{equation}
||\vec{\omega}|| = \frac{d\theta}{dt}
\end{equation}

But, its a vector! So there is an actual "direction" of rotation. If you have an object that's rotating and an axis for that rotation, take your fingers to the direction by which the object is rotating, your thumb is point at the direction of rotation and hence you could assign a sign.

** Deriving the Value of Kinetic Energy
[[file:KBhPHYS360RotationalKineticEnergyDerivation.org][See here.]]
