:PROPERTIES:
:ID:       C6B0902B-4701-4FDD-8BB9-B521F6128413
:END:
#+title: Self Evals: HIST301 Sem. 2
#+author: Houjun Liu

Describe a memorable moment of personal learning you experienced during this class. What did you discover about yourself as a learner? 

One of the most important point of personal growth is actually improving my notes system over this semester. As we discussed throughout the year, one of the things which I particularly enjoy tinkering with is how I preserve and iterate upon existing knowledge as a part of my scheme for learning.

Throughout the year, I particular enjoy the process of organizing knowledge and their corresponding reading to see large connections between concepts. It allows me to see a more nuanced and specific view into readings---where, if the density of content in a particular area is high, I know there maybe importance and controversy---which helps focus how I am reviewing and learning about the content.

What historical/academic skills do you want to work on next semester or next year? (consider the writing process, reading strategies, research, public speaking & participation, group collaboration, etc.)

I think I am interested in working on being more specific in my writing. This actually manifests in a different way that one would usually expect: my writing often has the trouble of being too convoluted, which is actually due to the fact that there is a lack of specificity to my writing which necessitates longer sentence structures to express complex ideas.

In this year, I have thrived to work on this: clarifying my writing and my style to a point where I can have a unique voice and tone without resulting to route convolutions that render my writing vague and confusing.

What deeper insights did you gain into United States history? Which issues will stay with you, and which will you continue to engage with, after our semester concludes?

I think knowing the context of American history is one of the things which is most effective as a part of working in the larger world. Because of the fact that history acts as one of the best predictors which dictates the future behavior of similar situations, it is helpful for me to be a student of history to ground my decisions on possible decisions in the people of the past.

Because of this predictability about history, it will be a very useful skill to analyze systems 

