:PROPERTIES:
:ID:       FB2ACCD9-9A09-4CA3-B44F-F2C2431321C6
:END:
#+title: Self Evals: SPAN401 Sem. 2
#+author: Houjun Liu

1) Spanish Language Proficiency

How would you describe or rate your improvement as far as Spanish language proficiency and knowledge is concerned?  Our class is dependent on students engaging in communicative activities: How would you rate your participation in these activities?  What communicative aspects of the Spanish language (speaking, listening, reading, writing) do you think you have improved most?

I tried to improve my ability in speaking and listening in the language, which is the objectives that I am most interested in improving in. Because of the fact that communication is one of the most important marks of mastering a language, I am happy to focus on and improve my ability in this area. 

2) Personal Growth

How would you describe your overall experience in this course? What are your strengths and weaknesses? How did you grow as a language learner this semester? 

> ahnateu

3) Habits of Learning

Briefly mention your habits of learning in this course, such as homework, study habits, class participation, and self-initiative: going beyond what is expected of you. What was most challenging for you in this course? What are your strengths and weaknesses? In what areas could you improve?

> ahnateu
