:PROPERTIES:
:ID:       9DA46441-BADF-4B66-BF23-F965347CB1AA
:END:
#+title: Self Evals: ENG301 Sem. 2
#+author: Houjun Liu

In considering recent assignments, what are you proud of? 

For the semester, I am actually very proud of my work re-thinking evidence I found for the Bluest Eyes essay as a part of the re-assessment. I think my original essay was not at a great place when I initially submitted it, as I---unfortunately as a point I need to improve on---has made the essay again into a logical series of deductions that slowly veered away from the content of the text.

In my re-assessment, I was able to rethink the body of evidence shown in the text to focus on being much more grounded in the work in honoring its content. Furthermore, I took care in rethinking my sentence structure to be more "conversational": keeping the same level of formality but reducing the amount of long trains of thought and logic as a way to clarify my writing.

What are your areas of strength in terms of literary analysis as we close the year?

I think I was able to successfully closely read the texts themselves fairly well. Despite a few analytical reaches, my initial layer of close reading---for myself---often brought nuance and complexity in the text which I did not see before.

Furthermore, I consider my class participation and ability to engage  



What are your continued goals as a writer/reader/speaker for next year? Think of this also as what you still learning or refining, or what's in progress for you.
