#+TITLE: E Unit 2 Essay Planning + Outline
#+AUTHOR: Exr0n
* Prompt
  #+begin_quote
  Option 1: "The concept of the balance of power was simply an extension of conventional wisdom. Its primary goal was to prevent domination by one state and to preserve the international order; it was not designed to prevent conflicts, but to limit them. To the hard-headed statesmen of the eighteenth century, the elimination of conflict (or of ambition or of greed) was utopian; the solution was to harness or counterpoise the inherent flaws of human nature to produce the best possible long-term outcome."

  Henry Kissinger, Diplomacy

  From one point of view, balance of power politics in the early modern period succeeded spectacularly, preventing a single European power from conquering the whole continent, although Napoleon almost succeeded. From another point of view, it exported great power conflict to the rest of the world, turning Africa, the Middle East, Asia, and the Americas into battlegrounds for rivalling European states. In the end, did the European balance of power succeed in its goal to, as Kissinger puts it, limit conflict and produce the “best possible outcome” from flawed human nature? Or did it magnify conflict and increase the likelihood of global war? Answer this question in a well organized essay using examples from multiple global regions.  (Kissinger, Mason, Roberts)
  #+end_quote
* Outline
** Intro
*** Background Info
**** Raison d'etat
     In the 16th century, as the Reformations saw the church lose its political standing over Europe, the emerging states of Europe needed some philosophy to balance power amongst them and prevent unification, which they imagined to require innevitable and brutal conflict. The statesmen of the time, following the example of Cardinal de Richelieu, First minister of France from 1624 to 1642 (Kissinger 58), settled on the policy of /Raison d'etat/: the idea that a group of states each pursuing its own selfish interests would create a balance of power, with weaker states banding together in times of need and no one state gaining a significant upper hand.

**** Mercantalism
     At roughly the same time, the concept of mercantalism, or the idea that economic transactions are zero sum games that the government must control and play, cropped up. Proponents such as Jean-Baptiste Colbert, minister of finance and minister of marine and colonies for France from 1661 to 1683, saw mercantalism as a component of Raison d'etat's <punctuation, apostrophe?> selfish furthering of the state. While Raison d'etat primarily concerned negotiations with and attitudes towards neighboring states, mercantalism had colonial implications.
     This dual philosophy of looking to gain the upper hand both militarily and economically, termed "balance of power politics" was supposed to keep peace and limit conflict in Europe. However, it ultamately magnified conflict both on the European subcontinent and in various colonial endevours.

*** Thesis
    Although Europe managed to remain disjoint and disunited, conflict based politics and the related mecentalist mindset hardly limited conflict or produced a desireable <WC> outcome: Raison d'etat is a viscious cycle that prolonged wars in Europe, exported conflict and oppression to India and the Caribbean, and forces itself upon territories it encounters.

** Richelieu + Raison d'etat
   Raison d'etat--the basis <WC> for 'balance of power politics'--countered unification by prolonging wars and levaraging suffering, creating unessesary conflict for a not-so-rosy <WC> continuation of power struggle <rephrase> that other states could respond only with their own selfish strategies <phrasing>.
   When Richelieu came to power in 1624, France was surrounded by Habsburg lands and the Holy Roman Empire still posed a military threat. However, when the Holy Roman Emperor refused peace terms with the Protestant princes on religious grounds, Richelieu was determined to take advantage of the fighting (Kissinger 61). As Henery Kissinger, American politician and diplomat explained in /Diplomacy/, "In order to prolong the war and exhaust the belligrants, Richelieu subsidized the enemeies of his enemies, bribed, [and] formented insurrections," (Kissinger 62) <quote integration?>

*** "In order to prolong the war and exhaust the belligrants, Richelieu subsidized the enemeies of his enemies, bribed, formented insurrections, [etc]" (Kissinger 62)
    By defenestrating <wc: too memey?> morality and focusing on political interests, Richelieu chose to protect France in the international game of prisoners dilemma <phrasing: game? of prisoner's dilemma>. Richelieu continued to act exclusively in the interest of the state, standing by while Germany was devastated and fighting on the side of the Protestant princes with to exploit France's growing power (Kissinger 62).

*** "France stood on the sidelines while Germany was devastated" (Kissinger 62)
    By taking advantage of existing conflict, letting Europe bleed until it was time to extract, France expanded its power until it could not be ignored. The balance of power that Richelieu expected could only come when neighbooring states banded together to stop a stroger power from taking over, with each state constantly reassessing its relationships with its neighbors. In other words, as soon as one state adopts Raison d'etat, all the neighboring states must do so as well or risk being crushed by the aggressor. In this way, Raison d'etat not only promotes war and death, it also proliferates by forcing the hand of others. In essence, Raison d'etat exploits the tragedy of the commons and create hostility between all parties--seeking a fragile balance of power built on conflict and shifting loyalties.
    <TODO: summarize, maybe a little more?>
*** "He seeks peace by means of war" (Quote on Kissinger 64, footnote 10)
*** "[Richelieu believed] the end justified the means" (Kissinger 64)

** India
   Not only did balance of power poltics prolong <WC> conflict <WC> in Europe, it also created an air of rivalary that brought other reigons, such as India, into the fray. Because Raison d'etat only creates a balance of power when other states are participating, expansion to other territories can lead only to conflict and domination.
*** "These armed forces of the merchant companies now became war-making entities that drew Indian governments and their armies into the commercial and national struggle between the British and the French." (Trauttmann 176)
    The colonial domination of India began with fortified trading posts owned by the French and British East Indian companies. As the rivalary between the British and French grew, their respcetive merchant companies were subliminally pressured to be more aggressive, turn more profit, and generally outpace the counterpart. When the opportunity to expand their respective operations arose, the trading companies began fighting battles, negotiating terms, and ruling large swaths of land in India. The British gained a solid foothold in 1757 when the British East India Company army defeated the Mughal governer of Bengal at Plassey in 1757 (Trauttman 176). It was in this way that the profit incentivised companies became, as American historian Thomas Trauttmann put it, "war-making entities" that "drew Indian governments into the commercial and national struggle between the British and the French" (Trauttmann 176).

*** +"These 'princely states' ... each had a British 'resident' who kept them apprised of British policy, and often interfered with the internal goverance and the sucession to the kingdom." (Trauttmann 179)+
*** "[The mutinies of 1806 and 1857] had elemnts of feeling that religion was under attack" (Trauttmann 179)
    As the British tightend it's grasp on India and drove the French out, it further assimilated the native power structure and peoples into it's military <rephrase>. The mercentalist ambitions of the company strove to extract profit from each interaction, failing to keep its soldiers happy. The mutanies that resulted, especially in 1806 and 1857, were sparked by the feeling that religion was under attack (Trauttmann 179). As the rebellion spread, the British struggled to quell the conflict that resulted from the mercantalist inspired, extraction oriented approach to rule.

*** "The aftermath of the failed Rebellion was a complex mixture of repression ond canciliation by the British. The mutineers themselves ... were harshly and publically punished, some of them being tied to the ends of cannon and blown in half." (Trauttmann 181)
    After the rebellion was extinguished, the Company used the remaining loyal troops to further repress the uprising, with some mutineers being tied to the ends of cannons and blown in half (Trauttmann 181). The mercantilist mindset and French rivalary drove the British to maximize extraction of value from India, repressing the people and creating conflict along the way. Raison d'etat was meant to limit conflict and prevent the inhumane domination of a territory by a single power, yet the British did exactly that to India in the process. Because India saw it's trade relation with Europe as a positive sum game instead of through the mercantalist lense, and because it did not participate in Raison d'etat, it was trampled by the states vying for power and suffered as a result. This serves as an example of how Raison d'etat brings down a healthy relationship and enforces conflict: an aggressive state forces others to fight it, or risk destruction themselves. Thus, Raison d'etat and mercantalism only achieves a balance of power by incentivising conflict and threatening destruction.

*** TODO salt hedge? How to cite?
*** "But the immediate cause of British rule in India was the worldwide struggle of England and France, which the English and French East India Companies joined in," (Trauttmann 177)
*** "India had been irresistably sucked into the worldwide conflict between British and French power" (Roberts 642)

** Caribbean
   Like India, colonial rivalaries brought European exploitation and conflict to the Caribbean, wiped out the native population, created demand for slaves, and brought more profit seeking Europeans to continue the cycle.

   When the Spanish later established colonies on the larger Caribbean islands, they were only there to gain some slight imperial advantages over their enemies back in Europe. As in India, the native inhabitants of the Caribbean were unable to resist the weapons and disease brought be the Europeans, and were subsequently trampled by the ambitions of Raison d'etat and the mercantalist agenda. However, the promise of new lands and rivalry between nations took the exploitation of the Caribbean multiple steps further. As British Historian J. M. Roberts explains, "The spanish occupation of the larger Caribbean islands ... attracted the attention of the English, French, and Dutch" (Roberts 650).

*** "The spanish occupation of the larger Caribbean islands ... attracted the attention of the English, French and Dutch" (Roberts 650)
    The selfish hunger for power endorsed by Raison d'etat brought the first Europeans to the Caribbean, and the fear of domination by those early settlers brought the rest of the Europeans too. Once settled, the mercantalist mindset and rivalary of European nations brought the backstabbing conflict to everyday Caribbean life. In fact, England's new tobacco colonies became of great importance not only because of the revenue that the mercantalist mindset so sought, but also because the "provided fresh opportunities for interloping in the trade of the Spanish empire" (Roberts 651).

*** "[Tobacco colonies in the new world] rapidly became of great importance to England, not only because of the customs revenue they supplied, but also because [they] provided fresh opportunities for interloping in the trade of the Spanish empire." (Roberts 651)
    The Europeans stayed and expanded their exploitative opperation in the Caribbean because mercantalist dictated that they had to extract as much profit as possible, and because Raison d'etat feared that others would take advantage if they did not.
*** "Production was for a long time held back by a shortage of labor, as the native populations of the islands succumbed to European ill-treatment and disease." (Roberts 650)
    Even when the original capacity for profit of the islands were saturated, the mercantalist mindset demanded more production. Instead of resting after wiping out the natives and turning a new land into a production factory, the default mindset focused on ever more profit. Roberts summarizes "production was for a long time held back by a shortage of labor, as the native populations of the islands succumed to European ill-treatment and disease." (Roberts 650) Raison d'etat was not satisfied with taking over a foreign land and decimamating the population--the focus of the sentiment was always to increase production--and if the natives died to the Europeans then the Europeans would have to import a  new workforce to abuse from elsewhere.
    The common thread through this intercontinental exploitation is the Raison d'etat induced rivalary between the states of Europe and the profit hungry mercantalist mindset that saw no limits. The Spanish landed in the Caribbean to extract profit from new lands. Other European states arrived to conflict the Spanish and balance out power. The European states stayed in fear of other states taking advantage of the situation, and they brought slaves in to out-produce their European rivals. Ironically, Raison d'etat was meant to strike a balance of power and prevent domination of a single power, yet India and the Caribbean were both trampled and suffered the ill effects of domination. The power struggle created by Raison d'etat sucked the Caribbean into the conflict, and after destroying the native population, the European countries were still locked in the viscious cycle of Raison d'etat. <that's a tautalogy, better summary sentence>

*** Lots of slaves: 6k slaves in 1643 but 50k in 1660 (Roberts 651)
*** "where colonial fronteers met and policing was poor and there were great prizes to be won, [the area] became the classical, indeed, legendary hunting ground of pirates." (Roberts 652)

** Conclusion

*** Summarize
    In Europe, states exercising balance of power politics caused states to view every interaction as a battle, promoting conflict and creating rivalary with hard power, soft power, and economic mercantalasim. The cynical <WC beligrant? not benevolent> international relations of states practicing Raison d'etat also forced the aggressive attitude upon surrounding states, as those who didn't fight back would be trampled. This rivalary not only consumed Europe but also spilled over into the various overseas colonies of its states, where natives were trampled and their land exploited in fear of another European power gaining the upper hand. <too much summary? it's three sentences..>

*** Direct Impact
    While the original supporters of balance of power politics may have seen this as a foolproof, trustless system to prevent domination of one European power over the rest of Europe, no such consideration was given to the colonized locations--although European states remained relatively intact, conflict was ultamately magnified both within Europe and in the rest of the world.

*** larger connections
    Thus, while Raison d'etat may have been the best option for any individual European state, it was beneficial for neither the individuals fighting mercantalist wars or optimizing extraction from remote colonies, nor for colonized countries that weren't on the same page about<wc> Raison d'etat and it's aggressive intentions.

* Editing
  Link: https://docs.google.com/document/d/152S-sC2tw8GyYGGW-uLJuS_A7vrrcxnLA76auaqI-vE/edit?usp=sharing
** WC
*** DONE Need more synonyms for "balance of power politics"
    CLOSED: [2020-11-02 Mon 17:58]
    No.
** how to introduce secondary sources? like kissinger and trauttmann
*** india docs are primary sources in google drive                   :answer:
     Robert Clive in India docs 1.pdf
** book names in +quotes+ or italics?
** how to cite external facts?
*** great salt hedge, sushu class
**** - Salt Hedge: Sushu, name of ppt, 2020                          :answer:
