#+TITLE: Revolution in China Stearns
* overview
** fall of Qing
*** Manchu 12-yo boy emperor Puyi abducted in 1912
*** power vacuum competed for by 'regional warlords, loose alliance of students, politicians, secret societes, japanese, communist movement'
*** internal divisions and foreign influences paved the way for the ult victory of Mao Zedong :claim:
** warlord cliques
*** dominated chinese politics for next 3 decades
*** most powerful clique was in north china headed by Yuan Shikai
*** Shanghai and Canton made second power center, favored politicians like Sun Yat-sen
** university students, teachers, and intellectuals
*** played critical roles in civilization but were defenseless in force
** secret societies
*** envisioned restoration of monarchical rule under a Chinese dynasty
** western power intervention and japan
*** wanted to capitalize on power vacuum
*** japan from mid-1890s to 1945 (end of WWI)
* may fourth movement
** Sun Yat-sen headed Revolutionary Alliance---loose combo of anti-Qing political groups that started the 1911 revolt
** claimed mandate of heaven but warlords had true power
** set up a Parliament and elected cabinets but had minimal actual effect
** Sun Yat-sen resigned in favor of Yuan Shikai in 1912 (northern warlord)
*** Yuan Shikai pretended to be democratic but built up military
*** few years later, used military and assassinations to remove opposition
** Japan and WWI
*** japan took german concessions in China after WWI
*** gave Yuan the 21 demands in early 1915, which would reduce china to a 'dependant protectorate'
*** Yuan was indecisive and instead rallied support for himself instead of responding
**** a rival warlord took his support by being hostile to japan and Yuan resigned in 1916
*** after the war (1919), japan won german concessions
**** this made the students upset -> protests and mass boycotts
** democracy and individualism popular in urban youth
*** democratic thinkers toured china
*** novel by Ba Jin depicts boy ignoring arranged marriage
*** however, elections and stuff didnt work because warlords were in control
**** so they decided more radical action was needed
** Bolshevik victory in Russia
*** chinese seriosuly considered marxism
*** Li Dazhao decided to interpret marxism for china's situation
**** he saw the pheasants as the vanguard of urban change
*** all chinese as proletarian, and bourgeois was the industrialized West (unification)
** marxist study club (including Mao Zedong)
*** also believed in authoritarian state that intervened helpfully in many aspects of life
** summer of 1921
*** a handful of marxist leaders from different parts of China met secretly in Shanghai
*** Communist party of China born
*** few supporters but provided new ideology over confucianism
* Seizure of Power by the Guomindang (nationalist party, Sun Yat-sen)
** promised international and domestic change, but only implemented international change
*** pushed foreigners out but didnt implement land reform which is what the pheasants cared about
** slowly forged alliances with 'key social groups' and built an army in south of china
** nationalists used communists as major link to peasants and urban workers
** also asked soviets for help
** soviet military academy
*** first headed by Chiang Kai-shek who didnt like the communists
*** but he had to wait for the army to be trained
** after Sun yat-sen dies in 1925, Chaing kai-shek captures and bribes warlords
*** becomes the head of a warlord hierarchy, essentially controlling china
* mao and the peasant option
** mao background
*** father was a prosperous peasant, but mao rebelled early
*** believed revolution was violent and peasants needed to use force to overthrow landlords
** after Chaing seized control, he massacared communists in Shanghai in 1927
** a later attack to communists in south central china caused Mao to spearhead a long march
*** 90k followers in 1934, thousands of miles to the more remote northwest
*** created a new communist center
** long march solidified Mao's leadership of the Chinese communist party, but japanese eroded Chaing's power structure
* global great depression
** a decade after WWI, caused many international crises
** caused by problems in economic systems and reliance on cheap raw goods
** causation
*** food overproduction drove down prices
**** high prices during the war led to overconfident loans
**** runaway spiral of loans from the US to european countries + postwar inflation?
**** optimized exploitation of colonies to produce coffee sugar rubber production worsened the same cycle
*** poor leadership
**** leaders were interested in their own debts being paid than facilitating balanced econ growth
**** protectionism reduced market opportunities and made it worse
** the formal advent of the Depression (October 1929)
*** us stock market crash brings everything down
**** bc the US gave out so many loans
**** people trying to cut losses made things worse
**** thus lower production levels and rising unemployment
**** reinforcing cycle from 1929 to 1933, even France and Italy drawn into vortex by 1931
** comparison
*** first great depression of the industrial age
*** also it was in the mess of the world wars which made it worse
*** and it lasted nearly a decade
** social impacts
*** created fears of loss of earnings or work
*** confused family and gender roles
*** economic hesitancy caused recessions through 1939
** non-western impacts
*** export economies got rekt (latain america, japan)
** western responses to the great depression

*** government tariffs, spending cuts, and inflation fear worsened the problem
*** people turned to radicalism both left and right
*** generally, parliaments were either frozen in indecision or straight up overthrown
*** eg. france got frozen
**** parliment reacted sluggishly, popular front (comprised of liberal, socialist, and communist parties) won election in 1936
**** but it too got second-thoughty  and fell in 1938, but everything was really a standstill
*** scandinavian states were somewhat socialist and neared a welfare state which was decent
*** british innovation (television) improved some sectors but not enough
** the new deal
*** herbert hoover did european-like stuff that went poorly
*** franklin roosevelt and the new deal (1930s) offered more direct aid
**** public works projects increased employment
**** social security system to form a social baseline
**** economic planning also helped
**** led to economic growth which was good, and restored faith in the US system, prevented more radical movements
** militarization of japan
*** authoritarian military rule took over japan and had conquered Chinese Manchuria w/o civilian government backing by 1931
*** many parties and ideas, generally anti-western
*** in May 1932, army officers murdered the prime minister. they also put down another coup attempt in 1936, but generally prime ministers became increasingly militaristic
*** in 1937, a small scuffle turned into a large scale battle when japanese generals decided to defeat China's armies to prevent future trouble
*** by 1938 Japan controlled a large-ish empire. military leaders and economic leaders liked this and pressed for more conquest in WWII
*** civilians were like brUh the entire time but the military was in control
** japanese industrialization and recovery
*** depression hit hard, but active government policies helped
**** increased spending to boost employment and generally boosted economy
**** export boom and "virtual elimination of unemployment by 1936" after the low point in 1931
**** lots of rapid industrialization stats
*** distinctive industrial policies
**** mass patriotism, group loyalt, lifetime contracts
*** by 1937, japan was looking industrialized, self sustainable, and generally good
