
#+TITLE: flo - hallmarks of cancer (2011) reading
#+AUTHOR: Exr0n
* sources                                                            :source:
** assignment: https://nuevaschool.instructure.com/courses/3087/assignments/56036
** reading: [[file:KBsrcHallmarksOfCancer2011Reading.pdf][Hallmarks of Cancer PDF]]
* Flow
** Abstract
*** hallmarks include
**** sustaining proliferative signaling
**** evading growth suppressors
**** resisting cell death
**** enabling replicative immortality
**** inducing ingiogenesis
**** activating invasion and metastasis
*** theese hallmarks are newer
**** reprogramming of energy metabolism
**** evading immune destruction
*** underlying
**** genome instability
***** genetic diversity that expedites acquisition of hallmarks
**** inflammation
***** "fosters multiple hallmark functions"
** Introduction
*** Cancer cells evolve into cancer cells because they need to be cancer cells??
**** TODO why do tumors have "the need ... to acquire the traints that enable them to become tumorigenic and ultimately malignant"? :question:
*** tumors are not simple / idle 'insular masses of proliferating cancer cells'
*** "recruited" normal cells (or 'stromal cells') are active parts of the tumor
*** 'the biology of tumors can no longer be understood simply by enumerating the traits of the cancer cells but instead must encompass the contributions of the "tumor microenvironment" to tumorigenesis.'
*** purpose is to consider new hallmarks that have been found or note that old ones weren't as general as we thought
** section: 'An Emerging Hallmark: Evading Immune Destruction'
*** the immune system usually eradicates the 'formation and progression of incipient neoplasias, late-stage tumors, and micrometastases', so why not in these cancers?
*** 'long standing theory of immune surveillance' -> something went interesting
**** 'cells and tissues are constantly monitored'
**** surveillance should elim cancer cells before they grow into tumors
**** thus, grown tumors have either hid from surveillance or limited the 'extent of immunological killing'
*** more cancer in immunocompromised individuals
**** but these are virus-induced cancers
***** so helping these people = reducing viral infilltration
**** other cancers still evade the immune system
*** 'genetically engineered mice and clinical epidemeology suggest that the immune system' actually hurts cancer
**** mice that are engineered to lack some immune parts got cancer faster/stronger/more
***** these guys are important in fighting cancer
****** CD8^+ cytotoxic T lymphocytes (CTLs)
****** CD4^+ T_h1 helper T cells
****** natural killer (NK) cells
***** 'demonstrable increase in tumor incidence'
***** lacking multiple -> 'more susceptible to cancer development'
***** 'both the innate and adaptive cellular arms of the immune system are able to contribute significantly to immune surveillance and thus tumor eradication' :conclusion:
*** transplantation experiments
**** cancer cells from immunodeficient mice have a bad time in normal mice
**** cancer cells from normal mice can initiate tumors in both types of hosts
**** maybe some cancer cells are more easily detected and those would normally die in normal hosts but live in comprimised hosts, but when transplanted they meet a competent immune system and die :conclusion:
**** Open question: do some carcinogens tend to induce more/less immunogenic cancer cells? :nextstep:
*** the immune system probably includes antitumoral responses
**** patients with colon and ovarian tumors who have lots of CTLs and NK cells have better prognosis
***** evidence is not as strong for other cancers                  :nextstep:
**** immunosupressed organ recievers got cancer from the donor
***** suggests doner had immune system which held cancer down until organ was transplanted
*** TODO 'still, the epidemiology of chronically immunosupressed patients does not indicate significantly increased incidences of the major forms of nonviral human cancer'
*** TODO something about HIV patients who lack T and B cells and how they should still be able to fight cancer with NK cells and CTLs
*** that was oversimplified as the tumor might also be actively supressing immune responses
**** may 'paralyze infiltrating CTLs and NK cells by secreting TGF-\beta or other immunosuppressive factors'
**** 'more subtle mechinisms .. recruitment of inflamatory cells that are actively immunosuppressive'
***** 'regulatory T cells (Tregs) and myeloid-derived suppressor cells (MDSCs)'
*** it is so far unclear whether the immune system plays a large enough role to be considered a hallmark of cancer
* Vocab
** neoplastic disease
*** anything that causes tumor growth (malignant or benign)
** ostensibly
*** maybe 'technically'?'
** tumor microenvironment
*** presumably inflammation, recruited normal cells, and other stuff that helps the tumor grow
** pathogenisis
*** evolution of 'pathogen' (cancer)
** ancillary proposition
*** maybe the starting / base proposition
** insular masses
*** stagnant or something, simple
** heterotypic interactions
*** many types of interactions
** tumorigenisis
*** the growth / development of a tumor?
** neoplasias
*** new uncontrolled growth of cells
** micrometastases
*** clumps of cancer cells that spread around the body
** etiology
*** study of cancer?
** immunogenic
*** easily detected by the immune system
** immunoediting
*** "natural selection" by the immune system
** prognosis
*** a prediction of the outcome of a cancer (or disease in general, apparently)
