#+TITLE: Jack's Personal Space
#+AUTHOR: Houjun Liu

Hello! Welcome to my corner of personal notes in Taproot.

* About
For a little bit about me, checkout [[https://www.jemoka.com/][my web presense]]! I will be here soon to update some thoughts about stuff and probably also mirror my [[https://medium.com/20minuterants][blog]].

I am one of the primary maintainers of Taproot, and the author of the [[https://github.com/InSanityHQ/taproot3/][current build system]]. As with most other members here, I go to school at [[https://www.nuevaschool.org][The Nueva School]], an independent school in the San Francisco bay area.

Hopefully, there will be more here. Soon; soon...


* Testing of Taproot 
#+begin_src python
print("howooo")
if 1 = 2:
    print("codeblock test!")
#+end_src

this is some more changes.

[[inkscape:haoeu.svg][ha]]

Yeah.

** Notes!
:PROPERTIES:
:NOTER_DOCUMENT: 1491, Atlantic article 3.22.pdf
:END:
- whaoeu
*** ha
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** thaoansotehu
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** test
:PROPERTIES:
:NOTER_PAGE: (1 . 0.22281167108753316)
:END:
this is cool
*** aoeu
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6925133689839572)
:END:
*** what is life, anyways
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6925133689839572)
:END:
what is it?
*** cool
:PROPERTIES:
:NOTER_PAGE: 13
:END:

*** Skeleton
**** Highlight on page 1
:PROPERTIES:
:NOTER_PAGE: (1 . 0.24074033333333333)
:END:
***** Contents
d groups, and that they had so little impact on their environment that even
after millennia of habitation it remained mostly wilderness. My son picked up the
same ideas at his schools
***** Comment
snotihsaonethusaoeu
