:PROPERTIES:
:ID:       8BE559F9-CD51-4455-8DD0-0A673CBD0944
:END:
#+title: Self Evals: SPAN401 Sem. 1
#+author: Houjun Liu

1) Spanish Language Proficiency

I think I am very confident that my Spanish language ability has improved drastically over this semester. After the classes this semester, I think I was able to have a much butter knowledge and grasp on my ability to speak Spanish spontaneously --- which ultimately feeds into my ability to actually use the language in a conversational manner. To this end, I think the Speaking and Listening portions of the class has been the most helpful: encouraging and challenging us to actively use the language in a way that would support our ability to achieve higher degrees of spontaneity.


2) Personal Growth

In this class, I was able to get a better grasp on my ability to learn Spanish through non-conventional means. Because of the unique and creative structure of the class, assessments are done through means which I could actually reflect on my ability to grow instead of having to worry about rote facts of knowledge. 

3) Habits of Learning

As usual, I'd like to think of myself as someone who has adequate study habits that would propagate myself well throughout class. I am highly participatory in class and I continue to try to challenge myself in Spanish learning. At the same time, I'd like to work on encouraging a good classroom environment and collaboration with other students in a multitude of ways --- "sharing the mic" and allowing others' growth.

# Briefly mention your habits of learning in this course, such as homework, study habits, class participation, and self-initiative: going beyond what is expected of you. What was most challenging for you in this course? What are your strengths and weaknesses? In what areas could you improve?

# Thank you for your hard work this semester.  I look forward to having you in class in the near future.  ¡Felices fiestas!
