:PROPERTIES:
:ID:       D9DC3A65-9529-4081-9B27-730F916B8CFB
:END:
#+title: Self Evals: ENG301 Sem. 1
#+author: Houjun Liu

// In considering recent assignments, what are you proud of? (aspects of your writing process, your argumentation, growth in meeting a particular learning outcome, working with a partner, orally communicating your ideas, etc.)
I am particularly proud of the work I have done to be a better class citizen w.r.t. "sharing the mic" and engaging others in conversation. This is especially pressing when in group discussions: where I actively try to support the systems of discussion in classes to help add my value to the room. As a generally talkative person, it has taken much effort on my part to be able to moderate class discussions and moderate my contribution to create a healthy and supportive environment.

// What are your areas of strength in terms of literary analysis as we close the semester?
Throughout this semester, I have been working to become more specific in my literary analysis. A piece of feedback that I found particularly valuable is that my analysis has became a bit broad and in need of more specificity; hence, for my final analysis, I attempted to zero-in on a much more specific theme to be able to write a --- while less ambitious -- much more nuanced piece.

// What are your continued goals as a writer/reader/speaker for next semester?
For next semester, I want to keep working on my skills in deep literary analysis and close reading while attempting, as topic and format allows, to slightly expand the scope while keeping the same level of nuance. Furthermore, I will remain to consider my class citizenship to harbor a more collaborative discussion environment.
