#+TITLE: Crucible Graded Discussion notes
#+AUTHOR: Dylan Wallace

* Crucible "system"
- People with power are able to persecute those with less power
  - This is done through the justice system by accusing others of the sin of witchcraft

* Compare and contrast the presentation of Abigail in Act 3 with her initial introductions in Act 1, looking at both dialogue and stage directions. Why specifically does Miller offer these specific aspects of continuity or discontinuity?
- In Act 1, Abigail is portrayed as someone who will do anything for their goals. She is the one who accuses Tituba as being a witch in order to get out of punishment for dancing in the woods.
- In Act 3, Abigail is portrayed in a similar way. She turns on Mary Warren after Mary Warren accuses her of lying. However, we also see signs of weakness, such as when Proctor confesses to committing adultery with Abigail.
- 
* Analyze and evaluate the evolving motifs of seeing or sight and knowing or knowledge. How do they work individually, and how do they intertwine?
- Motif of seeing is associated with hysteria and witchcraft, as well as false accusations
  - p45-46: "I see __ with the devil!"
* Consider Mr. Hale’s evolution as a religious authority, legal authority, and community member. How does he change or stay the same and why? How can we interpret his presence in Act 3?
- Legal authority
  - Becomes disillusioned with the judicial system following the
- Interpretation of presence
  - Defends Proctor's right to defence in the judicial process
  - Voice of reason?
* Choose a subject or instance from within Act 3 and put it “on the stand” for the purpose of thoughtful response and connection. (For example: In Act 3, Proctor goes in to "save his wife." Why does he bring in a quiet-spoken elderly man, an absent-minded farmer, and a sickly girl to present his case? Put this "shielding” on the stand. Grill it from different angles.)  
* Other
- Danforth, Putnam, Parris
  - Danforth :: Motivated by justice, wants to maintain the reputation of the court, accuses Proctor of undermining the court to prevent this. Danforth is a perpetuator of the witch hunt system.
  - Putnam :: Motivated by greed, wants to gain land from those that are hanged in witch trials. Putnam is not a perpetuator, but is an active participant and a malicious actor within the system.
  - Parris :: Motivated by pride, doesn't want to tarnish his name by having it known that his daughter and neice are liars.
