#+TITLE: Comparative Essay Prompt
#+AUTHOR: Houjun Liu
#+SOURCE:
#+COURSE:

* General Information
  | Due Date          | Topic                       | Important Documents |
  |-------------------+-----------------------------+---------------------|
  | Dec 14 by 12:30pm | Douglass/Jacobs Comparative | Dougless + Jacobs   |

* Prompt
  *Compare and contrast a thematic element from each autobiography (family, gender, education, sexuality, violence, Christianity, etc.). What is the effect of this element, and the way the author approaches it, in each text?*

* Quotes bin

** Douglass

*** Connection exists between rape (and the creation of offsprings) and economic value
This is done too obviously to administer to their own lusts, and make a gratification of their wicked desires profitable as well as pleasurable.

*** Demarcation of Slave Life into Monetary Value
that he was a good man, and that he could not think of taking me from him [i.e. killing him]; that, should he do so, he would lose the whole year’s wages

*** Manhood connected to independence from slavery
I was no longer content, therefore, to live with him or any other slaveholder. ... My tendency was upward. I was fast approaching manhood, and year after year had passed, and I was still a slave.

- Approaching vs. still
- and sentence structure creates a sense of rusted parallelity that constrasts the stillness
- Shows sense of desperation that exists within being a slave

** Jacobs

*** Children are exchanged for money is an insult
My children grew finely; and Dr. Flint would often say to me, with an exulting smile, "These brats will bring me a handsome sum of money one of these days."

- "brat" => old french brachet (animalizing, dehumanizing)

*** The value in "Womanhood" exists only in procreation
Woman are considered of no value, unless they continually increase their owner's stock. They are put on a par with animals

*** Slavery as a station lower than womanhood, and slaves are derived the privileges of motherhood
I said something about being unwilling to have my child supported by a man who had cursed it and me also. He rejoined, that a woman who had sunk to my level had no right to expect any thing else.

*** Love is something that could be taken away and manipulated though slavery. Objectification allows control
Why does the slave ever love? Why allow the tendrils of the heart to twine around objects which may at any moment be wrenched away by the hand of violence?

*** a
But when I reflected that I was a slave, and that the laws gave no sanction to the marriage of such, my heart sank within me. My lover wanted to buy me.

** Trash
# *** The "lack" is modified more strongly than the cleanliness, that the niceness of north is much more emphasized when the imagery of the south is in mind
# Every thing looked clean, new and beautiful. I saw few or no dilapidated houses, with poverty-stricken inmates; no half-naked children and barefooted women

# *** Children of common "Father" => that all that are African Amercians still carry mark of slavery
# Without home and without friends, in the midst of thousands of my own brethren—children of a common Father, and yet I dared not to unfold to any one of them my sad condition


* Claim Synthesis

* Defluffication
  /Chosen Thesis Claim/

  - Point a
  - Point b
  - Point c

  So what? SO WHAT

  *Restated Claim*


There's always the [[https://wp.ucla.edu/wp-content/uploads/2016/01/UWC_handouts_What-How-So-What-Thesis-revised-5-4-15-RZ.pdf][UCLA Writing Lab]].
