#+TITLE: Comparative Essay Prompt
#+AUTHOR: Houjun Liu
#+SOURCE:
#+COURSE:

* General Information
  | Due Date          | Topic                       | Important Documents |
  |-------------------+-----------------------------+---------------------|
  | Dec 14 by 12:30pm | Douglass/Jacobs Comparative | Dougless + Jacobs   |

* Prompt
  *Compare and contrast a thematic element from each autobiography (family, gender, education, sexuality, violence, Christianity, etc.). What is the effect of this element, and the way the author approaches it, in each text?*

* Quotes bin

** Douglass

*** Connection exists between rape (and the creation of offsprings) and economic value
:PROPERTIES:
:ID:       9D2F1AE4-24CE-4629-A023-672C32996450
:END:
This is done too obviously to administer to their own lusts, and make a gratification of their wicked desires profitable as well as pleasurable.

- To administer: service and manage: sense of maintainence
- Self-fufilling cycle

*** Demarcation of Slave Life into Monetary Value
:PROPERTIES:
:ID:       C554431F-B079-49A8-824D-0B169E29E064
:END:
that he was a good man, and that he could not think of taking me from him [i.e. killing him]; that, should he do so, he would lose the whole year’s wages ... and that I must not trouble him with any more stories, or that he would himself get hold of me. [by which he means to beat me?] 

- White people as someone that is only incentivized by monetary value
- White people percieve African Americans as someone who is motivated by beating
- => womanhood created monetary value

*** Manhood connected to independence from slavery
I was no longer content, therefore, to live with him or any other slaveholder. ... My tendency was upward. I was fast approaching manhood, and year after year had passed, and I was still a slave.

- Approaching vs. still
- and sentence structure creates a sense of rusted parallelity that constrasts the stillness
- Shows sense of desperation that exists within being a slave

** Jacobs

*** Children are exchanged for money is an insult
:PROPERTIES:
:ID:       268A6E50-E7A4-403B-81AE-105C9710263A
:END:
My children grew finely; and Dr. Flint would often say to me, with an exulting smile, "These brats will bring me a handsome sum of money one of these days."

- "brat" => old french brachet (animalizing, dehumanizing)

*** The value in "Womanhood" exists only in procreation
:PROPERTIES:
:ID:       0FDBF577-D415-4DBE-9FDE-A9EFE500EBD3
:END:
Woman are considered of no value, unless they continually increase their owner's stock. They are put on a par with animals

- Woman lowered on par as animals
- Womanhood becomes a tool

*** Slavery as a station lower than womanhood, and slaves are derived the privileges of motherhood
:PROPERTIES:
:ID:       82624FEF-9108-45BE-A7E1-7B15CB7A0B78
:END:
I said something about being unwilling to have my child supported by a man who had cursed it and me also. He rejoined, that a woman who had sunk to my level had no right to expect any thing else.

Dewomanizing and dehumanizing woman.

*** Love is something that could be taken away and manipulated though slavery. Objectification allows control
:PROPERTIES:
:ID:       D9DB4729-FDCE-483F-AD81-AA443A905001
:END:
Why does the slave ever love? Why allow the tendrils of the heart to twine around objects which may at any moment be wrenched away by the hand of violence?

*** The law prevents marrage and expression of true love
:PROPERTIES:
:ID:       8E426BDB-8F83-4EFD-BFD8-5795C28EBB9F
:END:
But when I reflected that I was a slave, and that the laws gave no sanction to the marriage of such, my heart sank within me.

- Duality in the word "sanction" protest against the dual-system of rules
- System prevents the expression of love

** Trash
# *** The "lack" is modified more strongly than the cleanliness, that the niceness of north is much more emphasized when the imagery of the south is in mind
# Every thing looked clean, new and beautiful. I saw few or no dilapidated houses, with poverty-stricken inmates; no half-naked children and barefooted women

# *** Children of common "Father" => that all that are African Amercians still carry mark of slavery
# Without home and without friends, in the midst of thousands of my own brethren—children of a common Father, and yet I dared not to unfold to any one of them my sad condition


* Claim Synthesis

** Children are objectified and a form of economic value.
The frame of children as something commotized and tradeable dimishes the process of procreation as a process of inventory maintainence. [[id:268A6E50-E7A4-403B-81AE-105C9710263A][Children are animalized and turned into comotities that could be traded for value.]] Therefore, the [[id:9D2F1AE4-24CE-4629-A023-672C32996450][creation of offspring seen and is actually creating economic value. "Maintaining" this cycle is therefore advantageous to slaveowner.]]

** Slaveowner incentivized by Monetary Value, therefore Control Love
[[id:C554431F-B079-49A8-824D-0B169E29E064][Slaveowners are only beholden to "economic" value]], and economic loss is worth to a slaveholder as much as physical suffering/life is to the slave. Therefore, [[id:D9DB4729-FDCE-483F-AD81-AA443A905001][love is therefore something that is controlled for]] by slaveholders.

** Woman is therefore reduced to a Tool to execute the means to control love
[[id:0FDBF577-D415-4DBE-9FDE-A9EFE500EBD3][The value in "Womanhood" exists only in procreation]] (a.k.a. producing economic value.) And therefore, [[id:82624FEF-9108-45BE-A7E1-7B15CB7A0B78][they are deprived of the privledges of motherhood as that afforded to white woman.]] Jacobs' narrative serves, therefore serves [[id:8E426BDB-8F83-4EFD-BFD8-5795C28EBB9F][as a protest against the legal and social blindess against genuine relations by Black individuals]].


* The Claim
Through tracking the objectification of the children between enslaved peoples' and White slaveowners, the combined narratives of Douglass and Jacobs demonstrates a self-reinforcing and dehumanizing reduction of enslaved Woman as a means of economic value production
