:PROPERTIES:
:ID:       A6A52499-E61D-4F2B-9A1C-386656F0ECCB
:END:
#+title: Didion Pastiche
#+author: Houjun Liu

David and I walks down Haight street past the psychedelic signs and random suddenly colourful buildings that seem to weave between patches. Most of the unique advantages color blurs in a sea of mixed rainbows, which David and the entire group of gen-Z students finds entirely baffling.
"Here, have a dime", Zachary points at the ground. I ask where it came from; he didn't know. I didn't think the Haight was a place where you find money lying right on the ground.

"They do some crazy stuff out there in down town", Alex says, slowly taking in a joint. The puff of air fills the small nook we are standing in, and the smell of weed consumes us slowly.
"The Haight is a rich-ass part of town" he says. I wonder if that's why the dime was dropped.
I ask his brother what their immediate plans are.
"He's got a job down there slicing wings, imma get an ID", Alex interrupts. His brother doesn't seem that interested in interacting with us, yet Alex, even while half-high, pitches the pair with pointed eloquence. Perhaps finding a job makes you want to be a salesman of yourself.

I pretend to peer into shop windows while counting dates. Yesterday was trans visibility day. Misha walks by and blurts out a "I love queer representation" before I realize that I was subconsciously staring at the large blue/pink heart mask painted above the little white building.
Smeared behind the heart, a sort of afterthought, almost-unintentional black strokes that were it not for the small whiskers of a rat running away could have been taken as graffiti backwash. I think it is a Banksy. They don't believe me, but Google's numerous colorful pictures of "Haight Banksy" dispels them.

David and Dylan wants to go to the old San Francisco Amoeba Records. Even through a double-masked N-95, there is a strong, sickly fragrance in the shop that both David and Dylan seems oblivious to. I walk in:
"No bags, here's a key, check it". I ask why. "Too much theft." I wonder how the Haight is rich-ass. 
The store seem to have a storied history which makes it kind of stuck in time instead of giving off a feeling of heritage. It might as well have been actually stuck in time, though, as a few minutes later I receive a text with an image of Kraftwerk's 2003 album Tour de France in it, plastered with a big "New!" sticker and sitting on the top shelf.

Alex focuses his attention back to the ID. "want to get a pluming license", he says, "the Union won't take me without an ID, they pay better." David agrees, "plumbing earns 100k or something, American labor pays." I ask if the pair wants to move out of the neighborhood. "Nah, the Haight has some good weed, cheap stuff. Can't get it the same anywhere else." The Haight is the first rich-ass neighborhood with cheap goods I know of.
