:PROPERTIES:
:ID:       9CBF0AFC-4C91-4EFD-A7FF-CA6905B9939B
:END:
#+title: Gatsby CFC Essay
#+author: Houjun Liu

F. Scott Fitzgerald's /The Great Gatsby/, a foundational work of American literature, is ripe with many frequently-analyzed motifs that serves as Fitzgerald's commentary upon 20th-century America. One of the most iconic analysis of /The Great Gatsby/ relates the enduring green color that surrounds Gatsby as representative of the American Dream: that anyone, regardless of their background, have equal opportunity and access to success in America. The opulent East Egg, a representation of financial and social achievement in America, prevailingly shines a "single green light ... that burns all night" (CITE) throughout the harbor---seemingly granting all that surrounds it with the allure of possible success like those living in the East Egg. The character most sensitive to this Green light in the work, Gatsby, is himself framed as an embodiment of this dream: that a military officer, seemingly drawn from no apparent background, was able to garner an immense amount of new wealth simply from his "business" dealings. One of Gatsby's earliest shows of wealth comes from his car---which Nick aptly noticed as being upholstered in "green leather" (CITE). Gatsby's ownership of the car, a sign of his achievements, results in him being "couched" in green: upon the newfound privilege delivered to him by the American Dream. Shortly prior to his finding of work on the yacht Tuolomee---a transitional moment in his life that begun his path towards prosperity---Gatz (Gatsby) was wearing "a torn green jersey" (CITE): symbolizing his yearning to the promise of upwards social mobility. However, the jersey's description as being "torn" brings an interesting counterpoint that foreshadows the nature to his success. Through leveraging this imagery of holes, the author illustrates that Gatsby's pursuit of the American Dream, eventually revealed to be driven by securities fraud, is itself flawed and not what the "classical" American Dream would expect; furthermore, Gatsby's ultimate goal in chasing wealth and success---the pursuit of Daisy---has underpinnings which is also disjoint from the classical treatment of the "American Dream". 

These inconsistencies in the aforementioned simple treatment of Fitzgerald's "green light", then, calls for a closer examination of the color green in The Great Gatsby. One possible avenue for this is analyzing blue, another color of symbolic weight in the work, in concert with the appearance of green: paying close attention in color transitions between green and blue to revise the classical model of the American Dream. While James Gatz---Gatsby's true self, wearing a "torn /green/ jersey" (CITE)---stepped upon the Tuolomee, Jay Gatsby---his idealized ego---stepped off and was given "a blue coat" (CITE) to wear by Dan Cody. Indeed, in his "green" pursuits of the American Dream, Gatsby was given by this enablers a "blue" coat which marked his artificial attempt to raise his perceived station: his transition from green to blue outerwear signals the beginning of a lie of personal identity in the creation of the character of Jay Gatsby. At the climax of the novel, Gatsby took Tom's "easygoing blue coupé" (CITE) instead of his green-leathered car to the Astoria, accompanying Daisy to the engagement where Tom exposed much of Gatsby's financial dealings: leading Gatsby to "[fight] on with ... the dead dream ... trying to touch what was no longer tangible" (CITE). While his blue coat signaled the beginning of a conscious /effort/ in deceit (via the creation of the "Gatsby" character), the blue coupé here signaled Gatsby's conscious /recognition/ of his self-deceitful dream of perusing Daisy: that at the Astoria to which he drove her, he recognized that the goal of partnering with Daisy "was no longer tangible" (CITE). The motif of green-blue transition in the work therefore acts to underscore the shaky foundation upon which the green "dream" is built: that it may become overshadowed by the construction of a falsehood which covers or even replaces the dream's original intent.

The simple analysis of blue ("lies of identity") as an afterthought supplementing green ("American Dream") does not take into account the full nuance of the symbol blue itself. Independently, the color blue is frequently used throughout the work and works to better characterize the nature of the deception in the American dream. The eyes of Dr. T. J. Eckleburg, "blue and gigantic" are placed---according to Nick---by "some wag of an oculist...[who] sank ... into eternal blindness or forgot them and moved away" (CITE). The eyes are set there as an advertisement essentially in vain: a literally "blind" attempt to attract customers that disregards the nuances of the locale which is all but entirely abandoned. This sense of unavailing effort threads though many appearances of the color blue throughout the work. George Wilson, when he was first introduced to the reader, was described as being a "blonde, spiritless man" where, upon seeing Nick and Tom with the potential hope of a car deal, "a damp gleam of hope sprang into his light blue eyes" (CITE). His struggling garage lay the little remainder of hope upon Tom's blue coupé---a "lie" never delivered, rendering Wilson's effort similarly in vain. Of course, the most significant defeat throughout the work exists in Gatsby's attempt to win the favor of Daisy. The main instrument by which he hopes to do so---his magnificent property across the Sound from her---as frequently described as having "blue gardens" (CITE) and "blue lawn" (CITE). Gatsby's trying effort, even early on in the work, is therefore foreshadowed to be a lying failure in its "blue" character. The color blue, taken independently, is a symbol that calls to a futility of effort that is exhibited by many of the characters.

By taking these two characterization of the color blue together, an novel understanding of the work can now be constructed that revises the classical framing of the green "American Dream." The American Dream ("green"), as interpreted by Fitzgerald, is a wavering facade that is quickly revealed (replaced, covered) to be an unachievable lie ("blue"); however, almost all of the characters in the book still try in useless pursuit in chasing the dream---despite its lack of ultimate fulfillment. It is likely no accident that, in color painting, blue is a component from which green is made. The subtle point made here is profound: that, built into the American Dream, there necessitates an element of failure and unfulfilling struggle. Because of this, the intense focus of the "green light" in classical Great Gatsby analysis is perhaps misplaced; instead, a renewed focus on examining the novel as one built upon falsehoods---a "blue-centered" perspective---will bring new understanding to Fitzgerald's argument about American society.
