:PROPERTIES:
:ID:       77210C47-22AE-4714-93FF-67FDF2EC60D9
:END:
#+title: Great Gatsby Essay
#+author: Houjun Liu

* General Information
| Due Date | Topic            | Important Documents |
|----------+------------------+---------------------|
| 2/18     | The Great Gatsby | The Great Gatsby    |

* Claim Synthesis

** Quotes Bin

*** Green

**** Green light as the only thing marking the opulent East Egg
:PROPERTIES:
:ID:       70BBF718-0677-40B1-8DB7-B15D9B48B625
:END:
I could have sworn he was trembling. Involuntarily I glanced seaward--and distinguished nothing except a single green light, minute and far away, that might have been the end of a dock. 

**** Gatsby's yellow car filled with Green leather => Gatsby moves around "couched" in Green
:PROPERTIES:
:ID:       A791D350-9AC9-419B-AAAE-812F6C8A1B6B
:END:
Sitting down behind many layers of glass in a sort of green leather conservatory we started to town.

**** Gatsby's attempt to improve Nick's house was achieved via a "greenhouse"
The flowers were unnecessary, for at two o'clock a greenhouse arrived from Gatsby's, with innumerable receptacles to contain it.

**** That inviting Daisy to his home removed the need for the green light to signify her
Possibly it had occurred to him that the colossal significance of that light had now vanished forever. ... It had seemed as close as a star to the moon. Now it was again a green light on a dock. His count of enchanted objects had diminished by one.

**** Gatsby experienced his moment of carrier shift while wearing a green jersey
:PROPERTIES:
:ID:       284CF1BF-8450-4708-9C75-F88F5FFBEF22
:END:
It was James Gatz who had been loafing along the beach that afternoon in a torn green jersey and a pair of canvas pants, but it was already Jay Gatsby who borrowed a row-boat, pulled out to the TUOLOMEE

**** Daisy giving out green cards to those that may kiss her?
"If you want to kiss me any time during the evening, Nick, just let me know and I'll be glad to arrange it for you. Just mention my name. Or present a green card. I'm giving out green----"

**** Tom's veranda looks out of the "green" sound, living "upon" green
I went with them out to the veranda. On the green Sound, stagnant in the heat, one small sail crawled slowly toward the fresher sea.

**** Wilson embodied and carried with him the green light
With an effort Wilson left the shade and support of the doorway and, breathing hard, unscrewed the cap of the tank. In the sunlight his face was green.

**** Misjudgment resulted in the colour green being applied to the Daisy death car

[The "death car"] came out of the gathering darkness ... Michaelis wasn't even sure of its color--he told the first policeman that it was light green.

**** Gatsby believed the promise of the Green Light as the American Dream
:PROPERTIES:
:ID:       C1E9737F-C3A6-4182-8A9E-1E0FA3386783
:END:
Gatsby believed in the green light, the orgastic future that year by year recedes before us.

*** Blue

**** Blue eyes watches over the valley of ashes
:PROPERTIES:
:ID:       6F63C1D6-4D6E-4DC9-A5EA-A288E7F5F297
:END:
The eyes of Doctor T. J. Eckleburg are blue and gigantic--their retinas are one yard high. ... Evidently some wild wag of an oculist set them there to fatten his practice in the borough of Queens, and then sank down himself into eternal blindness or forgot them and moved away.

**** Wilson's eyes are specifically blue, similar to that in the Valley of Ashes 
:PROPERTIES:
:ID:       B58FF500-6DF2-4D70-A0B6-D46F6A4004B0
:END:
He was a blonde, spiritless man, anaemic, and faintly handsome. When he saw us a damp gleam of hope sprang into his light blue eyes.

**** Myrtle introduced whilst wearing a blue dress
:PROPERTIES:
:ID:       C92BE86E-218E-4E37-B565-C065CFDA2A39
:END:
Her face, above a spotted dress of dark blue crepe-de-chine, contained no facet or gleam of beauty but there was an immediately perceptible vitality about her as if the nerves of her body were continually smouldering. 

**** Gatsby's Gardens described as "blue"
:PROPERTIES:
:ID:       0E322054-E585-4CEC-8BC9-FC5070AD222E
:END:
In his blue gardens men and girls came and went like moths among the whisperings and the champagne and the stars.

**** Daisy's Hair framed as Blue when she and Gatsby first re-met
A damp streak of hair lay like a dash of blue paint across her cheek and her hand was wet with glistening drops as I took it to help her from the car.

**** Gatzby's first pair of civillan clothing was a blue coat
:PROPERTIES:
:ID:       3067F396-6CBD-4251-8037-5EA3005C3D76
:END:
A few days later he took him to Duluth and bought him a blue coat, six pair of white duck trousers and a yachting cap.

**** Entry to the Hotel with the Tom<>Gatzby conflict via a blue coupé
:PROPERTIES:
:ID:       47A8A37B-EADE-48D7-BFB8-87EFF9E869FD
:END:
Wilson behind, and we sped along toward Astoria at fifty miles an hour, until, among the spidery girders of the elevated, we came in sight of the easygoing blue coupé.

**** Scene after Myrtle's Death is shown as being "cool" and "lovely" with blue
The shadow of a tree fell abruptly across the dew and ghostly birds began to sing among the blue leaves. There was a slow pleasant movement in the air, scarcely a wind, promising a cool lovely day.

**** Day Wilson committed homicide was "blue"
He was glad a little later when he noticed a change in the room, a blue quickening by the window, and realized that dawn wasn't far off. About five o'clock it was blue enough outside to snap off the light.

**** Nick went home when the leaves turned "blue", like before
:PROPERTIES:
:ID:       2139491B-286A-4266-869F-16F9E86FF02F
:END:
So when the blue smoke of brittle leaves was in the air and the wind blew the wet laundry stiff on the line I decided to come back home.

**** Ocean underscored his close dream
:PROPERTIES:
:ID:       A21CF278-F019-473C-BA69-8F16C9E2CB3A
:END:
He had come a long way to this blue lawn and his dream must have seemed so close that he could hardly fail to grasp it.


*** Other Stuff

**** Tom/Daisy + Wilson meeting is a product at Daisy' surging to visit garage
"But there's a garage right here," objected Jordan. "I don't want to get stalled in this baking heat."


** Sub-Claim Development

*** Traditional Claim
The colour of green signified the "American dream": a promise where everyone can achieve success given their work.

- [[id:284CF1BF-8450-4708-9C75-F88F5FFBEF22][Gatsby experienced his moment of carrier shift while wearing a green jersey]] 
- [[id:70BBF718-0677-40B1-8DB7-B15D9B48B625][Green light as the only thing marking the opulent East Egg]]
- [[id:A791D350-9AC9-419B-AAAE-812F6C8A1B6B][Gatsby's yellow car filled with Green leather => Gatsby moves around "couched" in Green]] + [[id:C1E9737F-C3A6-4182-8A9E-1E0FA3386783][Gatsby believed the promise of the Green Light as the American Dream]]  

*** New Claim

That, built into Fitzgerald's framing of the "green" American dream, is the necessity of a lie which underpins the dream.

**** The transition between green => blue signifies the beginning of lies

While the [[id:284CF1BF-8450-4708-9C75-F88F5FFBEF22][original "Gatz" stepped onto the ship, wearing a green jersey]], the [[id:3067F396-6CBD-4251-8037-5EA3005C3D76][Gatsby wearing a Blue coat stepped off]]. (personal lie started)

Gatsby originally sitting on seats of a [[id:A791D350-9AC9-419B-AAAE-812F6C8A1B6B][Green-lethered car]], but once he actually interacted with Daisy and his idealism was about to be broken, he drove Tom's [[id:47A8A37B-EADE-48D7-BFB8-87EFF9E869FD][blue coupe]]. (situational/life lie started: that his wealth is now worthless)

**** Blue, reasonably independently, shows that there is something in vain
- [[id:6F63C1D6-4D6E-4DC9-A5EA-A288E7F5F297][TJ Ecle's advertisement as forgotten, useless, and "desperate"]] <> Wag
- [[id:B58FF500-6DF2-4D70-A0B6-D46F6A4004B0][Wilson got his car, but he saw Tom through his blue eyes]]
- and of course, [[id:0E322054-E585-4CEC-8BC9-FC5070AD222E][Gatsby's garden has repeatedly]] [[id:A21CF278-F019-473C-BA69-8F16C9E2CB3A][been described as blue]]  

**** Conclusion paragraph tie-in thing
Through his book, Fitzgerald plays with the motifs of truth and truthiness; though he maintained a true account of the "Green" American dream, he also show that this dream can quickly transition into a lie which, in sheer vain, is preserved---that while lying is desperate and useless, it is nevertheless persued by those chasing the American dream. Also cover is blue.

* Actually Writing
Let's do it: [[id:9CBF0AFC-4C91-4EFD-A7FF-CA6905B9939B][Gatsby CFC Essay]]
