#+TITLE: Rip Van Winkle notes
#+AUTHOR: Peter Choi

1. Find out something about the writer's biography. How might the writer's life and experiences have contributed to the substance of the story?
   - He was single
   - adopted a daughter that died of TB
   - was going to be a lawyer, but decided to become a writer after he no longer had to run the family business.
   - Rip van winkle was inspired by german folktales

2. Find out what was going on in the United States at the time of the story's publication: historically, politically, socially, culturally. In what ways does the story reflect its time?
   - The American Revolution (end of it)
   - The formation of the United States
   - the story is quite literally about how Rip Van Winkle "travels" through time

3. Pay attention to patterns of imagery, metaphor, allusion, foreshadowing, dramatic irony, and other literary techniques.
   - very nice imagery on page 30 (the first paragraph)
   - "He...told them stories of ghosts, witches, and Indians." (31)
   - metaphor? (31, top)
   - "The great error in Rip's composition was an isuperable aversion to all kinds of profitable labor" (31)
   - personification: "her tongue was incessantly going" (32)
   - dog imagery (32)
   - scenery imagery (33)
   - simile "Nothing interupted the stillness of the scene, but the noise of the balls, whenever they were rolled, echoed along the mountains like rumbiling peals of thunder" (35)
   - i like the description of the town on page 36
   - good showing not telling and incorporation of history on page 37
   - nine pins has to be a metaphor for something.
