#+AUTHOR: Exr0n
#+TITLE: Notes on The Quantum World by Kenneth W Ford
* beneath the surface of things
** scale
*** wood seems solid, but is mostly empty space (atoms). Quantum effects are noticable on even smaller scales
	Atoms are like Propeller analogy: easy for something small and fast to get through, but hard for something large and slow.
** unintuitive
   Small (quantum mechanics) and fast (special relativity) things behave unintuitively
** particle history
*** electron and proton
	known to exist in 1926
*** photon
	no mass, created/detsroyed easily, was thought of as a funky 'almost particle' until it was discovered that they behave similarly to electrons and that electrons can be created/destroyed easily too
** fundamental discoveries in 1924-1928
*** matter has wave properties
*** fundamental laws are probabliistic
*** heisenburg uncertainty
*** discrete electron spin
*** every particle has an antiparticle
*** multiple momentums simultaneously
*** no two electrons can be in the same state of motion at the same time?
** unlike classical mechanics, properties and actions are not as distinct in the quantum world
** quantum mechanics won't follow common sense, which is to be expected because common sense is based on much larger things
** subatomic vs fundamental particles
*** hundreds of subatomic particles, but only a few are fundamental
*** most are composite
*** just like how there are hundreds of atoms but they are all composed of electrons, protons, neutrons
*** there are 24 fundamental particles excluding the higgs boson, graviton (which is not yet proven), and antiparticles.

* how small is small? How fast is fast? (scale)
** convienent units
*** femtometer (fm, $10^{-15} m$)
**** roughly a proton diameter
**** 6 miles is geometrically centered between the smallest particle probe and the radius of the known universe.
**** smallest prob is $10^{-18}$ meters. The plank length is $10^{-35}$ meters
*** speed of light (c, $3 \times 10^8 m/s^2$)
**** not as sped as distances are small
**** atoms and molecules vibrate roughly $10^{-5} c$ or $10^{-6} c$
**** the lighter something is, the faster it can go, so its likely that the rest-massless photon is the fastest
**** some theoretical tachyon business which can maybe go faster
*** time
**** humans
***** image flashed for a hundreth of a second (10 ms) can be precieved but not a thousandth
***** average human reaction time is 150-300ms
**** time to cross diameter of a proton at sped of light = $10^{-23}s$
**** particles that live long enough to leave trails in the detector live roughly $10^{-10}$ to $10^{-6}$
**** longest living is proton for 15 min (10^3)
*** mass
**** mass is inertia, measured by how hard it is to accelerate them (change their motion)
**** often measured as energy via $E = mc^2$
***** proton = 938MeV is easier to say than $1.67\times 10^{-27}kg$
*** electron volt (eV, energy auired by an electron being accelerated through an electric potential of 1 volt)
**** roughly a photon of red light
**** particle accelerators are made to create high energy particles that can then be converted to mass
**** modern accelerators go to roughly 1TeV, while protons move with only 1eV on the surface of the sun and weigh almost 1GeV.
*** charge ($e, 1.6\times 10^{-19}C$)
**** protons and electrons have the same magnitude of charge, deemed one unit. quarks have fractional charges
**** open questions
***** why is charge quantized/descrete
***** what happens near charged particles? inf charge as dist \to zero
***** if particles are physically sized, why dont parts of the particle repel itself
*** spin
**** two types: spin and orbital motion
**** measured with angular momentum
**** fundamental particles don't have a descernible spin but do have an angular momentum
**** $\hbar = \frac{h}{2\pi} = 1.05\times 10^{-34} kgm^2/s$
**** orbital angular momentum must be a multiple of $\hbar$ and spin angular momentum can be a multiple of $\frac{1}{2}\hbar$?
**** a particle type can have many spins, but the change in spin is often so drastic that they are considered two different particles
*** fundamental constants
**** most units are chosen arbitrarily based on earths size or something, but there are two fundamental ones
**** plank's constant $h$ defines the quantum scale... larger $h$ would make the universe 'lumpier' or 'more pixelated'
**** the speed of light $c$ is the fastest speed, or something.
**** there is expceted to be a third constant to form a complete basis, but we haven't found one yet
***** it would be a length or a time
* meet the leptons
** types (flavor) electron, muon, tau
** conserve {charge, flavor, energy, momentum}
** neutrinos are like the soul of its particle - tiny mass but same flavor
** they have multiples of half unit spins or something
** any particles can be created as long as everything is conserved
* the rest of the extended family
** quarks
*** six of them in groups of three
*** they group up in the wild to make up other composite particles
*** particles have integer charge, but quarks come in one-third multiples of charge
*** baryon number
**** another type of 'charge' that is also conserved
**** protons and neutrons are both baryonic (meaning they have baryon number?)
**** like leptons, the lightest baryon cannot decay because there is nothing to decay into (the proton)
**** quarks have one-third baryon number also
*** antiquarks
**** makes up meson with another singular quark (For a total baryon number of 0)
**** antiquark particles are unstable
*** color
**** red, green, blue, antired, antigreen, antiblue
**** all three or a normal with an anti is colorless..???

ended page 71
** composite particles
*** baryons vs mesons
**** baryons have half odd integral spins (1/2, 3/2, 5/2) while mesons have integral spins
**** baryons are made of 3 quarks each while mesons are made up of a quark and an antiquark
**** baryons are fermions and mesons are bosons. all are hadrons (strongly interacting) bc quarks are strongly interacting
**** mesons have baryon number zero
*** some baryons
**** lightest are proton and neutron (made up up and down quarks)
**** then heavier ones have strange quarks, and some even heavier have charm and bottom quarks
**** have not found a baryon that contains a top quark yet
**** other than the proton, all 'baryons are unstable (radoactive)'
**** they all live a really short time (see the table) roughly $10^{-10}$ to $10^{-19}$ seconds
*** some mesons

**** the pion (lightest meson)
***** Yukawa thought pions moving around gave rise to the strong nuclear force, but now we think its quarks exchanging gluons
***** there is a charged version of the pion which is made of a down quark and an anti-up quark (written \(d\bar u\))
***** the uncharged pion is made up of 'a mixture, pratly an up quark and an anti-up quark, partly a down quark and an anti-down quark, so we write its composition as $u \bar u \& d \bar d$' what the heck :question:
***** some different mesons have the same composition (neutral pion and eta)
***** mesons can decay entirely into leptons (while baryons cannot because they must conserve their non-zero baryon number)
** force carriers
*** physics is about things and what happens to them, and those particles were the things. these are what happens
*** all are bosons (integer spins) and there are no conservation laws so they can do whatever they want
**** not even conservation of angular momentum/spin?               :question:
*** there are six particle types, with one for each of the fundamental forces except the weak force which has three
**** graviton (the weakest force) (but it is the one we see the most because all the other forces can be negative are balanced (ex positive and negative charges yet most matter is mostly neutral))
***** its so weak that it doesn't really do anything in the subatomic world (can be ignored)
****** but maybe some weird quantum stuff makes it actually important on smaller scales
***** not much to say apparently, it cant be v precisely measured bc its so weak
**** weak force carriers (W and Z)
***** very massive but lacking physical size??                     :question:
***** they are actually three close siblings (much like the positive, negative, and neutral versions of pions)
***** discovered at proton synchotron at CERN
**** photon
***** proposed by Einstein in 1905, but not seen as a real particle until the 1930s
***** actually zero mass and zero size
***** force carrier for electromagnitism
***** electroweak theory
****** says that electromagnetic and weak forces are the same thing but on different scales
****** suggests heaver force carrier means weaker force and shorter range
****** except the electromagnetic force only cares about charged particles while the weak force affects all particles
**** strong interaction gluons
***** there are 8 of them, and 8 more antiparticles
***** made up of two colors (red antiblue or blue antigreen) for 2^3 = 8 combinations
****** are colors allowed to repeat (red antired) and is it always normal-anti (or is antired-green diff from green antired) :question:
***** quarks change color when they interact with a gluon
***** gluons can also directly exert force on one another (while photons can only interact with eachother via charged particles)
****** is there an example of this                                 :question:
***** strong force holds quarks within the particle, and gets stronger as distance increases
***** you can break a quark out of an atom, but the energy will become more quarks and antiquarks and you might get a pion out (bruh)
** feynmann diagrams
*** start with something like a spacetime diagram
**** the path tells us everything there is to know about a particle
**** but at events (ex. where the path changes directions) any number of things might happen
**** subatomic events seem to be instant and unsurvivable (nothing goes in and also comes out)
**** particles can also move backwards in time, apparently
*** features of the feynmann diagram
**** every vertex has three points, with two fermion lines (particles) and one boson line (force carrier)
***** *every interaction in the universe is the result of two fermions and a boson meeting in these triads*
**** arrows denote anti-ness (a forwards-in-time positron is the same as a backwards-in-time electron)
**** conservation laws are consistent at each vertex
**** composite particles don't interact with bosons, so we draw them as their constituent quarks
*** gluon exchange between quarks
**** gluon particles are determined by the quark pairs that they interact with? so a gluon being released and then absorbed by a diff quark essentially swaps the colors of the two quarks? :question:
**** is there a difference between a red quark sending a blue quark a red antiblue gluon and a blue quark sending a red quark a red antiblue glueon? :question:
**** quarks don't change their type (up down strange charm top bottom) when getting glueoned
