#+TITLE: LECTURE - Why does earth have magnetic field
#+AUTHOR: Peter Choi
#+DATE: 11/14/2021

Link to video: https://www.youtube.com/watch?v=I3zFeV24or8

* Terminology:
- Geomagnetic: Earth's magnetic field
- Paleomagnetic: Earth's ancient magnetic field
- Geodynamo: the "motor" that creates Earth's magnetic field

* Three requirements for a magnetic field:
1) Large electrically conducting fluid in planetary interior
2) Energy supply (eg, convection)
3) Planetary rotation

* How to make a dynamo (17:00-20:40):
1) put a conductive liquid into a vat
2) rotate that vat in one direction
3) apply a magnetic field through the rotating vat
4) put a propeller into the vat and turn the opposite direction that that vat is turning. This should create some turbulence which will "tangle" the applied magnetic field inducing another magnetic field.
5) Remove the applied magnetic field and see if the induced magnetic field stays (it should stay for a dynamo number over about 40 (see video for how that is calculated)).

* How does this dynamo business change in the context of earth? (20:40-23:06)
- the dynamo experiment described above has gravity pulling downward where as earth has gravity pulling towards the center
- Otherwise it is pretty much the same, this means that the jumble will actually arrange itself into vortexes which are parallel to each other and are parallel ish to Earth's axis of rotation.
- These vortexes induce a magnetic field. 
