#+TITLE: Understanding Research Papers
#+AUTHOR: Houjun Liu

* Understanding Research Papers
Jack attempting to read through research...

* Biggins 2014
:PROPERTIES:
:NOTER_DOCUMENT: Biggins2014.pdf
:END:
** Problem Setup
:PROPERTIES:
:NOTER_PAGE: (1 . 0.8807495741056218)
:END:

Equilibrium curve setup. Treat chain as a bit of a rope, so

- Horizontal change of a "bead": $dx$
- Length of a "bead": $ds$
- Angle by which the bead is above the ground: $\theta$
- Mass density: $\lambda$

And hence, $ds = \frac{dx}{sin(\theta)}$, and mass is $\lambda ds$ as it is indeed the mass density times length.
** There is no acceleration?
:PROPERTIES:
:NOTER_PAGE: (2 . 0.07922392886014551)
:END:
Apparently the acceleration due to gravity could be ignored... Not sure why/how.
** Change tension force over time to counter gravity
:PROPERTIES:
:NOTER_PAGE: (2 . 0.1131770412287793)
:END:
It seems, it stedy-state does not have an tangent acceleration (circular motion, only acceleration is perpendicular), we /know/?? that the tangent force has to balance gravity. And hence, Biggins claims:

\begin{equation}
    \frac{d}{dx} T(x) = \frac{\lambda g}{sin \theta} cos(\theta)
\end{equation}


