:PROPERTIES:
:ID:       F0B8CE04-DF8C-4B83-AD62-DCFE143266FE
:END:
#+title: Wordsmith
#+author: Houjun Liu

With the support of the normal force of the table below, the left end of the link does not sag and therefore more work is produced to lift the center of mass up.

As you can see, the center of mass travels farther in the y-direction with a table then without per our simulation.

This is also analytically confirmed by analyzing the torque in the reference frame of the table.



Hi hi hi here's some wordsmithing for bonus sneakiness (note the passive voice)

thank you this is really helpful. *more work is produced* seems a little sus maybe it:s just me. but could be confusing since the force to lift the chain link is the exact same but the work is not - and most people won:t see that what changes is the displacement. ig that:s what were trying to hide in the first place but it could also come across as confusing and not well thought out to the judges... i:ll keep thinking about it but thank you for writing this

