#+TITLE: Indigenous Intersection Essay Prep
#+AUTHOR: Houjun Liu
#+SOURCE: KBHIST301MasterIndex
#+COURSE: HIST301

* General Information
| Due Date | Topic                                     | Important Documents       |
|----------+-------------------------------------------+---------------------------|
| ?????    | Synthesis Essay: Indigenous Intersections | - Facing East             |
|          |                                           | - Follow the corn         |
|          |                                           | - White's Middle Ground   |
|          |                                           | - Atlantic on Mann's 1941 |

* Prompt
*Indigenous intersections with European culture*

1. What is an idea, theme, or commonality that connects the resources to each other?
2. What is your own thesis concerning this idea, theme, or commonality?
3. How can my thesis be supported by evidence from various sources? Revisit your
sources and notes – do they support your thesis?

* Quotes Processing
- "Words like 'invasion' and 'conquest' may now trip more easily fromourtongues thanquaintphrases like "the transit of civilization, 'yet the “master narrative” of early America remains essentially European- focused." (Facing 8)
- "Only after the establishment of large-scale European colonies—and the much bigger and more predictable patterns of trade they allowed— did Indians begin to use imported goods in ways that resembled the pur- poses for which they had been designed." (Facing 43)
- "The news things were **always** in some practical way superior to the old --- lighter, sharper, more durable --- but they were used in very familiar contexts." (Facing 44)
- "Something as basic as firemaking was radically simplified not just by axes that made firewood more readily obtainable but by flint and still 'strike-a-lights'" (Facing 44)
- "The vastly increased supply did not so much devalue what was once rare as create an innovative cultural phenomenon rooted in unprecedented abundance" (Facing 46)
- 


* Claim Synthesis

** Development
- /Claim/
  - Why does the claim address the prompt?
  - How does the evidence support the claim?
    - 1
    - 2
    - 3
  - So what?

* Defluffication
/Chosen Thesis Claim/

  - Point a
  - Point b
  - Point c

    So what? SO WHAT

    *Restated Claim*


There's always the [[https://wp.ucla.edu/wp-content/uploads/2016/01/UWC_handouts_What-How-So-What-Thesis-revised-5-4-15-RZ.pdf][UCLA Writing Lab]].
