#+TITLE: Category Theory: Ch1
#+AUTHOR: Dylan Wallace

Note that I will use semicolon notation rather than composition notation.
That is, $f;g = g(f(x))$.

* Partitions
We can divide a set into a set of subsets of the original set, such that their disjoint union is the original set. We call this a _partition_ on the original set.
For example, if $A = \{1, 2, 3, 4\}$, then the set of subsets $Part_{A} = \{\{1, 2\}, \{3, 4\}}$ is a partition on $A$.
We can think of a partition as a surjective map from the original set to another set, such that elements with the same image are in the same set in the partition.
That is, formally, a partition "is" a surjective map $f: A \twoheadrightarrow X$, where the partition is given by $Part_{f} = \{\{f(b)|b\in A, f(a) = f(b)\}|a\in A\}$.

* Preorders
A preorder (also sometimes called a poset) is a set with a relation, notated in tuple notation as $(P, \leq)$. The relation helps "order" the set. For example, there's an implicit order to numbers, so $\mathbb{N}$ can be thought of as a preorder.
By the way, in this context, a relation is a function of the form $\leq: a\times b \rightarrow Bool$.
Note that you can make a partition from a preorder. If two elements are equivalent, i.e. $a \leq b$ and $b \leq a$, then you can place them in the same partition.
An _upper set_ of a preorder is the set of elements in the preorder that are greater than or equal to a certain element.
The _cartesian product_ of a preorder is what you would expect the cartesian product would be. The relation is defined based on component-wise relations.

** Monotone maps
A monotone map is a mapping between two preorders that preserves structure.
If you have two preorders $A$ and $B$ and two monotone maps $f: A\rightarrow B$ and $g: B\rightarrow A$ such that $f;g = id_{A}$ and $g;f = id_{B}$, then $A$ and $B$ are said to be _isomorphic_.

** Meets
A _meet_ of a subset of a preorder $a\subset A$ is the greatest element of $A$ such that it is less than any element in $a$.
Similarly, the _join_ of a subset of a preorder $a\subset A$ is the smallest element of $A$ such that it is greater than any element in $a$.
Note that we can form a preorder on the set of all sets, where we define one set to be greater than another set if it is a superset of that set.
Then, we can say that the meet of a set containing two sets is the intersection of those sets, and the join of a set containing two sets is the union of those sets.
This is because a set containing two sets can be thought of as a subset of the set of all sets. Then, we know that the smallest set that is greater than two sets is their union, and the greatest set that is smaller than two sets to be their intersection.
Because of this, we notate meets with the symbol $\wedge$ and joins with the symbol $\vee$.
A monotone map preserves meets/joins if the map of a meet/join is the same as the meet/join of two maps. That is, $f: P\rightarrow Q$ preserves meets if $f(a\wedge b) = f(a)\wedge f(b)$ and preserves joins if $f(a\vee b) = f(a)\vee f(b)$.
If a monotone map doesn't preserve joins, it's said to have a "generative effect".

** Galois connections

