#+TITLE: Category Theory: Ch1
#+AUTHOR: Dylan Wallace

* Basic stuff first
** Partitions
We can divide a set into a set of subsets of the original set, such that their disjoint union is the original set. We call this a _partition_ on the original set.
For example, if $A = \{1, 2, 3, 4\}$, then the set of subsets $Part_{A} = \{\{1, 2\}, \{3, 4\}}$ is a partition on $A$.
We can think of a partition as a surjective map from the original set to another set, such that elements with the same image are in the same set in the partition.
That is, formally, a partition "is" a surjective map $f: A \twoheadrightarrow X$, where the partition is given by $Part_{f} = \{\{f(b)|b\in A, f(a) = f(b)\}|a\in A\}$.

** Preorders
A preorder (also sometimes called a poset) is a set with a relation, notated in tuple notation as $(P, \leq)$. The relation helps "order" the set. For example, there's an implicit order to numbers, so $\mathbb{N}$ can be thought of as a preorder.
By the way, in this context, a relation is a function of the form $\leq: a\times b \rightarrow Bool$.
Note that you can make a partition from a preorder. If two elements are equivalent, i.e. $a \leq b$ and $b \leq a$, then you can place them in the same partition.
An _upper set_ of a preorder is the set of elements in the preorder that are greater than or equal to a certain element.

