#+TITLE: Note Taking Thoughts
#+AUTHOR: Dylan Wallace

* Structure of knowledge
I think that most people agree that the structure of knowledge is fundamentally relational. That is, when mapping out knowledge, it takes the form of nodes representing ideas, and edges representing how those ideas intertwine.

I think that Spivak's theory of [[https://math.mit.edu/~dspivak/informatics/ologs--basic.pdf][Ologs]] is a "better" description of the structure of knowledge. Not only does knowledge take the structure of connected ideas, but the ideas themselves are only labels, and the relations between ideas ("morphisms") give each idea "meaning". Although every relation between two ideas is local in nature (i.e. the relation is defined only in terms of the two ideas), due to the infinitessimally large number of ideas, and therefore relations, every idea has, associated with it, an infinitessimal amount of relations to other ideas, enough to distinguish itself from another idea. Because ologs are categories, the yoneda lemma applies: An object is defined by its relation to others. As such, one implicit implication of Spivak's theory of ologs is that ideas are defined by their relationship to other ideas.

We see this concept in real life. When explaining what something is, for example what "arginine" is, we might say that it "is" an "amino acid." In explaining arginine in this way, we are defining arginine in terms of amino acids. This same phenomenon can be seen with any word.

*Corollary*: It's impossible to not be able to describe an idea in terms of language. If there exists an idea that is impossible to be described in terms of language, we can describe it as "an idea that is impossible to be described in terms of language." As such, the original premise is proven to be incorrect. An implication this has in the context of ologs is that there are no objects with only an identity morphism, or can only be described using a tautology.

If every idea is defined in relation to others, we can make these relations explicit by creating pairs of ideas and collections of morphisms that lead out from the idea. This is, to some extent, what Wikipedia does. Every idea (=wiki page) contains links to other ideas (=wiki pages) to help illustrate the position that the idea occupies in the zeitgeist.

To get more technical, we can think of the set of all relations from an idea to other ideas as the image of the functor $O(X, -)$, where $O$ is the olog in question and $X$ is the object (=idea) in question. Then, we can think of a functor from $O$ to the category of functors (op) that maps every object $X$ to the functor $O(X, -)$. Every morphism in $O(X, Y)$ is taken to a natural transformation from $O(Y, -)$ to $O(X, -)$, or a pullback along that morphism. (I think my math is right).

* Subjective and Objective knowledge and ideas
One thing that Spivak covers is the notion of subjective and objective knowledge. Spivak takes the position that ologs are a representation of a "mode" of thinking (that isn't a reference but a paraphrase), rather than being an objective portrayal of ideas. That is, ologs operate under a certain context.

One of my goals with this research project is to find a way to somehow create an atomic note-taking system with _minimum redundancies_ that facilitates _collaboration with ease_. The hard part is mainly the collaboration. To have collaboration without redundancies, we need participants of the note-taking system to work on the same ideas/notes rather than create a new note for every idea like they would in a personal note system. This is difficult for a few reasons:

1. Two people may not have any overlapping knowledge that allows one to augment the ideas of another;
2. Two people may have different knowledge topologies and therefore not agree on what should/shouldn't be a note

Of the two, the second is the "solvable" problem. The first problem is a problem that has to do with the knowledge of each participant, which can't be solved by the structure/form of the note-taking system. But I believe we should be able to do something about the second problem.

** The actual model of note-taking
We've established in section 1 that a set of idea-morphism list pairs is a way of representing an olog. Something like Wikipedia forms a category (in the most general sense).
I will further establish that a _personal note-taking system_ in our context consists of 

* Collaborative note-taking
A categorical way of looking at collaborative note taking in the way that I envision it is a union between different people's note-taking systems.
I can think of a way of doing this.
First, every person's note $N$ is turned into a product category $N \times \{\{A\}\}$, where $A$ is the author's identification
