#+TITLE: Note Taking Thoughts
#+AUTHOR: Dylan Wallace

* Structure of knowledge
I think that most people agree that the structure of knowledge is fundamentally relational. That is, when mapping out knowledge, it takes the form of nodes representing ideas, and edges representing how those ideas intertwine.

I think that Spivak's theory of [[https://math.mit.edu/~dspivak/informatics/ologs--basic.pdf][Ologs]] is a "better" description of the structure of knowledge. Not only does knowledge take the structure of connected ideas, but the ideas themselves are only labels, and the relations between ideas ("morphisms") give each idea "meaning". Although every relation between two ideas is local in nature (i.e. the relation is defined only in terms of the two ideas), due to the infinitessimally large number of ideas, and therefore relations, every idea has, associated with it, an infinitessimal amount of relations to other ideas, enough to distinguish itself from another idea. Because ologs are categories, the yoneda lemma applies: An object is defined by its relation to others. As such, one implicit implication of Spivak's theory of ologs is that ideas are defined by their relationship to other ideas.

We see this concept in real life. When explaining what something is, for example what "arginine" is, we might say that it "is" an "amino acid." In explaining arginine in this way, we are defining arginine in terms of amino acids. This same phenomenon can be seen with any word.

*Corollary*: It's impossible to not be able to describe an idea in terms of language. If there exists an idea that is impossible to be described in terms of language, we can describe it as "an idea that is impossible to be described in terms of language." As such, the original premise is proven to be incorrect. An implication this has in the context of ologs is that there are no objects with only an identity morphism, or can only be described using a tautology.

As a result of 

* Subjective and Objective knowledge and ideas
One thing that Spivak covers is the notion of subjective and objective knowledge. Spivak takes the position that ologs are a representation of a "mode" of thinking (that isn't a reference but a paraphrase), rather than being an objective portrayal of ideas. That is, ologs operate under a certain context.
One of my goals with this research project is to find a way to somehow create a note-taking system that can unite 
