#+TITLE: Ologs and Analogies: A Categorical Approach to Ontology
#+AUTHOR: Dylan Wallace

This essay assumes a knowledge of basic category theory

* What are Ologs?
Ologs are a category where objects are noun phrases and morphisms are verbs. As such, Ologs store ontological information.

A /Diagram/ of a category is a subset of the category in question. A diagram does not necessarily have to have all properties of a category. In the context of ologs, a diagram is a subset of the declarative information stored in the olog.

There exists a specific structure of diagram, which we will call /statements/. A statement is a diagram of an olog which contains two objects and a single morphism between them. The statement is the fundamental building block of an olog: An olog is equivalent to the direct sum of all statements in an olog.

* What's an analogy?
An analogy is an ontological comparison between two statements. We've established already that ontological statements are analogous to the two-object one-morphism diagrams in an olog. Then, an analogy in the context of an olog is a comparison between two statements in an olog.

Olog analogies are functors, but are usually not olog endofunctors. An olog analogy that is an olog endofunctor is a perfect analogy. This is because the analogy is applicable for any statement in the olog. 
