#+TITLE: Power Product Sum proof
#+AUTHOR: Dylan Wallace

* The claim
\begin{aligned}
a^{x + y} = a^x\cdot a^y
\end{aligned}

for any $a, b, x \in \mathbb{N}$

* The proof
We consider the category $Set$. Objects in $Set$ are sets, and they are isomorphic if they contain the same number of items.
As such, we describe every category by the number of items in it. We notate $\underline{1}$ to mean a set with one element, $\underline{2}$ to mean a set with no elements, and more generally, $\underline{x}$ to mean a set with $x$ elements.
We also note that for any two sets $x, y \in Ob(Set)$, there exists a set of all morphisms from $x$ to $y$, notated $Hom(x, y)$ or $Set(x, y)$. Morphisms between sets are functions, and we know that between a set of $x$ elements and a set of $y$ elements there are $y^x$ functions, or $|Hom(\underline{x}, \underline{y})| = y^x$. We notate $b^a$ where $b, a \in Ob(Set)$ to mean $Hom(a, b)$.
Now, we can think of a set $A$ which can be split perfectly into $x$ and $y$ (ie $x\cup y = A$ and $x\cap y = \emptyset$). Then, we can think of every function from $A$ to another set, say $a$, to be made of a pair of functions, one from $x$ to $a$ and the other from $y$ to $a$.
Replace $A$ with $x + y$. We then have $a^{x + y} \cong a^{x}\cdot a^{y}$. By virtue of being able to substitute numbers for sets and vice versa, we prove our poof.
