#+TITLE: Five Words - ##/##
#+AUTHOR: Dylan Wallace

* Words
** 直播 (zhi2bo1): v
- *Definition*: to broadcast live; to livestream
- 我今天直播了一项球塞 (wo3 ji1nti1an zhi2bo1 le yi1xia4ng qiu2sai4) :: Today I broadcasted a sports game
** 提问 (ti2we4n): v
- *Definition*: to question; to quiz; to grill
- 老师提问了，可是我答不上来 (la3oshi1 ti2we4nle wo3, ke3shi4 wo3 da2busha4nglai) :: The teacher asked me a question, but I wasn't able to answer it.
** 收获 (sho1uhuo4): n/v
- *Definition*: results, gains; to harvest, to gather in the crops
- 这个实习期我收获了不小啊！(zhe4ge shi2xi2qi1 wo3 sho1uhuo4le bu4xia3o a!) :: I took away a lot from this internship!
** 范畴论 (fa4ncho2ulu4n): n
- *Definition*: category theory
- 我学范畴论 (wo3 xue2 fa4ncho2ulu4n) :: I am learning category theory
** 奇怪 (qi2gua4i): v/a
- *Definition*: feel surprised; strange, surprising, odd
- 我有很多好朋友，可是他们的父母都奇怪 (wo3yo3u he3nduo1 ha3o pe2ngyou, ke3shi2 ta1men de fu4mu3 do1u qi2gua4i) :: I have many friends, but all of their parents are weird.
* Synthesis
我今天回家以后看了一项数学直播。直播教了大家范畴论。我觉得范畴论很奇怪。直播提问了大家很多次，可是我一个问题不能回答。但是直播有意思，所以我觉得我收获了不小。
