#+TITLE: Eric Foner Lectures
#+AUTHOR: Dylan Wallace

* The Market Revolution and Democracy
There were key economic and technological revolutions that occurred in the Antebellum period. They worked in tandem to change the landscape of the Antebellum period. For example, the Eerie Canal enabled farmers to get goods to other places in the US. This facilitated a shift from a self-subsisting economy to a more market-oriented economy. The invention of steamboats enabled the expansion of the agricultural market. Another example is the introduction of factories.

Many of the political issues of the Antebellum period had to do with the Market Revolution:

- Banking
- Free Trade
- Protective tariffs
- Internal improvement

Much of these "problems" originated in the Antebellum period.

Another "thing" that happened in the Antebellum period was the "rise of political democracy" (based on "universal white male suffrage"). A large percentage of the population was able to vote. Democracy became the defining characteristic of America.

Much of politics were grassroots.

* The Cotton Kingdom
Slavery was actually dying out in Antebellum Period but Industrial Revolution in England made cotton valuable; American South monopoly of cotton. Cotton gin sped up cotton harvesting and made slavery worse.

Internal slave trade replaces international slave trade. Creation of Cotton Kingdom (Alabama, Georgia, South Carolina, Mississippi, Louisiana, Arkansas): Heartland of slavery.

_"Cotton is King"_: Key commodity of world trade in 19th century, was like oil.

Entire nation was benefitting from cotton trade; made up about *50%* of profits. New York was centrally involved; merchants controlled shipping of cotton to Europe; prosperity tied to cotton. New York allowed 9 months of slave transit, up to 1840.

Current view of Southern plantation owners: *savvy business owners* rather than evil men

Slaves /were/ property back then. Combined value of slaves were 3 billion dollars (back then); Banks + Railroads + Factories: 2 billion dollars.

Pro-slavery ideology/narrative created: "Slaves are taken care of and are well off; better to be a slave to a master than to be impersonal to a factory owner"

Slavery is unbalanced in its geographic distribution; concentrated in the South.

- Lower South: Slavery
- Upper South: Not much slavery
Upper South wanted to tie economy to the North

Most White families did not own slaves (only 1/3). It was widely distributed though. Most slave owners owned only a few slaves. Plantations set tone of Southern society though (dominated politics, economy)

The South was the largest bastion of slavery

* Immigration before the Civil War
Many immigrants between 1815 and 1915. especially 40's and 50's

Major source of immigration were Europeans; 2 million. More than population of US when nation founded. Largest amount came from Ireland; also England, Scotland, Germany, Scandinavia (so called old immigration)

Most immigrants moved to North; didn't want to compete with slave labor. Most immigrants entered through New York; some moved West: Millwaquee, Chicago, Wisconsin, etc.

Factors in Europe induced Europeans to move to US: Factory system, population boom in Europe, agricultural revolution consolidates land owning

Many immigrants were skilled laborers; some immigrants were political dissenters (48'ers) - Marx, for example, considered it; Immigrants were peasants

Many people didn't go to US: Some to Poland, some to Russia, etc. Lots of immigration in Asia

Largest "push" of immigration was Irish famine; Irish were marginalized and famine led to Irish diaspora

Immigrants became proles of the era; physical labor

* Politics, Whiteness, Religion
Immigrants get mobilized by politics by "political machines" (e.g. Taminy Hall (?))

Political machine replaced welfare

Fernando Wood becomes Mayor of New York; Irish police movement, uses gangs to intimidate voters

Irish were "not white"? Misconception

Whiteness != Equal treatment; Irish were discriminated against; "Whiteness" doesn't matter

Growing presence of Catholic Church. Church in US becomes Irish dominated rather than English or American. Church becomes militant/expansionist in regards to Catholicism; alarms Protestants

Some Whigs wanted to appeal to immigrants




