#+TITLE: Synthesis Essay
#+AUTHOR: Dylan Wallace

* Synthesis
- Origins of Identity asserts that ideology spread throughout the 1700s through pamphlets
- Marketplace of Revolution asserts that ideology spread through a network resulting from a unified identity among the Colonists, which was created via boycotts and Baubles


- Ideological Origins
  - British anti-government ideas spread to Colonies because of culture
    - Spread throughout Colonial America via pamphlets
  - Stamp Act viewed as attempt to reduce Colonists to servants
  - 










** Thesis: The origins of the American Revolution can be attributed to both economic and ideological factors.
Old Thesis: The desire for economic liberty exibited in Marketplace is a consequence of the spread of English anti-Whig ideologies among the colonies.

- The boycott movement was primarily motivated by libertarian ideals
  - Boycott movement extra info
  - 
- The libertarian ideals that led to the boycott movement originated in the 18th century
- The two are directly related (causal)



- Economic factors that were acted upon via ideology led to the American Revolution
- Timing wise, spread of anti-Whig ideologies took place before Baubles
  - Spread: 1720s onwards, via pamphlets
  - Baubles: Originated in 1765 with Stamp Act
- There needs to have been a libertarian ideology popular among Colonists during the time period to see a response like that in Marketplace
  - For Baubles to have been conceived, the concept of economic liberty needs to have been popularized


- American Revolution -> caused by economic and ideological
  - Economic -> ideology spread
  - Ideology -> Caused Economic
- The economic factors
  - Stamp Act kicked off Revolution sentiment
    - Was economically taxing (literally)
    - Induced boycotts
  - 

- British critique ideology against parliamentary government spreads to US because of different culture
- Ideology serves as prerequisite for boycott movement




* Essay


The spread of libertarian ideology originating in Britain among the colonies facilitated the boycott movement of British goods in the 1760's and led to a unified inter-colonial movement.

Although it is commonly thought that the libertarian ideals that characterized the American Revolution originated in America, they can actually be traced back to the ideals of radical Whig thinkers in early 18th century Britain. The Glorious Revolution in 1688 established parliament as being the dominant ruling force in England, and as a result, concepts such as natural rights and Locke's idea of social contracts permeated throughout the English ideological zeitgeist. Despite this widespread adoption of these concepts, the radical Whigs took things further by emphasizing the importance of these concepts beyond that given by the mainstream. Radical Whig writers such as Trenchad, Gordon, and Bolingbroke wrote of the ostensive democratic façade that parliament hid behind to mask their corruption, and urged for restrictions on the powers of parliament by one way or another. These ideas, although popular within niche circles, never gained prominence within Britain; they were radical ideas for the time, after all. However, they did gain traction among another population: Colonists in America. The large population of land-owning individuals and farmers, as well as a weak presence of religious authority induced by religious diversity in the Colonies, made the Colonist populace largely accepting of the imported radical Whig ideals from Britain, and the ideology spread throughout the Colonies throughout the 18th century.

The unified colonial movement itself, meanwhile, was the result of the boycott movement in the 1760's.
After a worsening of finances after the French–Indian War, the English government looked at the Colonies as an untapped revenue source to help pay off the debts they accrued. In 1765, the Stamp Act was passed. It introduced a tax levied on all official documents, similar to existing laws on documents in England. The tax was viewed negatively by Colonists; some interpreted it as a sign that =Baubles=, whereas others interpreted it as =Britain wants to subjugate colonists=. Either way, the colonists

Prior to the boycotts, unity between the 13 British colonies in America was thought of being unattainabe. The primary reason for this sentiment was the conception that the culture of the colonies differed too greatly between each other to lead to unity. This sentiment was widespread among Englishmen and Colonists alike; Thomas Pownall, the former royal governer of Massachusetts, is quoted as claiming that colonists' "mental horizons were too narrow, too much the product of local history and culture, for them ever to cooperate with those who happened to live in other provinces." However, this would change after the boycotts.


Without the libertarian ideals that spread among the colonies in early 18th century, the boycott movement would not have been conceived, much less enacted upon.









































The cause for the American Revolution can be =interpreted= as a combination of both economic and ideological factors, which interlaced with each other to create the unique environment in which the American Revolution took place. (=TBD=)
The economic 








The desire for economic liberty that was exibited in the colonists' boycott movement of the 1760s is rooted in the spread of libertarian ideals earlier in the 18th century. (=TBD=)
The boycott movement against British goods was a characteristically libertarian reaction to perceived British tyranny. The origins of the boycott movement could be traced back to the passing of the Stamp Act in 1765, after which colonists became subject to laws similar to those in Britain that saw the taxation of official documents.
=Colonists viewed the passing the Stamp Act as a sign of Britain's expectation of=
Although the direct cause of the boycotts was the , without the permeation of libertarian ideals within colonialist society, the boycotts would never have been conceived, much less organized. In Britain, 



[Baubles of Britain movement was a libertarian reaction to perceived British tyranny] [Summary of boycott movement] [Direct cause of boycott] [Talk about how libertarian ideological permeation was a necessity for boycott to take place]
