:PROPERTIES:
:ID:       697FF899-67E4-4731-B87F-EE07B0F9A825
:END:
#+title: Antebellum Research Notes
#+author: Houjun Liu

Research notes: the Antebellum.

* Guiding Question
- In what respects was American discovery of technology used to rationalize inherent American superiority (sui generis) as a people?
- What social and political conditions in America allowed the proliferation of the discovery and implementation of technology in the antebellum period?

* Howe - What Hath God Wrought
:PROPERTIES:
:NOTER_DOCUMENT: WhatHathGodWrought.pdf
:END:

** The speed of communication increased the speed of production
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5405046480743692)
:END:
American farmers and planters—and most Americans then earned a living through agriculture—increasingly produced food and fiber for distant markets.
** The telegraph served as the intergrater and a pusher for manifest destiny
:PROPERTIES:
:NOTER_PAGE: (3 . 0.7304116865869853)
:END:
The electric telegraph then helped integrate this continental empire.
** That the telegraph is also an invention of "God", and therefore a justification for Manifest Destiny
:PROPERTIES:
:NOTER_PAGE: (4 . 0.19256308100929614)
:END:
As Morse later commented, the message "baptized the American Telegraph with the name of its author": God.
** That the telegraph is something used to justify and expedite America and Christianity's influence upon the world
:PROPERTIES:
:NOTER_PAGE: (4 . 0.6440903054448871)
:END:
This noble invention is to be the means of extending civilization, republicanism, and Christianity over the earth. It must and will be extended to nations half-civilized, and hence to those now savage and barbarous.
** Policitical parties could not be possible w/o the telegraph       :claim:
:PROPERTIES:
:NOTER_PAGE: (5 . 0.2337317397078353)
:END:
However, no such parties with mass followings could have come into existence without the revolution in communication.
** The early national period allowed the implentation of new ideas and change
:PROPERTIES:
:NOTER_PAGE: (7 . 0.398406374501992)
:END:
The early national period witnessed now and controversial ideas being formulated, publicized, and even in many cases implemented.
** "Modern" tech propergated the spread of novel ideas               :claim:
:PROPERTIES:
:NOTER_PAGE: (8 . 0.11571125265392782)
:END:
All such reforms were created, discussed, and propagated through the enormously expanded media of print and wire. 
** Speed of communication caused unessesary damage
:PROPERTIES:
:NOTER_PAGE: (9 . 0.3386411889596603)
:END:
A severe winter all Europe, these were large armies for North America. transportation over the Atlantic world slowed communication and made transportation difficult. Neither army knew that across the ocean, representatives of their respective countries had signed a treaty of peace eight days earlier.

** Earlier sentiments of irish racism also prevails
:PROPERTIES:
:NOTER_PAGE: (13 . 0.35562632696390656)
:END:
Perhaps Mullins’s suspicions were justified: Because his troops were Irish, they might have been thought expendable.

** Descrimination runs deep and compensation thereof was and still is used a political device
:PROPERTIES:
:NOTER_PAGE: (16 . 0.09341825902335456)
:END:
Besides twenty-four dollars cash, each soldier was supposed to receive 160 acres of public land, but forty years later, the black veterans were still trying to get their land claims honored.

** The cause of the American revolution may have not happened were communicatio be more rapid
:PROPERTIES:
:NOTER_PAGE: (17 . 0.1602972399150743)
:END:
When Congress declared war on Great Britain, June 18, 1812, its members did not know that two days earlier Foreign Secretary Castlereagh had announced in Parliament that the Orders in Council restricting American commerce would be suspended.

** Americans did not celebrate technology but instead people in their victory
:PROPERTIES:
:NOTER_PAGE: (18 . 0.13694267515923567)
:END:
Neither did they celebrate the technological know-how that enabled their artillery to perform so well. Instead the public seized upon the notion that western riflemen, untrained but sharp-eyes, had defeated the arrogant British.

** It also manifested a failure to foresee how much the future of the United States would owe to mechanization and government- sponsored enterprises like the federal armories that made cannons.
:PROPERTIES:
:NOTER_PAGE: (19 . 0.2961783439490446)
:END:

** Much of the society is extolling the /people/ instead of the technology --- with the latter often being the driving force behind success
:PROPERTIES:
:NOTER_PAGE: (19 . 0.29936305732484075)
:END:
It also manifested a failure to foresee how much the future of the United States would owe to mechanization and government-sponsored enterprises like the federal armories that made cannons.

** Technology represented a type of federalism (government sponsored technological development), instead of the success of the "husbandmen" individuals coming to fight.

* Factories: Lowell 
:PROPERTIES:
:NOTER_DOCUMENT: lowell Factory.pdf
:ID:       245EB844-E9B7-4611-801A-E8B42441162B
:END:

** Lowell factory organisation caused the formation of organized labor groups
:PROPERTIES:
:NOTER_PAGE: (1 . 0.45821325648414984)
:END:
In the 1830s, the factory owners lowered wages and the Lowell workers went on strike in 1834 and 1836 (though unsuccessfully), making them one of the first organized labor groups in the U.S

** Wages in factories were very low, and never raised despite the healthy benefits
:PROPERTIES:
:NOTER_PAGE: (2 . 0.30979827089337175)
:END:
who ever heard, of such a thing as their being raised again,” says the first speaker. “I confess that I never did, so long as I’ve worked in the mill, and that’s been these ten years.”
** That there is very little time for consumption
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6974063400576368)
:END:
The reason why, is because you are a rational, intelligent, thinking being, and ought to know enough to swallow your food whole; whereas a horse or an ox, or any other dumb beast knows no better than to spend an hour in the useless process of mastication.
** Factories allow for those without social standing to work and be not a burden to society
:PROPERTIES:
:NOTER_PAGE: (3 . 0.15273775216138327)
:END:
Namely, the many who have no home, and who come here to seek, in this busy, bustling “City of Spindles,” a competency that shall enable them in after life, to live without being a burden to society
** Conditions were brutal physically and emotionally
:PROPERTIES:
:NOTER_PAGE: (3 . 0.17291066282420747)
:END:
There are many things we do not like; many occurrences that send the warm blood mantling to the cheek when they must be borne in silence, and many harsh words and acts that are not called for.
** that there is very little intellectual independence
:PROPERTIES:
:NOTER_PAGE: (3 . 0.29971181556195964)
:END:
besides the clothing and feeding of the body is to be thought of; when the mind is to be clothed and fed
** That the promise of high wages are not delivered by the factory system
:PROPERTIES:
:NOTER_PAGE: (3 . 0.35590778097982706)
:END:
the practice of sending agents through the country to decoy girls away from their homes with the promise of high wages; when the market is already stocked to overflowing
** worker health is not protected, either
:PROPERTIES:
:NOTER_PAGE: (3 . 0.4337175792507204)
:END:
even then if the mind is enriched and stored with useful knowledge, it must be at the expense of health
** Parts of factor life considered "pleasant"
:PROPERTIES:
:NOTER_PAGE: (3 . 0.7680115273775215)
:END:
pleasant associations connected with factory life

* YAWP Market Revolution
:PROPERTIES:
:ID:       6E664BB7-1384-4AA8-8741-3DC9B99C1E5A
:NOTER_DOCUMENT: market_revolution_yawp.pdf
:END:
** That the idea of "advancement" is a universal concept in America
:PROPERTIES:
:NOTER_PAGE: (1 . 0.8741721854304636)
:END:
what one Baltimore paper in 1815 called an “almost universal ambition to get forward”
** Forces of the industrial revolution remade the nation and powered new developments while sparking the market revolution
:PROPERTIES:
:NOTER_PAGE: (2 . 0.11655629139072848)
:END:
Steam power, the technology that moved steamboats and railroads, fueled the rise of American industry by powering mills and sparking new national transportation networks. A “market revolution” remade the nation.
** Technology-driven market revolution drove vast commercialization and shifting away from self-sufficiency
:PROPERTIES:
:NOTER_PAGE: (2 . 0.23178807947019867)
:END:
More and more farmers grew crops for profit, not self-sufficiency. Vast factories and cities arose in the North. Enormous fortunes materialized.

... ironic, because self-sufficiency was the original goal
** Technology, by proxy, accelerates slavery?
:PROPERTIES:
:NOTER_PAGE: (2 . 0.36688741721854307)
:END:
As northern textile factories boomed, the demand for southern cotton swelled, and American slavery accelerated
** Transportation revolution allowed vast public advancement to the West (<>manifest destiny?)
:PROPERTIES:
:NOTER_PAGE: (5 . 0.280794701986755)
:END:
The so-called Transportation Revolution opened the vast lands west of the Appalachian Mountains.
** The proliferation of technology directly lead to the improvements of expansion and eentually globalization
:PROPERTIES:
:NOTER_PAGE: (6 . 0.4052980132450331)
:END:
If a transportation revolution began with improved road networks, it soon incorporated even greater improvements in the ways people and goods moved across the landscape
** Technological proliferation lead to economic proliferation
:PROPERTIES:
:NOTER_PAGE: (7 . 0.48344370860927155)
:END:
The ensuing web of rail, roads, and canals meant that few farmers in the Northeast or Midwest had trouble getting goods to urban markets.
** As a part of transportation rev., there was also communication rev which revolutionized transferrance of info
:PROPERTIES:
:NOTER_PAGE: (7 . 0.6556291390728477)
:END:
Such internal improvements not only spread goods, they spread information. The transportation revolution was followed by a communications revolution. The telegraph redefined the limits of human communication.
** The expansion of communication and transportation allowed the spread and nationalization of the market economy + expanded opportunities
:PROPERTIES:
:NOTER_PAGE: (8 . 0.13642384105960265)
:END:
They earned cash for what they had previously consumed; they purchased the goods they had previously made or gone without. Market-based farmers soon accessed credit through eastern banks, which provided them with the opportunity to expand their enterprise but left also them prone before the risk of catastrophic failure wrought by distant market forces.
