:PROPERTIES:
:ID:       203A2F1B-BD6D-4F2C-80BC-949A143A3E89
:END:
#+title: Are We Living in Guilded Age 2.0?
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Are We Living in the Gilded Age 2.0 _ - Edward T. O'Donnell.pdf
:END:
** :claim: The current praise for opulence is a mark of the guilded age
:PROPERTIES:
:NOTER_PAGE: (2 . 0.271523178807947)
:END:
where the opulence is unapologetic and the ranks of the hoi polloi can be seen swelling outside the gates
** Original guilded age is marked by poverty, rising inequality, and corportization of politics
:PROPERTIES:
:NOTER_PAGE: (2 . 0.3443708609271523)
:END:
period from roughly 1870 to 1900 marked by increased poverty, rising inequality and growing concern about corporate influence in politics.
** :claim: Guilded age had a sense of productive enthusiasm both by rising economy but also new tech
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6013245033112583)
:END:
Gilded Age enthusiasm was fueled not merely by the performance of the overall economy, but also by the new technologies it produced.
** Guilded age began the seperation of American social classes and lost of Republican values
:PROPERTIES:
:NOTER_PAGE: (3 . 0.19735099337748344)
:END:
That America was losing its republican character and becoming more like a European nation with a population of haves and have-nots locked into fixed classes.
** :claim: That, if there /is/ mass poverty, Republicanism has not fully suceeded
:PROPERTIES:
:NOTER_PAGE: (3 . 0.33112582781456956)
:END:
Note Whitman‘s reference to “surface successes.” He was urging his audience to look beneath the gilding to see the threat facing the nation.
** Wealth accumulated and concentraded in the Guilded age
:PROPERTIES:
:NOTER_PAGE: (3 . 0.4463576158940397)
:END:
By 1890, the top 1 percent of the U.S. population owned 51 percent of all wealth.
** In the guided age, there was a mark of admirement of the ultra-wealthy
:PROPERTIES:
:NOTER_PAGE: (3 . 0.9072847682119205)
:END:
As guests arrived to the mansion, surging crowds of lookey-loos had to be held back by police, like fans at a red-carpet premiere.
** Guilded age brought corporate lobbying
:PROPERTIES:
:NOTER_PAGE: (4 . 0.10993377483443709)
:END:
Industrialists used their influence to lobby lawmakers to adopt policies favorable to big business and hostile to organized labor.
** Bribery became used and meddled with in American politics
:PROPERTIES:
:NOTER_PAGE: (4 . 0.4291390728476821)
:END:
“There are two things that are important in politics. The first is money, and I can’t remember what the second one is.”
** As power consolidates, commoners' strikes became more common
:PROPERTIES:
:NOTER_PAGE: (4 . 0.56158940397351)
:END:
These include the first nationwide railroad strikes, the Great Uprising of 1877 and the Pullman Strike of 1894, both of which saw more than 100 people killed in clashes with police, state militia and federal troops.
** Guilded age also had an echo of anti-immigration, counter-terrirism, and nationalism
:PROPERTIES:
:NOTER_PAGE: (5 . 0.10993377483443709)
:END:
There was even concern about terrorism in the late-19th century, a threat associated with German anarchists and Irish nationalists
** Guilded age also included attempted political disinfranchisement
:PROPERTIES:
:NOTER_PAGE: (5 . 0.28211920529801326)
:END:
In the North in the 1870s, lawmakers in New York state tried unsuccessfully to strip voting rights from poor urban whites—a majority of them Irish and Irish American.
** Guilded Age also contained mass partisanship
:PROPERTIES:
:NOTER_PAGE: (5 . 0.4013245033112583)
:END:
The first Gilded Age was marked by intense partisanship, gridlock and presidential elections decided by razor-thin margins. Sound familiar?
** Guilded age was followed by Progressive progress
:PROPERTIES:
:NOTER_PAGE: (5 . 0.5059602649006623)
:END:
The original Gilded Age was followed by the Progressive Era (1900-1920), a period marked by a vast array of reforms that alleviated poverty, increased workplace safety, improved public health and education, restrained big business, adopted an income tax
