:PROPERTIES:
:ID:       69FA6AB3-929B-4246-A1A9-16B335076487
:END:
#+TITLE: Civil War
#+AUTHOR: Houjun Liu

* Two Focal Questions and Centering Points
- What /long term conditions/ contributed to the eruption of the Civil War?
- What /short term causes/ ignited armed conflict in 1861

> Is "Uncle-Tom's Cabin" a cause or a reflection of the civil war?

**Nothing in history in /inevitable/**. Its not inevitable that we had the civil war; Lincoln could have let the South seceded. 

* Conditions of War

** Geography
- Land and Climate
- Natural Resources
- Rivers & Coast

The North has worse geography, so they have diverse income and economics. The South has better geography, but then their economy is less diversified (focused on cotton, tobacco, sugar, etc.) Indigo was also an incredible crop in the south.

** Economic Development
- Northern states had lumber and trade => industrialization
- South had slave labor

** Demographics
- European Immigration is more popular in the North
- South's has heavy reliance on slave labor

** Slavery
- 3/5 Compromise
- Missouri Compromise
- Abolition Movement

*** Abolition
- Fugitive Slave Laws
- Emancipation: what to do with slaves? Do we free them into society
- Repatriation? The US created Liberia to send people back?

*** Uncle Tom's Cabin
Becomes best seller + heavily censored in the south

** Western Expansion
- Louisiana Purchase => leads into sentiments of manifest Destiny
- Missouri Compromise
- Mexican-American
- Kansas + Nebraska had mini civil-war over slavery

** Technological Changes
Industrial Revolution + Cotton 'Gin (1793).

** John Brown Raid
**John Brown* + his allies, including 5 African Americans capture federal arsenal at Harper's Ferry, VA.

** Elections
Lincoln swings the election, and wins the electoral college

** Ford Sumter
Ford Sumter protected the coastline, confederates creating a blockade by cutting off its supply. This marks the real beginning of the civil war.

"Nothing is inevitable until here."

* What If?
- **What if** Abe Lincoln fallen short of the electoral majority
- **What if** the north allowed the South to secede
- **What if** England and France had become more involved in the Civil War
- **What if** the South had survived the war intact

* Impending Crisis
[[id:A58FCD92-57A9-4C68-8AF9-FE0E95877DFF][Impending Crisis Reading]]

* Perspectives on Slavery

** Northern Arguments

*** Northern Sources
- Not directly anti-slavery, but just didn't want slavery to expand + did not want to partake
- Northerners against slavery because they think it against the economy

*** Impact of Slavery on Land
- Against bringing slavery to the new regions of the US, describing them to be free land
- If slavery is brought to the free land, it is no longer "free"
- Some Northerners were pro-division, who wanted the country to be divided
- Some believed the process of "slave-catching" to be a crime
- Talkes about delivering slaves to the south is a crime

*** Impact of Slavery on Economy
- That slavery is a dying institution as part of the capital
- That black people just needed to leave the country as a whole

** Southern Arguments

*** "States Rights"
- Feels like the process of abolishing slavery is abolishing
- William Haper downplayed slavery, and did not address the actual conditions of slavery
- Believes that the union simply want an easy solutions

*** Hiding the Want of Slavery
- Believes that the abolishment of the institution of slavery looses economic value

** Nat Turner
The process by which he murdered his master and also as a process by which they planned an insurrection. Realized the violence in the process of subjugation. 

Turner was a preacher, leveraging lots of religious allusion. Its important b/c there is 3 unique aspects of the reading: Turner provides a lot of detail and his reasoning.

- Provides intersection between religion and justification of slavery
- Counters the religious justification of slavery, and that slaves are preordained to rebel against their masters
- Sense of redeeming themselves

"Devil is being present is slave owners," that the classes should interchange. The process of killing

** Reflections
- Willmont provision: puts the conversation of slavery on every bill, did no 
- Douglass: slavery will die on its own eventually
- Turner: preacher that also leads rebellious

  
* Lincoln and Douglass

** Lincoln
Series of primary sources of his speeches, and letters to pro-slavery advocates.

- That skin color is an arbitutary justifications
- That the slavery is a bad look
- Founding farthers did /not/ want slavery permanently (all men are created equal)

That, even if support, all parts of the constitution could be changing.

- Lincoln did not argue for emancipation until later parts of the Source
- Slavery does not make sense if looking at skin colour, intellect, etc. (i.e. everyone who's dumber than someone else would therefore be their slave)
- Also anti-religious

Lincoln argued the insensibility of slavery. Kept having to clarify that he is not trying to completely get rid of slavery, also still don't think that the Black people should be full citizens.

Why did he free slaves:

- Encourages rebellions in the South
- Prevents the process of war
- Wishing Black men to join army

Also, Lincoln knows Douglass. Lincoln can't deny the articulation of Dauglass' history.

*** Civil War Strategy


** Douglass
- Douglass and Lincoln argued that slavery did not make sense
- Even in the lens of Christianity, Christianity could not support slavery

Douglass makes an emotional appeal against slavery. Douglass in religious, but does not support the Christianity that supports slavery. Struggling with his ideas of slavery: that if there is a god, why does it support slavery --- that it makes no religious sense in any grounds.


