:PROPERTIES:
:ID:       69FA6AB3-929B-4246-A1A9-16B335076487
:END:
#+TITLE: Civil War
#+AUTHOR: Houjun Liu

* Two Focal Questions and Centering Points
- What /long term conditions/ contributed to the eruption of the Civil War?
- What /short term causes/ ignited armed conflict in 1861

> Is "Uncle-Tom's Cabin" a cause or a reflection of the civil war?

**Nothing in history in /inevitable/**. Its not inevitable that we had the civil war; Lincoln could have let the South seceded. 

* Conditions of War

** Geography
- Land and Climate
- Natural Resources
- Rivers & Coast

The North has worse geography, so they have diverse income and economics. The South has better geography, but then their economy is less diversified (focused on cotton, tobacco, sugar, etc.) Indigo was also an incredible crop in the south.

** Economic Development
- Northern states had lumber and trade => industrialization
- South had slave labor

** Demographics
- European Immigration is more popular in the North
- South's has heavy reliance on slave labor

** Slavery
- 3/5 Compromise
- Missouri Compromise
- Abolition Movement

*** Abolition
- Fugitive Slave Laws
- Emancipation: what to do with slaves? Do we free them into society
- Repatriation? The US created Liberia to send people back?

*** Uncle Tom's Cabin
Becomes best seller + heavily censored in the south

** Western Expansion
- Louisiana Purchase => leads into sentiments of manifest Destiny
- Missouri Compromise
- Mexican-American
- Kansas + Nebraska had mini civil-war over slavery

** Technological Changes
Industrial Revolution + Cotton 'Gin (1793).

** John Brown Raid
**John Brown* + his allies, including 5 African Americans capture federal arsenal at Harper's Ferry, VA.

** Elections
Lincoln swings the election, and wins the electoral college

** Ford Sumter
Ford Sumter protected the coastline, confederates creating a blockade by cutting off its supply. This marks the real beginning of the civil war.

"Nothing is inevitable until here."

* What If?
- **What if** Abe Lincoln fallen short of the electoral majority
- **What if** the north allowed the South to secede
- **What if** England and France had become more involved in the Civil War
- **What if** the South had survived the war intact

* Impending Crisis
[[id:A58FCD92-57A9-4C68-8AF9-FE0E95877DFF][Impending Crisis Reading]]

* Perspectives on Slavery

** Northern Arguments

*** Northern Sources
- Not directly anti-slavery, but just didn't want slavery to expand + did not want to partake
- Northerners against slavery because they think it against the economy

*** Impact of Slavery on Land
- Against bringing slavery to the new regions of the US, describing them to be free land
- If slavery is brought to the free land, it is no longer "free"
- Some Northerners were pro-division, who wanted the country to be divided
- Some believed the process of "slave-catching" to be a crime
- Talkes about delivering slaves to the south is a crime

*** Impact of Slavery on Economy
- That slavery is a dying institution as part of the capital
- That black people just needed to leave the country as a whole

** Southern Arguments

*** "States Rights"
- Feels like the process of abolishing slavery is abolishing
- William Haper downplayed slavery, and did not address the actual conditions of slavery
- Believes that the union simply want an easy solutions

*** Hiding the Want of Slavery
- Believes that the abolishment of the institution of slavery looses economic value

** Nat Turner
The process by which he murdered his master and also as a process by which they planned an insurrection. Realized the violence in the process of subjugation. 

Turner was a preacher, leveraging lots of religious allusion. Its important b/c there is 3 unique aspects of the reading: Turner provides a lot of detail and his reasoning.

- Provides intersection between religion and justification of slavery
- Counters the religious justification of slavery, and that slaves are preordained to rebel against their masters
- Sense of redeeming themselves

"Devil is being present is slave owners," that the classes should interchange. The process of killing

** Reflections
- Willmont provision: puts the conversation of slavery on every bill, did no 
- Douglass: slavery will die on its own eventually
- Turner: preacher that also leads rebellious

  
* Lincoln and Douglass

** Lincoln
Series of primary sources of his speeches, and letters to pro-slavery advocates.

- That skin color is an arbitutary justifications
- That the slavery is a bad look
- Founding farthers did /not/ want slavery permanently (all men are created equal)

That, even if support, all parts of the constitution could be changing.

- Lincoln did not argue for emancipation until later parts of the Source
- Slavery does not make sense if looking at skin colour, intellect, etc. (i.e. everyone who's dumber than someone else would therefore be their slave)
- Also anti-religious

Lincoln argued the insensibility of slavery. Kept having to clarify that he is not trying to completely get rid of slavery, also still don't think that the Black people should be full citizens.

Why did he free slaves:

- Encourages rebellions in the South
- Prevents the process of war
- Wishing Black men to join army

Also, Lincoln knows Douglass. Lincoln can't deny the articulation of Dauglass' history.

*** Civil War Strategy


** Douglass
- Douglass and Lincoln argued that slavery did not make sense
- Even in the lens of Christianity, Christianity could not support slavery

Douglass makes an emotional appeal against slavery. Douglass in religious, but does not support the Christianity that supports slavery. Struggling with his ideas of slavery: that if there is a god, why does it support slavery --- that it makes no religious sense in any grounds.


* The Civil War

** Confederate Side
Robert E. Lee saw himself as a Virginian: he identified himself with the State first. This is very similar to the sense of identification today: that people identify themselves more as Republican/Democrat.

- Believes that defensive war is easier
- Knew that logistics were not on their side, but thought had values on their side

** Union Side
Ulysses S. Grant was the main general, and later president, of the United States of the North.

** Inequities: Compare and Contrast
"Despite the inequities favouring the North, the South almost pulled it off."

*** Advantages

**** North
- Food crops (the South was concentrated as cash crops) => population and food crops are pretty much actually matched
- Banks/economics
- Factories
- Horses!
- **Railroad Transportation**: enormous advantage for the North
  - Railroad companies

The Infrastructure much favored the North. Photography had played a big part in documenting the war.

**** South
- Most of the war was fought in South
- Mules!

President Jefferson Davis + VP Alexander Stevens => "Deo Vindice" (With God as Our Vindicator.)

*** Rail Lines

- Different gauges North vs. South
- Most of the West is rail tied to the Northeast, so the North could get food from the West
- Transportation in the South were much along the rivers
- Missouri becomes important state: "Wilson's Creek" --- controlling Missouri means controlling Mississippi

*** Resources

North had more....

- Workers
- Factories
- Money
- Muskets

** Geolocations
- When the war breaks out, Virginia Hillbilling people seperated and formed West Virginia
- Richmond + Wash. DC were very closed to each other, much fighting occured in the South
- South had a vast coastline, which the North attempts to blocade

** Who's Fighting this War?
- The Upper class hired substitute to fight war
- Much immigrants

- 48% Farmer
- 24% Mechanic
- 16% Laborer
- 5% Businessmen
- 3% Professional
- 4% Others

** "Anaconda Plan"
- Use Navy to create blockade and stop trade along coast
- Wrap around to divide the south: emphasis by blocking Mississippi
- "Sherman's March" --- cut through the south (burning what they oculd)

** "I Can Do It All!"
Lincoln wanted a knockout blow, but McClellan wanted a slow war that would save troops.

** Progress of War
- Battle of Bull Run
- Richmond became a battlefield and is under siege for the entirety of the war
- Has taking Missouri failed, the North would have cost its western flank which would have cut off the West from the North => the battle of Oak Hills won Missouri
- Battle of Ironclads: first ships armed with Ironclads; the Monitor vs. Merrimac. The Monitors could shoot the blocade runners
- War in the East: battle around the capital cities, both sides realized ethat there are lot of casualities

** Lincoln Excludes Emancipation from 2 States
- Border states allowed slavery
- Lincoln emancipated the Southern states' slaves to foment rebellion North
- Emancipation Proclamation didn't free any slaves
- African American recruiting 
- Southerners disheartened and terrified

** The Progress of the war
- South made a gambit: push into Maryland and get into Gettisberg
- Retreat to Cemetery Hill: roughly shaped like fishook and would easily hold the line
- Confederacy thought they have not lost a battle since then, to the point of ignoring the battlefield
- Little Roundtop hill changes the course for the civil war

Both armies lost ~23,000 solders; but Lee lost 60% of his army and Union lost only 1/3. At this point, the momentum swinngs the war.

- Vicksburg in the South falls in the Union, guaranteeing control of the Mississippi
- By 7/4, 1867, the momentum shifts
- Lincoln, wanting the end the war, institutes the draft again
- Riots began against the draft in New York --- Lincoln starts throwing protesters in jail
- Anaconda blocade causes Southern inflation: $6.45 worth of goods becomes $65.75
- Sherman cuts into the South, and brought huge emotional imact into the war
- Lincoln chooses a democrat as a Vice President (D-Tennessee Andrew Johnson) => appealing to both parties + Border States
- Surrender at Appomattox: Lincoln let the southern solders go home

** Casualties
- 620,000 Lives Cost: dramatic impact
- Lincoln was assassinated at Ford's Theatre: only 1 part of many plans
  - Lincoln
  - VP
  - Secretary of War
- Lincoln called "the last casualty of the civil war"


* Historiography documents
- [[id:78B72ED0-A29E-44B6-B3B6-8A1F0A0C6B01][Fauner's American Freedom]]  
- [[id:8592E00E-1E8F-458A-AC05-2C79BFC79289][Lincoln's Civil War Brilliance]]
- [[id:5EE2D837-2C20-4BB8-AE18-38926A078EBA][Fauner's Lincoln's View of Slavery]]  
- [[id:9F909304-A845-468A-974F-108DF85BE800][Faust]] 
- [[id:546782A8-BF13-430A-B3C5-2C81974F158C][Owen's Emancipation Strategy]] 
- [[id:A79220FB-67C9-4052-8B9C-C620B0B82BAB][Why Reconstruction Matters]] 
