:PROPERTIES:
:ID:       CBAEE4FF-BB18-4DFB-A3B3-F5A082743038
:END:
#+title: Evaluating the Progressive
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Evaluating the Progressive - Richard L. McCormick (Student Copy) (1).pdf
:END:
** That the process of reform was "convulsive": A
:PROPERTIES:
:NOTER_PAGE: (1 . 0.30357142857142855)
:END:
Convulsive reform movements swept across the American landscape from the I 890s to 1917.
** "Progressivsm" became a word that was shunned
:PROPERTIES:
:NOTER_PAGE: (1 . 0.5136054421768708)
:END:
Thelen perhaps exaggerated the point, but this much, at least, is true: there is a malaise among historians about the concept of progressivism and a growing urge to avoid the word itself whenever possible.
** That progressivism is often pained as being too positive
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6173469387755102)
:END:
Historians, being naturally wary of such value-laden terms, tend to seek a more neutral language that is better suited to imparti"al analysis
** That the liberal progressivem is a way of quelling discontent
:PROPERTIES:
:NOTER_PAGE: (2 . 0.15391156462585034)
:END:
They were not genuinely intended to uplift the disadvantaged, but rather to assuage guilty liberal consciences. And the devices upon which they relied, namely, expensive governmental bureaucracies,
** That progressives pivoted to the ceremonial fixes than those that are systemic
:PROPERTIES:
:NOTER_PAGE: (2 . 0.358843537414966)
:END:
progressives' attraction to "ceremonial," rather than .far. reaching, solutions by observing the reformers' own deep need to feel better about American society
** That liberals frequently invent problem and try to solve them
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5824829931972789)
:END:
But liberals often seem (and seemed) to occupy the foolish, middle position of alternately recognizing and denying the existence of basic social and economic divisions.
** Early 20th centry conservative reform is often messy
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6615646258503401)
:END:
historians are dissatisfied with the concep_t of progressivism is the awful complexity and diversity of early twentieth-century reform.
** One way to define "Progressives" as a product of business collaboration
:PROPERTIES:
:NOTER_PAGE: (3 . 0.21428571428571427)
:END:
a number of scholars have located the progressive impulse in the drive of newly formed business and professional groups to achieve their goals though cooperation and expertise
** Business collaboration model of progressivism is too heartless compared to the progressive agitation seen
:PROPERTIES:
:NOTER_PAGE: (3 . 0.336734693877551)
:END:
Hays's and Wiebe's organized, expert progressives seem too bland, too passionless, and too self-confident to have waged the frantic battles many reformers did.
** Perhaps the disorganization of progressivism is because progressivism doesn't exist, so we need to ignore this framing
:PROPERTIES:
:NOTER_PAGE: (3 . 0.48384353741496594)
:END:
Filene proposed th e more drastic response to the complexity of progressivi sm: abandon the concept of a progressive movement.
** To understand progressivsm, we first need to define the underlying trend across all progressive reforms: B
:PROPERTIES:
:NOTER_PAGE: (4 . 0.20408163265306123)
:END:
The first is to identify the basic characteristics that were common, in varying measure, to many (and probably most) progressive reforms.
** Progressives solidified big business, while improving the conditions of industrial life
:PROPERTIES:
:NOTER_PAGE: (4 . 0.35714285714285715)
:END:
They undertook reforms not to dismantle modem industry and commerce but rather to improve and ameliorate the conditions of industrial life.
** Nevertheless, progressives often took issue with the wrongdoings of big industry
:PROPERTIES:
:NOTER_PAGE: (4 . 0.4030612244897959)
:END:
Outpourings of anger and dismay about corporation wrongdoing and of suspicion for industrial values frequently punctuated the course of refom
** Progressives wanted overall control over their governements
:PROPERTIES:
:NOTER_PAGE: (4 . 0.5518707482993197)
:END:
Progressive intellectuals, as well as popularizers, produced a vast literature denouncing laissez-faire and affirming the capacity of men and women to better their conditions.
** Progressives wanted to work independently of govn't originally, but realised that most reforms relied on governmental support
:PROPERTIES:
:NOTER_PAGE: (4 . 0.7015306122448979)
:END:
most progressives preferred to work through voluntary associations for non­ coercive improvements in economic and social conditions. As time passed, how­ ever, more and more of their reforms relied on the hand of government.
** Progressivism came from evangelical protestants and natural/social sciences
:PROPERTIES:
:NOTER_PAGE: (5 . 0.11819727891156462)
:END:
Progressivism took its inspiration, as well as much of its substance and
technique, from two bodies of belief and  knowledge: evangelical Protestantism
and the sciences, both natural and social.
** Progressivism was the first universal reform momevent
:PROPERTIES:
:NOTER_PAGE: (5 . 0.5943877551020408)
:END:
Finally, progressivism was the first (perhaps the only) reform movement to be
experienced by the whole American nation.
** Traditionally, it is believed that what was agitated for was the goal and once the agitation was achieved the goal is too: C
:PROPERTIES:
:NOTER_PAGE: (6 . 0.21003401360544216)
:END:
Older interpretations of progressivism implicitly assumed that the rhetoric explained the goals and that if a reform became law the results fulfilled the intentions behind it.
** Public involvement and regulations became much more rampant in the 1900s
:PROPERTIES:
:NOTER_PAGE: (7 . 0.14030612244897958)
:END:
public officials became widely involved in monitoring and regulating how people lived and worked
** Although the call te reform were always in moralistic language, the true purpose were often much more complicated
:PROPERTIES:
:NOTER_PAGE: (7 . 0.7470288624787775)
:END:
Commonly the progressives presented their plans in moralistic, democratic language, but often the true purposes of many reformers were more complicated.
** By the end of the progressive era, there became more regulation on political parties, and voting turnout was lower
:PROPERTIES:
:NOTER_PAGE: (8 . 0.7028862478777589)
:END:
Political parties had been regulated. and the active electorate had become relatively smaller and less enthusiastic.
** There were good and bad components of the new system, and no clear "progressivism": D
:PROPERTIES:
:NOTER_PAGE: (9 . 0.1468590831918506)
:END:
Voting had become more difficult for many (especially blacks and ew immigrants), but for others new avenues of political participation had opened.
** That the progressive enforcement of uniformity upon diversity was actually threatening the health of a community
:PROPERTIES:
:NOTER_PAGE: (10 . 0.1731748726655348)
:END:
Numerous social reforms of the early twentieth century expressed the progressives' desire to impose uniform living habits on a culturally diverse population whose behavior sometimes seemed to threaten the morality and health of the community.
** Example of uniforminy in action and mind is demonstrated by prohibition
:PROPERTIES:
:NOTER_PAGE: (10 . 0.2609271523178808)
:END:
The prohibition of alcoholic beverages was perhaps the prototypical reform of this type .
** Although: inability to fufill promised reform is not unique to progressivism
:PROPERTIES:
:NOTER_PAGE: (11 . 0.4074702886247878)
:END:
The failure of reform to fulfill all of the expectations behind it was not, of course, unique to the Progressive era.
** Progressive insistence on modernity actually hindered them: E
:PROPERTIES:
:NOTER_PAGE: (11 . 0.699490662139219)
:END:
Often their methods worked, but often progressive programs simply did not prove capable of accomplishing what had been expected of them.
** Scientific data collection quantified the degree of failure
:PROPERTIES:
:NOTER_PAGE: (11 . 0.7563667232597623)
:END:
Worse, the progressives' scientific reforms frequently involved the collection of data, making it possible to know just how far short of success their programs sometimes fell
** Progressives also disregarded the consiquences of industrialization
:PROPERTIES:
:NOTER_PAGE: (12 . 0.13412563667232597)
:END:
progressives' deep ambivalence about industrialism and its consequences.
** That progressivism failed because it is promising too much
:PROPERTIES:
:NOTER_PAGE: (13 . 0.30135823429541597)
:END:
it is important to recall how terribly ambitious were the reformers' stated aims and true goals. They missed some of their marks because they sought to do so much
