:PROPERTIES:
:ID:       45CE0E4A-0798-4D37-BA60-535F2F1B9C29
:END:
#+title: Forced Founders: Holton
#+author: Houjun Liu

* Biographicals
Written by Woody Holdon. Historian on USC.

* Claim
The leads who lead the revolution that were influenced by grassrules movement (pg 1)

#+begin_quote pg1
Small farmers exerted direct ... pressure onto the gentlemen.
#+end_quote

1. Virginians --- land speculators --- were interested to push the frontiers => this was contented by the British => sparked rebellion
2. Virginians interested in commercial boycotts => wanted to reduce debt to British merchants

That the non-elites affected the elite groups; which is hard to justify as most of the sources are from the gentlemen population: that the non-elites would deceive the eleties, and eleties' perspective would be deceived.

Looking at Freedom Struggles

1. landspectors vs indians
2. tobacco growers vs. mechanst and the palaments

* Landspectors vs. Indians
:PROPERTIES:
:ID:       295F2860-F4BA-439D-837E-2727BBB2650F
:END:
Land was used as a trading agreement, upon which the elites could build their empire. Also, owning land is also used as an negotiation tool. George Washinton wanted to move further inland: provided better opportunities for farming.

Internal struggles of the Indians made it easier for Americans to move in and build further inland. Colonists pushed further inline. The proclamation line, which was meant to ensure overall safety, actually mode more discord.

Theme --- the viability of [] influenced inter-indian colonists: that colonists, Indians, and Britian were all fighting over the same line.

* Colonists Tobacco Growers vs British Merchants
:PROPERTIES:
:ID:       E8B81379-493C-4120-B8ED-C2F25F7D9F9E
:END:
All focused on the elite class.

The gentry of the US relied upon Profit, and people were angry at the loss of trading. An anti-middlemen sentiment became an anti-(British) merchants sentiment.

Over time, colonists achieved debt and a trade deficit, which then started resenting the Parliament (contrast to [[id:7BE0BFCA-1FCB-46EA-A1CB-F68822612F77][Baylin]]). They, of course, used a lot of language relating to slavery.

Leading Virginians fueled the Revolutionary ideals, which would acquire bigger independence.

#+begin_quote
The American Revolution was a class conflict between tobacco growers and British merchants, combined with the royal navy.
#+end_quote

* On Slavery
Jefferson's denouncement of slavery: not so much morals as per economic impact (to prevent debt).

Much of the propaganda mentioned America as being "enslaved" by Britian: the image of the /enslaved/ worker, specifically, the navigation act. British manipulation of colonists' commerce turned them into the "slaves" of Britain.

Wanted to end the slave /trade/: although it corresponds to the ending of slavery in Britain, was simply an act that secures the monopoly

* Critiques
1. Undermined his own argument by speaking on their economic situations, which they are doing out of essentially personal gain
2. Started with one claim, and built it up with reasoning for why its true
   

Revolution as a process to "free" one of the debts. It's almost ironic.


