:PROPERTIES:
:ID:       9F909304-A845-468A-974F-108DF85BE800
:END:
#+title: Faust
#+author: Houjun Liu

* Faust
28th president of Harvard.

* Claim
In order to move forward and make process as a nation, people had to move forward and deal with war. Had to deal with the more complicated real situation and had to deal with conflicts as a whole: was trying to convince themselves that they had a goal and something had to be done.

Up to the point, it was the biggest conflict of casualties. Gurilla warfare: there were a lot of woman and children + shortage of food in the south that brought starvation.

Discussed what factors lead to the high amount of casualties. There was a lot of really efficient weaponery: leveraged in a war that was outdated and society that was outdated. Therefore, the count of death is really large.

This war turned from looking fancy and procession to simply trying to survive. This position was not possible and was willingly walking into the scenario. Industrialized "modern" warfare: through that barbarity.

Question "how does society get through brutal warfare." There was a lot of death due to disease due to the civil war: death and religion are closely connected.

The source talked about the existance of a common religiosity: people came together in one identity and tried to justify themselves getting involved with the war. They would like to deal with it so that they could form the narrative to justify this level of sacrafise.
