#+TITLE: French and Indian War
#+AUTHOR: Houjun Liu

An extension upon [[file:KBhHIST301ColonialAmerica.org][Colonial America]]. 

* Background...
The title of something illuminates the perspective.

- British Name: =French and Indian War=
- French Name: =7-Years War= (oh yeah btw this war does not last 7 years)

This war manifests themselves between the French and the British so each other calls themselves against each other.

Also, remember this: the only thing worth going to war about is... well.. MONEY.

* Tensions Brewing

** Benign Neglect: system of British rule
Everything goes into Indian Colonies. Colonists continually spread west looking for land, and exercises a policy of...

/Benign neglect/: rule as long as production continues, but act autonomously 

** Albany Plan: beginning to colonial unity
**Albany Plan**: colonies would unite to address western-frontier

- Crown rejects plan because feared colonial unity
- Colonies reject plan because feared loosing autonomy

And so, it collapses.

* British and French War Setup 
Lot's of fighting around the St. Laurence River with the French, which the crown believes the colonies would support. The French, then, ceded a crap tonne of land after the war to the British.

** The Proclamation Line of 1763
But! The dividing line between newfound British (prev. French) territory was drawn: named **Proclamation Line** --- shoved the colonizers at their old place just to avoid conflict with the Indian allies.

The colonists are pissed off by the British decision (like, they fought a war, and like they can't use the land? smh)

This, of course, this is one of the seeds of the American Revolution: it's really about land, and really about that resources

*** Changes Instituted by the Proclamation Line
- Patriot, pre-1763: Crown-loving (loyalists)
- Patriot, post-1763: Anti-crown

*** Quartering
To keep troops to protect the frontier, the crown decide to make people "quartered" at people's home.
