:PROPERTIES:
:ID:       78B72ED0-A29E-44B6-B3B6-8A1F0A0C6B01
:END:
#+title: Fauner's American Freedom
#+author: Houjun Liu

* Thesis
Idea of freedom, which is integral to national identity, continually changes throughout the war especially w.r.t.

* Evidence

** Pre-war

*** Freedom for the North
pg. 10 Freedom of each man to enjoy what they do and produce what they do

*** Freedom for the South
pg. 10 Freedom to leverage what other men do and to gain profit from them

** Post-war

*** Former Slaves
Freedom meant escaping injustices slavery and reaping American Society

*** Freedom for the White Southerners
Freedom believes to the ability to maintain their property

** Page 12
- "freedom" => starting to transition to thinking about emancipation
- at any given time, the definition of freedom is conflicting
- We see freedom as not a rebirth but as a swell
- Antibellium era swells an anti-institutionalization view
- Patriotism = sense of unconditional loyalty to whomever is in office
- Art Pieces treated as primary sources: Douglass photograph pg. 18 --- Douglass in his art could subvert racist portrays

** Post freedom
Without ownership of property, freedom would be impossible. Republicans saw emancipation as a process that restores African American men to power in their household. It fixes the dominant understanding of economic freedom as a right of property ownership.

** Freedom
"The author says having both sides fighting for freedom is a uniquely American idea" --- Adam. Southern plantation wanted to maintain their "way of life"
