:PROPERTIES:
:ID:       5EE2D837-2C20-4BB8-AE18-38926A078EBA
:END:
#+title: Fauner's Lincoln's View of Slavery
#+author: Houjun Liu

A summary of Will Rush...

Lincoln carried some abolitionist values but never aligned himselve in anti-slavey party.

- Lincoln is anti-abolition was originally not a morality point, but instead wanted to just stick to America's founding creed
- Lincoln was "pushed" through the abolitionist/emancipatory stance
- Lincoln downplayed slavery to not think it was degrading to them

He was trying to better the economy by abolishing slavery. Not too much critiques of the work --- dismanting complicated figures who get glorified and oversimplified by history. that ---

"these characters from history are human beings, and that they changes with the context with their time". We have a tendency to villify and deify 

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Reader Civil War & Reconstruction.pdf
:END:

** Foner argues that Lincoln is quintessentially American
:PROPERTIES:
:NOTER_PAGE: (33 . 0.21059602649006623)
:END:
perhaps the quintessential American

** Foner attempts to place Lincoln in context
:PROPERTIES:
:NOTER_PAGE: (33 . 0.3165562913907285)
:END:
tries to explain Lincoln in the larger context of the time in which he lived

** Argues that Lincoln was a figure that evolved with the evolution of America
:PROPERTIES:
:NOTER_PAGE: (33 . 0.33245033112582784)
:END:
there is no single moment or single quote that can represent Lincoln’s evolving position on slavery, instead Lincoln’s greatness was his capacity for growth as the nation wrestled with its original sin.

** Lincoln at first was not an abolitionist
:PROPERTIES:
:NOTER_PAGE: (33 . 0.43973509933774835)
:END:
he at first stood at odds with abolitionism, willing to confer with abolitionist leaders but unwilling to count himself among their membership

** Lincoln did not argue for equality, but instead used a constitutionally-following argument
:PROPERTIES:
:NOTER_PAGE: (33 . 0.5046357615894039)
:END:
based on natural rights and the U.S. Constitution with the idea that the races didn’t need to be equal but that slavery violated the natural right

** :claim: Lincoln was a patriot that disregarded his (moral) believes in favor of constitutional fairness
:PROPERTIES:
:NOTER_PAGE: (33 . 0.5602649006622517)
:END:
Lincoln was opposed to slavery not on the grounds of moral, political, or religious impetuous, but rather because he saw slave labor as theft in violation of the Nation’s founding creed.

** Civil war push Lincoln into ultimate abolitionism
:PROPERTIES:
:NOTER_PAGE: (33 . 0.6847682119205298)
:END:
he tied the survival of the Union to the death of slavery

** That Lincoln morphed into having impact
:PROPERTIES:
:NOTER_PAGE: (33 . 0.7377483443708609)
:END:
Lincoln as a man who grew to have such an enormous impact
