:PROPERTIES:
:ID:       33247E45-65A4-4DFD-B722-B01E4DE3FC95
:END:
#+title: Guilded Age Presos
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Gilded Age Presentations Block 3.pdf
:END:
** Oil drilling advancement created boom in industry, and created the opportunity for businessmen
:PROPERTIES:
:NOTER_PAGE: (14 . 0.30600461893764436)
:ID:       E798EE2C-3DC0-44EF-AF32-11FBBC952534
:END:
Drake's drilling technique was able to tap oil repositories originally thought impossible to extract oil from. In a manner similar to that observed during the gold rush, people on the fringes of society and experienced businessmen alike rushed to take advantage of this development.
** Technology enabled corporatization
:PROPERTIES:
:NOTER_PAGE: (16 . 0.27136258660508084)
:ID:       C61D9FA4-9D15-4AA2-9F86-5E190C4BD119
:END:
As companies grew, more and more employees needed to work in urban areas as opposed to rural areas, and skyscrapers provided a high density of office space. The availability of modem building materials such as cast iron and steel and the technological advancement of steel skeleton buildings enabled the construction of stable, tall vertical spaces.
** Skyscraper technology also caused financial and corporate boom
:PROPERTIES:
:NOTER_PAGE: (18 . 0.7378752886836027)
:ID:       DF5B17DD-CBC6-410A-87D8-00A888A6E97A
:END:
The capital-intensity and technological intricacies of skyscraper construction were unachievable for small construction firms. This led to the development of large general contracting firms that had both the personnel, capital, and technology to successfully erect skyscrapers.
** Scientific development bent into theory for social change
:PROPERTIES:
:NOTER_PAGE: (24 . 0.5739030023094688)
:ID:       65276E43-BBB5-4AD8-A462-F9C5ED6EEBC5
:END:
He initially used Social Darwinism as a theory in order to advocate for laissez-faire economics and the government lessening economic restrictions, like taxation
