:PROPERTIES:
:ID:       FF80B946-C392-455D-9EAD-A831DDDF87E5
:END:
#+title: Guilded Age Primary Sources
#+author: Houjun Liu

* Reading Notes: Child Labor
:PROPERTIES:
:NOTER_DOCUMENT: On Child Labor - The Labor Standard (1877).pdf
:END:

** That the process of value production is emotionless
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6719576719576719)
:END:
Among all these 300, although I was with them for hours, I did not hear a laugh or even see a smile.

** Sense of wastefulness of youthhood
:PROPERTIES:
:NOTER_PAGE: (1 . 0.75)
:END:
forty boys are picking their lives away.

** That there is a sense of sadness of lives wasted by industrialization
:PROPERTIES:
:NOTER_PAGE: (1 . 0.8677248677248677)
:END:
It is a painful sight to see the men going so silently and gloomily about their work, but it is a thousand times worse to see these boys.

** Deathrates are shockingly high
:PROPERTIES:
:NOTER_PAGE: (2 . 0.10331125827814569)
:END:
another result I found in a little miners’ graveyard, beside a pretty little church, where more than every other stone bears the name of some little fellow under fifteen years of age

** That child workers are shut away from the "civilized" qualities of the world
:PROPERTIES:
:NOTER_PAGE: (2 . 0.20794701986754968)
:ID:       83723888-C66F-40F1-9646-103A1307849F
:END:
for there they can make more money. Not three boys in all this roomful could read or write. Shut in from everything that is pleasant, with no chance to learn, with no knowledge of what is going on about them

** That compaines, due to mine accident, have subjugated the busing fees
:PROPERTIES:
:NOTER_PAGE: (2 . 0.20927152317880796)
:END:
Sometimes, after the boys have got to the mine, they find that some accident has stopped the work; then they have nothing to do for the day and get no pay.

** Sometimes, due to busing fees, there can be reverse debt
:PROPERTIES:
:NOTER_PAGE: (2 . 0.27947019867549666)
:END:
that his indebtedness to the company for railroad fares is some dollars more than the company’s indebtedness to him for labor


* Reading Notes: Rockefeller 
:PROPERTIES:
:NOTER_DOCUMENT: Testimony before the U.S. Industrial Commission - John D. Rockefeller (1899).pdf
:END:

** Claims that Standard Oil had made made material sacrafices to modernise and expedite
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6940397350993377)
:END:
It has sought for the best superintendents and workmen and paid the best wages. It has not hesitated to sacrifice old machinery and old plants for new and better ones.

** That corporations are the natural ending state for large-growning partnerships
:PROPERTIES:
:NOTER_PAGE: (1 . 0.8052980132450331)
:END:
The business may grow so large that a partnership ceases to be a proper instrumentality for its purposes, and then a corporation becomes a necessity

** Blames the need for multi-state incorporation upon incapatible state laws
:PROPERTIES:
:NOTER_PAGE: (1 . 0.8860927152317881)
:END:
Our Federal form of government, making every corporation ere- ated by a State foreign to every other State renders it necessary ... [to] organize ... in ... different states

** That the expansion of pipelining is an enviromental concern
:PROPERTIES:
:NOTER_PAGE: (2 . 0.15405046480743692)
:END:
and the forests of the country were not sufficient to supply the necessary material for an extended length of time.

** Reductionistic argument that there needed to be a corporation in every state through which the pipeline passed
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2390438247011952)
:ID:       5DB11E2E-3047-4B2A-814C-565436D7DBFE
:END:
To operate pipe lines required franchises from the States in which they were located, and consequently corporations in those States,
** Claims that multi-state industrial combinations are necessary
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2682602921646746)
:END:
It is too late to argue about advantages of industrial combinations. They are a necessity.

** Arguing that expansion requires multi-corporation collaboration
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2895086321381142)
:END:
And if Americans are to have the privilege of extending their business in all the States of the Union, and into foreign countries as well, they are a necessity on a large scale, and require the agency of more than one corporation.

** Claims that Americans are well-paid for their labour
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5298804780876494)
:END:
eceiving in return therefor from foreign lands nearly $50,000,000 per year, most of which is distributed in payment of American labor.

** That antitrust would be a hinderance to progress
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6334661354581673)
:END:
legislators will be blind to our best industrial interests if they unduly hinder by legislation the combination of persons and capital requisite
