:PROPERTIES:
:ID:       EB6239BC-7258-4942-AE73-66A9806949F0
:END:
#+title: Green death
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Green Death in the Haymarket.pdf
:END:
** Socialism as the initial fuel for uprising
:PROPERTIES:
:NOTER_PAGE: (1 . 0.35281615302869285)
:END:
socialist agitators took to the streets all over the North and West sides
** Established the idea of the non-working class, "tramps"
:PROPERTIES:
:NOTER_PAGE: (1 . 0.7396386822529224)
:END:
"dangerous class of vagrants called ‘tramps’ who would prefer to beg or steal than to work.”
** The jailing of police superindendent reduced public confident
:PROPERTIES:
:NOTER_PAGE: (1 . 0.7927736450584484)
:END:
However, these arrests did little to increase citizens con­ fidence in the police department, whose former superintendent had been jailed on corruption charges
** Gun industry monetized the want for protection via distrust in police
:PROPERTIES:
:NOTER_PAGE: (2 . 0.06623931623931624)
:END:
The Western Gun Works offered a solution: a new lightweight, silver-plated pistol made of the best English steel with a rifled barrel.
** Distriction began being drawn between true poverty and "dishonest" poverty
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5299145299145299)
:END:
The publisher, who cared deeply about the quality of life in his city, loathed Irish ward heelers and saloonkeepers, gamblers and socialist rabble-rousers, but he knew “honest poverty” when he saw it.
** Immigrants are labelled as "invisible"
:PROPERTIES:
:NOTER_PAGE: (2 . 0.7692307692307693)
:END:
huge, largely invisible cotnmunity of immigrant working people, embers of anger and frustration smoldered that summer.
** Immigration and resistance to Americanization as a part which caused dissenting sentiments
:PROPERTIES:
:NOTER_PAGE: (3 . 0.3122994652406417)
:END:
These immigrants also clung to their cultural, social and linguistic heritage with “a tenacity that resisted easy Americanization.”
** Immigrant-based "Free-thinkers" and benevolent societies eventually lead to the first societies
:PROPERTIES:
:NOTER_PAGE: (4 . 0.11538461538461539)
:END:
When lumberyard owners cut the wages of common laborers from $1.50 to $1.25 a day, the Bohemians reacted to the blow as a community
** Socialist sensiments were being cultured feasting from the failure of organised labour
:PROPERTIES:
:NOTER_PAGE: (5 . 0.4166666666666667)
:END:
THE SOCIALISTS WERE indeed busy cultivating their party that spring.
** The election win of republicans overshadowed the development of socialism
:PROPERTIES:
:NOTER_PAGE: (6 . 0.2898395721925134)
:END:
Still, Chicago’s top business and political leaders had no reason to notice a few hundred votes tallied by the socialists, because these elites were celebrating the reelection of a Republican mayor
** Insurgency intensified when lives are put on the line
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6459893048128342)
:END:
was one of the first to notice the reports of workers blocking trains in West Virginia, strikers plundering an armory in Maryland, scores of “insurgent camp fires”
** The "sucess" of strike and struggle deemed as infectious
:PROPERTIES:
:NOTER_PAGE: (7 . 0.5358288770053476)
:END:
rergrTof terror prevailed” and that “riot fever” was spreading west.
** Independent strikes pictured as one homogeous group
:PROPERTIES:
:NOTER_PAGE: (7 . 0.6855614973262032)
:END:
The next day freight handlers on the Illinois Central Railroad struck and marched through other Chicago yards and shops calling others out to join them. The evening Tribune simply proclaimed: “It Is Here.
** Used sexism to justify workmen rights
:PROPERTIES:
:NOTER_PAGE: (7 . 0.8117647058823529)
:END:
“Working men of Chicago! it began “Have you no rights?—No ambition?-—No Manhood?
** Citizen militia (still independently organized groups) told to put down
:PROPERTIES:
:NOTER_PAGE: (9 . 0.10138740661686234)
:END:
That afternoon fire bells rang all over the city, calling the militia to their armories, and that evening Civil War veterans met to form volunteer companies under the command of former army generals
** Police presece still won out
:PROPERTIES:
:NOTER_PAGE: (9 . 0.42369263607257207)
:END:
By the end of the day, however, Workingmen’s Party activists were laying low after being driven from the streets by the police
** Political messaging of event was subsumed by disorderly warfare
:PROPERTIES:
:NOTER_PAGE: (10 . 0.26844919786096255)
:END:
The significance of the work stoppage was overshadowed, however, by warfare that resumed along Halsted Street.
** Gender difference highlighted as a figure of disorderlyness
:PROPERTIES:
:NOTER_PAGE: (10 . 0.532620320855615)
:END:
It was TERROR’S REIGN, according to the Chicago Times, and a sure sign of it was the presence of wild women in the crowd.
** "Sent out to suppress rioters, the police became rioters themselves."
:PROPERTIES:
:NOTER_PAGE: (11 . 0.5358288770053476)
:END:
Sent out to suppress rioters, the police became rioters themselves.
** Business people attained a vested interest in security
:PROPERTIES:
:NOTER_PAGE: (12 . 0.2689434364994664)
:END:
Chicago’s richest man, Marshall Field, would donate thousands to purchase arms and would insist the money be invested in constructing fortresslike armories.
** Automated radicalism is encouraged
:PROPERTIES:
:NOTER_PAGE: (13 . 0.22305229455709713)
:END:
Thes e radicals were encouraged not only by the mil- itaficyoTthe strikers but by the behavior of hundreds of city dwellers who joined the workers in a series of community uprisings that expressed long-standing grievances
** Civil Millitias actually encouraged further protests
:PROPERTIES:
:NOTER_PAGE: (13 . 0.5731056563500534)
:END:
the massive use of the militia and the U.S. Army to suppress civil protest.
** Governmental systems actively working against workers
:PROPERTIES:
:NOTER_PAGE: (15 . 0.7286324786324787)
:END:
The superintendent then opened a spring latch door, shoved Parsons into a dark hallway and whispered in his ear, “Take warning.
** Definance marked the organization of Parsons
:PROPERTIES:
:NOTER_PAGE: (16 . 0.546524064171123)
:END:
The Board of Trade was not going to drive Albert Parsons out of Chicago. Within a month after his ordeal, he would be back on the streets, campaigning for the Workingmen’s Party.
