:PROPERTIES:
:ID:       322169B4-822C-4295-8193-73AE483142C3
:END:
#+title: Guilded Age Terminology
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Gilded Age Terminology.pdf
:END:
** Renaming the Guilded Age brings with it the removal of many literary traditions
:PROPERTIES:
:NOTER_PAGE: (1 . 0.2059447983014862)
:END:
Since I admire Mark Twain, who famously coined the term in a novel that he cowrote with Charles Dudley Warner, such a suggestion feels disloyal if not downright un-American.
** Despite the traditional guilded age narrative, the government of the time was not actually completely stagnent
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6029723991507431)
:END:
Despite the persistent idea that government stagnated before 1900, recent scholarship shows that the late nineteenth century was by no means an era of laissez faire.
** Instead of the traditional stagenation->progressive analysis, we can increase the timescale and look for broader themes
:PROPERTIES:
:NOTER_PAGE: (3 . 0.5997876857749469)
:END:
we could step back and look for themes and threads extending across the entire period between 1877 and 1920, or perhaps even 1932.
** :claim: that the "Long Progressive Era" was marked by growing pains of government expansion
:PROPERTIES:
:NOTER_PAGE: (3 . 0.7101910828025477)
:END:
What did mark the Long Progressive Era was a diverse, creative array of proposals for expanding government power and institutional capacity.
** The discontinuity and shift in perspective could be accounted for be the 1890 depression
:PROPERTIES:
:NOTER_PAGE: (4 . 0.14118895966029724)
:END:
Discontinuities within the period could be acknowledged if we identified an Early Progressive Era, running from about 1880 to 1894, and a Late Progressive Era, roughly dating from 1894 to 1920. What divided these was the cataclysmic depression of 1890s
** That social and economic inequality has always been a thing in America
:PROPERTIES:
:NOTER_PAGE: (4 . 0.39808917197452226)
:END:
New Gilded Age" would have to confront the fact that social and economic inequality, selfish uses of wealth, and indifference to the poor have characterized most eras of U.S. history, not just the first three decades after the Civil War.
** Nineteeth centruy historians does not have a clear definition of what a "guilder" is
:PROPERTIES:
:NOTER_PAGE: (5 . 0.2908704883227176)
:END:
istorians of the late nineteenth century, in contrast, have failed to reach a consensus as to what to call its dramatis personae, let alone what made them distinctive.
** There is no clear "good" "bad" value judgement in terms relating to business, and the "guilded age" was the only one main true pejorative
:PROPERTIES:
:NOTER_PAGE: (6 . 0.3174097664543524)
:END:
The phrase "Gilded Age," it is worth remembering, is the only widely used periodization that is unambiguously pejorative
** Wealth and oustentation was a long-standing issue
:PROPERTIES:
:NOTER_PAGE: (6 . 0.5084925690021231)
:END:
Yet did this really set them apart from businesspeople in the early republic? Or, for that matter, did it distinguish them in a fundamental way from wealthy Americans in any decade from the seventeenth century to the present?
** Age of Industrialization is a neutral term that's more suitable
:PROPERTIES:
:NOTER_PAGE: (7 . 0.1464968152866242)
:END:
Richard would banish the misleading and rather gaudy adjective "Gilded," replacing it with, as I understand him, something like the Age of Industrialization.
** Titling as "the guilded age" primes the reader incorrectly
:PROPERTIES:
:NOTER_PAGE: (7 . 0.2494692144373673)
:END:
Titles tell the reader what to expect within the text and, because the author anticipates that expectation from the reader, they become a kind of sieve or filter when the author goes about gathering and synthesizing material for that text.
** Individual progressivism no longer have a use after society became wholly progressive
:PROPERTIES:
:NOTER_PAGE: (8 . 0.7303609341825902)
:END:
That is why, in so many surveys, "the Populists just up and died" after 1900. Those historians who call the Progressive Era their home have had no use for the Populists
