:PROPERTIES:
:ID:       F5BB3FDC-3211-4D50-A152-E0B7D43F1EF5
:END:
#+TITLE: Guilded Age
#+AUTHOR: Houjun Liu

This is the index note to the Guilded Age.

* Reading Notes
- [[Reading:203A2F1B-BD6D-4F2C-80BC-949A143A3E89][Are We Living in Guilded Age 2.0?]] 
- [[id:89A5BB23-7307-4BF5-8432-F3DFBB139A6C][American Colossus]]
- [[id:EB6239BC-7258-4942-AE73-66A9806949F0][Green death]] 

* Context
Guilded Age: 1877-1900.

- Deepened divide in racism
- Deepened split between poor and rich
- Fluidity of social classes became more set

** Issues of the Guilded Age
- Balancing the problems of Late-State capitalism
- Sense of anger towards others' who don't give back
- Racial inequality and injustice

** Why "Guilded"?
Guilded: Outside Lined with Gold, Inside Contains Metal and is Less Valuable.

The Guilded Age consists of three different sections:

- Business (Top!)
- Labour
- Government

The Guilded Age is the most rapid expansion of change in America; it is the time when industrialization affect every aspect of America. Influences:

- Industrialization
- Immigration
- Urbanization
- Corruption

* Background: Civil War & Modern America
There are three pieces

- "Homestead Act": legal way to give people land in the west
- "National Banking Act": unified a uniform economic system, and to connect markets
- "Pacific Railroad Act": expansion of connection; also formed the first "Corporations" based on railroad organization structures.

* Issues of the Guilded Age

** Immigration
"They are coming to take our jobs!" (Irish Edition.)

USCIS processed people in Ellis (Irish processing, took about 2 days to process) and Angel (Chinese processing, took about 6 /months/ to process) islands: beginning having racial immigrant discrimination.

** Urbanization
Populations in the United States tripled in about 50 years. Immigrants were stuffed into Tennaments. The Guilded age saw the beginning of skyscrapers.

** Social Activism
Because of the issues began during the Guilded Age, more people essentially stepped instead of the governement to play a role in supporting welfare.

** Industrialization
"Pulling yourself up by your bootstraps." /Steel/ is invented. All of the technology has been moved to provide maximum output; this comes, of course, at an environmental cost. Large unions are starting to take off. Railroad Strike: federal troops fired upon railroad workers; argued the case for union but also for corp. influence on politics.

** Politics
- Democrats: racist, states rights, limited federal government.
- Republicans: supported businesses, immigrations.

Yes, they are still flipped.

But either way, democracy was rampant: 80% turnout! This is, however, one of the most corrupt time in American politics. The party system: local political bosses would provide favours for a vote --- in an absence of welfare, in exchange for a vote, wolud provide protection and social welfare. At this time, there was mass lack of reliance.

** Culture
Victorianism! Proper manners, conservatism, etc. Bikes and contraceptives! There is also a fear that "manliness was declining": that no more farming means need for more sports, body building, etc. Also, "name brands", "sears catalogue", and consumerism is taking hold.

** Corportization
Corporations, as an idea, took hold. That the owners of a group is seperated by management, it allows the expansion of the size of companies. Monopolies in industries run while: concentrated wealth in addition to corrupted politics.

Taylorism: Taylor decided to make a shovel for each type of movement --- which makes people repeat the same task over again but increased efficiency. "Taylor-made" comes from this.

** Third Party
"Omaha Platform"

- Expanding Credit
- Bracketed income tax
- Social reforms

Lays the groundwork for the progressive moment. This was a socialist movement!

* Who is America?
Guilded age introduced heavy dichotomy between the ultra-poor and the ultra-wealthy with massive economic inequality. Many went into the work hoping to join the middle/upper-class, but didn't.

* Research Project
[[id:C47ADD80-D40F-4ED2-A97F-01343C1BE333][Guilded Age World Fair Project]]

* New American South
Election between Hayes vs Tildon was very close. Democrats gave Republicans Hayes, but then asked the Republican millitary to leave the South and hence they have no way of enforcing the rights.

** Redeemer Governments
Democrats put in systems to relegate African Americans to second-class citizenship into the south. Lynchings became the weapon of choice of enforcing Jim Crow.

- Within 20 years, Jim Crow became implemented by every state
- 1896 Plessy vs Ferguson upholding the process of segregation
- Convict leasing: convicts' labour was leased to create infrastructure

Economic transformation: put in sharecropping (crops in lieu or in addition to rent) and convict leasing. This is essentially modern slavery because debt is used as a process to enslave people as they will never actually be paid enough to pay back debt. 

** Push for Civil Rights
"Booker T. Washington": help promote Southern society will gain equality. Founded the "Tuskegee Institute".

"W.E.B. Dubois": make the most talented and artistic people push for civil rights. "Civil rights by copyright."

* The West
- Transcontinental railroad: power over towns and concessions
- Rise of Cowboys and "cattle bonanza"
- Prairies settled with new farming equipment and new Russian wheat strands: "Americanlization" 

The "turner thesis": American democracy is formed at the frontier. However, Western Expansion is actually much of a tragedy, and this is actually leads to Imperialism. 

** Indian Removal
- Policy of Indian removal to force into treaties + reservation
- Sioux Wars (crazy horse, etc.): Native American resistance
- Native Americans of California extreme violence; as well as slave labour
- Dawes Act of 1887 and forced "assimilation": forced the breakup of many reservations

* Imperialism
:PROPERTIES:
:ID:       223F4A89-FFE7-445D-9F0C-C87865697353
:END:

Imperialism: a policy of extending a country's power and influence though diplomacy or military force.

1. Colonies
2. Protectorate --- nations has own government legally controlled by outside power
3. Sphere of influence

U.S. Imperialism, why?

1. "Desire for Military strength": for a nation to be an international player, you have to have a strong navy
2. "Thirst for new markets": if we continue to expand, we will have more economic power
3. "Belief in supernatural superiority": trust that own culture is better

Alaska --- "Seward's Ice Box", purchased from czarist Russia.

Hawaii --- Annexed 1898, a sugar company, to get around import taxes, asked the US to annex Hawaii.

Spanish-American War ---- newspaper receive letter sent by Spanish minister to not protect Cuba. The US then proceeded to fight for the territories. 

Filipino rejected treaty of Paris, America fights. America burned food and crops to starve rebels, and built infrastructure earning elite support due to infrastructure. 

* Teddy Roosevelt
- Large personality: expanded scope of the Presidency --- "if it doesn't explicit say its belong to the congress, it belongs to me"
- Moralist (Support American People), Imperialist (Believes in American Righteousness), Progressive
- Monroe Doctrine & Roosevelt Corollary: America for Americans
- The Panama Canal - engineered /coup!/ to build the panama canal
  

