#+TITLE: Colonial America
#+AUTHOR: Houjun Liu
#+COURSE: HIST301
#+SOURCE: KBHIST301MasterIndex

* Talking about the Essay
See [[file:KBhIntersectionsEssayPrep.org][Intersection Essay Prep]].

** File Organization
- Take a look at "Colonial America, notes", which are the notes of the class
- A PDF of the slides are also available

** When is the draft due?
IDK. He still won't tell. :(

* European Colonization
A "world-wide imperial contest", a global political competition. Not primarily motivated by spreading /democracy/, its about Monies.

- Spanish: started the conquest, for the Spanish armada
- English: bubbling, for minor economic modivation
- French: interested in fur, and trying to maximize gain and investment

So, compare and contrast the three systems.

* Voyages of Discovery

** Motivations
- Rise of a /business/ oriented class
- Pooling of resources for investment
- Tech: astrolabe, maps, compass, better ships, etc.

** Mercantilism
A pair-relationship between colonies:

- Mother Country provides...
  - Finished products
  - Protection
  - Governance
- Colonies provides... 
  - Raw materials
  - Monopolies on market
  - Loyalty

* Colonizers

** Russians!
Russia traveling from west => east; competing with the northern going group.

** Spain!
"Superpower" built upon the Spanish Navy (the "armada.")

- Mission: churches religions and cultures (supposed to be self-sufficient)
- Presidio: military gates and posts
- Pueblos: living

*** Goals
- Find Gold!
- Acquire Land!
- Develop Trade!
- Christian conversion (mostly to get papal decree

*** Weaknesses
- Spanish empire stretched pretty thin
- Did not allow others to come trade, which means limited trade

** England!
Leveraged *Privateers*: pirates with royal decrees, to destroy ability. Defeated the armada by chasing them and sticking them into the English isle.

All business adventures to make money. Settlers were not as loyal because there were a group of dissidents, beggars, and ex-convicts. Also, they are not motivated by missionary reasons.

** France
French along the river systems. Everything flows from the river systems.

Based on *trade* rather than *architecture*. Leveraged the Fur Trade as the primary exclusive source of income.

* Colonized
- No respect for Native American cultures or strategies of land use
- Every mission courtyard had a place where those who disobeyed where wipped
- Father Junipero Serra: think that the native were "childlike" and required education

  -----

* Colonial America, the Thirteen American Colonies
The original British colonies sucked. The English didn't want for them to trade with each othere, but with England.

Oh by the way: Florida was /not/ the Thirteen Colonies


** Jamestown, Virginia
1607, John Smith's colonies. It was a Charter colony, it was a business by the order of the Crown.

- 50% Mortality in Year 1
- Not self sufficient: hunting gold instead of deer, did not plant enough
- Too many "gentlemen", not enough laborers. Smith: "He how will not work shall not eat."

John Rolfe introduces *tobacco*: provides economic foundation for Virginia. Tobacco causes cancer, and so if Barry catches you smoking he will....

- 1619: House of Burgesses formed; 1st elected representative body in North America
- 1619: First Africans sold; indentured servants became racialized
- 1622: Powhatan attack the settlement
- 1624: Crown buys Jamestown; it becomes a "Crown Colony"

*** Bacon's Rebellion 
Jamestown grew rapidly b/c of tobacco. Willian Berkeley proceeds to corrupt the House of Burgesses to restrict political rights to landowners.

Nathaniel Bacon had a /coup d' etat/ against Berkeley.

**Significance**: illuminates growing sociopolitical tensions between landless men vs. those in power.

** The Mayflower
Group of other "Pilgrims" arriving in the new New World. Agree to create a covenant, promising to obey" just and equal laws."

- "Covenant and combine ourselves together in a **civil body politic**"
- "Enact, constitute, and frame just and equal laws"

** Puritan's Colonies: Massachusetts Bay
Massachusetts Co. Puritan's Goal: establish a "City of God."

- Wanted to setup a Puritan colony that allow
- Lack of religious toleration: forced the Quakers to leave

Puritans planted food to support the growth of these colonies.

*** From Massachusetts and Plymouth
Plymouth is a basis for the subsequent settlement of...

- Rhode Island
- Connecticut
- Now Hampshire
- Maine

*** Structure of Settlements
- Members bounded by covenants
- Houses & Meeting house laid in common pasture
- "Selectmen" elected to do roles

*** Puritans' System' Problems
Communism doesn't work b/c there is a fundamental lack of trust between human communities.

- Didn't value religious differences
- ()? Became royal colonies

*** Religious Differences
| Puritans       | Quakers               |
|----------------+-----------------------|
| Predestination | Nonviolence           |
| Conversion     | God exists in all men |

** Connecticut
Settlers from Massachusetts bay looking for more land. Received charter to elect their own governor.

** New Netherlands (NY)
Dutch established the Patroon system: land granted for bringing new settlers. Crown awards land to Lord York after defeat of Dutch.

** New Sweden (Delaware)
Also gave to lord York somehow?

** New Jersey and Pennsylvania
Sold land to the Quakers. As a thank you to the William Penn, who gave the Quakers' land, they:

*** Pennsylvania's System
- Established a liberal frame of government with assembly
- Good relations with Native Americans - "Paid for Land"
- Had no army, believed in peace

*** Philadelphia
- City laid out as a grid
- Established the first model for urban planning in many colonies

** Maryland
Catholic colony. Had religious toleration after realizing the Puritans came swooping in.

** Carolina
1663, chartered by the crown. Planned to attract settlers with religious & political freedom. Central to the trading of slavery.

** Georgia
Buffer zone between Carolina (productive slave trading region) and Spanish Florida

- Attempted to create Utopian societies
- ... but failed

* Emergence of Colonies
I need notes from someone here.

- Expansion towards west
- Concentration of agriculture in the south
  - Cotton
  - Tobacco
  - Cotton => created technology to fluffy cottons

Lots of **tax** from the British. Individuals bitter about the large industry in England compared to the large raw products form the Americas.

** The Deed of Gift of Robert Carter
Begin /manumission/: began freeing slaves in 1791, one of the first emancipators.

=> A lot of racial tensions were allowed to continue and contributed to the problem
  
** Port Cities
Port cities grew bigger and became hubs of cultural and political activity.

- Revolutionary sparks occurred first at big cities {Boston, Philly, NYC}
- Served as industrial centers
- Increased education
  


* And so, explain
- What characteristics do these colonies have in common?
- What relationships were building between the colonies and the crown
- What "roots" of democracy emerged?
- What "American" values emerge
