:PROPERTIES:
:ID:       16363FE1-4269-44C9-979E-66D69816A3FD
:END:
#+title: Historiography Essay Writing
#+author: Houjun Liu

Simultaneous, shared societal observations of subjugation between social classes --- when viewed as the intersection between aristocratic politics and common economics --- created the dynamic opportunity for the alignment of colonial interests that synthesizes the disregard for practicality by Bailyn and ignorance of ideology by Breen towards one of the collective increased need for independence against the British governmental systems: creating a portrayal of the revolution as a timely reactionary force that unified cross-class interests and justified the rhetoric of manifest destiny in early-American history.

The process of ideological alignment in early American colonies began with a set of tangible observations of economy perceived universally by all social classes. The increase in British taxation and ministry in the Colonies provoked, especially in the upper-class, a sense of "deepening corruption, ... which ... deluged all to the eternal disgrace of the British nation." (CITE) Bailyn's framing of the pre-Revolutionary agitation as the idealistic fight against the "arbitrary and despotic ... ravages" (CITE) of Britain, while creating sound theoretical basis, fails to adequately highlight the practical incentive driving the root of such observations aforementioned --- taxation and market economics. The colonists' dependence upon importation from British economy created "rising colonial debts [that triggered] an economic slump" (CITE), according to Breen, well before any acts of British subjugation. Due to the self-propagating nature of this crisis (that increased importation /from/ Great Britain would naturally trigger further debt to them), such a crisis acted to "draw attention to ... individual consumer choices" (CITE) during purchases as individual actions of purchases had increased in gravitas in influencing trade relations. This newfound focus for goods purchasing brought the originally distant geopolitical influences of Britain into the purview of commoners' daily decisions: bootstrapping Bailyn's theoretical claims of despotism upon Breen's more practical grounds of economy. Complementary societal observations of the economy --- though framed in the differing terms of British malfeasance and trading deficit respectively --- ultimately serves to create a unified lens by which both the upper and lower classes are forced to confront the force of Britian's colonial influence.

Universal observation of British influence, when actuated by preexisting concerns of each social class, creates then the fundamental beliefs that centers colonial attention around that of Independence. Reducing importation, as highlighted above, was a great priority for colonists. Colonial Newspapers "believed [that] ... achieving greater self-sufficiency ... would shift the colonial workforce away from agriculture toward manufacturing" (CITE) in hopes of building a "self-reliant economy." (CITE) These newfound believes to self-sufficiency, according to Breen, was a direct response to the mounting Colonial liabilities to the British that eventually brought discussions of independence. Critically missing from this narrative, however, is the ideological impetus that would justify such an understandable --- yet nevertheless quite dramatic --- leap from economic self sufficiency to political independence. Baylin's argument, though markedly missing the practicality of the above observations of economics, brings the philosophical leap needed to justify revolution; "a plan", according to one colonist, "had been deliberately framed and pertinaciously adhered to ... to sacrifice to a passion for arbitrary dominion the universal property ... of Americans" (CITE.) Fed by the fears against despotic magistrates observed by upper-class society, the desire for independence to achieve self-reliance is now corroborated by a more fundamental fear of arbitrary control that would threaten to remove the instruments of self-reliance. Colonial interpretations of British influence --- only when treated as being a dynamic force intermixed between social classes --- provides both the theoretical and practical basis by which Independence from the British becomes a valid remedy to aforementioned issues in Colonial American society.

British Independence, though shown to be /ideally/ advantageous for both social classes in early American society, is exercised through a revolution --- an act that requires the rhetorical and uniform support of all; therefore, the messaging of the revolution necessitates the dynamic synthesis of practical and political arguments into one cohesive and idealist message resonant comprehensively across the American Colonies. Breen frames this rhetoric as again one purely regarding market economics: that the Colonists framed the cost of independence as a "threat ... to turn independent consumer choice into slavish dependence." (CITE) This framing, as with before, captures only partial colonial intent; upon closer examination, the frequent occurrence of the language of slavery indicates a deeper cause made to resonate even in lower classes: that the act of American Revolution is one of the self-"inheritance of liberty ... [and] America’s destiny in the context of world history" (CITE baylin). When treated in this lens of "manifest destiny", early American colonists created the perfect parallel between social classes and causes: both social classes desired to gain increased control of their domestic issues in their sphere, which British independence --- as a means to gain such control --- promptly offers. Indeed, the cause of America is one of "self-defense, of public faith, and of the /liberties/ of mankind" (CITE): a cause that offers a preservation that extends beyond that of political and ideological independence --- as originally intended in this statement by Baliyn --- but into the more grounded independence of economy as well. By treating arguments for Revolution as one that must drive beyond merely one class, the language of "Manifest Destiny" is aptly justified as the supporting thread by which both political fears of subjugation and economic fears of indebtedness can be unified.

The complementary synthesis of the top-down and bottom-up arguments of Bailyn and Breen respectively regarding early American history provides a dynamic view of the Revolution as a reactionary force that tied political and economic concerns of Colonists under the uniform language of self-determination and "manifest destiny." The arguments of each author, treated independently, would prevent the need for a more generalized argument such as manifest destiny commonly seen in early American literature; their synthesis aptly surfaces the demand to unify class-specific factors
