:PROPERTIES:
:ID:       48A5D4F8-E6A7-491A-9EC3-DFE111B23B29
:END:
#+title: History Research Project Writing
#+author: Houjun Liu

American involvement in WWII was triggered by Japan's surprise attack on Pearl Harbor. Although suffering temporary losses, this event became instrumental in America joining the war and working to ensure Allied victory. Despite Japan's clear knowledge that a surprise attack would provoke American aggression, the state nevertheless perused the aggressive instrument of first-attack as its response to escalating non-aggressive tension. Although this choice may seem misguided, it was perceived as being the most optimal one due to multiple failures in both the American and Japanese foreign policy---especially surrounding the American oil embargo to Japan. While the United States treated its oil embargo as a platform on which diplomacy can be built, the Japanese perceived the action as confirming the beginning of an inevitable---and proactive---attack upon Japan by America. This discord in understanding triggered the Japanese attack on Pearl Harbor, and serves to illustrates an instance of American democrcy's failure to recognize foreign sentiment---specifically, the Japanese spirit of expansionism. 

As a part of its WWII campaign control Southeastern China, the Imperial Japanese Army was pushing from Vichy France and the Hainan islands into Northern Indochina territory. The US had significant interest in keeping German and its allies---Japan included---from dramatic expansion, so it naturally elected to deny many of the industrial exports with which Japan can wage war; due to the sheer dependence of Japanese Heavy and Military Industry on such exports (CITE gompert), the entire Japanese economy was sprung into negative growth by the US export ban. Before the passage and subsequent (abrupt) institution of the actual ban, the Japanese government descended into a period of panic purchase of petroleum and other oil products from the US, which massively dwindled the American domestic supply (CITE gompert). In response to stopped exports, "the Japanese government professed surprise and shock" towards the "harshness" (CITE gompert) of American response. Subsequently, according to most modern WWII historians, the Japanese government triggered the attack on Pearl Harbor as a preemptive military response to the looming economic crisis. Most in the American government was taken by surprise the strength and gravity with which the Japanese treated the embargo---as, to the United States---the step taken seemed to be a much more deliberative and diplomatic action. (cite Donovan) While classical analysis of the event places most focus---perhaps rightly so---upon a multiplicity of Japanese failures in recognizing the preserved strength of the US military, there is far less careful treatment of the US' perceived nonchalance to multiple Japanese signs of distress which warned of their impending escalation. Despite the revisionist model which indicates that Roosevelt intended to trigger the escalation via economic means, it is possible to synthesize a different perspective rooted in American diplomacy's inability to recognize the contribution of foreign cultures to diplomatic decision making.

The American "embargo" against exporting Japanese oil was not intended to be a forceful tool of retaliation which Japan treated it to be. In response to Japan's invasion of Vichy's France's Southern Indochina territories, the immediate response of the United States was not to impose an oil embargo but instead a freeze of Japanese assets in the United States. (Cite Gompert) Even as conditions deteriorated, the US still allowed Japanese oil brokers to apply for export licenses for oil---intending to leave critical Japanese infrastructure largely intac (CITE Donovan). In fact, the United States intentionally attempted to leverage oil as a sign of good-will and de-escalation: the "Japanese imports of oil [was] going forward at a rate which there is no commercial justification" (CITE herzhog). Oil exports continued for most of the Japanese Indochinese escalation. Moves to institute an embargo by the US finally began as the Gulf coast was entering a period of oil and oil tanker shortage---rendering it "politically untenable....to ship fuel out of areas with shortages." (CITE donovan). The actually implemented "ban" was even softer then actually executed: essentially amounting to only a poorly executed export "diminishment" that, mostly due to an error in administration, became a ban (CITE Gompert). In terms of US deployment, then, the "export ban" is a very soft adjustment to foreign policy which is not meant to trigger a forcible response.

Treatments to the internal Japanese response during this period must be taken with broad care as most English-language resources on this topic is written by American historians; however, the secondary analysis of Japanese verbal responses and American records offers a unique insight into the Japanese perspective upon the attack on Pearl Harbor: that it was a quick and /inevitable/ step in response to American policy. Historian David Gompert highlights that, at the point of the German invasion of the Soviet Union, "Japan ... began to shape its relationships ... for a coming confrontation with the United States. (CITE Gompert) The tension between Japan and the United States extended beyond geopolitics, with a culturally-implied tension "identify[ing] the U.S. as one of the principle enemies of Japan ... as far back as 1909" (CITE Donovan). Furthermore, according to the historian James H. Herzhog, the signing of the Tripartite Pact---a collateral defense agreement between Japan, Germany, and Italy---"left little doubt that the United States would eventually fight Japan" (CITE Herzhog). With Japan's perception of inevitability of a conflict, any amount of escalation from the US, perhaps even those unperceived as being escalation, would confirm the preset bias of an impending attack. It is, then, trivial to recognize how the "surprise and shock" resulted from the American embargo constituted enough aggression to motivate the Japanese navy to pursue war (CITE gompert). In their reference frame, the "plan to seize the U.S. processions in the Central Pacific would ensure ... Japanese control of all the oil" (CITE donovan), as well as remove hindrances to Indochinese operations which the Japanese saw in the U.S. Pacific Fleet. To the Japanese government, the American economic response---despite its relative weakness---is perceived as the first step to an inevitable attack: rendering the unexpectedly forcible response.

Although, taken independently, the conflict and confusion between both parties seem entirely coincidental, a closer analysis reveals that it is a unique combination of cultural and political ignorance on both parties that ultimately built the direct cause for the attack on Pearl Harbor. Japanese naval officers, especially those younger, carried a "Bushido sprit"---roughly translated as "warrior" sprit, Bushido rendered a "cultural ignorance" and willingness to serve Japanese expansionism at all costs (cite Barbara Tuchman?) Therefore, when presented with the option of attacking Dutch and British possessions instead of provoking the United States and Philippines, the Japanese government---somewhat blinded in sprit---did "not give the option serious consideration" (CITE donovan). The converse of this is true for American diplomacy. Through its diplomatic advances, America failed to recognize the "arrogance, the urge to conform, ... and do-or-die spirit " (CITE gompert) that is central to Japanese decision making: evaluating sections essentially based on what would have worked for /itself/. The prompt acknowledgment of this sprit in Japan by America would force it to realize that "sanctions were not [going to] change policies; [instead], sanctions were hurdles to overcome" (CITE gompert) to Japan. Indeed, American diplomacy failed because it required the Japanese government to concede; Japan, expected that it would have to engage in either "a confrontation with the United States or a conciliatory strategy" (CITE grompert), chose the former due to its "Bushido sprit": leading, ultimately, the trigger of American involvement to WWII.

American diplomacy's failure to recognize and account for Japanese sentiment, combined with Japan's mischaracterization of American intention, were ultimately the triggers that lead to the development of the attack on Pearl Harbor. Although both states acted in their best self-interest, the ultimate outcome became disadvantageous for both Japan and America. In a time of precarious global geopolitical tension when instruments such as export embargos are again being deployed, a deeper cultural understanding of the opposing party would likely serve to correctly target the intention of attacks.
