:PROPERTIES:
:ID:       38848782-B72F-48BC-9215-5EF1C960A109
:END:
#+title: History Viedo Commentary
#+author: Houjun Liu

Kevin, it was very interested to see the influences of external influences to the US strategically shape internal-to-US policy. The pull away to isolationism follows the proliferation of technology, which was lastly enabled by exploration and (subjugation of) trade from other, foreign states. The Jeffersonian ambition for the US therefore drove a sense of the Antebellum "upwards force", which I highlighted as a major factor of the proliferation of technology. The dislike but reliance on the European system may also support the reasoning behind the acts of corporate and technological espionage which we see later.

Jackson, your video really highlighted for me the tribulistic and seconality which slavery would bring to a region. The process of self-organization ("ideological cohesion"), similar to the proliferation of technology, was used by politicians as a /tool/ to achieve their own personal or political ends. It is intriguing to me that our mundane daily systems or effects could actually be leveraged and politicized, even in the antebellum period.

Elianna, the multifaceted expression of elite culture in regimented styles and conventions tied a really interesting contrast to a sense of roughness that existed in the lower class. I wonder if this dichotomy between the two classes exacerbated the sense of class conflict and drew class discord or instead created and propelled the antebellum "upwards force."

Adam, I find it very interesting that the proliferation of print media (an older piece of technology), in addition to the dissemination of the telegraph as I highlighted in my research, also helped contribute to the politicization and separation in the antebellum period. It therefore re-emphasizes the thought I had in my own research that brings an argument against the direct causation of politicization by new technology.

Anoushka, the leveraging of music as a form of dichotomy and, though it, the creation of shared culture was a fascinating point of conclusion upon which you came; I am intrigued by the degree of influence by which shared culture had over even actual facts or identities which are spread through other means. Furthermore, I am interested in how the new technologies developed in the antebellum period may have shaped or propagated the spread of these items of music and culture.

