:PROPERTIES:
:ID:       38848782-B72F-48BC-9215-5EF1C960A109
:END:
#+title: History Viedo Commentary
#+author: Houjun Liu

Kevin, it was very interested to see the influences of external influences to the US strategically shape internal-to-US policy. The pull away to isolationism follows the proliferation of technology, which was lastly enabled by exploration and (subjugation of) trade from other, foreign states. The Jeffersonian ambition for the US therefore drove a sense of the Antebellum "upwards force", which I highlighted as a major factor of the proliferation of technology. The dislike but reliance on the European system may also support the reasoning behind the acts of corporate and technological espionage which we see later.

Jackson, your video really highlighted for me the tribulistic and seconality which slavery would bring to a region. The process of self-organization ("ideological cohesion"), similar to the proliferation of technology, was used by politicians as a /tool/ to achieve their own personal or political ends. It is intriguing to me that our mundane daily systems or effects could actually be leveraged and politicized, even in the antebellum period.

Adam, that
