:PROPERTIES:
:ID:       A58FCD92-57A9-4C68-8AF9-FE0E95877DFF
:END:
#+title: Impending Crisis Reading
#+author: Houjun Liu

* Chapter 1
:PROPERTIES:
:NOTER_DOCUMENT: Impending Crisis, C1.pdf
:END:

** Sense of want of peace
:PROPERTIES:
:NOTER_PAGE: (2 . 0.43696275071633234)
:END:
threatening that "if Mexico protracted the war," more land cessions, in addition to California and the Southwest, "must be required as further indemnity."

** Mexican war regarded as a war of slavery
:PROPERTIES:
:NOTER_PAGE: (3 . 0.333810888252149)
:END:
it was regarded as a war of unjustified aggression on behalf of the evil institution of slavery

** The expansion of America was actually a disappointing result due to divisions in congress
:PROPERTIES:
:NOTER_PAGE: (4 . 0.3753581661891117)
:END:
This gigantic step in the growth of the American republic was not taken with enthusiasm by either president or Congress, but resulted from the fact that the elements in opposition could find no viable alternative and no basis on which they could combine.

** :claim: the sense of divisive expansion was a result of the "impulsive" sense of manifest destiny
:PROPERTIES:
:NOTER_PAGE: (4 . 0.45558739255014324)
:END:
an ominous fulfillment for the impulses of American nationalism.

** The force of manifest destiny threatened the union itself
:PROPERTIES:
:NOTER_PAGE: (9 . 0.12607449856733524)
:END:
Much of the national harmony had rested upon the existence of a kind of balance between the northern and southern parts of the United States. The decision to fight the war had disturbed this balance, and the acquisition of a new empire which each section desired to dominate endangered the balance further.

(Mexican-American war was the instigator of the revolotuion)

"Perhaps it may even be said that the developments which gave American nationalism the strength to survive also generated a supreme threat to its survival ."

* Chapter 2
:PROPERTIES:
:NOTER_DOCUMENT: Impending Crisis, C2.pdf
:END:

** The normal force of manifest destiny was re-appropriated to be that advocating for slavery
:PROPERTIES:
:NOTER_PAGE: (2 . 0.23197492163009403)
:END:
assailing the expansionist plans of the administration, suggesting that the ulterior purpose was to extend the area of slavery

** Division on the passage of the bill became independent of party lines but instead seperated by geography
:PROPERTIES:
:NOTER_PAGE: (3 . 0.3401253918495298)
:END:
The roll call produced a division not between Whigs and Democrats, but between northerners and southerners.

** North-South divide highly prevalent in internal-party politics
:PROPERTIES:
:NOTER_PAGE: (3 . 0.36990595611285265)
:END:
Ever since the days when Martin Van Buren had jockeyed to displace John C. Calhoun the favor of Andrew Jackson

** :claim: Sectionality and politics are two different things, they become conflated != they are the same
:PROPERTIES:
:NOTER_PAGE: (6 . 0.2946708463949843)
:END:
it is well to recognize that sectionalism was not initially or intrinsically a political phenomenon, and it is important to consider sectionalism in its prepolitical form

** :claim: that the discord in culture would have caused conflict regardless of slavery
:PROPERTIES:
:NOTER_PAGE: (7 . 0.274294670846395)
:END:
The two cultures still would have clashed even if all the Negroes had been free.
** South + North values different things, which contributed to cultural difference
:PROPERTIES:
:NOTER_PAGE: (7 . 0.7241379310344828)
:END:
Southerners placed a premium on the values of loyalty, courtesy, and physical courage­ these being the accustomed virtues of simple, agricultural societies with primitive technology. ... [Whereas northern states] had begun to respond to the dynamic forces of industrialization, mass transportation, and modem technology
** :claim: View of "culture-driven-sectionalism" ignores the actual large amonut similarity between the two cultures
:PROPERTIES:
:NOTER_PAGE: (8 . 0.09717868338557993)
:END:
The outstanding weakness of this cultural interpretation is that exaggerates the points of diversity between North and South, mini mizes the similarities, and leaves out of account all the commonalities and shared values of the two sections which have been discussed in the preceding chapter.
** Differences in production augmented differences in philosophy
:PROPERTIES:
:NOTER_PAGE: (8 . 0.30094043887147337)
:END:
with the result that the North drew steadily further ahead of the South in population, wealth; and productivity
** Another theory concerns the fact that African American settlement may compete with Caucasian settlement
:PROPERTIES:
:NOTER_PAGE: (10 . 0.5031347962382445)
:END:
n the southern states-the free-soil movement dealt with them where they did not exist-in the territories; instead of proposing to free them, it proposed to keep them (and free Negroes as well) out of the new areas where they might compete with white settlers.
** When the Revolution took place, a moral unity was created that actually started abolition
:PROPERTIES:
:NOTER_PAGE: (11 . 0.3824451410658307)
:END:
both North and South had moved in unison to condemn slavery as an evil. The upper South had witnessed a formidable movement for the voluntary manumission of slaves
** :claim: Antislavery was ignited because it became clear that southern states wish to stick to it
:PROPERTIES:
:NOTER_PAGE: (12 . 0.10658307210031348)
:END:
increasingly clear that slavery was not in the process of extinction and the issue would not take care of itself.
** Culture, Economics, and Ideologies were pitched as the standard for explaining sectional conflict
:PROPERTIES:
:NOTER_PAGE: (12 . 0.4184952978056426)
:END:
cultural, economic, and ideological have long been the standard formulas for explaining the sectional conflict
** Slavery was the touchpoint for the intangible conflict of values
:PROPERTIES:
:NOTER_PAGE: (12 . 0.603448275862069)
:END:
Slavery presented. An inescapable ethical ques tion which precipi tated a sharp conflict of values.
** Each section painted a strawman of the other to react to
:PROPERTIES:
:NOTER_PAGE: (13 . 0.3072100313479624)
:END:
As they became isolated, instead of reacting to each other as they were in actuality, each reacted to a distorted mental image of the other
** :claim: That the sectionalization and painting of strawman actually cause further discord w.r.t. being blinded to similarities
:PROPERTIES:
:NOTER_PAGE: (13 . 0.4373040752351097)
:END:
It caused both northerners and southerners to lose sight of how much alike they were and how many values they shared
** North divided upon emphasis: whether to preserve human rights/slavery at all costs, or to preserve the Union, etc.
:PROPERTIES:
:NOTER_PAGE: (14 . 0.1974921630094044)
:END:
** That, due to the divided contexts of the North, idelogical code-switching and context-switching is needed to preserve the Union and abolish slavery
:PROPERTIES:
:NOTER_PAGE: (15 . 0.5188087774294671)
:END:
Abraham Lincoln could say that "if slavery is not wrong then nothing is wrong," but he could also pledge himself to enforce the fugitive-slave clause of the Constitution and to defer the goal of emancipation into the remote future.
** The attempt to reconciliation split Northern value is dangerous
:PROPERTIES:
:NOTER_PAGE: (15 . 0.658307210031348)
:END:
extremely threatening to the tranquillity of the northern mind
** When Mexico war took place, the careful Northern seperation was disturbed
:PROPERTIES:
:NOTER_PAGE: (16 . 0.46394984326018807)
:END:
The slavery problem, which had been so carefully diffused and localized, could not now be kept from coming to a sharp focus as a national issue
