:PROPERTIES:
:ID:       BD73F5A0-EAEE-4EF5-8005-AFCD0D3A1D35
:END:
#+title: Japan's Attack on Pearl Harbor - Gompert 2014
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: 2022 - Japan’s Attack on Pearl Harbor, 1941.pdf
:END:
** :claim: Japan sohuld not have bombed peral harbor
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5132555673382821)
:END:
Japan’s decision to bomb Pearl Harbor was a blunder of the highest order
** :claim Biggest trigger of American war invollvement was the decision to invade indochina (Laus, etc.)
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5683987274655355)
:END:
Perhaps the greatest misstep was the July 2, 1941, decision to invade southern Indochina.
** Economic self-sufficiency became a major goal of Japan after WWI
:PROPERTIES:
:NOTER_PAGE: (3 . 0.27677624602332984)
:END:
A group of Japanese officers observing events in postwar Germany became obsessed with the importance of gaining economic autarky, including self-sufficiency through conquest.
** Japan and China conflict set the stage for western bitterness
:PROPERTIES:
:NOTER_PAGE: (3 . 0.48780487804878053)
:END:
Japanese victories at Nanking, Xuzhou, Hankou, Guangzhou, Wuchang, and Hanyang did not fully suppress Chinese nationalist armies, and bitter fighting persisted.
** :claim: American support of China in Sino-Japanese conflict was because that they were "agast by the atrocities"
:PROPERTIES:
:NOTER_PAGE: (4 . 0.3552492046659597)
:ID:       F53D90C3-2495-47B7-A2DE-F6DA377DB187
:END:
Aghast by Japanese atrocities, America provided material assistance to the Republic of China.
** US at the time had a weak army, yet strengthened its navy + moved it to Hawaii
:PROPERTIES:
:NOTER_PAGE: (4 . 0.5949098621420997)
:END:
Japanese officials interpreted the growth and shift of U.S. sea power as a threat to its
own sea control, trade, national well-being, and strategy.
** America's first response, after Sept. 1940 attacks in Northern Indochina, was to implement embargo on parts for warmaking
:PROPERTIES:
:NOTER_PAGE: (4 . 0.7783669141039237)
:END:
That same month the United States halted its exports of scrap iron, steel, and aviation fuel to Japan on the grounds that it was needed at home. The embargo also extended to arms, ammunition, critical raw materials, aircraft parts,
** By Jan 1941, denial of war materials grew to create big dent in Japanese industry
:PROPERTIES:
:NOTER_PAGE: (5 . 0.09968186638388124)
:ID:       D9E88F2E-D20B-44EE-8C49-A7C60A9191CB
:END:
January of 1941, the denial of war material was extended to copper, brass,
bronze, zinc, nickel, and potash, causing a major impact on Japanese industry
** Japanese pact to get resources and military with Germany + Italy meant to deter the US,  but actually was viewed as an aggression
:PROPERTIES:
:NOTER_PAGE: (5 . 0.16012725344644752)
:ID:       8F90F636-4FE2-4F56-B4DB-4C945FB52F40
:END:
While Japan hoped that this would deter the United States,13 in fact it compounded the affect of Japan’s occupation of northern Indochina and was taken in Washington as a move
to counter American opposition to Japanese expansionism.
** Japan attempted to remain neutral, even given the pact, come Germany <> Soviet invasion
:PROPERTIES:
:NOTER_PAGE: (5 . 0.26617179215270415)
:END:
Despite German pressure, Japan maintained its neutrality with Russia and continued its move to the south.
** :claim: At the point of German <> Soviet invasion, the relationship between Japan and other world powers began to be shaped in favour of a US-Japan Conflict
:PROPERTIES:
:NOTER_PAGE: (5 . 0.2895015906680806)
:ID:       B1F28AFD-CF2C-4961-B4AD-583177086B4A
:END:
Japan thus began to shape its relationships with the major powers for a coming confrontation with the United States.
** :claim: that, because incorrect implementation, peace deals fail
:PROPERTIES:
:NOTER_PAGE: (5 . 0.47189819724284204)
:END:
While their intentions were good, a thorough review of the episode by the historian R. J. C. Butow concludes that in fact they created con- fusion by misleading both sides with regard to the origins of various peace proposals.
** :claim: that the japanese creation of the co-prosperity sphere both ruptured Japanese-American relations and also remove its alliances
:PROPERTIES:
:NOTER_PAGE: (5 . 0.7253446447507954)
:END:
Under this decision, Japan would not attack the Soviet Union despite pressure to do so from Germany; Japan would not abrogate the Tripartite Pact with Germany; and Japan would secure control over all of Indochina militarily.
** Japanese home minister warned against war with US, but Imperial Conference rejected it
:PROPERTIES:
:NOTER_PAGE: (6 . 0.15270413573700956)
:ID:       D52925D2-1CCD-4548-B2ED-31ED0605C467
:END:
The home minister, Kiichiro Hiranuma, warned that war with the United States should be
avoided at all cost, but the Imperial Conference rejected the warnings.
** :claim: Japan was taken by surprise of the second round of American embargo despite their first round
:PROPERTIES:
:NOTER_PAGE: (6 . 0.2492046659597031)
:ID:       AB3A1679-98FF-48BC-B47A-0D06BED2F663
:END:
There was no serious examination in Tokyo of the possibility of imposition of a total embargo by the United States, Britain, and the Netherlands. They were taken by surprise.
** France gave up the ports in southern Indochina, and so despite Roosevelt's warnings, Japan invaded 
:PROPERTIES:
:NOTER_PAGE: (6 . 0.45281018027571585)
:END:
With the door to the rest of Indochina now opened by France, Roosevelt’s warnings not to walk into that open door were disregarded
** And so Ameria froze Japanese assets. Notably, however, no oil embargo
:PROPERTIES:
:NOTER_PAGE: (6 . 0.5068928950159067)
:ID:       EC710F33-4079-46DA-8D78-D233F397EDA5
:END:
In response, the United States first froze all Japanese financial assets in the United States. But an oil embargo was postponed.
** Another intepretation of roosevelt's decision caused oil embargo (so... technical error?)
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6339522546419097)
:ID:       951DDFF3-F448-4CEB-8C1F-831EC388B137
:END:
In August 1941, Acheson interpreted Roosevelt’s earlier decision strictly and took steps to impose what amounted to a de facto oil embargo on Japan by canceling Japan’s ability to pay for the oil
** Ambivalence to tech error lead to oil embargo
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6724137931034483)
:ID:       B9451D3F-B325-4CF6-9066-B32A80957304
:END:
Roosevelt did not object.
** The Japanese government was cut off from its econ source, and was shocked
:PROPERTIES:
:NOTER_PAGE: (6 . 0.7241379310344828)
:ID:       6175011D-D0CE-4DD6-BBF7-B15725B0A422
:END:
The cumulative impact of sanctions severely stressed the Japanese economy. Despite the clear warning, the Japanese government professed surprise and shock that the Americans would react this harshly
** Security by obscurity made the Japanese foreign office seem deceptive
:PROPERTIES:
:NOTER_PAGE: (7 . 0.10079575596816975)
:END:
intelligence made Nomura appear deceptive
** :claim: revisionist history claims that Roosevelt meant to trigger war to proxy Germany
:PROPERTIES:
:NOTER_PAGE: (7 . 0.17374005305039786)
:END:
Revisionist historians have questioned Roosevelt’s motives during the second half of 1941, arguing that he boxed Tokyo in by giving them no choice
** That the attack on Pearl harbor was an escalation given
:PROPERTIES:
:NOTER_PAGE: (7 . 0.3952254641909814)
:END:
which were either national economic suffocation or surrender of Tokyo’s empire on the Asian mainland.
** Japan had to either concede or eventually fight
:PROPERTIES:
:NOTER_PAGE: (7 . 0.5623342175066313)
:ID:       0047D6DE-91D2-4EE5-ACE3-A0D261766917
:END:
force massive concessions from the Dutch East Indies would lead either to a confrontation with the United States or to a conciliatory strategy by Japan.
** After the embargo, japanese navy persued war
:PROPERTIES:
:NOTER_PAGE: (7 . 0.7811671087533156)
:ID:       6B7E0A02-0796-4894-9BD2-C52556918728
:END:
After the occupation of southern Indochina and the imposition of the U.S. oil embargo, the Japanese navy shifted ground from its earlier opposition to war.
** To make a policy, Japan's navy and army had to agree, but navy is less belligerent
:PROPERTIES:
:NOTER_PAGE: (8 . 0.7957559681697612)
:END:
Military leaders fell into factions: The navy was generally less belligerent than its army counterparts. Both groups were needed for a policy consensus, so the navy had an effective veto.
** Japanese suffered from cultural ignorance of America
:PROPERTIES:
:NOTER_PAGE: (9 . 0.17241379310344826)
:END:
They carried an aggressive Bushido spirit and suffered from what Barbara Tuchman called “cultural ignorance.”
** Tokyo had a strategic peace deadline, which was passed
:PROPERTIES:
:NOTER_PAGE: (11 . 0.3793103448275862)
:END:
An emissary, Saburo Kurusu, was sent to Washington in a final effort to negotiate peace, but his efforts fell short as Tokyo’s deadline approached
** Diplomacy failed because it required Japanese to conceal
:PROPERTIES:
:NOTER_PAGE: (11 . 0.48541114058355433)
:END:
The first was the diplomatic path. Bluster had failed. To be successful on this path, Tokyo would have to reverse course and end its occupation of Indochina...And by then, diplomatic channels were clogged with distrust.
** Maintaining US neutrality and attacking Britian failed because.... they didn't think of it?
:PROPERTIES:
:NOTER_PAGE: (11 . 0.5994694960212201)
:END:
Tokyo could proceed with an attack on Dutch and British possessions but spare Pearl Harbor and the Philippines...But the option was not given serious consideration. It remains unclear how the United States would have responded
** Or, just go for overtake and ignore other countries and hope US tires itself
:PROPERTIES:
:NOTER_PAGE: (11 . 0.7068965517241379)
:END:
Tokyo could follow the advice of Yamamoto to strike deeply at the enemy’s heart and hope that the United States would tire of war
** Japan didn't declar war, and just went for it
:PROPERTIES:
:NOTER_PAGE: (12 . 0.35411140583554374)
:END:
The attack took place before Japan could formally declare war, creating the “day of infamy.” America instantly took a war footing. Six months later, at Midway, Japan sought to finish off the American carriers.
** Spirit and culture distorted japanese view of ar
:PROPERTIES:
:NOTER_PAGE: (12 . 0.6856763925729442)
:END:
The information they had was filtered through a prism of militarism, extreme nationalism, arrogance, the urge to conform, a pull toward groupthink, and do-or-die spirit.
** :claim: Therefore, American sactions were not going to be effective
:PROPERTIES:
:NOTER_PAGE: (13 . 0.09814323607427056)
:END:
To this military-dominated culture, sanctions were not reasons to change policies; sanctions were hurdles to overcome. Diplomatic concessions were viewed as weak and
a sign of flawed character.
** Japanese intervention saw as not liberating but invading
:PROPERTIES:
:NOTER_PAGE: (13 . 0.3992042440318302)
:END:
The Chinese saw the Japanese as invaders, not liberators. The resulting atrocities set American opinion strongly against Japan and produced a hardening of U.S. policy, including sanctions.
** :claim: Japanese believed that the US millitary was weak
:PROPERTIES:
:NOTER_PAGE: (13 . 0.506631299734748)
:END:
Japanese leaders appreciated that the American economy was much
stronger than theirs and that over time America’s military could dominate theirs. But
they took a short-term view, believing that a quick victory could solidify their control
in Southeast Asia,
** Japanese surprised by US oil embargo
:PROPERTIES:
:NOTER_PAGE: (14 . 0.24403183023872677)
:END:
Despite warnings from Nomura, which they tended to ignore or discount, the leadership in Tokyo seemed surprised by the American decision to implement an oil embargo
** The benefits of a Japanese surprise attack was short
:PROPERTIES:
:NOTER_PAGE: (14 . 0.786472148541114)
:END:
Japan was right about the importance of the U.S. Navy to America’s military capabilities in Asia. But the benefit from surprise can be short-lived. Hitler’s surprise attack on the Soviet Union grounded to a halt just as Tokyo launched its attack on Hawaii.
** :claim: Japanese ambition were the main hinderance
:PROPERTIES:
:NOTER_PAGE: (15 . 0.2639257294429708)
:END:
The Japanese leaders were, in Tuchman’s words, “prisoners of their outsized ambitions.”
** :claim: American time pressure worsened Japanese 
:PROPERTIES:
:NOTER_PAGE: (15 . 0.3740053050397878)
:END:
Time pressure, including limited oil supplies, swung the navy in favor of military action. Its assessment that war might be short was flawed.
** :claim: Underestimation of America is the principle
:PROPERTIES:
:NOTER_PAGE: (15 . 0.539787798408488)
:END:
The fundamental flaw in the Japanese model of reality that lead to Pearl Harbor was underestimation of America—its willingness to take a tough diplomatic stand, its ability to recover from attack and respond, and its willpower.
