:PROPERTIES:
:ID:       8592E00E-1E8F-458A-AC05-2C79BFC79289
:END:
#+title: Lincoln's Civil War Brilliance
#+author: Houjun Liu

* Lincoln's Civil War Brilliance
:PROPERTIES:
:NOTER_DOCUMENT: Lincoln's Brilliance McPherson.pdf
:END:
** Framed the process of allowing slavery in some parts as entirely hipocritical
:PROPERTIES:
:NOTER_PAGE: (1 . 0.7880794701986755)
:END:
“because of the monstrous injustice of slavery itself” and also “because it deprives our republican example of its just influence in the world—enables the enemies of free institutions, with plausibility, to taunt us as hypocrites.”
** :claim: lincoln was antislavery in priciple, but is not an abolitionist
:PROPERTIES:
:NOTER_PAGE: (2 . 0.16821192052980133)
:END:
Lincoln was antislavery but not an abolitionist. That is, he considered slavery a violation of the natural rights to life, liberty, and the pursuit of happiness enunciated in America’s founding charter (written by an antislavery slaveowner).

<>Thomas Jefferson
** Lincoln did not directly call for abolition
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2781456953642384)
:END:
Lincoln and most Republicans in the 1850s did not call for the immediate abolition of slavery
** Lincoln's Kentuckian background afforded him symphathy towards slave*owners*
:PROPERTIES:
:NOTER_PAGE: (2 . 0.423841059602649)
:END:
Lincoln also said he could “understand and appreciate” how “very difficult” it would be “to get rid of” slavery “in any satisfactory way....
** Still racism exists deeply
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5390728476821192)
:END:
“What then? Free them all, and keep them among us as underlings? Is it quite certain that this betters their condition?”
** Lincoln himself acknowledges internal sense of superiority above African Americans
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6105960264900663)
:END:
Lincoln confessed that “my own feelings will not admit of this; and if mine would, we well know that those of the great mass of white people will not.
** To some radical disuninists, antislavery == abolition
:PROPERTIES:
:NOTER_PAGE: (2 . 0.7721854304635761)
:END:
divergence between “antislavery” and “abolitionist” was a distinction without a difference
** As a semipolitical move, Lincoln became more definite in painting a strawman than he was before
:PROPERTIES:
:NOTER_PAGE: (3 . 0.16821192052980133)
:END:
In 1864 Lincoln had a much more definite idea of “what to do” and a great deal more “earthly power” to do it than in 1854. His “brethren of the south” were now “rebels”
** Sending slaves away stopped as soon as slaves began "fighting gallantly"
:PROPERTIES:
:NOTER_PAGE: (3 . 0.29271523178807946)
:END:
now that they were fighting so “gallantly in our ranks” their commander in chief no longer wanted them to go.
** Lincoln still promoted race-based seggregation
:PROPERTIES:
:NOTER_PAGE: (3 . 0.8092715231788079)
:END:
"I do not propose to discuss this, but to present it as a fact with which we have to deal. I cannot alter it if I would.... It is better for us both, therefore, to be separated"
** Attempted colonization for home for Black individuals was in large part a failure
:PROPERTIES:
:NOTER_PAGE: (4 . 0.2185430463576159)
:END:
A good many Republicans agreed with one of their number who branded Lincoln’s “scheme” of colonization as “simply absurd” and “disgraceful to the administration.”
** Galliantness of Black people in the civil war is something that seemed to change Lincoln's racial views
:PROPERTIES:
:NOTER_PAGE: (4 . 0.4013245033112583)
:END:
Because of Lincoln’s admiration for the courage of black soldiers and their contribution to Union victories, his “racial views seemed to change”
** :claim: that Union victory (built on the backs of Black soliders) was decisive to the victory of Lincoln
:PROPERTIES:
:NOTER_PAGE: (5 . 0.26225165562913905)
:END:
nstead of being “badly beaten” at the polls in November, as he had expected in August, Lincoln was decisively reelected.
** Lincoln also began discussion of black enfranchisemesnt
:PROPERTIES:
:NOTER_PAGE: (5 . 0.4185430463576159)
:END:
“This was a remarkable statement,” Foner rightly asserts. “No American president had publicly endorsed even limited black suffrage.”
** Douglass praised Lincoln as a president that offered Black men their representation
:PROPERTIES:
:NOTER_PAGE: (5 . 0.7218543046357616)
:END:
Lincoln was “emphatically, the black man’s president,” said Douglass, “the first to show any respect for their rights as men.”
** Later Douglass stepped back his speech, and recognized the simply the loathing of slavery by Lincoln
:PROPERTIES:
:NOTER_PAGE: (6 . 0.10198675496688742)
:END:
Lincoln’s flaws may have been in the eyes of racial egalitarians, “in his heart of hearts he loathed and hated slavery.” His firm wartime leadership saved the nation and freed it “from the great crime of slavery. . . . The hour and the man of our redemption had met in the person of Abraham Lincoln.”
** Douglass's shifting perspective exemplified by his later speech
:PROPERTIES:
:NOTER_PAGE: (6 . 0.2052980132450331)
:END:
Douglass’s speech in 1876 “mimicked his own shifting perspective” on Lincoln over the previous two decades.
** :claim: Douglass originally believed that Lincoin was fundimentally pro-slavery, but just using anti-slavery as leverage
:PROPERTIES:
:NOTER_PAGE: (6 . 0.32847682119205296)
:END:
Because Lincoln seemed to move too slowly and reluctantly in that direction, Douglass berated him as a proslavery wolf in antislavery sheep’s clothing.
** Douglass even supported the replacement of Lincoln at one point
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6503311258278146)
:END:
For a time Douglass even supported efforts to replace Lincoln with a more radical Republican candidate for president in the election of 1864
** :claim: Douglass and Lincoln discord comes from the fact that Douglass was a orator to proclaim principle and Lincoln is a sly politicition
:PROPERTIES:
:NOTER_PAGE: (6 . 0.8596026490066225)
:END:
Douglass was a radical reformer whose mission was to proclaim principles and to demand that the people and their leaders live up to those principles. Lincoln was a politician, a practitioner of the art of the possible,
** :claim: Lincoln's prowess exists in dealing with an issue radically but in a manner that way seem slow and "backhanded" to obscure his motive
:PROPERTIES:
:NOTER_PAGE: (7 . 0.36821192052980134)
:END:
Douglass and many other contemporaries failed to appreciate or even to understand Lincoln’s political legerdemain. Many historians have similarly failed. But Oakes both understands and appreciates it, and he analyzes with more clarity and precision than anyone else what he describes as the “typically backhanded way” in which Lincoln handled slavery, a tactic that “obscured the radicalism of his move.”
** :important: :claim: The north cared first about the union, then about slavery. Lincoln, by making emancipation a millitary issue, achiveed radicallism without being radical
:PROPERTIES:
:NOTER_PAGE: (8 . 0.4688741721854305)
:END:
As Oakes comments, any diligent reader of Lincoln’s words “might have found it odd that a proclamation ostensibly designed to overturn General Hunter’s emancipation order” contained a paragraph “declaring the President’s authority to free the slaves in the rebel states whenever ‘military necessity’ required it.”
...
[yet] The cause of the Union united the North; in 1862 the issue of emancipation still deeply divided it.
** Lincoln was much less racist in private than his contemporaries
:PROPERTIES:
:NOTER_PAGE: (9 . 0.12185430463576159)
:END:
But in private, Lincoln was much less racist than most other whites of his time. He was “disgusted by the race-baiting of the Douglas Democrats,
** That the equivocacy in opposing equality is to appease proslavery race arguments and erase race from table
:PROPERTIES:
:NOTER_PAGE: (9 . 0.2423841059602649)
:END:
Lincoln’s statements expressing opposition to social and political equality, Oakes maintains, were in fact part of his antislavery strategy. Lincoln “wanted questions about race moved off the table,”
** Lincoln leveraged racism to make emancipation palatable
:PROPERTIES:
:NOTER_PAGE: (9 . 0.6821192052980133)
:END:
Lincoln “was once again using racism strategically” to “make emancipation more palatable to white racists,”
** Hence, after emancipation, no longer does he had to be racist
:PROPERTIES:
:NOTER_PAGE: (9 . 0.7735099337748345)
:END:
After issuing the Emancipation Proclamation on January 1, 1863, Lincoln stopped using racism as a strategic diversion.
** Lincoln was never privately racist
:PROPERTIES:
:NOTER_PAGE: (10 . 0.1205298013245033)
:END:
Douglass also found that Lincoln in person had none of that “pride of race” he had earlier accused him of possessing. “In his company I was never in any way reminded of my humble origin, or my unpopular color,” wrote Douglass.
