:PROPERTIES:
:ID:       2C6B06B4-09DC-4FC1-B2DE-50D4E7BF5B36
:END:
#+title: Marketplace of Revolution: Breen
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: Breen-Marketplace_Of_Rev.pdf
:END:

** Leading to Non-Importation
*** Farming and self-sufficiency still an attractive image
:PROPERTIES:
:NOTER_PAGE: (13 . 0.7764705882352941)
:END:


** The Establishment of Non-Importation
*** The slump in economy was a tangiable touchpoint for colonists w.r.t. adverse affects of British associations
:PROPERTIES:
:NOTER_PAGE: (25 . 0.3764705882352941)
:END:

*** Initial blame for downturn was those that were extravigant
:PROPERTIES:
:NOTER_PAGE: (25 . 0.8470588235294118)
:END:

*** Opuluence and overpurchase as a response to post-war depression
:PROPERTIES:
:NOTER_PAGE: (27 . 0.6823529411764706)
:END:

*** Wished to achieve higher autonomy of manufacturing
:PROPERTIES:
:NOTER_PAGE: (28 . 0.1411764705882353)
:END:


** The Result of Non-Importation
*** Luxury and Extravagance had to be tuned down
:PROPERTIES:
:NOTER_PAGE: (26 . 0.16470588235294117)
:END:

*** Rhetoric for frugality shifted from as a form of preserving humble provincial origins to that of an act of patriotism
:PROPERTIES:
:NOTER_PAGE: (26 . 0.23529411764705882)
:END:

*** The definition for luxury is also fluid and varied between families
:PROPERTIES:
:NOTER_PAGE: (27 . 0.5882352941176471)
:END:


** The Analysis Thereof
*** Non-Importation movement was ignored as a part of most's analysis of Revolution
:PROPERTIES:
:NOTER_PAGE: (14 . 0.6588235294117647)
:END:

*** :claim: Non-Importation movement as a direct cause of the revolution, which is caused by higher demand for consumerarism
:PROPERTIES:
:NOTER_PAGE: (14 . 0.6588235294117647)
:END:



* Thesis
That the colonists shared experience as consumers. The shared experience developed a sense of unity and provided protests in the political marketplace.

* Evidence
Breen claiming that there is a widespread belief that there is a centralization of values, and the courts came to support the Boston courts.

British troops saw the colonists being luxurious, but really they were just hoarders. :facepalm: Franklin met with the house of commons, which showed that the colonies had a lot of control of the economy, and claimed that they want to have better treatment. Franklin put on a show; colonialism was really great for the British because they would buy British imports.

To keep the colonists in check, the British imposed higher tariffs. Because of the high spending problem: "save your money, and you will save your country."

** A Looksie at Funerals
White gloves were purchased every time for funerals. That stopped because white glove purchase was just giving more money to the British.

* Critiques
Revolution was a dynamic process. Requires corporation from everyone: crucial for the elites to cut down their spending. The biggest problem exists with people that can't afford it.

Unity in the diverse colonial setting: people are all centered around anti-tax, anti-exploitation.
