:PROPERTIES:
:ID:       364CE879-87D7-45C7-89C6-98394BD5F443
:END:
#+TITLE: National Period
#+AUTHOR: Houjun Liu

The Early Part of the United States' History! "Does not get you through your SAT."

* The Earliest Presidents
- Washington
- Adams
- Jefferson
- Madison
- Monroe

* Westward Expansion
Always assumed that they would expand west and take rights from the Indians. The **second amendment** was as much about bearing arms against Indians than it is about bearing arms against the British.

** Getting Texas
James Polk leveraged the Mexican-American war to acquire the new Western technology.

** Louisiana Purchase
Did not actually have authority to do so, but just did it kind of for funzies.

* Federalism vs Anti-Federalism 
The perspectives of the new ideas remain. /John Adams/ was a pretty large power grabber to solidify the federalist position. Pushing Virginia and New York to ratify was a pretty large point because they have the biggest negotiating point.

* The Executive
Washington gave a lot of precedents to the presidents.

- Served two terms & steps down: does not try to take over
- Set a tone and expectation that presidents will not live their whole life in power
- **Advised to avoid the fight between France and England**

** Washinton

*** Wiskey Rebellion
:PROPERTIES:
:ID:       F9807938-9194-4922-86BB-EEE5AA1FB757
:END:
A rebellion rose against taxes of the Whiskey. Washinton's leadership and success in putting down the rebellion offers sharp contrast to the Articles' handling of Shay's Rebellion.

*** Dealing with Native Americans
Washinton dealt with the NAs by chasing them out into newly-treaties land via leveraging the military.

*** Hamilton's Financial Programs

**** Fixing Problems
- Pay of all war debts
- Raise revenue
- Create a central bank
- Most southern-states opposed northern states debts being paid off
- **capital in the south**

**** L'Enfant Plan  
Washinton D.C., with its grid layout and diagonal streets, was quite a master-planned city.

** Adams
Did not endear himself to others, and was quite a short stature. Was not quite benefited by the fact that Washington --- who was tall and polished.

*** Alien and Sedition Acts
Got a lot of criticism by acts to exclude aliens from voting and preventing people from criticizing the government.

*** XYZ Affair
France wanted America to force a bribe before they would see the American ambassador.

*** Virginia & Kentucky Resolutions
Two different parties was leading and vice-leading. Jefferson was trying to jab the president in the back: trying to nullify federal law.

** Jefferson
"Democratic Republican party": identify difference with the elite Federalists. Plantation owner with two families (look it up!).

- Among the political and economic elite in the US
- Wins the election, and inherits justices that were Federalists

Tells Madison to ignore Jefferson. The /Marbury v. Madison/ is declared unconstitutional: which then solidifies the standing of the court as a group to interpret the laws. Jefferson was furious, as this expanded the power of the Judicial branch. But he did not wish to take action because if he did than Marbury would win.

*** Louis and Clarke
Looking for the water root of the Missouri River.

Flipped over the Rockies to hope to find the ocean, but no. It is not the ocean: its more land! They carried on, traded with the Native Americans for sustenance, and finally reach the Pacific Coast.

York, their slave, gets here the first vote to make the decision whether or not to return after the Pacific. The wife of a Frenchmen helped navigate the diplomacy of the group and translates. She helped create the opportunities for trade.

They make it back alive.

*** Louisiana Purchase 
Naepolean needed money.

** Madison
War of 1812 hits, US was at war with England to get Quebec. Naepolean was defeated in Europe, and DC was eventually burned. Also Andrew Jackson was fighting this war.

** Monroe
The Missouri Compromise tries to keep the senate balance by bringing Maine as a free state: creating a 36*30 line. Monroe Doctrine: tried to push out England and France and will protect Latin America; this would therefore establish hegemony and a sphere influence ("England protected the 13 colonies, too.")

* Antebellum Social Changes
- Women's Roles: limited freedoms & limited access to upper-class education
- Free African Americans in the North --- had freedoms and had no political/civil rights
- Second Great Awakening: religious ideas in the Americas transforms
  - Huge revival period of religions (like the '60s, '70s, '80s)
  - Pushing for things to reform society
