:PROPERTIES:
:ID:       E76DEC89-743F-4B3F-8DA3-C7A50667AB00
:END:
#+title: New Deal Primary Sources
#+author: Houjun Liu

* FDR
:PROPERTIES:
:ID:       156A55FC-A3F0-434B-A1D2-144A02635FF7
:NOTER_DOCUMENT: Great Depression - Primary Sources.pdf
:END:
** Swiftness as a important standard
:PROPERTIES:
:NOTER_PAGE: (11 . 0.7748344370860927)
:END:
I will address them with a candor and a decision which the present situation of our nation impels
** Comments on the need to remove political backwash/sluggishness
:PROPERTIES:
:NOTER_PAGE: (11 . 0.8225165562913908)
:END:
This is pre-eminently the time to speak the truth, the whole truth, frankly and boldly.
** Cities are oversubscribed
:PROPERTIES:
:NOTER_PAGE: (12 . 0.13245033112582782)
:END:
Hand in hand with this, we must frankly recognize the overbalance of population in our industrial centers
** That the founding of America had many more confounding variables
:PROPERTIES:
:NOTER_PAGE: (12 . 0.1576158940397351)
:END:
We are stricken by no plague of locusts. Compared with the perils which our forefathers conquered because they believed and were not afraid, we have still much to be thankful for.
** That great depression is a failure of leadership
:PROPERTIES:
:NOTER_PAGE: (12 . 0.2675496688741722)
:END:
Primarily, this is because the rulers of the exchange of mankind's goods have failed through their own stubbornness and their own incompeteµce, have admitted their fail­
ure and abdicated.
** International trade are less important than good internal circulations
:PROPERTIES:
:NOTER_PAGE: (12 . 0.6384105960264901)
:END:
Our international trade relations, though vastly important, are, in point of time and necessity, secondary to the establishment of a sound national economy.
** That fullillment and monetary/social sucess are two different things
:PROPERTIES:
:NOTER_PAGE: (12 . 0.6887417218543046)
:END:
Recognition of the falsity of material wealth as the standard of success goes hand in hand with the abandonment of the false belief that public office and high political position are to be valued only by the standards of pride of place and personal profit
** If congress is slow, he will not be afraid to act
:PROPERTIES:
:NOTER_PAGE: (13 . 0.1947019867549669)
:END:
But in the event that the Congress shall fail to take one of these two courses, and in the event the national emergency is still critical, I shall not evade the clear course of duty that will then confront me.
** It is possible to do changes without political change
:PROPERTIES:
:NOTER_PAGE: (13 . 0.4198675496688742)
:END:
Our Constitution is so simple and practical that it is possible always to meet extraordinary needs by changes in emphasis and arrangement without loss of essential form
** That change is the democratic process working
:PROPERTIES:
:NOTER_PAGE: (13 . 0.4741721854304636)
:END:
The people of the United States have not failed. In their need they have registered a mandate that they want direct, vigorous action
** That his acts are on behalf of the best interests of the people
:PROPERTIES:
:NOTER_PAGE: (13 . 0.5298013245033113)
:END:
They have made me the present instrument of their wishes. In the spirit of the gift I take it.
** It is possible, though, that procidural changes may need to take place
:PROPERTIES:
:NOTER_PAGE: (13 . 0.543046357615894)
:END:
But it may be that an unprecedented demand and need for undelayed action may call for temporary departure from that normal balance of public procedure.

* Woman on the Breadline
:PROPERTIES:
:ID:       8EF292ED-7A20-4F46-AE32-BC866F79BF8C
:NOTER_DOCUMENT: Great Depression - Primary Sources.pdf
:END:

** That there is food accessible but not reachable is painful
:PROPERTIES:
:NOTER_PAGE: (7 . 0.9175675675675676)
:END:
Is there any place else in the world where a human being is supposed to go hungry amidst plenty without an outcry
** there is simply a lack of available jobs
:PROPERTIES:
:NOTER_PAGE: (7 . 0.9311258278145695)
:END:
We sit here every day, waiting for a job. There are no jobs
** There is a connection of emotion but not words
:PROPERTIES:
:NOTER_PAGE: (8 . 0.20794701986754968)
:END:
That is why we don't talk; much. We look at the floor dreading to see that knowledge in each other's eyes: There is a kind of humiliation in it.
** That people are seperated among both sides, having no jobs and no opportunities
:PROPERTIES:
:NOTER_PAGE: (8 . 0.5509933774834437)
:END:
The woman in charge flew into a rage that probably came from days and days of suffering on her part, because she is unable to give jobs, having none
** There are both young and old out of a job
:PROPERTIES:
:NOTER_PAGE: (8 . 0.6119205298013245)
:END:
There are young girls too, fresh from the country. Some are made brazen too soon by the city.
** Sense of security with seeing someone's eyes
:PROPERTIES:
:NOTER_PAGE: (8 . 0.8211920529801324)
:END:
Her blue eyes are not clever but slow and trusting.
** That people are not saving, and are overly materialistic
:PROPERTIES:
:NOTER_PAGE: (9 . 0.22913907284768212)
:END:
No one saves their money, she says, a little money and these foolish young things buy a hat, a dollar for breakfast, a bright scarf. And they do.
** That urge to get status is a kind of death
:PROPERTIES:
:NOTER_PAGE: (9 . 0.4013245033112583)
:END:
You know it is suicide but you can't help it
** That a social standing became more important than life
:PROPERTIES:
:NOTER_PAGE: (9 . 0.40927152317880794)
:END:
A woman will shut herself up in a room until it is taken away from her, and eat a cracker a day and be as quiet as a mouse so there are no social statistics concerning her
** Prostitution is also technically difficult
:PROPERTIES:
:NOTER_PAGE: (9 . 0.543046357615894)
:END:
It's very difficult and humiliating to sell one's body.
** There is a nakedness inselling onself or labour
:PROPERTIES:
:NOTER_PAGE: (9 . 0.7258278145695364)
:END:
It is even harder to try to sell one's self, more humiliating. It is even humiliating to try to sell one's labor.When there is no buyer.
** That there are helpful men who would board girls?
:PROPERTIES:
:NOTER_PAGE: (9 . 0.7708609271523179)
:END:
I have known girls to sleep in men's rooms for the night on a pallet without molestation and be given breakfast in the morning
** Its easier to find work and support when single
:PROPERTIES:
:NOTER_PAGE: (9 . 0.8291390728476821)
:END:
It's no wonder these young girls refuse to marry, refuse to rear children.
** Work may never pay off either
:PROPERTIES:
:NOTER_PAGE: (10 . 0.43973509933774835)
:END:
The endless labor, the bending back, the water­ soaked hands, earning never more than a week's wages, never havingin their hands more life than that
** That there is no fulfillment
:PROPERTIES:
:NOTER_PAGE: (10 . 0.5019867549668874)
:END:
suffering of endless labor without dream, ... being a slave without the se­
curity of a slave
