:PROPERTIES:
:ID:       52604F20-B9B8-4D8B-BF90-E769CEB61C10
:END:
#+title: Oil Logistics in the Pacific War - Donovan 2001
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: ADA407830.pdf
:END:
** :claim: a large reason why Japan went to war with the United States was over oil
:PROPERTIES:
:NOTER_PAGE: (7 . 0.3152317880794702)
:END:
A secure and reliable source of oil was one of the primary reasons that Japan chose to go to war with the United States that fateful Sunday in December 1941.
** This seems like a very grand takeaway.... Not sure if.
:PROPERTIES:
:NOTER_PAGE: (7 . 0.6596026490066225)
:END:
Commanders and their staffs must never forget the importance operational logistics plays in achieving operational and national objectives. ... Although it is valuable to learn from one’s own personal mistakes, it is usually less painful to learn from someone else’s error, and thereby ensure that their blunder does not become your own.
** :claim: oil is a central element
:PROPERTIES:
:NOTER_PAGE: (8 . 0.44827586206896547)
:END:
Oil played a crucial, if not the key, role in the Japanese decision to go to war with the U.S. in 1941.
** Japanese tried to develop Netherlands East Indies as a potential source of oil
:PROPERTIES:
:NOTER_PAGE: (9 . 0.23607427055702918)
:END:
Thus, the NEI was deemed to be more malleable to Japanese desires than the increasingly recalcitrant U.S. Some of the Japanese demands included participation in NEI natural resource development, freedom of access and enterprise in the NEI, as well as a steady supply of oil.
** US initial embargo from shipping oil was due to the need to maintain stability of supply
:PROPERTIES:
:NOTER_PAGE: (9 . 0.759946949602122)
:ID:       F2D2579E-2E82-4ADE-BB13-EEF63F2963BD
:END:
To ship fuel out of areas with shortages to semi-belligerent foreign governments was politically untenable for the U.S. government. Thus from Japan’s point of view, the commodity most desired by them was being choked of
** Japan moved to the French Indochina mostly to protect itself in case of war, but made war inevitable
:PROPERTIES:
:NOTER_PAGE: (10 . 0.5384615384615384)
:END:
The Japanese were not making this move as a step towards provoking the U.S., Britain, or the NEI to war; Tokyo wished economic negotiations to continue. The move into southern Indochina was a preemptive action that would help the Japanese if conflict with the ABCD powers became inevitable
** Japanese felt that US economic sanctions were not actually possible because
:PROPERTIES:
:NOTER_PAGE: (11 . 0.09946949602122016)
:END:
Japanese felt that the U.S. would not follow through with such a move, because it would provoke
a war at a time when the U.S. was not ready to fight.
** US + UK coordinated response to Japan
:PROPERTIES:
:NOTER_PAGE: (11 . 0.23342175066312995)
:END:
Therefore, reaction from the U.S. was swift. With the Japanese movement into southern French Indochina, the U.S. froze all Japanese assets on 25 July 1941. The governments of Great Britain and the NEI soon followed with their own freezing actions.
** There was originally a lifeline for the Japaneses to apply for a license for oil export, but no approvals were granted
:PROPERTIES:
:NOTER_PAGE: (11 . 0.553050397877984)
:ID:       EDFBC302-10C7-4F44-B02D-9E6404128AA0
:END:
Roosevelt’s freeze order allowed the Japanese to apply for export licenses for oil; however, hard-liners within FDR’s administration acted if the freeze was total, so no licenses were ever approved.
** Although the Japaneses wanted better strategic position by occupation, they are now cut off economically
:PROPERTIES:
:NOTER_PAGE: (11 . 0.649867374005305)
:END:
This situation put the Japanese into a quandary; they did not gain any oil by moving into southern Indochina. Now they had isolated themselves from 90% of their annual requirements.
** Systemic Japanese saw eventual US Japan conflict, its just a matter of time
:PROPERTIES:
:NOTER_PAGE: (13 . 0.41379310344827586)
:ID:       4EA5ABFA-15FB-4F50-8717-6E1CE5EFC19B
:END:
All these factors played into the Japanese belief that they eventually and inevitably would come into conflict with the U.S. As far back as 1909, the U.S. was identified as one of the principal enemies of Japan.
** Japanese defense strategy against US was passive, and so ridding American ships at the Pearl harbor seemed to be more appealing
:PROPERTIES:
:NOTER_PAGE: (14 . 0.6140583554376657)
:END:
Japan would have to devote the majority of its fleet to support amphibious landings if the Southern Operation of seizing the NEI and Malay barrier was to succeed. ... If that fleet could be neutralized or destroyed at Pearl Harbor, it would deprive the U.S. fleet of any initiative and allow the Japanese to run unhindered in the Southern area.
** The attack of pearl harbour is a terrible idea according to navy doctrine
:PROPERTIES:
:NOTER_PAGE: (14 . 0.8183023872679045)
:END:
This line of thought ran totally counter to 30 years of navy doctrine, and
ordinarily it would have been dismissed out of hand
** Japanese placed a lot of value on Areial warfare, and to take out the US pacific fleet in one swoop
:PROPERTIES:
:NOTER_PAGE: (15 . 0.46949602122015915)
:END:
Yamamoto placed a heavy emphasis on aerial warfare due to an earlier posting with the air arm of the IJN. With the advances the IJN made in aerial warfare, Yamamoto began contemplating an aerial strike at the U.S. Fleet at Pearl Harbor.
** Japan, with the plan in hand, decided to move forward with the war if there was diplomatic impasse
:PROPERTIES:
:NOTER_PAGE: (17 . 0.5053050397877984)
:END:
It was decided at the 5 November 1941 Imperial Conference that Japan would go to war with the U.S. (and Great Britain), if negotiations to break the diplomatic impasse were not successful by 1 December 1941
** Japanese attacked because it would have ran out of oil in about 18 months if it did not move forward with occupation
:PROPERTIES:
:NOTER_PAGE: (18 . 0.34615384615384615)
:END:
If this did not occur, adding in such factors as normal stockpile depletion and getting the oil fields back into production, the Japanese would run out of oil in about 18 months.
** :claim: To Japan, the attack would solve both the occupational, self-sufficient, and diplomatic problems
:PROPERTIES:
:NOTER_PAGE: (18 . 0.7241379310344828)
:ID:       8AE07D25-0A86-4B0C-A211-C29C9C348050
:END:
The concurrent plan to seize the U.S. possessions in the Central Pacific would ensure that the Japanese would control all the oil producing regions between the West Coast of the U.S. and the Persian Gulf.
** The US also had an oil problem as well, and specifically had a great lack of oilers
:PROPERTIES:
:NOTER_PAGE: (22 . 0.4522546419098143)
:END:
All major fleet logistics, repair, and storage were at the naval base at Pearl Harbor. The U.S. Navy also suffered from a severe shortage of oilers which limited the operations radius of the Fleet.
** The US had also been out of oilers
:PROPERTIES:
:NOTER_PAGE: (31 . 0.383289124668435)
:END:
Although there had been an increase in the number of fleet oilers, they were all kept busy ferrying fuel between bases
** The lack of fuel limited the reach of the pacific fleet, leaving the japanese worry unfounded?
:PROPERTIES:
:NOTER_PAGE: (31 . 0.48408488063660476)
:ID:       E9C669B2-5DC6-4913-AB22-9FA2E9C15D1E
:END:
This shortage of tankers effectively limited the radius of the Pacific Fleet
** :claim: The Japanese should have attacked the oil supply instead
:PROPERTIES:
:NOTER_PAGE: (31 . 0.7586206896551724)
:END:
Thus, the fleet was tied to its oil supply at Pearl Harbor48and if the Japanese had attacked the oil storage and the associated oilers at Pearl Harbor on 7 December, they would have driven the U.S. Pacific Fleet back to the west coast
