#+TITLE: Post Revolution
#+AUTHOR: Houjun Liu

* The Articles of Confederation Sucked, so We Don't talk about it

* Writing the Constitution
:PROPERTIES:
:ID:       09A45E6D-F4C0-4B15-8874-A1FCD7F051FF
:END:

- People are entrenched in their positions
- There was a coordinating effort needed, and Washington provided final thoughts and synthesis.

** On Slavery
"The root of Evil is Greed" --- greed drove slavery. Hence, we need to be conscious of our greed: that people want to not have to work and for others to work for themselves.

Each generation shoves its problems down.

** On States
People identify with their states, not with the government. For instance, from the time up until the civil war, people still strongly identified with their states.

#+begin_quote
I go where Virginia goes.
#+end_quote

--- Robert E. Lee

Therefore, people advocated strongly with state interests.

* The Plan of the Government
:PROPERTIES:
:ID:       5177DA8F-DC77-45CB-AF5F-69C08B18961B
:ROAM_ALIASES: "US Government Setup"
:END:

The Process of Crocheting a Government...

** We the People
De-Identify with states, and to begin to think about all of the people (i.e. rich white men.) What changes through the constitution is {amendments, and **interpretations**}.

Interpretations are a system that evolve and change over time, to adapt old texts to new meaning.

** Key Concepts of the Constitution
*** Three Branches
:PROPERTIES:
:ID:       B93F5619-1AFC-4E84-9889-D8A08D876E68
:END:
- Legislative Branch: this should be the "more powerful" branch, it's article I
- Executive Branch: job was to execute the laws that legislative branch put out there
- Judicial Branch: very little thought of, but technically helps understand laws

*** Checks and Balances
1. Legislative Branch comes up laws that checks executive branch
2. Judicial Branch interpreted law

*** Federalism
"Federalism": certain powers can only be national government, some powers reserved for the states.

**** National
- Foreign Affairs
- Currency
- Military

**** State
- Education
- Community (police, etc.)

*** Changes and Amendments
1. Change the constitution: amend it
2. Reinterpret the constitution: judge it

** Roles for the Branches of Government
:PROPERTIES:
:ID:       F6185B8F-6D0B-42C7-9B31-57C7A7C2E7D4
:END:

The US government is intentionally inefficient.

*** The Legislature
- Congress controls budget
- Congress has power to declare war: wanted people to not be able to blame one person for everything
- Senate approves Ambassadors, Treaties and Justices
  - Senate has checks on executive branch
  - Senate is considered more powerful
- Congress can impeach presidents

+ Power over judicial: confirms nominations & could impeach judges
+ Power over executive: approves nominations and and controls the budgets. Could override the Presidents's vetos and remove a president from office

*** Executive Branch
- Could propose laws and suggest budgets to the house, who will put it into a vote
- Did not want tyranny of one person controlling to the military
- Commander in Chief still centralized to make war-making efficient
- Appoints ambassadors and justices

+ Power over judicial: could appoint judges
+ Power over legislative: could veto laws

*** Judicial
Nominated by presidents and interpret laws could change the interpretation of laws.

Checks and balances figure balances figure

+ Power over executive: could declare presidential acts unconstitutional
+ Power over legislative: could declare laws unconstitutional

**** Laws vs. Amendments
Amending the constitution takes an enormous super-majority. States must ratify the amendments. Laws are changed by various interpretation by the judicial branches.

** Federalism

Pro national government. Against Anti-Federalists, who advocated strong state rights and didn't want national layer.

*** "Delegated Powers": National
- Declare war
- Negotiate treaties
- Issue money
- Regulate interstate & foreign trade
- Military forces

*** "Concurrent Powers": Both
- Levy taxes
- Define *crimes* and their punishments
- Determine voting qualifications: yes, states actually decide
- Borrow money

*** State Powers (TBD, didn't have time)
- Education and society
- Societal governance

** Ratifying
- Constitution was only ratified as a promise of the Bill of Rights were made
- The Amendment process allows for adjustments to the plan of government over time

* Readings about the constitution
- Latham Constitution: [[id:088740EE-5FB9-47D7-8095-1F0F92778C9F][Latham on Constitution]]
- Fed vs Anti Fed: [[id:34F564F9-251F-4D1E-A651-B5C47D7B9066][Fed vs Anti Ped Papers]] 

*Reflection*

1. I believe that Dickinson would have a fairly positive response to the Constitution (which, demonstrably, he did.) Having been an usually moderate framer, Dickinson's chief concerns surrounds that of the representation that a small state Delaware gets in the larger federal government. The Connecticut compromise --- a bicameral plan for the legislature --- was successfully introduced into the Constitution, which in kind signifies the rhetorical success of Dickinson. Although he did not achieve the full halt of the slave trade as he wished, Dickinson nevertheless supported the passage of the constitution and thought of the slave trade as a side agitation that could be addressed later.
2. I agree that absolute democracy, as Latham highlighted, cannot practically be achieved while respecting the conflicting wishes of all classes (i.e. respecting freedom vs. regulating security/trade, etc.) --- paradoxically preventing the "democratic" resolution that respects the opinions of both. However, I don't necessarily agree with the frame of the ratification of the constitution as a light coup d'etat. The chaotic start of the United States signifies the exploration of a sense of unknown, and not necessarily a systemic failure. The Constitution simply takes the unreconcilable issues with the previous system in perspective and syntheses a largely-improved program that, while respecting the democratic ideals of the original declaration, revises the terms of union to actually be practical.
3. Being in and reaping the benefits of the federalist system in the United States, I have a very biased lens with respect to how an anti-federalist society would result. What I found very interesting about Federalist Paper 10, however, is its claim that a larger and purely-democratic society is susceptible to functioning. In the current American system, some degree factioning may actually help expedite the deadlock to which the Federalist-driven two-party system has granted. I nevertheless fully agree with the idea that Federalism perhaps increases central executor space and allows the protection of minority opinions. Hence, although a combination of Federalism with a degree of freedom maybe helpful for the American landscape, the current system is likely one of the best to maintain governmental function.
