:PROPERTIES:
:ID:       191D9305-CDBF-433A-9DCA-EC746421148F
:END:
#+title: Self Evals: MATH520 Sem. 1
#+author: Houjun Liu

Write a thoughtful personal essay/memoir about your semester in MVC, describing your experiences, adventures, successes, and failures this fall!

You should write introductory and concluding paragraphs, and a couple paragraphs about each of the two main topics we've discussed this fall (baby lin alg and high-dimensional differentiation). Describe what you learned, how you felt about the material at the time and how you feel about it now, what was challenging or frustrating about it, and what successes you had that you're proud of. The last two could be about specific problems, or about a more general mathematical/intellectual theme. Were there specific problems you really enjoyed? Or with which you really struggled? Were there ideas that you thought were really cool that are still in your mind? Or things you feel you still don't full understand, but wish you did? How has your knowledge of calculus deepened since last year? What things do you understand better?

Because you've all been TeX'ing up your problem sets for the last month or two, I'm also curious about how that's affected how you think about/communicate/work through math, etc.

I think most of you know this about me, but it's worth repeating: I care a lot about self-evals, and I'm NOT looking for a bunch of clichés. I don't want you to just say what you think your teachers want to hear in self-evals. Rather, I'm just looking for an honest, detailed, thorough reflection on the semester.

-----

What I really appreciated in the process of me learning MVC this year is the combination of familiarity and nuance which exists in MVC. This experience actually reflects similarly with the act of re-reading the Axler textbook for Linear Algebra --- that, my work despite I had a general idea of MVC while in my Single Variable Calculus education, my more "solid" definition of MVC did not come until the introduction of this class.

For instance, we spent much time actually solidifying my knowledge of vector projections in an engineering perspective. Because of the fact that my background in "baby linear algebra" was much more theoretical in basis, getting the "numerics" of Linear Algebra was very helpful in actually projecting these ideas into similar concepts in physics.

In terms of optimizations, the problem sets allowed me greater ease to explore high-dimensional space, and to be able to quickly apply ideas to practical problems involving optimization. The knowledge in this class also helped with tasks in machine learning --- exploring ideas in gradient descent with a more solid mathematical background.

Exploring note-taking, I was able to integrate SageMath into my workflow and perform the in-line graphing and mathematics utilities into my TeX documents. This allowed greater freedom and a faster throughput in performing the route "work" of calculations, while creating space for quickly rendering graphical representations of elements. 

Overall, this class allowed me the opportunity to explore unique tools, solidify techniques, and created more solid background for calculus from which I could solve for properties in the physical world.
