:PROPERTIES:
:ID:       CD67AC28-8735-4C42-9B2A-54EEBD66CE6D
:END:
#+title: Self Evals: CS240 Sem. 1
#+author: Houjun Liu

* Share an example of something that made you proud (for instance, a difficult problem you solved in one of your projects or an improvement you made to your work).
What I am most proud of in this was my implementation of a semi-working parallel-processing rainbow table that was able to crack MD5 password hashes for ciphertext up to 5 characters long. Although --- especially for MD5 --- faster solutions for password deciphering exists --- the fact that the algorithm was able to reasonably guess a ciphertext was exhilarating to see. Added to this challenge was my decision to use Rust (a language completely new to me at the time of the assignment), which eventually led me down a track of both learning the language itself but also exploring its parallel-processing tools: one of its greatest strengths.

* Of the concepts we discussed, which one(s) did you find most interesting or surprising, and why?
I found the discussion of "overflows" as part of user-input validation the most particularly surprising part of the course. Although I was aware of buffer and integer overflows prior to the class, I have also thought of "computer security" as a concept that involves more of an direct-approach of breakage (not unlike engineering an apparatus) instead of something that more leverages the inherent properties of near-hardware design.

* What concepts did you find most challenging, and why?
I believe I was most challenged by implementing the rainbow table. To make such an algorithm work --- though the basic design is quite simple --- there are many small implementation details for which the algorithm was either initially inefficient or otherwise completely incorrect (as in the case for the reduction function) on. Therefore, there are many design challenges which needed to be resolved as part of the assignment.

* What are some ways that you displayed good habits of mind or contributed to a good learning environment in the class?
The ability to self-reflect was the most useful piece of information that I gained from this class. That, per every task I took, there needed to be a self-reflective component by which I evaluated my work against typical benchmarks. For further performance tasks in the job field, this type of reflection may also help me better advocate for myself and my work.

* What was the most useful or memorable piece of feedback you received this semester, and how did you act on it?
By most memorable piece of feedback surrounds the construction of the authorization scheme. We had a long and fruitful discussion, as a continuance for our midterm parent-teacher conferences, regarding the balance between well-maintained, robust code vs. small, elegant code. We attempted to put this balance in perspective as we navigated the design decisions on the 
