:PROPERTIES:
:ID:       03888566-DC61-4082-BDDA-8023DBDD2E92
:END:
#+title: Self Evals: HIST301 Sem. 1
#+author: Houjun Liu

This course invited you to be engaged into a cohort of interdependent learners and teachers in the classroom. Did this emphasis help you in this class? To what degree were you able to make a full commitment to this invitation?

I was very captivated by the novel read-discuss-synthesize cycle that was especially prevalent over the last few days of class. I feel like the free-form, "harkness" like discussion format allowed us greater freedom to understand and explore nuances of history in a way that turned to be highly fruitful as well as engaging in a way that a more "rigid" class format would not have been able to provide. The deep engagement that my peers had in the class was also very helpful in my ability to be engaged as part of the course content. Throughout this class, I have also been helpfully encouraged to "share the mic" --- participating in discussions and engaging my group in a matter that not only allows my own synthesis but also supports that of the others. In the next semester, I hope to continue to work on this aspect of my learning: creating systems and guardrails in place 
