:PROPERTIES:
:ID:       7E98317C-CCB1-4C46-8E9C-3B238EE355AE
:END:
#+title: The Many-Headed Hydra: Linebaugh and Rediker
#+author: Houjun Liu

* Thesis
The "Montley Crew" drew the lower class. (pg2, left)

- Working class
- Sailors and slaves

#+begin_quote
From mutary to insurrection, the motley crew became the driver of revolution and push America to the first ... of revolution.
#+end_quote

That the revolution was co-opted. The reading was about salor and slaves w.r.t. the revolution.

* Evidence
Montley crew would destroy the King's properties. Thought their own situation was pretty against slavery and participated against rebellious events. Driven to oppress and took advantage of the split to rebel. Talked about how rebellions are pretty fast-spread, there.

Bringing together sailors and slaves, the Montley crew was formed: sailors, slaves, etc. They had the energy to fight for freedom. Really believed the ideal of freedom, and were motivated to fight against it.

Montley crew against oppression and against subjugation.

When does the revolution get out of the Montley crew and get into the hands of the wealthy people?

- Wealthier, higher class land owners were utilizing, but were frightened by the montley crew
- Also wanted to maintain slave and maintain their economic status: want to advocate for the Montley crew but also maintain where they are

Both feared the Montley Crew and used their efforts. The wealthier landowners liked the physical drive of revolution, but also want to conveniently keep use these people.

That the Montley crew were the muscle which fought the revolution but didn't get the same relief from dept and problems as did the elite.


* Top Down vs. Bottom Up
Definitely bottom up. One group of people were dying (Montley), and the other group of people were actually reaping the benefits.

Every spot of the world were hunted by oppression: but the people he adopted this from were actually oppressed. They were fighting their own rights, and the wealthy landowners came in and went: "yes! us too." (smh.)
