:PROPERTIES:
:ID:       0E661E8F-0A9B-4220-B547-3FAA3791639F
:END:
#+title: US Navy Vis a Vi Embargo - Herzog 1966
#+author: Houjun Liu

* Reading Notes
:PROPERTIES:
:NOTER_DOCUMENT: 2022 - Influence of the United States Navy in the Embargo.pdf
:END:
** Steel and Petroleum is required for every war, both of which japan depended on 
:PROPERTIES:
:NOTER_PAGE: (2 . 0.39859154929577467)
:END:
MAJOR prereqms1tes to any war machine are steel and petroleum and in both categories Japan since its modernization depended heavily upon imports.
** Pearl harbour attack likely carried out on American fuel
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6098591549295775)
:END:
it is highly probable that the aircraft which attacked Pearl Harbor and the carriers which transported them across the Pacific operated on American fuel
** The US allowed fuel exports even despite it maybe used for Japanese war making
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6901408450704226)
:END:
Obviously, decisions were made which allowed exportations of oil to continue even in the face of the threat of war in the Pacific.
** US came up with a plan to cut Germanic and Japanese supply of oil
:PROPERTIES:
:NOTER_PAGE: (3 . 0.7098591549295775)
:END:
Britain was to get all its oil from the Caribbean area; Britain was to arrange with the Dutch government to destroy the oil wells in the Indies; and, finally, it was to concentrate bombing attacks on the synthetic oil plants in Germany. Where then, and how, would Japan and Germany get oil for war
** But, hesitate to implement cutting Japanese oil because it may accelerate Japan's move into the indes
:PROPERTIES:
:NOTER_PAGE: (4 . 0.15211267605633805)
:END:
A ban on oil might force the Japanese to make a decision about going into the Indies and Welles doubted that the American people were ready to support a counter military move.
** The scaled down oil ban, after some fiddilng, would not have hindered Japanese warmaking
:PROPERTIES:
:NOTER_PAGE: (5 . 0.4887323943661972)
:END:
By using the special blend of crude oil, which was not restricted, the Japanese could meet their gasoline needs
** :claim: The US navy was in favour of the embargo, and wanted an active role in how better to enforce it
:PROPERTIES:
:NOTER_PAGE: (6 . 0.21971830985915494)
:END:
The memorandum from Admiral Anderson was dually significant. First, it stated a position for the navy, namely, that since the embargo of oil was of interest to the navy, the navy was ready to give suggestions on how' better to enforce that embargo
** :claim: After the reciept of the Navy memo, Sec. Knox shared it with hardline groups
:PROPERTIES:
:NOTER_PAGE: (6 . 0.3676056338028169)
:END:
The second significance of the memorandum concerns its treatment after Secretary Knox received it. Not only was Knox in agreement with the suggestions contained in the subject memorandum, he wanted to share them with the leader of the "hard-line" group, Secretary Morgenthau.
** :claim: Part of the navy wanted tigher controls
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6253521126760564)
:END:
Obviously part of the navy favored tight controls.
** 9/27, the Tripartite Pact indicated that Japan fighting US is not if but when
:PROPERTIES:
:NOTER_PAGE: (7 . 0.24507042253521127)
:END:
On September 27, the Tripartite Pact between Japan, Germany, and Italy was signed, leaving little doubt that the United States would eventually fight Japan.
** Four sides of pressure was on the state department either to act or not act
:PROPERTIES:
:NOTER_PAGE: (7 . 0.4591549295774648)
:END:
- One faction wanted to hardline cut
- Other faction wanted to lower octane levels to make more work
- Navy wanted no war
- Dutch wanted America not to poke Japan too much

One faction, including Hornbeck and Norman Davis, stood for further use at once of American economic power as a deterrent, while Hamilton and his associates in the Far Eastern division advised otherwise. Morgenthau, Stimson, and Ickes wanted to lower the octane levels of exports; in the navy, though Knox still seemed inclined to use pressure, Stark and his admirals said that the navy was not ready for war. Meanwhile the Dutch were asking the state department to refrain from actions which would in­ crease Japanese pressure against the Indies.
** Plan Dog: America fight in conjuction with Britian against Germany, if forced, also fight Japan with defense and economy
:PROPERTIES:
:NOTER_PAGE: (8 . 0.4943661971830986)
:END:
It was his "Plan Dog," which proposed American military support to Britain to defeat Germany and if forced to fight in the Pacific against Japan, to fight a defensive war using eco­ nomic restrictions to limit the Japanese.
** The British wanted US to fight Japan
:PROPERTIES:
:NOTER_PAGE: (8 . 0.6352112676056338)
:END:
The British were active again in attempting to get United States co-opera­ tion against Japan.
** It became comercially disadvantageous to have oil exports
:PROPERTIES:
:NOTER_PAGE: (9 . 0.27605633802816903)
:ID:       E74B7001-BFAB-409B-A4D9-C0A81EAD9804
:END:
Japanese imports of oil now going forward at a rate for which there is no commercial justification.
** While the embargo is not passed, the Japanese gasoline imports continued to increase
:PROPERTIES:
:NOTER_PAGE: (10 . 0.14366197183098592)
:ID:       04F77134-5874-407B-AC7D-FAB51FA09D5B
:END:
In the meantime, Japanese imports of gasoline and crude oils from which aviation gasoline could be obtained continued to increase.
** The government promised to take stronger steps if Japanese were to advance into the far east
:PROPERTIES:
:NOTER_PAGE: (11 . 0.7760563380281691)
:ID:       AD5ED8FB-802C-471B-AE6C-57BB0863CE84
:END:
If Japan now took any overt step through force or through the exercise of pressure to conquer or to acquire alien territories in the Far East, the Government of the United States would immediately impose various embargoes,
** Higher navy officials supported the embargo
:PROPERTIES:
:NOTER_PAGE: (13 . 0.2211267605633803)
:END:
Throughout the period of embargo considerations the navy was divided. The secretary of the navy and certain officers below the senior admirals were for tight controls or even complete embargo.
** Lower naval personell refused the embargo
:PROPERTIES:
:NOTER_PAGE: (13 . 0.2661971830985916)
:END:
The chief of naval operations, who had the advantage of personal contact with the president and who agreed with the president's trusted Mr. Welles, opposed actions which would result in war with Japan
