#+TITLE: Forner take on causes of Civil War
#+AUTHOR: Peter Choi
#+DATE: 11/30/2021

* Immigration before the Civil War
Link: https://www.youtube.com/watch?v=f2smxup513o&list=PLSuwqsAnJMtyg3ROpOADVoW1NV5kmskFM&index=42

** Notes:
- 1815-1915, 30 million immigrants, huge number of immigrants
- mostly Europeans (old immigration)
  - Ireland was one of the main sources of immigrants
- Most of these immigrants went to the North
  - the Nothern population grows
  - A lot of the immigrants come through New York
- Why was there an increase in European immigrants?
  - European population was growing fast
  - factory system was disrupting peoples way of working
  - agriculture system became more industrialized
  - craft labor was being pushed out of europe in place of factories
  - there was also a lot of political "outcasts" that moved to the United States
  - A lot of the immigrants were poor
  - biggest push: the Irish Famine
- A lot of other places had an influx in immigrants as well
- The immigrants became the lowest part of the labor force, they did a lot of physical labor

* Immigrants in America:
Link: https://www.youtube.com/watch?v=6-UqUKFQa1s&list=PLSuwqsAnJMtyg3ROpOADVoW1NV5kmskFM&index=43

** Notes:
- Immigrants tended to live with other immigrants from the same country
- they did not try to culturally assimilate
- there was a decent amount of cultural mixing
- Irish "cluster" together in ghettos, they become a target of anti immigrant sentiment
- The idea of being "Irish" was something that came with immigration
  - there were many different places in the territory known as Ireland, that didn't really have anything to do with each other except for geographical location.
  - with migration these immigrants were clumped with people from the same place, but not necessessarily the same background
- In these ghettos there is a increase in crime and disease, the immigrants living in the ghetto get blamed for it
- Immigrants saved money

* The Politics of slavery:
Link: https://www.youtube.com/watch?v=qeCfEe__Q4g&list=PLSuwqsAnJMtyg3ROpOADVoW1NV5kmskFM&index=33

** Notes:
- before 1840s congress had the power to make rules about slavery
- during the 1840s, more two groups had power to make rules about slavery:
  1) the states (kind of the notion of popular soverneighty
  2) and thus the people
- Popular soverneighty makes it easy for the gov (they do not have to talk about slavery) and makes the people happy
- Wigs and dems have support in north and south, they do not want to talk about slavery because they have support of both slave and non slave states, so it would tear their party apart.
- South politicians proteced slavery
- North politicians did not really talk about slavery, it was not really an issue
- Growing numbers of antislavey groups in the north
- Polk was opposed by the northern politicians
- the wigs nominated taylor
- the dems nominated the popular sovernieghty guy
- see history notes for election of 1860 people running for president
- Free soil party: land was free of slavery, free of charge
  - it's candidates were established people
  - were the first to link personal economic interest with anti-slavery
  - Say nothing about the rights of free blacks, were not as extreme as abolishonists
  - free soil was a sign to the south that anit-slavery was becoming a more popular opinion

* The Fugitive Slave question:
Link: https://www.youtube.com/watch?v=8ADV566_9uc&list=PLSuwqsAnJMtyg3ROpOADVoW1NV5kmskFM&index=36

** Notes:
- Fugitive slave law is the strongest violation of the rights of the states enacted by congress before the civil war.
- It protected the institution of slavery
- Placed the power of the law in hands of commisioners
- the slaves did not have rights, was a trial for identification
- fines on people who help slavers, or people who refused to look for fugitive slaves
- free black people often got caugth up in this mess
- It was a situation in which slave law "entered" the north (extraterritoriality)
- People came the the US to find freedom, slaves had to leave the US to find freedom
- Slavery is usually debated it the abstract, it needs to be seen on the personal level as well
- there was some violence that followed this act
