#+TITLE: EXCERPTS OF RECONSTRUCTION HISTORIOGRAPHY
#+AUTHOR: Peter Choi
#+DATE: 12/13/2021

* Willam A. Dunnig, "The Undoing of Reconstruction," 1901 (The Atlantic)
- The reconstruction technically ended when the last state, Georgia, rejoined the Union
- The reconstruction left the following senario:
  1. Black people enjoyed equal political rights
  2. the Republican party was in vigorous life in all of the Southern states and held firm control in some of them
  3. Blacks had an influenec in political affairs out of all relation to their intelligence and property
- the cessation of the national military in 1868-1870, gave rise to the KuKlux
- the government was trying to send some military support to quell the KuKlux rise, but they were faced with the issue of white people not wanting to fight with black people, and the government could not ban either group from fighting in the military.

* WEB DuBois, excerpts from Black Reconstruction (1935)
- what history textbooks teach about the civil war is wrong:
  - the violence was caused by abolitionists
  - Black people did not put in effort to get emanpipated
- There is a need to rewrite history with less government documents and more primary source documents
- and then says fancily that racism is a problem


* Howard Zinn, excerpt from A People’s History of the United States (1980)
- The civil war was a fight to regain national terriroty, markets, and resources. Not a fight for civil rights.
- Right after the civil war there was this breif period in which black people were actually somewhat free
- they voted in black people and there was some mixed public education
- but then the south organized the Ku Klux Klan and the nothern poloticians had to weight support for black rights against stability in the south
- they chose stability in the south, especially with the rise in violenece

* Paul Johnson, excerpt from A History of the American People (1997)
- the reconstruction was where hatred against blacks was really formed.

* Heather Cox Richardson, “Letters from an American” Blog November 3, 2021
- there has been increased rhetoric against professors, especially if they teach about crictial race theory
- this is bad and we see this pattern with authoritative governments
- the main method of the republican party is these "cultural attacks"
- the voting rights crisis right now mirrors the restriction of black voting during the reconstruction
  - former Confederates insisted that black voting redistributed the wealth from white people to black peaple and that voting black was essentially socialism --> corrupt
- the federal government said that the south could not discriminate based on race, and so the south started to discrminate on things like property ownership, education and other things that disguised the racism
- then the government pushed back some more
- today we are in a similar place where the republicans are restriciting the right to vote, the pattern continues
