#+TITLE: The Civil War and the Story of American Freedom by Eric Forner
#+AUTHOR: Peter Choi
#+DATE: 12/6/2021

* Introduction
- Freedom and liberty are fundamental to Americans' identity
- Freedom and liberty are often used interchangeably
- Freedom and liberty (fal) are often looked back as a constant definition that did not change throughout history, but Forner thinks that the definition that changed (link to history is a series of arguments)
- This reading will focus on the definition of fal throughout the civil war

* "We All Declare for Liberty"
- Abraham Lincoln: "We all declare for liberty...but in using the same word we do not all mean the same thing"
  - the north saw freedom as everyone enjoying the products of their labor
  - the south saw freedom as the power to do as they please with other men, as well as their products of labor
- The North winning the Civil War changed the definition of freedom to the northern meaning
- The Civil War changed the idea of the power of the American Government:
  - The Gov got more power, but it was the power to "create positive social change"
  - it went from northeners not liking the gov because it supported slavery to liking the gov because it abolished slavery
- Civil War was a fight for slavery as well as the country --> a fight for less state rights and more power in the central gov because states rights was a more pro slavery stance
- North triumph meant new definition of freedom as well as a new nation coming out of the war that would be built on this idea of new freedom

* What is Freedom?
- After the war the notion of freedom became a hot topic of debate because that would define what would happen to enslaved peoples
- thus control of the definition was also a hot topic
- Through this lens, the definition of freedom post civil war was not some static definition, but rather a "battle ground" for debate
- there were three different "definitions" of freedom:
  - the one of the former slaves
  - the one of the Southern whites
  - the one of the Republican North
    
* Hiram Powers: /America/
- talks about how a Bust, was canstantly changed, and how that was a reflection of how the united states definition of freedom was constantly changing as well

* Alexander Gardner: /What Do I want, John Henry? Warrenton Virginia, November 1862/
- Contraband: slaves who escaped their Southern plantations and offered their service to the Northern army
- this was a topic of debate as to whether the north should have a slavery esc thing when they are ficting against it
- To a slave the definition of freedom was shaped by the historical context, so the rhetoric around the american revolution and the culture of freedom during the antebellum era, as well as their situation, slavery.
- Foner aruges, that to a slave, freedom was escaping slavery -- punishment by the lasch, the sepration of famililes, denial of access to education, the sexual exploitation of black women by their owners -- and sharing the privileges and entitlements of American citizen ship
- they adopted the exodus story to reflect this
- Politically freedom meant the right to vote, and land, though it was always changing because it was a slow expansion of more rights as opposed to a quick change over night
- the southerners defined freedom of african American slaves as small as possible to try to keep their slaves as slaves, mostely economically driven, black laws

* Susan Torrey Merritt: /Antislavery Picnic at Weymouth Landing, Massachusetts/
- there were antislavery fairs all over the united states.

* Samuel J. Miller: /Fredrick Douglass/
- Fredrick douglass had a painting painted of him and he tried to look very stern in the picture as to show his disappointment for slavery as well as dismantle the notion that African Americans were these weird uncivilized people (and dismalte the cartoon drawing ideas surrounding slaves)

* The Great Constitutional Revolution
- The need to define what slavery was and what freedom was was the main question of debate during the reconstruction
- It started with the 13th amendament that abolished slavery
- and then the civil rights act of 1866 that declared all people born in the US were citizens
- and then the 14th amendment made it part of the constitution.
  - the 14th also said that citizens had to have equal rights and protection from the law...
- Next the 15th barred states from making race qualifications for voting
- These changes were known as the Great Constitutional Revolution

* Boundaries of Exclusion
- After the civil war there were still boundaries of exclusion, for example the chinese exclusion act
- Same thing with Women's right to vote
  - slavery of marrige
  - a lot of the women's sufferage movement reflected the Slave's path do freedom
- the changes after the civil war were considered racical changes, and not fulfillment of the constitution
- after the war slaves did not have land, so they had to depend on their former owners for work creating a kind of sudo-slavery
- this solidified a kind of economic inequality in the United States

* Davide Gilmore Blythe: /Old Virginia Home/
- An analysis of a piece of art that gives us some insight as to what people thought about the civil war
- Bascially, although the slavers were free, it did not mean there was not still racism against them

* Constant Mayer: /Love's Melancholy/
- A panting of a mourning woman as a reflection of the gender envirenment in the reconstruction era, and kond of how there was this romanticization of missing one's husband
- a piece on the traditional roles of men and women
