#+TITLE: The Market Revolution in Early America: An Introduction
#+AUTHOR: Peter Choi
#+DATE: 10/30/2021

* what is the Market revolution?
- It is a loosely defined term meaning: the displacement of traditional and cultural control of economics to a more capitalist control of economic

* What led to the market revolution?
- The abundance of land and resources in America
- Ideals of freedom gave people the ability to spend more freely and thus spend more
- the culture/what the united states was built on of the US led to more market:
  1. pioneering
  2. innovation
  3. slavery
- a lot of the time the cause is attributed to the idea of liberal capitalism (freedom of economics), after the US broke away from the more restrictive economics under the crown, but this is a shallow answer to the cause of the market rebellion. There are three questions we can consider:
  1. how can we apply economic theory to what we saw during the market rebellion?
  2. how can we apply social theory?
  3. how can we apply cultural theory?

* Downsides of the market revolution
- there was a lot of economic instability 
