#+TITLE: American Revolution Historiography Essay Prep
#+AUTHOR: Huxley Marvit
#+COURSE: 
#+SOURCE: 


#flo #ret #disorganized #hw

--------------

# Historiography essay

#+begin_example
  title: prompt
  American Revolution Historiography Essay

  In a paper approximately 4 pages in length, write a synthesis essay using at least two of the American revolution articles. The goal of the paper is to write about the historiography of the American revolution, synthesizing different interpretations to make your own argument about the causes of the American revolution. 

  Synthesis writing is not that much different from what you did in 10th grade where you incorporated multiple sources while answering questions posed in the prompt. You are not summarizing the texts, comparing/contrasting, or making a judgement about how one source stacks up against another. Instead, you are using the sources to develop and advance your own idea about the revolution. 

  Your synthesis might take one of two general tracks (though I am open to discussing additional ideas as well):

  1.  Historiography: How might the sources help us to think about how histories of the revolution are told. You might think about the types of arguments the authors are making: do they construct a top-down or bottom-up narrative? Do they highlight political, economic, cultural, or ideological factors in their explanation of the events leading up to the revolution? What are the implications of these organizational and analytical decisions? Your paper might resemble a “state of the field” highlighting the insights and lingering questions from our accumulative understanding of the revolution. You might also highlight what is “at stake” in these arguments about the revolution
      
  2.  Historical synthesis: Using the evidence and insights from the authors, what kinds of conclusions might you draw about the revolution. You might look at different causal forces to talk about the radical potential or radical results of the revolution (or lack thereof). You might develop connections between the different analytical perspectives offered by the authors--for example, how might we look at ideological roots, elite anxiety, and popular participation as being constituent parts of a larger whole? Does the revolution represent an advancement in democracy or a continuation of elite rule? What sort of ideas, fears, and interests do the authors point to in describing the motivations of the different actors involved in the revolution?
      

  To assemble the material for your essay, you should feel free to utilize your notes from the presentations of other readings, consult with your classmates, and/or read parts of the other readings while preparing your essay. While your thesis should of course be your own original work, it is always a good idea to talk about your ideas with others, including your classmates.
#+end_example

what was the cause of the american revoltion?

thinking:

historians that we read think about causality wrong

proximal and distal causality?

infinite chain of causality

cause -> cause -> effect

multiple causes can lead to multiple effects which in turn have effects

there is no single cause! it fits into this graph-network of causes and
effects

essay: fit the causes of the american revolution into this graph
framework of cause -> effect

for example, being able to unite over shared rejection of goods might be
a proximal cause, but it is not /the/ cause of the revolution.

big idea: *NEW MODEL OF CAUSALITY* this is, historiography.

- summaries of the readings:

  - Holton: forced founders

    - economic situations!

      - each chapter about how lack of independence has negative
        economic impacts

    - elites had to do stuff because of their debt?

  - Wood: The Radicalism of the American Revolution

    - united by values
    - popular belief shaped by lived experience

      - this is what drove the revolution

  - Bailyn: The Ideological Origins of the American Revolution

    - british political radicals?
    - enslaving america via taxes?

  - Breen: The Marketplace of Revolution

    - social resources allowed people to unite across colonies

      - shared rejection of goods!

  - Linebaugh and Rediker: Many Headed Hydra

    - Not about great men, it's really about

      - sailors, slaves, mobs

    - marxist! rise of the proletariat!

[forced founders + ->

bailyn -> [wood, holton] ->

linebaugh: breen: [wood, holton] : bailyn <- time

- many different people united.

  - how did they unite?

- people could united their ideals through shared rejection of goods

  - why did they have the ideals?

- shared lived experience -- in debt

  - why did they have that lived experience -- why were they in debt?

- taxes!

  - why did they have taxes?

the complex nature of causality

outline: - thesis - causality is complex and historians pick a small
piece that matches a ideological agenda -

with this updated model, the "cause" of the revolution becomes
multifactorial {graph}

proximal - distal

given complexity, how do we think about causality? exponential
reweighting

C -> c --> c --> c -> E 1 2 3 4 ^ this c

them: [c, c, c] -> me: c -> c -> c

luck:

inp -> [] -> oup

[] = (divine) luck = [god*random]

A

A -> -> -> B e = c

#+begin_verse
  e != 0
#+end_verse

*primary cause is flawed*

history = [] -> oup [] ??

( { ) }

() {}

models: god random (luck) primary cause too interdependant

theology -> modernism -> postmoderism!

groups:

- theological

  - by god

- modernism

  - by cause

- postmodernism

  - no cause

- transcendent-modernism

  - graph

objective truth != exist useful truth = exist postmodern -> useful truth
!= exist

*** Thesis!
    :PROPERTIES:
    :CUSTOM_ID: thesis
    :END:
models of causality are based on

historians look for causes.

causes historians find

the concept of the cause of the american revolution has evolved

perceived cause has co-evolved with changes in the view of causality
itself -- it has gone from theological causality, to modernistic
causality, postmodernistic

*the frameworks in which we situate causes have evolved just as the
assigned causes themselves have changed. we can understand these
frameworks -- how they have shifted, and even where they should go -- by
looking at them from a higher level of abstraction: the evolving view of
causality itself.*

*** Outlining
    :PROPERTIES:
    :CUSTOM_ID: outlining
    :END:

- intro: models of causality

  - the frameworks in which we situate causes have evolved just as the
    assigned causes themselves have changed.
  - we can understand these frameworks -- how they have shifted, and
    even where they should go -- by looking at them from a higher level
    of abstraction: the evolving view of causality itself.

- theological causality

  - the american revolution was caused by god / divine intervention, and
    we can't hope to understand it

- modernistic causality

  - the american revolution was caused by this cause, and this lets us
    understand it

- postmodernistic causality

  - the american revolution had no cause, and we cannot understand it

- transcendent-modernism

  - the american revolution had a graph of causes, and while we may not
    be able to understand it, we can still learn from it

- conclusion

*** Evidencing
    :PROPERTIES:
    :CUSTOM_ID: evidencing
    :END:

- theological

  - breen, end of page 7.

    - "divine luck defying close analysis"

  - declaration of independence!

    - natures god
    - https://www.washingtonpost.com/news/volokh-conspiracy/wp/2015/07/05/the-declaration-of-independence-and-god/

- modernism

  - breen!
  - holton!
  - bailyn!
  - rettiker!

- postmodernistic

  - the existance of all these different intepretations?

- transcendent-modernism

  - my thing! with the graph!

*** finer
    :PROPERTIES:
    :CUSTOM_ID: finer
    :END:

- intro: models of causality

  - the frameworks in which we situate causes have evolved just as the
    assigned causes themselves have changed.
  - we can understand these frameworks -- how they have shifted, and
    even where they should go -- by looking at them from a higher level
    of abstraction: the evolving view of causality itself.

- theological causality

  - the american revolution was caused by god / divine intervention, and
    we shoudn't try to understand it

    - breen, constitution
    - also includes just luck that we shouldnt try to understand

      - 13 clocks striking at the same time

  - asks: how do we please god?

- modernistic causality

  - the american revolution was caused by this cause, and this lets us
    understand it

    - while the actual causes vary, this model is the most prominent

      - causes vary from x to y

        - from holton to rediker

    - distinction from theological with god being the cause, is that
      modernism claims to be able to understand from their cause

  - asks: what were the true causes?

- postmodernistic causality

  - the american revolution had no cause, and we cannot understand it
  - this is the next logical step, from such a wide pool of perspectives
  - posits that no lessons can be learned; where transcendent-modernism
    differs
  - asks: nothing.

- transcendent-modernism

  - the american revolution had a graph of causes, and while we may not
    be able to understand it, we can still learn from it
  - while modernisism argues that there is a solution to the problem of
    history, postmodernism argues there isnt,

    - transcendent modernism argues we don't need one.

  - model causality as a graph with infinitesimal granularity

    - the graph!

  - how did the factors interact, and what can we learn from them?

- conclusion

  - ?? maybe,

    - all models of dealing with a "black wall" (instead of black box)
    - dont worry
    - heres the solution
    - there isnt a solution
    - there doesnt need to be a solution

*** Quote bin
    :PROPERTIES:
    :CUSTOM_ID: quote-bin
    :END:
*** fridge
    :PROPERTIES:
    :CUSTOM_ID: fridge
    :END:
as the very framework in which we situate causes has evolved just as the
assigned causes themselves have changed.

** Writing. Begin.
   :PROPERTIES:
   :CUSTOM_ID: writing.-begin.
   :END:
Grappling with causality is inherent in the historical analysis process.
This process is predicated on the concept of cause and effect;
constructed histories take an effect, assign a cause, then explain the
connection between them. Even with a single effect, say, the American
revolution, these histories take many different forms and evolve as time
goes on. They have shifted from arguments involving divine right,
through the "great men" narrative, and into economic and cultural
explanations. These are all assigned causes to the American revolution,
the evolution of which is a history in and of itself. However, just as
these assigned causes evolve over time, the frameworks these causes
reside in have coevolved. The very way we think about causality has
changed, allowing us to ask and consider new questions which are only
allowed to emerge in certain frameworks of causality. We can understand
these frameworks -- how they have shifted, what their limits are, and
even where they should go -- by looking at them from a higher level of
abstraction: the evolving view of causality itself.

One of the first frameworks took the form of theological causality, a
framework which most modern historians reject. This framework's causes
stem from the divine: god caused the American revolution to happen, and
we shoudn't try to understand it. The modern historian Breen points to
this framework as something that should be avoided in his 2004 book /The
Marketplace of Revolution/. He calls the histories emerging from this
framework

"a kind of divine blessing defying close analysis"

Causes in this framework stem from the divine, and thus, we should not
try to understandf

When applied to the American revolution,
