#+TITLE: American Revolution Historiography Essay Prep
#+AUTHOR: Huxley Marvit
#+COURSE: 
#+SOURCE: 


#flo #ret #disorganized #hw

--------------

# Historiography essay

#+begin_example
  title: prompt
  American Revolution Historiography Essay

  In a paper approximately 4 pages in length, write a synthesis essay using at least two of the American revolution articles. The goal of the paper is to write about the historiography of the American revolution, synthesizing different interpretations to make your own argument about the causes of the American revolution. 

  Synthesis writing is not that much different from what you did in 10th grade where you incorporated multiple sources while answering questions posed in the prompt. You are not summarizing the texts, comparing/contrasting, or making a judgement about how one source stacks up against another. Instead, you are using the sources to develop and advance your own idea about the revolution. 

  Your synthesis might take one of two general tracks (though I am open to discussing additional ideas as well):

  1.  Historiography: How might the sources help us to think about how histories of the revolution are told. You might think about the types of arguments the authors are making: do they construct a top-down or bottom-up narrative? Do they highlight political, economic, cultural, or ideological factors in their explanation of the events leading up to the revolution? What are the implications of these organizational and analytical decisions? Your paper might resemble a “state of the field” highlighting the insights and lingering questions from our accumulative understanding of the revolution. You might also highlight what is “at stake” in these arguments about the revolution
      
  2.  Historical synthesis: Using the evidence and insights from the authors, what kinds of conclusions might you draw about the revolution. You might look at different causal forces to talk about the radical potential or radical results of the revolution (or lack thereof). You might develop connections between the different analytical perspectives offered by the authors--for example, how might we look at ideological roots, elite anxiety, and popular participation as being constituent parts of a larger whole? Does the revolution represent an advancement in democracy or a continuation of elite rule? What sort of ideas, fears, and interests do the authors point to in describing the motivations of the different actors involved in the revolution?
      

  To assemble the material for your essay, you should feel free to utilize your notes from the presentations of other readings, consult with your classmates, and/or read parts of the other readings while preparing your essay. While your thesis should of course be your own original work, it is always a good idea to talk about your ideas with others, including your classmates.
#+end_example

what was the cause of the american revoltion?

thinking:

historians that we read think about causality wrong

proximal and distal causality?

infinite chain of causality

cause -> cause -> effect

multiple causes can lead to multiple effects which in turn have effects

there is no single cause! it fits into this graph-network of causes and
effects

essay: fit the causes of the american revolution into this graph
framework of cause -> effect

for example, being able to unite over shared rejection of goods might be
a proximal cause, but it is not /the/ cause of the revolution.

big idea: *NEW MODEL OF CAUSALITY* this is, historiography.

- summaries of the readings:

  - Holton: forced founders

    - economic situations!

      - each chapter about how lack of independence has negative
        economic impacts

    - elites had to do stuff because of their debt?

  - Wood: The Radicalism of the American Revolution

    - united by values
    - popular belief shaped by lived experience

      - this is what drove the revolution

  - Bailyn: The Ideological Origins of the American Revolution

    - british political radicals?
    - enslaving america via taxes?

  - Breen: The Marketplace of Revolution

    - social resources allowed people to unite across colonies

      - shared rejection of goods!

  - Linebaugh and Rediker: Many Headed Hydra

    - Not about great men, it's really about

      - sailors, slaves, mobs

    - marxist! rise of the proletariat!

[forced founders + ->

bailyn -> [wood, holton] ->

linebaugh: breen: [wood, holton] : bailyn

- many different people united.

  - how did they unite?

- people could united their ideals through shared rejection of goods

  - why did they have the ideals?

- shared lived experience -- in debt

  - why did they have that lived experience -- why were they in debt?

- taxes!

  - why did they have taxes?
