:PROPERTIES:
:ID:       D57C3037-E5BD-45CB-A8FF-AC7A0C3B6632
:END:
#+TITLE: Taproot

#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: author:nil

* Welcome
Howdy 👋, welcome to Taproot, the connected Zettlekastenish braindump of Huxley, Albert, Zach, Houjun, Dylan, Peter, and David. Take a look around, either in person or using this [[https://taproot3.sanity.gq][Handy Web Portal]].

This is the third version of the Taproot infrastructure. The website is set in =Helvetica Neue=, the generated PDFs are set in =Liberation Sans= and built using =xelatex=. Source files are written in or transpiled to =org= using =pandoc=, and built using =ox-html= and =org-publish=.

The software stack of Taproot is licensed under =GPL-3.0 License= and the text is licensed by =CC BY-NC-SA 4.0=. The license texts are available to view [[https://www.gnu.org/licenses/gpl-3.0.en.html][here]] and [[https://creativecommons.org/licenses/by-nc-sa/2.0/][here]] respectively.

Taproot is organized under a few global indexes of subject-specific areas. Enter Taproot by following down these lovely rabbit holes of notes:

* Notes

** School Notes
- Physics (Mechanics and EM): [[id:0E0AE645-9904-468C-AA37-100334B3B1B4][Physics Global Index]]
- Biology: [[id:1B1DC72F-80C5-4CF1-80B3-85AE4BE49C02][Biology Global Index]]
- Humanities @TheNuevaSchool
  - English: [[id:4576115D-0301-443C-9A74-D03095136AE7][English Global Index]]
  - History: [[id:0AB37414-6E00-4058-BF44-8A8BCB125283][History Global Index]]
- Mathematics (Calc, not calc, etc. etc.): [[id:BB405D47-99C4-43EA-AA0D-A424DB216E76][Mathematics Global Index]]
- Computer Science: [[id:9CB1B07C-C6E9-4EA0-957E-9FE6933CFA9B][Computer Science Global Index]]

There are secretly actually others, like Japanese or Spanish. But those are too bad for mere mortals to cast eyes on.

** Projects
Coming Soon!

** Personal Corners
- Huxley: [[file:corners/huxley/KBxSort.org][Sort! with Huxley]]
- Jack: [[id:D7528D4D-4CEE-4EC5-8ABF-11681B978B10][Jack's Personal Index]]
- David's entire notes: [[id:5EECF70E-52FD-438A-A5C9-BFE99195EFCE][David's Notes Index]]  

* Philosophy
Zettelkasten, maybe. But basically, create a repository of knowledge that should be easy to refer back to and effective for relearning things.
We strive to create atomic, self contained notes that link to other references. Think a more granular Wikipedia.

* Joining Us
Its probably a bit hard (we all go to school in the same area, we generally take similar classes, etc.)

* Epilogue
Thanks for stopping by!

A "taproot" is a "large, central, and dominant root from which other roots sprout laterally" [[https://en.wikipedia.org/wiki/Taproot][See Wikipedia]]. Also, it's a food!
