#+TITLE: Taproot

#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: author:nil

* Welcome
Howdy 👋, welcome to Taproot, the connected Zettlekastenish braindump of Huxley, Albert, Zach, Houjun, Dylan, and David. Take a look around, either in person or using this [[https://taproot3.sanity.gq][Handy Web Portal]].

This is the third version of the Taproot infrastructure. The website is set in =Helvetica Neue=, the generated PDFs are set in =Liberation Sans= and built using =xelatex=. Source files are written in or transpiled to =org= using =pandoc=, and built using =ox-html= and =org-publish=.

The software stack of Taproot is licensed under =GPL-3.0 License= and the text is licensed by =CC BY-NC-SA 4.0=. The license texts are available to view [[https://www.gnu.org/licenses/gpl-3.0.en.html][here]] and [[https://creativecommons.org/licenses/by-nc-sa/2.0/][here]] respectively.

Taproot is organized under a few global indexes of subject-specific areas. Enter Taproot by following down these lovely rabbit holes of notes:

* Notes

** School Notes
- Physics (Mechanics and EM): [[file:physics/index.org][Physics Global Index]]
- Biology: [[file:biology/index.org][Biology Global Index]]
- Humanities @TheNuevaSchool
  - English: [[file:english/index.org][English Global Index]]
  - History: [[file:history/index.org][History Global Index]]
- Mathematics (Calc, not calc, etc. etc.): [[file:mathematics/index.org][Mathematics Global Index]]
- Computer Science: [[file:cs/index.org][Computer Science Global Index]]

There are secretly actually others, like Japanese or Spanish. But those are too bad for mere mortals to cast eyes on.

** Projects
Coming Soon!

** Personal Corners
- Huxley: [[file:corners/huxley/KBxSort.org][Sort! with Huxley]]
- Jack: [[file:corners/jack/index.org][Jack's Personal Index]]
- David's entire notes: [[file:corners/david/index.org][David's Notes Index]]  

* Philosophy
Zettelkasten, maybe. But basically, create a repository of knowledge that should be easy to refer back to and effective for relearning things.
We strive to create atomic, self contained notes that link to other references. Think a more granular Wikipedia.

* Joining Us
Its probably a bit hard (we all go to school in the same area, we generally take similar classes, etc.)

* Epilogue
Thanks for stopping by!

A "taproot" is a "large, central, and dominant root from which other roots sprout laterally" [[https://en.wikipedia.org/wiki/Taproot][See Wikipedia]]. Also, it's a food!

