#+TITLE: Taproot

#+OPTIONS: toc:nil

* Welcome
Howdy 👋, welcome to Taproot. Take a look around, either in person or from our [[https://taproot3.sanity.gq][Handy Web Portal]]

* Take a Looksie
#+begin_export html
<div class="navrow">
    <a class="link-index" href="./theindex.html">
        <span class="link-callout">Index</span>
        <span class="link-desc">Start here for a concise summary of what's here!</span>
    </a>
    <a class="link-nav" href="./sitemap.html">
        <span class="link-callout">Navigation</span>
        <span class="link-desc">A lovely list of every note.</span>
    </a>
</div>
#+end_export

* Philosophy
Zettelkasten, maybe. But basically, create a repository of knowledge that should be easy to refer back to and effective for relearning things.
We strive to create atomic, self contained notes that link to other references. Think a more granular Wikipedia.

* Structure
At the moment, Taproot is organized by the course that each concept falls into.
The project was started with Zettelkasten style IDs prefixed with "KB", but was soon moved to semantic naming.

* Epilogue

Thanks for stopping by!

A "taproot" is a "large, central, and dominant root from which other roots sprout laterally" [[https://en.wikipedia.org/wiki/Taproot][See Wikipedia]]. Also, it's a food!

