:PROPERTIES:
:ID:       82B3744E-FD5D-4C0C-B2AB-35FD563A6171
:END:
#+title: Algos PS#6 FSM
#+author: Houjun Liu

* Fifteen Square Puzzle
From the definition of the problem, we have the state $(A,B)$:

- $A$ is a list $(a_1\ldots a_{15})$ with all the values skipping the empty square
- $B$ is a tuple $(X,Y)$ containing the coordinates of the empty square

We also define "out of order" as pairs of not-necessarily-continuous values that are not strictly increasing, and "parity" as $mod\ 2$ of the number of out-of-order pairs plus the row number of the empty square.

** Defining Transitions
For every single case, there is four possible transitions to make

1. Move empty square up
2. Move empty square down
3. Move empty square left
4. Move empty square right

** Proving Invariant
We will show that the base state has a specific parity. At $((1\ldots 15), (4,4))$, the starting base state, it has parity $0 + 4 = 0 (mod\ 2)$.

Let's declare parity $=0\ (mod\ 2)$ as the invariant.

** Proving Invariant through Transitions
Let's prove that invariant is invariant through all transitions. 

