:PROPERTIES:
:ID:       C74E94DF-D5B9-44C4-A49E-B08AC4E54542
:END:
#+title: Torque Number 8
#+author: Houjun Liu

* Problem 5: Energy Approach

** Velocity and Angular Velocity
Velocity at the top of the ramp: $0$. Because there are no sliding (hence there are no heat), there is not going to be another component (beyond rotational, translational, and potential energy.)

We know, then:

\begin{equation}
   \Delta KE +\Delta PE = 0 
\end{equation}

From the fact that the object slid from the top of the ramp ($h$), we know that the sliding took a total potential energy loss of $Mg\Delta h$. 

Therefore:

\begin{equation}
   -Mgh + \frac{1}{2} M{v_f}^2 + \frac{1}{2}I_o {\omega_f}^2 = 0
\end{equation}

Separating the variable off to both sides:

\begin{align}
    &\frac{1}{2} M{v_f}^2 + \frac{1}{2}I_o {\omega_f}^2 = Mgh\\
\Rightarrow & M{v_f}^2 + I_o {\omega_f}^2 = 2 Mgh
\end{align}

Because there are no sliding:

\begin{equation}
   {\omega_f} R = v_f
\end{equation}

We now have two equations and two variables:

\begin{equation}
   \begin{cases}
    M{v_f}^2 + I_o {\omega_f}^2 = 2 Mgh\\
   {\omega_f} R = v_f
\end{cases}
\end{equation}

Substituting the second result into the top expression:

\begin{equation}
   M{\omega_f}^2 R^2 + I_0{\omega_f}^2 = 2Mgh
\end{equation}

Finally, solving for $\omega_f$:

\begin{align}
    &{\omega_f}^2(M R^2 + I_0) = 2Mgh\\
\Rightarrow &{\omega_f}^2 = \frac{2Mgh}{(M R^2 + I_0)}\\
\Rightarrow &{\omega_f} = \sqrt{\frac{2Mgh}{M R^2 + I_0}}\ \blacksquare
\end{align}

Multiplying the expression by $R$ to figure $v_f$:

\begin{equation}
v_f = R\sqrt{\frac{2Mgh}{M R^2 + I_0}}\ \blacksquare
\end{equation}

** Acceleration and Angular Acceleration
Taking the timed derivative of $v_f$:

\begin{equation}
   a_{CM} = \frac{R}{2\sqrt{\frac{2Mg}{M R^2 + I_0}}} \frac{2Mgh}{M R^2 + I_0}} \frac{dh}{dt}
\end{equation}

to figure change in height, we see that, because of the ramp:

\begin{equation}
   \frac{dh}{dt} = \frac{d c}{dt} \sin\theta
\end{equation}

where $c$ is the ramp remaining.

Furthermore, we see that:

\begin{equation}
   \frac{dc}{dt} = \vec{v}
\end{equation}

Hence:

\begin{equation}
 \frac{dh}{dt} =  R\sqrt{\frac{2Mgh}{M R^2 + I_0}}\sin\theta
\end{equation}

Substituting this back to the expression:

\begin{align}
   a_{CM} &= \frac{R}{2\sqrt{\frac{2Mgh}{M R^2 + I_0}}} \frac{2Mg}{M R^2 + I_0}  R\sqrt{\frac{2Mgh}{M R^2 + I_0}}\sin\theta\\
&= R^2  \frac{Mg}{M R^2 + I_0} \sin\theta\ \blacksquare
\end{align}

The same logic follows for $\alpha$, simply without an extra constant of $R$ being multiplied. To figure out its derivative, then we can again divide $R$ out from the above expression to result in:

\begin{align}
   \alpha_{CM} &= R \frac{Mg}{M R^2 + I_0} \sin\theta\ \blacksquare
\end{align}

* Problem 6: Force and Torque 

** Figuring Torque
We will figure torque for the object, then use it for calculations. We will set the origin of the system to the lower-left of the triangle.

We will set the origin as being at the center of mass at the top of the ramp. Gravity and normal force, therefore, is coaxial with the center of mass in the world coordinate frame and hence not accounted for here.

We see that:

\begin{equation}
   I_0\alpha = -RF 
\end{equation}

Relating the slide down the ramp, by projecting the gravity vector onto the direction down the ramp; given that $\theta$ is the vertical incline of the ramp, $\sin\theta$ is the "horizontal" projection along the ramp:

\begin{equation}
Mg\sin\theta - F = Ma_x
\end{equation}

And finally, relating rotational and acceleration movements, given no sliding:

\begin{equation}
   a_x = R\alpha 
\end{equation}

We now have three expressions relating unknowns $\alpha$, $F$, and $a_x$. Substituting both expressions into the second:

\begin{align}
   &F = \frac{I_0\alpha}{R} \\
\Rightarrow & Ma_x = Mg\sin\theta - \frac{I_0\alpha}{R} \\
\Rightarrow & MR\alpha = Mg\sin\theta - \frac{I_0\alpha}{R} \\
\Rightarrow & MR\alpha + \frac{I_0\alpha}{R}= Mg\sin\theta  \\
\Rightarrow & \alpha\left(MR + \frac{I_0}{R}\right)= Mg\sin\theta  \\
\Rightarrow & \alpha\left(\frac{MR^2+I_0}{R}\right)= Mg\sin\theta  \\
\Rightarrow & \alpha= Mg\sin\theta \left(\frac{R}{MR^2+I_0}\right) \\
\Rightarrow & \alpha= R\left\frac{Mg\sin\theta }{MR^2+I_0}\right\ \blacksquare
\end{align}

We can see that the expression derived here is now exactly the same as that found with energetic methods above.

We can figure $a_{CM}$ by simply multiplying again the above expression with $R$:

\begin{equation}
   a_{CM} = R^2\left\frac{Mg\sin\theta }{MR^2+I_0}\right\ \blacksquare
\end{equation}

** Time to reach bottom
We can figure the time to reach bottom by integrating $a_{CM}$ twice then solving for time.

\begin{equation}
   \iint R^2\left\frac{Mg\sin\theta }{MR^2+I_0}\right\ dt
\end{equation}

Now, we understand that the initial velocity and position of the object is $0$. Hence:

\begin{equation}
   \iint R^2\left\frac{Mg\sin\theta }{MR^2+I_0}\right\ dt = R^2\left\frac{Mg\sin\theta }{MR^2+I_0}\right \frac{t^2}{2}
\end{equation}

To figure the time at the bottom of the ramp, we solve the above-derived expression for travel throughout the length of the ramp:

\begin{align}
    &\left\frac{R^2Mg\sin\theta }{MR^2+I_0}\right \frac{t^2}{2} = \frac{h}{\sin\theta} \\
\Rightarrow\ &t^2 = \frac{MR^2+I_0}{R^2Mg\sin\theta }\frac{2h}{\sin\theta} \\
\Rightarrow\ &t = \sqrt{\frac{MR^2+I_0}{R^2Mg\sin\theta }\frac{2h}{\sin\theta} }\\
\Rightarrow\ &t = \frac{1}{R\sin\theta} \sqrt{\frac{2h(MR^2+I_0)}{Mg}}\ \blacksquare
\end{align}

** Angular Velocity at the Bottom
We can figure the angular velocity at the bottom by taking a single integral of the expression for angular acceleration, then supplying the right-derived expression for $t$.

\begin{equation}
\int \alpha\ dt = \omega = tR\left\frac{Mg\sin\theta }{MR^2+I_0}\right
\end{equation}

Supplying the expression for $t$ above herein:

\begin{align}
    \omega_f &= R\left(\frac{1}{R\sin\theta} \sqrt{\frac{2h(MR^2+I_0)}{Mg}}\right)\left\frac{Mg\sin\theta }{MR^2+I_0}\right\\
&= \sqrt{\frac{2h(MR^2+I_0)}{Mg}}\left\frac{Mg}{MR^2+I_0}\right\\
&= \sqrt{\frac{2h(MR^2+I_0)}{Mg}}\sqrt{\left(\frac{Mg}{MR^2+I_0}\right)^2}\\
&= \sqrt{\frac{2Mgh}{MR^2+I_0}}\ \blacksquare
\end{align}

We can see that this result agrees with that above.

* Foods for Thought
- The object is currently rolling perfectly; apart from counteracting slide, friction does not translate the point of contact (otherwise, it would be doing sliding) at all---hence doing no work.
- The slope of the ramp, $\theta$ is not in the expression for $\omega_f$ --- meaning it has no influence on the final angular velocity.
