:PROPERTIES:
:ID:       C0D06323-3156-49E2-BD3A-4B947F665430
:END:
#+TITLE: La Historia de las Cosas
#+AUTHOR: Houjun Liu

Para mí, la cosa el más sorprendente es que, según el video, usamos 30% de los recursos y generamos 30% de los desechos en todo el mundo a pesar de tenemos solamente 5% de la población mundial. Esto hecho se muestra que la pérdida estupendo que lo entero complejo industrial genere. Para nos compensamos este uso de los recursos, necesitaríamos de 3-5 planetas para continuar este patrón de comportamiento. Y, durante nuestro uso y abuso de estos recursos, liberamos y añadimos unos químicos neurotóxicos que son destructivo para los usuarios. En este manero, tanto el usuario como el mundo está dañado.

Necesito más información sobre la economía de la industria de la moda. ¿Quiénes están los partes interesadas? y, ¿cómo lo apaciguamos? Además, ¿qué son los impactos tangibles en la cadena de suministro de decisiones sostenibles?

Mejoraré mi conciencia cuando la compra y reciclaje de mis cosas para optimizar a opciones más sostenibles. Porque no estoy muy materialista, pienso que, para mí, es más importante a hacer decisiones conscientes cuando en realidad soy hacerlos. Además, necesito aprender sobre el paisaje entero para hacer una buena elección para el planeta y yo mismo. 
 


