#+TITLE: Colonial America
#+AUTHOR: Houjun Liu
#+COURSE: HIST301
#+SOURCE: KBHIST301MasterIndex

* Talking about the Essay
See [[file:KBhIntersectionsEssayPrep.org][Intersection Essay Prep]].

** File Organization
- Take a look at "Colonial America, notes", which are the notes of the class
- A PDF of the slides are also available

** When is the draft due?
IDK. He still won't tell. :(

* European Colonization
A "world-wide imperial contest", a global political competition. Not primarily motivated by spreading /democracy/, its about Monies.

- Spanish: started the conquest, for the Spanish armada
- English: bubbling, for minor economic modivation
- French: interested in fur, and trying to maximize gain and investment

So, compare and contrast the three systems.

* Voyages of Discovery

** Motivations
- Rise of a /business/ oriented class
- Pooling of resources for investment
- Tech: astrolabe, maps, compass, better ships, etc.

** Mercantilism
A pair-relationship between colonies:

- Mother Country provides...
  - Finished products
  - Protection
  - Governance
- Colonies provides... 
  - Raw materials
  - Monopolies on market
  - Loyalty

* Colonizers

** Russians!
Russia traveling from west => east; competing with the northern going group.

** Spain!
"Superpower" built upon the Spanish Navy (the "armada.")

- Mission: churches religions and cultures (supposed to be self-sufficient)
- Presidio: military gates and posts
- Pueblos: living

*** Goals
- Find Gold!
- Acquire Land!
- Develop Trade!
- Christian conversion (mostly to get papal decree

*** Weaknesses
- Spanish empire stretched pretty thin
- Did not allow others to come trade, which means limited trade

** England!
Leveraged *Privateers*: pirates with royal decrees, to destroy ability. Defeated the armada by chasing them and sticking them into the English isle.

All business adventures to make money. Settlers were not as loyal because there were a group of dissidents, beggars, and ex-convicts. Also, they are not motivated by missionary reasons.

** France
French along the river systems. Everything flows from the river systems.

Based on *trade* rather than *architecture*. Leveraged the Fur Trade as the primary exclusive source of income.

* Colonized
- No respect for Native American cultures or strategies of land use
- Every mission courtyard had a place where those who disobeyed where wipped
- Father Junipero Serra: think that the native were "childlike" and required education

  -----

* Colonial America, the Thirteen American Colonies
The original British colonies sucked. The English didn't want for them to trade with each othere, but with England.

Oh by the way: Florida was /not/ the Thirteen Colonies


** Jamestown, Virginia
1607, John Smith's colonies. It was a Charter colony, it was a business by the order of the Crown.

- 50% Mortality in Year 1
- Not self sufficient: hunting gold instead of deer, did not plant enough
- Too many "gentlemen", not enough laborers. Smith: "He how will not work shall not eat."

John Rolfe introduces *tobacco*: provides economic foundation for Virginia. Tobacco causes cancer, and so if Barry catches you smoking he will....

- 1619: House of Burgesses formed; 1st elected representative body in North America
- 1619: First Africans sold; indentured servants became racialized
- 1622: Powhatan attack the settlement
- 1624: Crown buys Jamestown; it becomes a "Crown Colony"

** The Mayflower
Group of other "Pilgrims" arriving in the new New World. Agree to create a covenant, promising to obey" just and equal laws."

- "Covenant and combine ourselves together in a **civil body politic**"
- "Enact, constitute, and frame just and equal laws"

