#+TITLE: Indigenous Intersection Essay Prep
#+AUTHOR: Houjun Liu
#+SOURCE: KBHIST301MasterIndex
#+COURSE: HIST301

* General Information
| Due Date | Topic                                     | Important Documents       |
|----------+-------------------------------------------+---------------------------|
| ?????    | Synthesis Essay: Indigenous Intersections | - Facing East             |
|          |                                           | - Follow the corn         |
|          |                                           | - White's Middle Ground   |
|          |                                           | - Atlantic on Mann's 1941 |

* Prompt
*Indigenous intersections with European culture*

1. What is an idea, theme, or commonality that connects the resources to each other?
2. What is your own thesis concerning this idea, theme, or commonality?
3. How can my thesis be supported by evidence from various sources? Revisit your
sources and notes – do they support your thesis?

* Quotes Processing

** Kwotes Bin
- "Words like 'invasion' and 'conquest' may now trip more easily from our tongues than quaint phrases like "the transit of civilization, 'yet the “master narrative” of early America remains essentially European-focused." (Richter 8) AA
- "The paucity of historical sources and the enormous distances in time and culture that yawn between the twenty-first and seventeenth centuries make it impossible to see the world through her eyes." (Richter 9) AB
- "At this point in our fractious nation’s experience, it seems more than necessary and desirable to find frames of reference capable of embracing the common, if often excruciating, origins of the continent's diverse peoples." (Richter 10) AC
- "Only after the establishment of large-scale European colonies—and the much bigger and more predictable patterns of trade they allowed did Indians begin to use imported goods in ways that resembled the purposes for which they had been designed." (Richter 43) AD 
- "The news things were **always** in some practical way superior to the old --- lighter, sharper, more durable --- but they were used in very familiar contexts." (Richter 44) AE
- "Something as basic as firemaking was radically simplified not just by axes that made firewood more readily obtainable but by flint and still 'strike-a-lights'" (Richter 44) AF
- "The vastly increased supply did not so much devalue what was once rare as create an innovative cultural phenomenon rooted in unprecedented abundance" (Richter 46) AJ
- "But all of this Indian abundance depended on a kind of mobility and flexible use of the landscape that would prove incompatible with the colonists’ ways of interacting with the environment." (Richter 57) AH
- "With literally everyone sick, and the able-bodied adults more incapacitated than the rest, the everyday work of raising crops, gathering wild plants, fetching water and firewood, hunting meat, and harvesting fish virtually ceased." (Richter 61) AI
- "Nice distinctions between restoration for victims and bloodthirsty revenge must frequently have blurred." (Richter 66) AJ
- "The Indian's world ... was ... the creation of individuals and shattered families who recombined and reinvented themselves to survive in unprecedented circumstances. In all of this, eastern Native people were anything but passive victims unable to change." (Richter 66) AK
- "As Nathan Huggins once said of African American history, 'it is exactly this triumph of the human spirit over adversity that is the great story.' The same is true for Native American history from the early seventeenth century onward." (Richter 68) AM
- "There were elaborate markets in each city and a far-flung trade network that used routes established by the Toltecs." (Dunbar-Ortiz 7) BA
- "Native peoples were colonized and deposed of their territories as distinct peoples—hundreds of nations—not as a racial or ethnic group." (Dunbar-Ortiz 2) BB
- "Indigenous survival as peoples is due to centuries of resistance and storytelling passed through the generations, and I sought to demonstrate that this survival is dynamic, not passive." (Dunbar-Ortiz 2) BC
- "Being pressed for tribute through violent attacks, peasants rebelled and there were uprisings all over Mexico. Cortes’s recruitment of resistant communities all over Mexico as allies aided in toppling the central regime." (Dunbar-Ortiz 7) BD
- "Averaging thirty feet wide, these roads followed straight courses, even through difficult terrain such as hills and rock formations. The highways connected some seventy-five communities." (Dunbar-Ortiz 8) BE
- "Cahokia supported a population oftens of thousands, larger than that of London during the same period." (Dunbar-Ortiz 9) BF
- "the practice of herbal medicine and even surgery and dentistry, and most importantly both hygienic and ritual bathing, kept diseases at bay" (Dunbar-Ortiz 9) BG
- "According to the value system that drove consensus building and decision making in these societies, the community’s interest overrode individual interests." (Dunbar-Ortiz 10) BH
- "Algonquians eventually accepted Jesuit celibacy, but the Jesuits never accepted Algonquian sexual mores, particularly when other Frenchmen proved so enthusiastic about them." (White 60) CA
- "Sex was hardly a personal affair; it was governed and regulated by the appropriate authorities." (White 60) CB
- "To understand sexual relations between Algonquians and Europeans, we must remove the combination of sexual fantasy, social criticism, and Jansenism with which the French often veiled their descriptions." (White 61) CC
- "She could leave her husband and return to her own family whenever she chose. Among many groups adultery was not harshly punished" (White 62) CD
- "adultery a meaningless category. And, indeed, it was the categories themselves that were the problem. European conceptions of marriage, adultery, and prostitution just could not encompass the actual variety of sexual relations in the pays d'en haut." (White 63) CE
- "Prostitution had little to do with that term as commonly understood ... Sex accompanied a general agreement to do the work commonly expected of women in Algonquian society" (White 65) CF
- "This stress on a powerful female religious figure, whose power, like that of the Jesuits, was connected with sexual abstinence, attracted a congregation composed largely of women" (White 67) CG
- "Jesuit influence threatened not only sexual activity but also the ability of traders and coureurs de bois to create the ties to Algonquian society on which their trade, and perhaps their lives, depended." (White 68) actual event
- DA claims NM living was long and well, with a healthy life balaince
- DB that even European settlers marveled at the frequent bathing of NM

*** Discussion of Culture
- BH native groups had a sense of belonging and community interest
- CB there was systems governing and de-personalising intercourse
- CC french descriptions of relationships were complicated by fantasy and social crititism (and a divine grace argument a la Jansenism)

*** Discussion of Trade
- AD *only* after the establishment of flourishing European trading could the Indians use goods as they intended

# *** Wastepaper Basket
# - CA Jesuits had conflicts with Frenchmen regarding celibacy, and Algonquian sexual behavior spurred the interests of the Frenchmen

* Claim Synthesis

** Quote Organization

*** On the culture of sex
- CE European constructions of sex does not manifest in that of the NM tradition
- CH But, the application of these philosophies were nevertheless effective and damaging: CG that there is a figure who's power centers around abstinence was appealing, Jesuit preaching disrupted the way by which society was conducted around sex 

*** On the prevalence of technology
- AH NM technology was incompatible with European ways
- BA infrastructured and trade flourished as established by the Toltecs, BF cities of Cahokia was large and well-supported
- AE Richter claims that European technology was always better and was a drop-in replacement for NM tech

*** On the importance of narrative
- AC claims that it is necessary to create a common narrative that blends the diversity into one
- BB each NM group was a distict nation and not just one large group, and BC storytelling serves at the heart of the continuaunce of tradition
- AB Richter claims impossibility of recovering an Americacentric narrative b/c cannot see through "their" (NM's) eyes

** The Claim
**Treatment towards the culture of sex, growth of technology and importance of narrative in early American society by both White and Richter reflects the often Eurocentric misappropriations --- under the pretense of attempting to illustrate a natively American perspective --- of the agency of Native American action.**

-----

There's always the [[https://wp.ucla.edu/wp-content/uploads/2016/01/UWC_handouts_What-How-So-What-Thesis-revised-5-4-15-RZ.pdf][UCLA Writing Lab]].
