:PROPERTIES:
:ID:       C121ACAE-D34D-4EB7-91E8-8FD6A90BCA3F
:END:
#+title: Anna and Christeen Needfindind
#+author: Houjun Liu

- Blind people are struggling with COVID tests b/c they can't see results
- Braille COVID tests (rapid tests)

* Target user group?
- VA Menlo Park: https://www.va.gov/directory/guide/facility.asp?ID=5195
- Cell: (650) 614-9997

** People-Focused
<> People Goal

1. Talk to 2 people in this domain you're interested in.
2. Formulate your understanding + write it down.
3. Talk to 2 more people, and confirm that you got what their problems are right. Then, ask what could be improved about their problem statement.
4. Hypothesize potential _products_ that could solve their problems
5. Talk to 10 more people, ask if the hypothesis hold water, and if not, why not?
6. Refine your product idea further, and tighten up a target segment.
7. Talk to 10 people in your target segment, and get a few nods.

Q: Wait but that requires 40 people?

A: Yes. If you can't even find 30 people to talk about this stuff, your network either is lacking and you have to build that, OR your market is too small

Of course, by the end, in those 10, maybe 5 will be interested in the end and 2 of them will buy. But, if you have 30 people, and all 30 people LOOVE your solution, then you probably have a problem: you found an awesome need, but why the gosh darn has no one built the thing yet? 

Once you are all done: "When you need more advise, ask for money. When you need money, ask for advise".

Therefore:

- You know exactly what your market segment is
- You know what their needs are
- You know what the industry looks like

You probably understand more about the market more than most of the people you interviewed in the end.

If you sell your thing too early, you will cut off the air supply to advise.


