#+TITLE: Emacs Workshop
#+AUTHOR: David and Jack

...a workshop about Emacs for Wednesday Workshops.


* Proposal
Faculty Sponsor: **Morgan Snyder**

Gain Omnipotence With Emacs — The One True Editor

** Description
Learn about the fascinating and powerful world of Emacs, an extensible text editor that can write code, supercharge your version control, take notes, manage windows, organize your to-dos, and probably do your dishes all at once without ever closing it! Create your very own custom editing environment by writing Emacs Lisp code that transforms Emacs into your exact needs by exploring the editor via its self-documenting functionality and deeply customizing its UI, behavior, and keybinds. Come to find out why Emacs has remained the trusted tool of thousands of software developers, writers, note-takers, and productivity enthusiasts worldwide for the past 45 years!

** Goals
- Set up and learn about basic Emacs features to quickly edit files without the mouse
- Create the basis of an init.el file to start deeply customizing Emacs to customize and expedite
- Learn about installing third-party packages to add a multitude of new functions, and introduce common packages like Magit and LSP


* Emacs: 

- Broad ecosystem
- Infinite extensibility (self-documenting)
- Advanced base features
- 

Learn about the fascinating and powerful world of Emacs, an extensible text editor that can write code, supercharge your version control, take notes, manage windows, organize your to-dos, and probably do your dishes all at once without ever closing it! 

