#+TITLE: Torque and Angular Momentum 2
#+AUTHOR: Dylan Wallace

* 1)
To finish the proof...
Given two objects, $A$ and $B$, with a force $F$ between them,
the torque on $A$ and $B$ is given by

\begin{aligned}
\tau_{A} &= \vec{r}_{A} \times \vec{F}_{A} \\
\tau_{B} &= \vec{r}_{B} \times \vec{F}_{B} \\
\end{aligned}

where $\vec{F}_{A}$ is the foce applied by $B$ on $A$, and vice versa.
We know that because of N-3 $\vec{F}_{A} = -\vec{F}_{B}$. (We also know that the forces point towards each object.)
Therefore,
\begin{aligned}
\tau_{AB} &= \tau_{A} + \tau_{B} \\
&= \vec{r}_{A} \times \vec{F}_{A} + \vec{r}_{B} \times \vec{F}_{B} \\
&= \vec{r}_{A} \times \vec{F}_{A} + \vec{r}_{B} \times -\vec{F}_{A} \\
\end{aligned}

We know that the direction of the two cross products are orthogonal to the plane that the two objects' position vectors and the origin of the system form.

\begin{aligned}
\tau_{AB} &= \vec{r}_{A} \times \vec{F}_{A} + \vec{r}_{B} \times -\vec{F}_{A} \\
&= |\vec{r}_{A}||\vec{F}_{A}|\sin{\theta_{A}} - |\vec{r}_{B}||\vec{F}_{A}|\sin{\theta_{B}} \\
&= |\vec{r}_{A}|\sin{\theta_{A}} - |\vec{r}_{B}|\sin{\theta_{B}} \\
\end{aligned}

The law of sines states that for a triangle $\triangle ABC$, $\frac{\overline{\rm BC}}{\sin{\theta_{A}}} = \frac{\overline{\rm AC}}{\sin{\theta_{B}}}$. We know that this applies in our particular proof because the objects $A$, $B$, and the origin form a triangle. As such,

\begin{aligned}
|\vec{r}_{A}|\sin{\theta_{A}} &= |\vec{r}_{B}|\sin{\theta{B}} \\
\tau_{AB} &= 0 \\
\end{aligned}

The internal torque of any two objects of a system is zero, so the total internal torque must also be zero.

* 2)
We know that for one of the $\vec{L}$s: 
\begin{aligned}
\vec{r} &= R\hat{i} + h\hat{k} \\
\vec{L}_{1} &= \vec{r} \times m\vec{v} \\
\vec{v} &= R\omega\hat{j}\\
\vec{L}_{1} &= (R\hat{i} + h\hat{k}) \times mR\omega\hat{j} \\
&= -hmR\omega\hat{i} + mR^2\omega\hat{k}\\
\end{aligned}

We know that there are two masses, symmetric about the z-axis, so we know that the angular momentum of the other object can be derived just by multiplying the $\hat{i}$ and $\hat{j}$ terms by -1.

\begin{aligned}
\vec{L}_{2} &= \vec{L}_{1} \,\cdot \begin{bmatrix}-1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1\end{bmatrix} \\
&= hmR\omega\hat{i} + mR^2\omega\hat{k} \\
\end{aligned}

We can add the two to get the aggregate angular momentum of the system:

\begin{aligned}
\vec{L} &= \vec{L}_{1} + \vec{L}_{2} \\
&= (-hmR\omega\hat{i} + mR^2\omega\hat{k}) + (hmR\omega\hat{i} + mR^2\omega\hat{k}) \\
&= 2mR^2\omega\hat{k} \\
\end{aligned}

* 3)
** a)
$\vec{L}_{N} &= \sum_{i=1}^{N} m_{i}l_{i}^2 \cdot \omega\hat{k}$
** b)
$\vec{L} &= \int_{V} l^2 (M/V_{0}) \,dV \cdot \omega\hat{k}$
First, because we know that the object is axially symmetric, the $\hat{i}$ and $\hat{j}$ components of the torque addition will be eliminated by the negative values for those components of the symmetric counterpart, so we will only be left with a $\hat{k}$ component.
Given this, we can express the angular momentum as an integral over the volume.
WIP

* 4)
We can represent the angular momentum of the two points distance $l$ away from the origin as a function of $l$:
\begin{aligned}
\vec{v}_{1} &= -\vec{v}_{2} \\
\vec{l}_{1} &= -\vec{l}_{2} \\
\vec{L}(r) &= \vec{r}_{1}\times m\vec{v}_{1} + vec{r}_{2}\times m\vec{v}_{1} \\
&= \vec{r}\times m\vec{v} - \vec{r}\times -m\vec{v} \\
\\
\vec{r} &= r\hat{i} \\
\vec{v} &= L\omega\hat{j} \\
m &= \frac{M}{L} \\
\\
\vec{L}(r) &= r\hat{i}\times ML\omega\hat{j} + (-r\hat{i}\times -ML\omega\hat{j}) \\
&= 2rLM\omega\hat{k} \\
\end{aligned}

Now that we have a function of the angular velocity in terms of the distance from the center, we can integrate. Keep in mind that we will integrate from $0$ to $\frac{L}{2}$, because our angular velocity function is the sum of the two point masses that are $r$ away from the center.

\begin{aligned}
\vec{L} &= \int_{0}^{\frac{L}{2}} \vec{L}(r) dr \\
&= \int_{0}^{\frac{L}{2}} 2rLM\omega\hat{k} dr \\
&= [r^2LM\omega\hat{k}]^{\frac{L}{2}}_{0} \\
&= \frac{L^3}{4}M\omega\hat{k} \\
\end{aligned}
