#+TITLE: Torque and Angular Momentum 1 - Revised
#+AUTHOR: Dylan Wallace

* 1)
\begin{aligned}
\vec{L} &= \vec{p} \times m\vec{v} \\
\end{aligned}

The circle has a circumference of $2\pi R$, and it takes $\frac{2\pi}{\omega}$ seconds to travel that distance, so the tangential velocity must be $\vec{v} = 2\pi R \div \frac{2\pi}{\vec{\omega}} &= R\vec{\omega}$ 
Therefore,
\begin{aligned}
\vec{L} &= \vec{R} \times mR\vec{\omega} \\
\end{aligned}

The vector is pointing out of the page, as the object is rotating counterclockwise.
\begin{aligned}
|\vec{L}| &= mR|\vec{R}||\vec{\omega}|\\
&= mR^2\omega \\
\end{aligned}

We know that $\sin{\theta}$ is 1 because the vectors are perpendicular.

* 2)
We can think of $\vec{r}$ as the sum of some initial position vector and velocity times the time.

\begin{aligned}
\vec{r} &= \vec{r}_{0} + \vec{v}t \\
\end{aligned}

Then, we can look at angular momentum:

\begin{aligned}
\vec{L} &= \vec{r} \times m\vec{v} \\
&= (\vec{r}_{0} + \vec{v}t)\times m\vec{v} \\
&= (\vec{r}_{0}\times m\vec{v}) + (\vec{v}t\times m\vec{v}) \\
&= \vec{r}_{0} \times m\vec{v} \\
\end{aligned}

We see that angular momentum is not reliant on t. As such, it is conserved.

* 3)
We are given:
\begin{aligned}
\vec{L} &= \vec{p}\timesm\vec{v} \\
\frac{d\vec{L}}{dt} &= \frac{d\vec{p}}{dt}\times m\vec{v} + \frac{d\,m\vec{v}}{dt}\times \vec{p} \\
&= \vec{v} \times m\vec{v} + m\vec{a} \times \vec{p}
&= 0 + \vec{p} \times m\vec{a} \\
&= \vec{p} \times\vec{F} \\
&= \vec{\tau} \\
\end{aligned}
