#+TITLE: Armadillos
#+AUTHOR: Dylan Wallace

* (a)
See diagram
* (b)
The momentum of the flatcar's initial state with $N$ armadillos is given by
\begin{aligned}
p_{car;0} = v_{car;0}(M + Nm)
\end{aligned}
The momentum of the armadillos (as a collective) jumping off of the flatcar is given by
\begin{aligned}
p_{armadillos} = -v_{car;0}Nm
\end{aligned}
The momentum is negative because it is in the opposite direction of the flatcar.
Because of conservation of momentum, the sum of the momentum of the empty flatcar and the momentum of the armadillos must equal the initial momentum:
\begin{aligned}
p_{car;0} &= p_{armadillos} + p_{car} \\
p_{car} &= p_{car;0} - p_{armadillos} \\
&= v_{car;0}(M + Nm) - ((u-v_{car;0})Nm) \\
&= v_{car;0}(M + 2Nm) - uNm \\
\end{aligned}
The mass of the flatcar is just $M$, so the velocity must reflect that:
\begin{aligned}
p_{car} &= v_{car}M \\
v_{car} &= \frac{p_{car}}{M} \\
&= \frac{v_{car;0}(M + 2Nm) - uNm}{M} \\
&= v_{car;0} + 2(v_{car;0} - u)\frac{Nm}{M} \\
\end{aligned}
* (c)
We define $v_{j}$ as the velocity of the flatcar with armadillos after the $j$-th armadillo has jumped.
When $j = 1$,
\begin{aligned}
v_1 &= \frac{v_{0}(M + (N+1)m) - um}{M + (N - 1)m} \\
\end{aligned}
When $j = 2$,
\begin{aligned}
v_{2} &= \frac{v_{1}(M + (N - 1)m) - (u - v{1})m}{M + (N - 2)m} \\
&= \frac{v_{1}(M + Nm) - um}{M + (N-2)m} \\
\end{aligned}
and so on. That is, for any arbitrary $1 <= j <= N$,
\begin{aligned}
v_{j} &= \frac{
\end{aligned}

* (d)
As the mass of the flatcar approaches zero, the mass component of the momentum of the flatcar will decrease, and as a result, when all the armadillos are off of the flatcar, the velocity component will reach infinity.

* (e)

* (f)

* (h)

* (i)
