:PROPERTIES:
:ID:       3CFDD390-3FCE-40A4-94AE-A5D93246BEAE
:END:
#+title: History Gallery Walk
#+author: Houjun Liu

* Why does it capture imagination?
The process of processing oil essentially took what people seen as a waste product into a globally-hot commodity. As technology increases, the process of industrialization "unlocked" much of these seemingly disconnected and wasted resources and drove possible future monopolies.

* Interesting historical insights
- Whale blubber was used as a means of oil until whales ran out
- DC current proprietors (i.e. Edison) had a propaganda campaign which claimed that AC current was something dangerous
- The Guilded age shifted away from a general perception of "beauty" to a functionality-first change

* Themes / Connections
- Issues/products are often bourne out of solving problems
- Humans pivot to subjugation of resources and people as a means achieving a task

* Guilded age reflection
- How did your group function as a team? What role did you play as a team member?
- If you could do this project over again, what would you change about how you or your team navigated the learning process?
- How was the research process for you? What would you like to gain as part of your research skillset? (finding sources, navigating different types of sources, interacting with the librarian, creating bibliographies, etc.)
- What was a moment of historical learning for you? What did you enjoy most about this project? Would you change anything?

Our group functioned very well as a team; as with a lot of projects, I acted as the role of project manager: syncing deliverables and setting deadlines to push forward each individual group member. The research process of the project went very smoothly, as we each came to the product with a unique perspective on class and workers and were able to synthesize them together into one coherent product. However, in terms of artifact creation, I think I our group could have better collaborated if I had taken into account the skillets in each of the members and better distributed the creative process to each individual.
In terms of the actual research, I think the research project last semester offered me a good foundation on how to approach independent-driven research, and to better distribute the balance of my tasks within research. I especially was thankful for the actual work of creating an "annotated bibliography", which allowed me the chance to consider my sources and vet them in an effective manner.
As I noted in my presentation, I was surprised by the fact that the widespread prevalence of gun violence was actually instigated by a single set of corporations looking to monopolize upon a singular sentiment in the American public. As such, it makes me wonder if there are more widespread social "trends" that are created as part of such marketing efforts.
I enjoyed the ability to collaborate with others and create a fruitful projects in such a quick turnaround as this project offers. I am looking forward to all other forms of assessment in the class in the future!



