#+TITLE: Inertial Circular Motion
#+AUTHOR: Houjun Liu

In this problem, we aim to determine functions $f_1$, $f_2$, that represents the velocity and acceleration vectors respectively of a circularly movable reference frame.

* Defining First Principles
We begin by defining $\vec{r}$, the vector representing the radius of the rotating frame, as follows:

\begin{equation}
   \vec{r} = r \cos(\theta) \hat{i} + r \sin{\theta} \hat{j} 
\end{equation}

We define $\theta$ as the angle up from the horizontal at which $\vec{r}$ is located, and therefore the vector $\vec{r}$ is simply the magnitude thereof $r$ projected upon that angle $(\cos\theta, \sin\theta)$ into a vector.

Furthermore, we define a unit vector in the direction of $\vec{r}$ as $\hat{r}$. That is:

\begin{equation}
   \hat{r} =  \cos(\theta) \hat{i} + \sin{\theta} \hat{j} 
\end{equation}

Lastly, we define a vector $\hat{\theta}$, a unit vector orthogonal to $\vec{r}$. It is defined as such as the direction of $\vec{\theta}$ would, at any given instance, be perpendicular to the direction of $\vec{r}$ and parallel to the direction to its movement.

\begin{equation}
\hat{\theta} = -\sin{\theta}\hat{i} + \cos{\theta}\hat{j}
\end{equation}

* Determining changes in direction 
We now create definitions for changes in "direction" --- the changes present in $\hat{r}$ and $\hat{\theta}$ --- which we will leverage later.

\begin{align}
    \frac{d\hat{r}}{dt} &= \frac{d}{dt}(\cos{\theta}\hat{i} + \sin{\theta}\hat{j}) \\
&= -\dot{\theta} \sin{\theta}\hat{i} + \dot{\theta}\cos{\theta}\hat{j} \\
&= \dot{\theta} (-\sin{\theta}\hat{i} + \cos{\theta}\hat{j}) \\
&= \dot{\theta}\hat{\theta}
\end{align}

Hence, the change in the direction of $\hat{r}$, aptly and intuitively, could be modeled by the change in the angle $\theta$ times the direction of $\theta$.

\begin{align}
\frac{d\hat{\theta}}{dt} &= \frac{d}{dt}(-\sin\theta \hat{i} + \cos\theta \hat{j}) \\
&= -\dot{\theta}\cos{\theta} \hat{i} - \dot{\theta}\sin\theta\hat{j} \\
&= -\dot{\theta} (\cos\theta\hat{i} + \sin\theta\hat{j}) \\
&= -\dot{\theta}\hat{r}
\end{align}

We now note that, indeed, the change in the direction of $\theta$ is modeled by the direction at which $\vec{r}$ exists, and the angle of $\theta$ as $\theta$ must be orthogonal to $\vec{r}$.

* Solving for $f_1 = \vec{v}$
We now begin to solve for a function $f_1(\hat{r},\hat{\theta},\dot{r},\dot{\theta},r) = \vec{v}$. We know that the velocity of the frame as a whole could be modeled by the following expression:

\begin{align}
    \vec{v} &= r \frac{d\hat{r}}{dt} + \hat{r} \frac{dr}{dt} \\
&= r \dot{\theta}\hat{\theta} + \hat{r}\dot{r}
\end{align}

The derivation of this expression simply follows variable substitution to result in the expression modeling velocity: that the velocity of the point is determined by the radius-scaled velocity in the angle of the object (how fast it spins), plus the velocity of the radius itself (how fast it grows.)

* Solving for $f_2 = \vec{a}$. 
We here wish to determine a function $f_2(\hat{r},\hat{\theta},\dot{r},\dot{\theta},\ddot{r},\ddot{\theta},r) = \vec{a} = \frac{d}{dt}\vec{v}$

Deriving the value of this expression, therefore, simply acts as a matter of taking the derivative of the top-derived expression and performing variable substitution for $\dot{\hat{r}}$ and $\dot{\hat{\theta}}$ as determined above as needed. 

\begin{align}
    \vec{a} &= \frac{d}{dt} (r\dot{\theta}\hat{\theta} + \hat{r}\dot{r}) \\
&= ((\frac{d}{dt}r) \dot{\theta}\hat{\theta} + ((\frac{d}{dt} \dot{\theta})\hat{\theta} + (\frac{d}{dt} \hat{\theta})\dot{\theta})r) + ((\frac{d}{dt}\hat{r})\dot{r} + (\frac{d}{dt}\dot{r})\hat{r}) \\
=& ((\dot{r})\dot{\theta}\hat{\theta} + ((\ddot{\theta})\hat{\theta} + (-\dot{\theta}\hat{i})\dot{\theta})r) + ((\dot{\theta}\hat{\theta})\dot{r} + (\ddot{r})\hat{r}) \\
=& (\dot{r}\dot{\theta}\hat{\theta} + \ddot{\theta}\hat{\theta}r - \dot{\theta}^2 \hat{r}r) + (\dot{\theta}\hat{\theta}\dot{r} + \ddot{r} \hat{r}) \\
=& \hat{\theta}(2\dot{r}\dot{\theta} + \ddot{\theta}r) + \hat{r} (\ddot{r} - \dot{\theta}^2r)
\end{align}

We could now figure that acceleration is actually four terms, scaled by their respective directions ($\hat{\theta}$ and $\hat{r}$). That is:

- $2\dot{r}\dot{\theta}$ is a term representing the coriolis effect: a fictitious force pushing objects as either of radius change or spin speed changes
- $\ddot{\theta}r$ is a term that models the tangential acceleration: how quickly does the object accelerates at a direction tangent to the spin
- $\ddot{r}$ is a term that models the acceleration of the radius, as it evidently shows
- $\dot{\theta}^2 r$ is a term that models the inward acceleration that maintains the shape of the circle. It is $\dot{\theta}^2 r = \omega^2 r$







