:PROPERTIES:
:ID:       D13C0042-D9A0-462B-9DC0-56E727711F71
:END:
#+title: Statistics!
#+author: Houjun Liu



* Introduction to Probability
:PROPERTIES:
:ID:       E171D73A-8F0D-4D3B-8E35-18F4632CD634
:ROAM_ALIASES: "Very Brief Intro to Probability"
:END:

Probability: the likelihood of something happening

- "Success"
- "Failure"

At the moment, those are the two categories.

** A Statistical Trial
Each trial is an event with an outcome. Say, your case for "success" is rolling a 6. All other events are considered as a "failure"

Therefore...

\begin{equation}
    Prob(success) = \frac{\#\ times\ sucess}{\#\ trials}
\end{equation}

Statistics is not a hard and fast mathematical thing. 

*** Definitions
In order to perform the trials, we need to define a few things.

$X$ - Random Variable: a statistic that we could measure

There is a basic bell curve that comes with most trials, given , and the $y$ is the count.

We don't want to sample the whole population, so we therefore want to sample a subset.

**** Mean
The mean of our samples could be defined as follows:

\begin{equation}
    \bar{x_{10}} = \frac{\sum^n_{i=1}x_i}{n}
\end{equation}

Where little $x_{10}$ represents the random variable of a subset of the population, and hence $\bar{x_{10}}$ is the mean of the 10 samples. If we increase the sample size, it will become harder for the sample size to deviate.

Hence...

\begin{equation}
    \bar{x_{10}} \approx \bar{X}
\end{equation}

that the mean of 10 random samples is pretty close to the actual mean.

And, the distribution of the sampled means will become a bell curve slightly "fatter" than that in the original distribution. **As sample size increases, the skinnier the bell curve for the distribution of means increases.**

**** Standard Deviation
`n-1` standard deviation.

