:PROPERTIES:
:ID:       764EFDF1-0599-48AD-A7A7-53C3895389C1
:END:
#+title: Torque Number 1
#+author: Houjun Liu

We are given the following information:

\begin{align}
   &|\vec{T}| = 1500N \\
   &|\vec{r}| = 80m\\
   &\theta = 16.7^\circ
\end{align}

* Magnitude of Torque
The magnitude of the torque is given by the length of the lever arm multiplied by the magnitude of force, that is:

\begin{equation}
   ||\vec{r}| |\vec{T}| sin(\theta)|
\end{equation}

Therefore:

\begin{equation}
   |1500\cdot 80 \cdot 0.28736| = 34483.2 \approx |\vec{\tau}|
\end{equation}

* Length of the Lever arm
Based on the expression for the magnitude of the torque, we can see that $||\vec{r}|sin(\theta)|$ is the "length" of the lever arm were $\vec{T}$ be applied totally perpendicularly. Therefore, the length of the lever arm would be:

\begin{equation}
   |80 \cdot 0.28736| = 22.99
\end{equation}

* Direction of Torque
As we deducted above, the system's torque is in the "positive" direction. Treating $\vec{r}$ as the positive direction as well, we can apply the right hand rule and recognize that the direction of torque is into the page.

* Value of $\theta_1$
The value of $\theta_1$ is the angle between the lever vector and the torque vector. In this case, $\theta_1 = 163.3^\circ$. Though the outer angle between the two vectors is different (i.e. $180- 163.3 =16.7$), the value of $\sin$ between the two angles ($180-\theta$ and $\theta$) would be the same (i.e. that $\sin(180-\theta)=\sin(\theta)$).

